// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"time"
)

type Querier interface {
	// CreateRole: Inserts a new role into the system
	// Purpose: Add new role definitions (e.g., Admin, Cashier, etc.)
	// Parameters:
	//   $1: Role name
	// Returns:
	//   Newly created role's full data (including timestamps)
	CreateRole(ctx context.Context, roleName string) (*Role, error)
	// CreateTransfer: Records a new transfer transaction
	// Purpose: Create a transfer between accounts/cards
	// Parameters:
	//   $1: transfer_from - Source account/card number
	//   $2: transfer_to - Destination account/card number
	//   $3: transfer_amount - Amount transferred
	//   $4: transfer_time - When the transfer occurred
	//   $5: status - Initial status of the transfer
	// Returns:
	//   The newly created transfer record
	// Business Logic:
	//   - Sets creation and update timestamps automatically
	//   - Used for recording money movements between accounts
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (*CreateTransferRow, error)
	// DeleteAllPermanentRoles: Permanently deletes all soft-deleted roles
	// Purpose: Bulk cleanup of trashed roles
	// Parameters: None
	DeleteAllPermanentRoles(ctx context.Context) error
	// DeleteAllPermanentTransfers: Permanently removes all trashed transfers
	// Purpose: Clean up all soft-deleted transfers
	// Business Logic:
	//   - Irreversible bulk deletion
	//   - Only affects trashed records
	//   - Frees database space
	DeleteAllPermanentTransfers(ctx context.Context) error
	// DeletePermanentRole: Permanently deletes a trashed role
	// Purpose: Remove role from DB after soft delete
	// Parameters:
	//   $1: Role ID
	DeletePermanentRole(ctx context.Context, roleID int32) error
	// DeleteTransferPermanently: Hard-deletes a transfer
	// Purpose: Permanently remove a transfer record
	// Parameters:
	//   $1: transfer_id - ID of transfer to delete
	// Business Logic:
	//   - Physical deletion from database
	//   - Only works on already trashed transfers
	//   - Irreversible operation
	DeleteTransferPermanently(ctx context.Context, transferID int32) error
	// FindAllTransfersByCardNumberAsReceiver: Retrieves all transfers where the card was the receiver
	// Purpose: View incoming transfer history for a specific card
	// Parameters:
	//   $1: card_number - The card number that received the transfers
	// Returns:
	//   All transfer fields for incoming transfers (transfer_to = card_number)
	// Business Logic:
	//   - Only includes active transfers (non-deleted)
	//   - Orders by transfer_time (newest first)
	//   - Useful for tracking money received by a cardholder
	FindAllTransfersByCardNumberAsReceiver(ctx context.Context, transferTo string) ([]*FindAllTransfersByCardNumberAsReceiverRow, error)
	// FindAllTransfersByCardNumberAsSender: Retrieves all transfers where the card was the sender
	// Purpose: View outgoing transfer history for a specific card
	// Parameters:
	//   $1: card_number - The card number that initiated the transfers
	// Returns:
	//   All transfer fields for outgoing transfers (transfer_from = card_number)
	// Business Logic:
	//   - Only includes active transfers (non-deleted)
	//   - Orders by transfer_time (newest first)
	//   - Useful for tracking money sent by a cardholder
	FindAllTransfersByCardNumberAsSender(ctx context.Context, transferFrom string) ([]*FindAllTransfersByCardNumberAsSenderRow, error)
	// GetActiveRoles: Retrieves only active (non-deleted) roles with optional search and pagination
	// Purpose: Display roles that are currently usable in the system
	// Parameters:
	//   $1: Search query (nullable)
	//   $2: Limit
	//   $3: Offset
	// Returns:
	//   role_id, role_name, timestamps, and total_count
	GetActiveRoles(ctx context.Context, arg GetActiveRolesParams) ([]*GetActiveRolesRow, error)
	// GetActiveTransfers: Retrieves paginated active transfers with search
	// Purpose: List all non-deleted transfers with filtering options
	// Parameters:
	//   $1: search_term - Optional text to filter by source or destination account
	//   $2: limit - Maximum records to return per page
	//   $3: offset - Records to skip for pagination
	// Returns:
	//   All transfer fields plus total_count of matching active records
	// Business Logic:
	//   - Only includes active transfers (deleted_at IS NULL)
	//   - Filters on transfer_from and transfer_to fields
	//   - Orders by transfer_time (newest first)
	//   - Provides pagination metadata
	//   - Used in transfer management interfaces
	GetActiveTransfers(ctx context.Context, arg GetActiveTransfersParams) ([]*GetActiveTransfersRow, error)
	// GetMonthTransferStatusFailed: Retrieves monthly failed metrics for fund transfers
	// Purpose: Analyze failedful transfer trends across comparison periods
	// Parameters:
	//   $1: period1_start - Start date of first comparison period (timestamp)
	//   $2: period1_end - End date of first comparison period (timestamp)
	//   $3: period2_start - Start date of second comparison period (timestamp)
	//   $4: period2_end - End date of second comparison period (timestamp)
	// Returns:
	//   year: Year as text (e.g., '2023')
	//   month: 3-letter month abbreviation (e.g., 'Jan')
	//   total_failed: Count of failedful transfers
	//   total_amount: Sum of failedful transfer amounts
	// Business Logic:
	//   - Only includes failedful transfers (status = 'failed')
	//   - Covers two customizable time periods for comparison
	//   - Zero-fills months with no transfer activity
	//   - Formats output for consistent visualization (year as text, month as 'Mon')
	//   - Orders by year and month (newest first)
	//   - Useful for identifying seasonal transfer patterns and cash flow analysis
	GetMonthTransferStatusFailed(ctx context.Context, arg GetMonthTransferStatusFailedParams) ([]*GetMonthTransferStatusFailedRow, error)
	// GetMonthTransferStatusFailedCardNumber: Retrieves monthly failed metrics for fund transfers
	// Purpose: Analyze failedful transfer trends across comparison periods
	// Parameters:
	//   $1: card_number  - filter by card_number
	//   $2: period1_start - Start date of first comparison period (timestamp)
	//   $3: period1_end - End date of first comparison period (timestamp)
	//   $4: period2_start - Start date of second comparison period (timestamp)
	//   $5: period2_end - End date of second comparison period (timestamp)
	// Returns:
	//   year: Year as text (e.g., '2023')
	//   month: 3-letter month abbreviation (e.g., 'Jan')
	//   total_failed: Count of failedful transfers
	//   total_amount: Sum of failedful transfer amounts
	// Business Logic:
	//   - Only includes failedful transfers (status = 'failed')
	//   - Covers two customizable time periods for comparison
	//   - Zero-fills months with no transfer activity
	//   - Formats output for consistent visualization (year as text, month as 'Mon')
	//   - Orders by year and month (newest first)
	//   - Useful for identifying seasonal transfer patterns and cash flow analysis
	GetMonthTransferStatusFailedCardNumber(ctx context.Context, arg GetMonthTransferStatusFailedCardNumberParams) ([]*GetMonthTransferStatusFailedCardNumberRow, error)
	// GetMonthTransferStatusSuccess: Retrieves monthly success metrics for fund transfers
	// Purpose: Analyze successful transfer trends across comparison periods
	// Parameters:
	//   $1: period1_start - Start date of first comparison period (timestamp)
	//   $2: period1_end - End date of first comparison period (timestamp)
	//   $3: period2_start - Start date of second comparison period (timestamp)
	//   $4: period2_end - End date of second comparison period (timestamp)
	// Returns:
	//   year: Year as text (e.g., '2023')
	//   month: 3-letter month abbreviation (e.g., 'Jan')
	//   total_success: Count of successful transfers
	//   total_amount: Sum of successful transfer amounts
	// Business Logic:
	//   - Only includes successful transfers (status = 'success')
	//   - Covers two customizable time periods for comparison
	//   - Zero-fills months with no transfer activity
	//   - Formats output for consistent visualization (year as text, month as 'Mon')
	//   - Orders by year and month (newest first)
	//   - Useful for identifying seasonal transfer patterns and cash flow analysis
	GetMonthTransferStatusSuccess(ctx context.Context, arg GetMonthTransferStatusSuccessParams) ([]*GetMonthTransferStatusSuccessRow, error)
	// GetMonthTransferStatusSuccessCardNumber: Retrieves monthly success metrics for fund transfers
	// Purpose: Analyze successful transfer trends across comparison periods
	// Parameters:
	//   $1: card_number  - filter by card_number
	//   $2: period1_start - Start date of first comparison period (timestamp)
	//   $3: period1_end - End date of first comparison period (timestamp)
	//   $4: period2_start - Start date of second comparison period (timestamp)
	//   $5: period2_end - End date of second comparison period (timestamp)
	// Returns:
	//   year: Year as text (e.g., '2023')
	//   month: 3-letter month abbreviation (e.g., 'Jan')
	//   total_success: Count of successful transfers
	//   total_amount: Sum of successful transfer amounts
	// Business Logic:
	//   - Only includes successful transfers (status = 'success')
	//   - Covers two customizable time periods for comparison
	//   - Zero-fills months with no transfer activity
	//   - Formats output for consistent visualization (year as text, month as 'Mon')
	//   - Orders by year and month (newest first)
	//   - Useful for identifying seasonal transfer patterns and cash flow analysis
	GetMonthTransferStatusSuccessCardNumber(ctx context.Context, arg GetMonthTransferStatusSuccessCardNumberParams) ([]*GetMonthTransferStatusSuccessCardNumberRow, error)
	// GetMonthlyTransferAmounts: Retrieves monthly transfer amounts
	// Purpose: Track total transfer amounts over each month of the selected year
	// Parameters:
	//   $1: reference_date - Any date within the target year (used to define monthly range)
	// Returns:
	//   month: 3-letter month abbreviation (e.g., 'Jan')
	//   total_transfer_amount: Sum of transfer amounts in that month
	// Business Logic:
	//   - Generates complete monthly series for the target year
	//   - Includes all transfers regardless of method
	//   - Filters out soft-deleted records (deleted_at IS NULL)
	//   - Zero-fills months with no transfer activity
	//   - Useful for visualizing monthly cash flow patterns
	GetMonthlyTransferAmounts(ctx context.Context, dollar_1 time.Time) ([]*GetMonthlyTransferAmountsRow, error)
	// GetMonthlyTransferAmountsByReceiverCardNumber: Retrieves monthly transfer amounts
	// Purpose: Track total transfer amounts over each month of the selected year
	// Parameters:
	//   $1: card_number  - filter by card_number
	//   $2: reference_date - Any date within the target year (used to define monthly range)
	// Returns:
	//   month: 3-letter month abbreviation (e.g., 'Jan')
	//   total_transfer_amount: Sum of transfer amounts in that month
	// Business Logic:
	//   - Generates complete monthly series for the target year
	//   - Includes all transfers regardless of method
	//   - Filters out soft-deleted records (deleted_at IS NULL)
	//   - Zero-fills months with no transfer activity
	//   - Useful for visualizing monthly cash flow patterns
	GetMonthlyTransferAmountsByReceiverCardNumber(ctx context.Context, arg GetMonthlyTransferAmountsByReceiverCardNumberParams) ([]*GetMonthlyTransferAmountsByReceiverCardNumberRow, error)
	// GetMonthlyTransferAmountsBySenderCardNumber: Retrieves monthly transfer amounts
	// Purpose: Track total transfer amounts over each month of the selected year
	// Parameters:
	//   $1: card_number  - filter by card_number
	//   $2: reference_date - Any date within the target year (used to define monthly range)
	// Returns:
	//   month: 3-letter month abbreviation (e.g., 'Jan')
	//   total_transfer_amount: Sum of transfer amounts in that month
	// Business Logic:
	//   - Generates complete monthly series for the target year
	//   - Includes all transfers regardless of method
	//   - Filters out soft-deleted records (deleted_at IS NULL)
	//   - Zero-fills months with no transfer activity
	//   - Useful for visualizing monthly cash flow patterns
	GetMonthlyTransferAmountsBySenderCardNumber(ctx context.Context, arg GetMonthlyTransferAmountsBySenderCardNumberParams) ([]*GetMonthlyTransferAmountsBySenderCardNumberRow, error)
	// GetRole: Retrieves role details by role_id
	// Purpose: Fetch a single role record (regardless of deleted status)
	// Parameters:
	//   $1: Role ID
	// Returns:
	//   role_id, role_name, and timestamps
	GetRole(ctx context.Context, roleID int32) (*Role, error)
	// GetRoleByName: Retrieves role by exact role name
	// Purpose: Check role existence or fetch role info based on name
	// Parameters:
	//   $1: Role name (exact match)
	// Returns:
	//   role_id, role_name, and timestamps
	GetRoleByName(ctx context.Context, roleName string) (*Role, error)
	// GetRoles: Retrieves all roles (active & trashed) with optional name search and pagination
	// Purpose: General listing of roles regardless of status
	// Parameters:
	//   $1: Search query (role name, nullable)
	//   $2: Limit (number of records per page)
	//   $3: Offset (starting index for pagination)
	// Returns:
	//   role_id, role_name, timestamps, and total_count (for pagination support)
	// Business Logic:
	//   - Supports fuzzy search on role_name
	//   - Includes both active and trashed roles
	//   - Useful for admin panels with filters and pagination
	GetRoles(ctx context.Context, arg GetRolesParams) ([]*GetRolesRow, error)
	// GetTransferByID: Retrieves a single transfer by its ID
	// Purpose: Get detailed information about a specific transfer
	// Parameters:
	//   $1: transfer_id - The ID of the transfer to retrieve
	// Returns:
	//   All fields for the specified transfer or NULL if not found/deleted
	// Business Logic:
	//   - Only returns active transfers (deleted_at IS NULL)
	//   - Useful for transfer verification and detailed viewing
	GetTransferByID(ctx context.Context, transferID int32) (*GetTransferByIDRow, error)
	// GetTransfers: Retrieves paginated transfer records with search capability
	// Purpose: List all active transfers for management UI with filtering options
	// Parameters:
	//   $1: search_term - Optional text to filter transfers by source or destination account (NULL for no filter)
	//   $2: limit - Maximum number of records to return per page
	//   $3: offset - Number of records to skip for pagination
	// Returns:
	//   All transfer fields plus total_count of matching records
	// Business Logic:
	//   - Excludes soft-deleted transfers (deleted_at IS NULL)
	//   - Supports partial text matching on transfer_from and transfer_to fields (case-insensitive)
	//   - Orders by transfer_time (newest transfers first)
	//   - Provides total_count for pagination calculations
	//   - Useful for transfer monitoring and auditing
	GetTransfers(ctx context.Context, arg GetTransfersParams) ([]*GetTransfersRow, error)
	// GetTransfersByCardNumber:  Retrieves all transfers where the given card number is either the sender or the receiver
	// Purpose:
	//   Useful for displaying all transfer history related to a specific card
	// Parameters:
	//   $1: card_number - Card number to search for in both transfer_from and transfer_to
	// Returns:
	//   All transfer columns for matched records
	// Business Logic:
	//   - Excludes soft-deleted records (deleted_at IS NULL)
	//   - Sorted by most recent transfer first (DESC)
	GetTransfersByCardNumber(ctx context.Context, transferFrom string) ([]*GetTransfersByCardNumberRow, error)
	// GetTransfersByDestinationCard: Retrieves all transfers where the specified card is the destination (transfer_to)
	// Purpose:
	//   Track incoming transfers for a user or card
	// Parameters:
	//   $1: card_number - The destination card number
	// Returns:
	//   All transfer columns for matched records
	// Business Logic:
	//   - Excludes soft-deleted records (deleted_at IS NULL)
	//   - Sorted by most recent transfer first (DESC)
	GetTransfersByDestinationCard(ctx context.Context, transferTo string) ([]*GetTransfersByDestinationCardRow, error)
	// GetTransfersBySourceCard: Retrieves all transfers where the specified card is the source (transfer_from)
	// Purpose:
	//   Track outgoing transfer history for auditing or user activity
	// Parameters:
	//   $1: card_number - The source card number
	// Returns:
	//   All transfer columns for matched records
	// Business Logic:
	//   - Excludes soft-deleted records (deleted_at IS NULL)
	//   - Sorted by most recent transfer first (DESC)
	GetTransfersBySourceCard(ctx context.Context, transferFrom string) ([]*GetTransfersBySourceCardRow, error)
	// GetTrashedRoles: Retrieves only soft-deleted roles with optional search and pagination
	// Purpose: For trash/recycle bin management
	// Parameters:
	//   $1: Search query (nullable)
	//   $2: Limit
	//   $3: Offset
	// Returns:
	//   role_id, role_name, timestamps, and total_count
	GetTrashedRoles(ctx context.Context, arg GetTrashedRolesParams) ([]*GetTrashedRolesRow, error)
	// GetTrashedTransferByID: Retrieves a single soft-deleted transfer by its ID
	// Purpose:
	//   Used for viewing trashed data or restoring transfers
	// Parameters:
	//   $1: transfer_id - ID of the transfer
	// Returns:
	//   The transfer row if it exists and is soft-deleted
	// Business Logic:
	//   - Includes only soft-deleted records (deleted_at IS NOT NULL)
	GetTrashedTransferByID(ctx context.Context, transferID int32) (*Transfer, error)
	// GetTrashedTransfers: Retrieves paginated soft-deleted transfers
	// Purpose: List all deleted transfers for recovery or audit purposes
	// Parameters:
	//   $1: search_term - Optional text to filter deleted transfers
	//   $2: limit - Maximum records to return per page
	//   $3: offset - Records to skip for pagination
	// Returns:
	//   All transfer fields plus total_count of matching deleted records
	// Business Logic:
	//   - Only includes soft-deleted transfers (deleted_at IS NOT NULL)
	//   - Same filtering capabilities as active transfers
	//   - Maintains newest-first ordering
	//   - Used in admin interfaces for transfer recovery
	GetTrashedTransfers(ctx context.Context, arg GetTrashedTransfersParams) ([]*GetTrashedTransfersRow, error)
	// GetUserRoles: Retrieves all roles assigned to a specific user
	// Purpose: Identify the access level(s) of a user
	// Parameters:
	//   $1: User ID
	// Returns:
	//   List of roles (id, name, timestamps)
	GetUserRoles(ctx context.Context, userID int32) ([]*Role, error)
	// GetYearlyTransferAmounts: Retrieves yearly transfer amounts
	// Purpose: Analyze total transfer amounts over a 5-year period
	// Parameters:
	//   $1: current_year - The final year to include (e.g., 2024), includes 5-year span (current_year - 4)
	// Returns:
	//   year: 4-digit year
	//   total_transfer_amount: Sum of transfer amounts in that year
	// Business Logic:
	//   - Covers a 5-year window (current_year - 4 to current_year)
	//   - Filters out soft-deleted records (deleted_at IS NULL)
	//   - Groups by calendar year
	//   - Useful for identifying long-term money movement trends
	GetYearlyTransferAmounts(ctx context.Context, dollar_1 interface{}) ([]*GetYearlyTransferAmountsRow, error)
	// GetYearlyTransferAmountsByReceiverCardNumber: Retrieves yearly transfer amounts
	// Purpose: Analyze total transfer amounts over a 5-year period
	// Parameters:
	//   $1: card_number  - filter by card_number
	//   $2: current_year - The final year to include (e.g., 2024), includes 5-year span (current_year - 4)
	// Returns:
	//   year: 4-digit year
	//   total_transfer_amount: Sum of transfer amounts in that year
	// Business Logic:
	//   - Covers a 5-year window (current_year - 4 to current_year)
	//   - Filters out soft-deleted records (deleted_at IS NULL)
	//   - Groups by calendar year
	//   - Useful for identifying long-term money movement trends
	GetYearlyTransferAmountsByReceiverCardNumber(ctx context.Context, arg GetYearlyTransferAmountsByReceiverCardNumberParams) ([]*GetYearlyTransferAmountsByReceiverCardNumberRow, error)
	// GetYearlyTransferAmountsBySenderCardNumber: Retrieves yearly transfer amounts
	// Purpose: Analyze total transfer amounts over a 5-year period
	// Parameters:
	//   $1: card_number  - filter by card_number
	//   $2: current_year - The final year to include (e.g., 2024), includes 5-year span (current_year - 4)
	// Returns:
	//   year: 4-digit year
	//   total_transfer_amount: Sum of transfer amounts in that year
	// Business Logic:
	//   - Covers a 5-year window (current_year - 4 to current_year)
	//   - Filters out soft-deleted records (deleted_at IS NULL)
	//   - Groups by calendar year
	//   - Useful for identifying long-term money movement trends
	GetYearlyTransferAmountsBySenderCardNumber(ctx context.Context, arg GetYearlyTransferAmountsBySenderCardNumberParams) ([]*GetYearlyTransferAmountsBySenderCardNumberRow, error)
	// GetYearlyTransferStatusFailed: Retrieves yearly failed metrics for fund transfers
	// Purpose: Compare annual failedful transfer performance year-over-year
	// Parameters:
	//   $1: current_year - The target year (includes this year and previous)
	// Returns:
	//   year: Year as text (e.g., '2023')
	//   total_failed: Count of failedful transfers
	//   total_amount: Sum of failedful transfer amounts
	// Business Logic:
	//   - Only includes failedful transfers (status = 'failed')
	//   - Compares current year with previous year
	//   - Zero-fills years with no transfer activity
	//   - Orders by year (newest first)
	//   - Useful for year-over-year growth analysis and financial reporting
	//   - Helps identify annual transfer volume and money movement trends
	GetYearlyTransferStatusFailed(ctx context.Context, dollar_1 int32) ([]*GetYearlyTransferStatusFailedRow, error)
	// GetYearlyTransferStatusFailedCardNumber: Retrieves yearly failed metrics for fund transfers
	// Purpose: Compare annual failedful transfer performance year-over-year
	// Parameters:
	//   $1: card_number  - filter by card_number
	//   $2: current_year - The target year (includes this year and previous)
	// Returns:
	//   year: Year as text (e.g., '2023')
	//   total_failed: Count of failedful transfers
	//   total_amount: Sum of failedful transfer amounts
	// Business Logic:
	//   - Only includes failedful transfers (status = 'failed')
	//   - Compares current year with previous year
	//   - Zero-fills years with no transfer activity
	//   - Orders by year (newest first)
	//   - Useful for year-over-year growth analysis and financial reporting
	//   - Helps identify annual transfer volume and money movement trends
	GetYearlyTransferStatusFailedCardNumber(ctx context.Context, arg GetYearlyTransferStatusFailedCardNumberParams) ([]*GetYearlyTransferStatusFailedCardNumberRow, error)
	// GetYearlyTransferStatusSuccess: Retrieves yearly success metrics for fund transfers
	// Purpose: Compare annual successful transfer performance year-over-year
	// Parameters:
	//   $1: current_year - The target year (includes this year and previous)
	// Returns:
	//   year: Year as text (e.g., '2023')
	//   total_success: Count of successful transfers
	//   total_amount: Sum of successful transfer amounts
	// Business Logic:
	//   - Only includes successful transfers (status = 'success')
	//   - Compares current year with previous year
	//   - Zero-fills years with no transfer activity
	//   - Orders by year (newest first)
	//   - Useful for year-over-year growth analysis and financial reporting
	//   - Helps identify annual transfer volume and money movement trends
	GetYearlyTransferStatusSuccess(ctx context.Context, dollar_1 int32) ([]*GetYearlyTransferStatusSuccessRow, error)
	// GetYearlyTransferStatusSuccessCardNumber: Retrieves yearly success metrics for fund transfers
	// Purpose: Compare annual successful transfer performance year-over-year
	// Parameters:
	//   $1: card_number  - filter by card_number
	//   $2: current_year - The target year (includes this year and previous)
	// Returns:
	//   year: Year as text (e.g., '2023')
	//   total_success: Count of successful transfers
	//   total_amount: Sum of successful transfer amounts
	// Business Logic:
	//   - Only includes successful transfers (status = 'success')
	//   - Compares current year with previous year
	//   - Zero-fills years with no transfer activity
	//   - Orders by year (newest first)
	//   - Useful for year-over-year growth analysis and financial reporting
	//   - Helps identify annual transfer volume and money movement trends
	GetYearlyTransferStatusSuccessCardNumber(ctx context.Context, arg GetYearlyTransferStatusSuccessCardNumberParams) ([]*GetYearlyTransferStatusSuccessCardNumberRow, error)
	// RestoreAllRoles: Restores all soft-deleted roles in bulk
	// Purpose: Bulk recovery of all trashed roles
	// Parameters: None
	RestoreAllRoles(ctx context.Context) error
	// RestoreAllTransfers: Recovers all trashed transfers
	// Purpose: Mass restoration of deleted transfers
	// Business Logic:
	//   - Clears deleted_at for all trashed transfers
	//   - Useful for system recovery
	//   - Use with caution in production
	RestoreAllTransfers(ctx context.Context) error
	// RestoreRole: Restores a previously trashed role
	// Purpose: Undelete a soft-deleted role
	// Parameters:
	//   $1: Role ID
	RestoreRole(ctx context.Context, roleID int32) (*Role, error)
	// RestoreTransfer: Recovers a soft-deleted transfer
	// Purpose: Reactivate a previously deleted transfer
	// Parameters:
	//   $1: transfer_id - ID of transfer to restore
	// Business Logic:
	//   - Clears deleted_at timestamp
	//   - Only works on trashed transfers
	RestoreTransfer(ctx context.Context, transferID int32) (*Transfer, error)
	// TrashRole: Soft-deletes a role (moves to trash)
	// Purpose: Mark role as deleted without removing it permanently
	// Parameters:
	//   $1: Role ID
	TrashRole(ctx context.Context, roleID int32) (*Role, error)
	// TrashTransfer: Soft-deletes a transfer
	// Purpose: Remove transfer from active view without permanent deletion
	// Parameters:
	//   $1: transfer_id - ID of transfer to trash
	// Business Logic:
	//   - Sets deleted_at timestamp
	//   - Only affects active transfers
	//   - Preserves data for audit/recovery
	TrashTransfer(ctx context.Context, transferID int32) (*Transfer, error)
	// UpdateRole: Updates role name by ID
	// Purpose: Modify role information (e.g., name correction)
	// Parameters:
	//   $1: Role ID
	//   $2: New role name
	// Returns:
	//   Updated role's data
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (*Role, error)
	// UpdateTransfer: Modifies transfer details
	// Purpose: Update all fields of an existing transfer
	// Parameters:
	//   $1: transfer_id - ID of transfer to update
	//   $2: transfer_from - Updated source account
	//   $3: transfer_to - Updated destination account
	//   $4: transfer_amount - Updated amount
	//   $5: transfer_time - Updated timestamp
	// Business Logic:
	//   - Only updates active transfers (non-deleted)
	//   - Updates modification timestamp automatically
	//   - Used for correcting transfer details
	UpdateTransfer(ctx context.Context, arg UpdateTransferParams) (*UpdateTransferRow, error)
	// UpdateTransferAmount: Changes only the transfer amount
	// Purpose: Adjust the amount of a transfer
	// Parameters:
	//   $1: transfer_id - ID of transfer to update
	//   $2: transfer_amount - New transfer amount
	// Business Logic:
	//   - Only updates active transfers
	//   - Updates both amount and transfer timestamp
	//   - Used for amount corrections
	UpdateTransferAmount(ctx context.Context, arg UpdateTransferAmountParams) (*UpdateTransferAmountRow, error)
	// UpdateTransferStatus: Changes transfer status
	// Purpose: Update processing status of a transfer
	// Parameters:
	//   $1: transfer_id - ID of transfer to update
	//   $2: status - New status (e.g., 'completed', 'failed')
	// Business Logic:
	//   - Only updates active transfers
	//   - Updates modification timestamp
	//   - Used to reflect transfer processing outcomes
	UpdateTransferStatus(ctx context.Context, arg UpdateTransferStatusParams) (*UpdateTransferStatusRow, error)
}

var _ Querier = (*Queries)(nil)
