// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"time"
)

type Querier interface {
	// CreateRole: Inserts a new role into the system
	// Purpose: Add new role definitions (e.g., Admin, Cashier, etc.)
	// Parameters:
	//   $1: Role name
	// Returns:
	//   Newly created role's full data (including timestamps)
	CreateRole(ctx context.Context, roleName string) (*Role, error)
	// CreateSaldo: Creates a new saldo record (idempotent upsert per active card)
	// Purpose: Initialize a balance record for a new card
	// Parameters:
	//   $1: card_number - The card number to associate with this saldo
	//   $2: total_balance - The initial balance amount
	// Returns:
	//   The saldo record (existing balance is preserved if already present)
	// Business Logic:
	//   - Sets creation and update timestamps automatically
	//   - Used when issuing new cards
	//   - Atomic idempotency: relies on the partial unique index
	//     idx_saldos_card_number_active (card_number WHERE deleted_at IS NULL) so
	//     that concurrent creates for the same card (e.g. Kafka card-created event
	//     racing with the API create) never produce duplicate active rows.
	//   - An existing NON-ZERO balance is preserved (this command is not an
	//     administrative balance correction); but a zero balance left behind by the
	//     Kafka card-created placeholder event is overwritten so the API create
	//     always wins the race against the consumer.
	CreateSaldo(ctx context.Context, arg CreateSaldoParams) (*CreateSaldoRow, error)
	// CreateSaldoIfNotExists: Creates a saldo record only when none exists for the card
	// Purpose: Used by the Kafka consumer that reacts to card-created events. The event
	//   carries total_balance=0 and must NEVER overwrite a real balance already set via
	//   the API, so it uses DO NOTHING instead of DO UPDATE.
	// Parameters:
	//   $1: card_number - The card number to associate with this saldo
	//   $2: total_balance - The initial balance amount
	// Business Logic:
	//   - Atomic no-op when an active saldo already exists for the card
	//   - Prevents duplicate rows even when racing with the API create
	CreateSaldoIfNotExists(ctx context.Context, arg CreateSaldoIfNotExistsParams) error
	// CreditSaldo: Atomically credits a card balance by a positive delta.
	CreditSaldo(ctx context.Context, arg CreditSaldoParams) (*CreditSaldoRow, error)
	// DebitSaldo: Atomically debits a card balance when sufficient funds exist.
	DebitSaldo(ctx context.Context, arg DebitSaldoParams) (*DebitSaldoRow, error)
	// DeleteAllPermanentRoles: Permanently deletes all soft-deleted roles
	// Purpose: Bulk cleanup of trashed roles
	// Parameters: None
	DeleteAllPermanentRoles(ctx context.Context) error
	// DeleteAllPermanentSaldos: Permanently removes all trashed saldos
	// Purpose: Clean up all soft-deleted records
	// Business Logic:
	//   - Irreversible bulk deletion
	//   - Only affects records marked as deleted
	//   - Frees database space from old records
	DeleteAllPermanentSaldos(ctx context.Context) error
	// DeletePermanentRole: Permanently deletes a trashed role
	// Purpose: Remove role from DB after soft delete
	// Parameters:
	//   $1: Role ID
	DeletePermanentRole(ctx context.Context, roleID int32) error
	// DeleteSaldoPermanently: Hard-deletes a trashed saldo
	// Purpose: Permanently remove a previously soft-deleted record
	// Parameters:
	//   $1: saldo_id - The ID of the saldo to delete
	// Business Logic:
	//   - Physical deletion from database
	//   - Only works on already trashed records
	//   - Irreversible operation
	DeleteSaldoPermanently(ctx context.Context, saldoID int32) error
	// GetActiveRoles: Retrieves only active (non-deleted) roles with optional search and pagination
	// Purpose: Display roles that are currently usable in the system
	// Parameters:
	//   $1: Search query (nullable)
	//   $2: Limit
	//   $3: Offset
	// Returns:
	//   role_id, role_name, timestamps, and total_count
	GetActiveRoles(ctx context.Context, arg GetActiveRolesParams) ([]*GetActiveRolesRow, error)
	// GetActiveSaldos: Retrieves active saldos with pagination and optional search
	// Purpose: List all non-deleted saldos with optional filtering for administrative views
	// Parameters:
	//   $1: search_term - Optional filter by card_number (case-insensitive, NULL for no filter)
	//   $2: limit - Number of records to retrieve
	//   $3: offset - Records to skip (pagination)
	// Returns:
	//   Active saldo records with total_count for pagination
	// Business Logic:
	//   - Filters out trashed saldos (deleted_at IS NULL)
	//   - Supports partial matching on card_number
	//   - Results ordered by saldo_id
	GetActiveSaldos(ctx context.Context, arg GetActiveSaldosParams) ([]*GetActiveSaldosRow, error)
	// GetMonthlySaldoBalances: Retrieves monthly balance totals for a given year
	// Purpose: Provide monthly balance trends for financial reporting and dashboards
	// Parameters:
	//   $1: reference_date - A date used to determine the year to analyze
	// Returns:
	//   month: 3-letter month abbreviation (e.g., 'Jan', 'Feb')
	//   total_balance: Sum of balances for that month (0 if no data exists)
	// Business Logic:
	//   - Generates a complete 12-month series for the specified year
	//   - Uses LEFT JOIN to ensure all months appear in results
	//   - COALESCE returns 0 for months with no balance data
	//   - Only includes active saldo records (deleted_at IS NULL)
	//   - Groups by month and orders chronologically
	//   - Useful for cash flow analysis and financial planning
	GetMonthlySaldoBalances(ctx context.Context, dollar_1 time.Time) ([]*GetMonthlySaldoBalancesRow, error)
	// GetMonthlyTotalSaldoBalance: Retrieves monthly balance totals for comparison periods
	// Purpose: Compare monthly balance trends between two time periods
	// Parameters:
	//   $1: period1_start - Start date of first comparison period
	//   $2: period1_end - End date of first comparison period
	//   $3: period2_start - Start date of second comparison period
	//   $4: period2_end - End date of second comparison period
	// Returns:
	//   year: The year as text
	//   month: 3-letter month abbreviation
	//   total_balance: Monthly balance total (0 if no data)
	// Business Logic:
	//   - Aggregates balances for two customizable time periods
	//   - Only includes active saldos (deleted_at IS NULL)
	//   - Ensures both periods' months appear with zero-filling
	//   - Formats output for consistent visualization
	//   - Results ordered by year and month (newest first)
	GetMonthlyTotalSaldoBalance(ctx context.Context, arg GetMonthlyTotalSaldoBalanceParams) ([]*GetMonthlyTotalSaldoBalanceRow, error)
	// GetRole: Retrieves role details by role_id
	// Purpose: Fetch a single role record (regardless of deleted status)
	// Parameters:
	//   $1: Role ID
	// Returns:
	//   role_id, role_name, and timestamps
	GetRole(ctx context.Context, roleID int32) (*Role, error)
	// GetRoleByName: Retrieves role by exact role name
	// Purpose: Check role existence or fetch role info based on name
	// Parameters:
	//   $1: Role name (exact match)
	// Returns:
	//   role_id, role_name, and timestamps
	GetRoleByName(ctx context.Context, roleName string) (*Role, error)
	// GetRoles: Retrieves all roles (active & trashed) with optional name search and pagination
	// Purpose: General listing of roles regardless of status
	// Parameters:
	//   $1: Search query (role name, nullable)
	//   $2: Limit (number of records per page)
	//   $3: Offset (starting index for pagination)
	// Returns:
	//   role_id, role_name, timestamps, and total_count (for pagination support)
	// Business Logic:
	//   - Supports fuzzy search on role_name
	//   - Includes both active and trashed roles
	//   - Useful for admin panels with filters and pagination
	GetRoles(ctx context.Context, arg GetRolesParams) ([]*GetRolesRow, error)
	// GetSaldoByCardNumber: Retrieves saldo information for a specific card
	// Purpose: Get the current balance and details for a particular card
	// Parameters:
	//   $1: card_number - The card number to lookup
	// Returns:
	//   All saldo fields for the active record matching the card number
	// Business Logic:
	//   - Only returns active saldo records (deleted_at IS NULL)
	//   - Useful for checking card balances before transactions
	GetSaldoByCardNumber(ctx context.Context, cardNumber string) (*Saldo, error)
	// GetSaldoByID: Retrieves single active saldo by ID
	// Purpose: Fetch a specific saldo record for display or processing
	// Parameters:
	//   $1: saldo_id - Unique identifier of the saldo
	// Returns:
	//   Single saldo record if it is active (deleted_at IS NULL)
	// Business Logic:
	//   - Ensures only active saldos are returned (soft-deleted saldos are excluded)
	//   - Used for detail views or transaction lookups
	GetSaldoByID(ctx context.Context, saldoID int32) (*GetSaldoByIDRow, error)
	// GetSaldos: Retrieves paginated list of active saldos with search capability
	// Purpose: List all active saldos for admin or user dashboard with optional filtering
	// Parameters:
	//   $1: search_term - Optional text to filter saldos by card_number (NULL for no filter)
	//   $2: limit - Maximum number of records to return
	//   $3: offset - Number of records to skip for pagination
	// Returns:
	//   All saldo fields plus total_count of matching records
	// Business Logic:
	//   - Excludes soft-deleted saldos (deleted_at IS NULL)
	//   - Supports partial text matching on card_number (case-insensitive)
	//   - Returns saldos ordered by saldo_id
	//   - Provides total_count for pagination calculations
	GetSaldos(ctx context.Context, arg GetSaldosParams) ([]*GetSaldosRow, error)
	// GetTrashedRoles: Retrieves only soft-deleted roles with optional search and pagination
	// Purpose: For trash/recycle bin management
	// Parameters:
	//   $1: Search query (nullable)
	//   $2: Limit
	//   $3: Offset
	// Returns:
	//   role_id, role_name, timestamps, and total_count
	GetTrashedRoles(ctx context.Context, arg GetTrashedRolesParams) ([]*GetTrashedRolesRow, error)
	// GetTrashedSaldoByID: Retrieves a single soft-deleted saldo record by ID
	// Purpose: View details of a trashed saldo for recovery or audit purposes
	// Parameters:
	//   $1: saldo_id - The ID of the saldo record to retrieve
	// Returns:
	//   All fields for the specified trashed saldo or NULL if not found/not deleted
	// Business Logic:
	//   - Only returns soft-deleted saldos (deleted_at IS NOT NULL)
	//   - Useful for admin interfaces showing deleted items
	//   - Can be used before restoring a deleted saldo
	GetTrashedSaldoByID(ctx context.Context, saldoID int32) (*Saldo, error)
	// GetTrashedSaldos: Retrieves soft-deleted saldos with search and pagination
	// Purpose: Display trashed saldos for recovery or permanent deletion
	// Parameters:
	//   $1: search_term - Optional search by card_number (NULL for no filter)
	//   $2: limit - Max number of records
	//   $3: offset - Number of rows to skip
	// Returns:
	//   List of trashed saldos and total_count of matches
	// Business Logic:
	//   - Includes only soft-deleted saldos (deleted_at IS NOT NULL)
	//   - Partial match on card_number
	//   - Useful for building a "Trash Bin" feature in the UI
	GetTrashedSaldos(ctx context.Context, arg GetTrashedSaldosParams) ([]*GetTrashedSaldosRow, error)
	// GetUserRoles: Retrieves all roles assigned to a specific user
	// Purpose: Identify the access level(s) of a user
	// Parameters:
	//   $1: User ID
	// Returns:
	//   List of roles (id, name, timestamps)
	GetUserRoles(ctx context.Context, userID int32) ([]*Role, error)
	// GetYearlySaldoBalances: Retrieves yearly balance totals for a 5-year period
	// Purpose: Show annual balance trends for long-term financial analysis
	// Parameters:
	//   $1: reference_year - The target year (includes this year plus previous 4 years)
	// Returns:
	//   year: The 4-digit year
	//   total_balance: Sum of balances for that year
	// Business Logic:
	//   - Covers a 5-year rolling window (reference_year-4 to reference_year)
	//   - Only includes active saldo records (deleted_at IS NULL)
	//   - Groups by calendar year
	//   - Results ordered chronologically
	//   - Useful for identifying year-over-year trends and growth patterns
	GetYearlySaldoBalances(ctx context.Context, dollar_1 interface{}) ([]*GetYearlySaldoBalancesRow, error)
	// GetYearlyTotalSaldoBalances: Retrieves yearly balance totals for current and previous year
	// Purpose: Compare annual balance trends between current and previous year
	// Parameters:
	//   $1: current_year - The year to analyze (includes this year and previous)
	// Returns:
	//   year: The year as text
	//   total_balance: Annual balance total (0 if no data)
	// Business Logic:
	//   - Shows comparison between specified year and previous year
	//   - Only includes active saldos (deleted_at IS NULL)
	//   - Ensures both years appear with zero-filling if missing
	//   - Results ordered by year (newest first)
	//   - Useful for year-over-year financial analysis
	GetYearlyTotalSaldoBalances(ctx context.Context, dollar_1 int32) ([]*GetYearlyTotalSaldoBalancesRow, error)
	// RestoreAllRoles: Restores all soft-deleted roles in bulk
	// Purpose: Bulk recovery of all trashed roles
	// Parameters: None
	RestoreAllRoles(ctx context.Context) error
	// RestoreAllSaldos: Recovers all trashed saldo records
	// Purpose: Mass restoration of deleted saldos
	// Business Logic:
	//   - Clears deleted_at for all trashed records
	//   - Useful for system recovery scenarios
	RestoreAllSaldos(ctx context.Context) error
	// RestoreRole: Restores a previously trashed role
	// Purpose: Undelete a soft-deleted role
	// Parameters:
	//   $1: Role ID
	RestoreRole(ctx context.Context, roleID int32) (*Role, error)
	// RestoreSaldo: Recovers a soft-deleted saldo
	// Purpose: Reactivate a previously trashed saldo record
	// Parameters:
	//   $1: saldo_id - The ID of the saldo to restore
	// Business Logic:
	//   - Clears the deleted_at timestamp
	//   - Only works on currently trashed records
	RestoreSaldo(ctx context.Context, saldoID int32) (*Saldo, error)
	// TrashRole: Soft-deletes a role (moves to trash)
	// Purpose: Mark role as deleted without removing it permanently
	// Parameters:
	//   $1: Role ID
	TrashRole(ctx context.Context, roleID int32) (*Role, error)
	// TrashSaldo: Soft-deletes a saldo record
	// Purpose: Remove a saldo from active use without permanent deletion
	// Parameters:
	//   $1: saldo_id - The ID of the saldo to trash
	// Business Logic:
	//   - Sets deleted_at timestamp
	//   - Only affects currently active records
	//   - Preserves data for possible recovery
	TrashSaldo(ctx context.Context, saldoID int32) (*Saldo, error)
	// UpdateRole: Updates role name by ID
	// Purpose: Modify role information (e.g., name correction)
	// Parameters:
	//   $1: Role ID
	//   $2: New role name
	// Returns:
	//   Updated role's data
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (*Role, error)
	// UpdateSaldo: Modifies saldo record details
	// Purpose: Update card number and balance for an existing saldo
	// Parameters:
	//   $1: saldo_id - The ID of the saldo to update
	//   $2: card_number - New card number to associate
	//   $3: total_balance - New balance amount
	// Business Logic:
	//   - Only updates active records (deleted_at IS NULL)
	//   - Automatically updates the modification timestamp
	//   - Useful for administrative corrections
	UpdateSaldo(ctx context.Context, arg UpdateSaldoParams) (*UpdateSaldoRow, error)
	// UpdateSaldoBalance: Updates only the balance amount for a card
	// Purpose: Adjust card balance without changing card association
	// Parameters:
	//   $1: card_number - The card number to update
	//   $2: total_balance - New balance amount
	// Business Logic:
	//   - Card-specific update (uses card_number instead of saldo_id)
	//   - Only updates active records
	//   - Useful for balance adjustments and corrections
	UpdateSaldoBalance(ctx context.Context, arg UpdateSaldoBalanceParams) (*UpdateSaldoBalanceRow, error)
	// UpdateSaldoWithdraw: Processes a withdrawal transaction
	// Purpose: Record a withdrawal and update the remaining balance
	// Parameters:
	//   $1: card_number - The card used for withdrawal
	//   $2: withdraw_amount - The amount being withdrawn
	//   $3: withdraw_time - Timestamp of the withdrawal
	// Business Logic:
	//   - Only processes if sufficient balance exists (total_balance >= $2)
	//   - Updates both withdrawal amount and remaining balance
	//   - Records withdrawal timestamp
	//   - Only affects active records
	UpdateSaldoWithdraw(ctx context.Context, arg UpdateSaldoWithdrawParams) (*UpdateSaldoWithdrawRow, error)
	// UpdateSaldoWithdrawMetadata: Records withdrawal metadata after the atomic ledger debit.
	UpdateSaldoWithdrawMetadata(ctx context.Context, arg UpdateSaldoWithdrawMetadataParams) (*UpdateSaldoWithdrawMetadataRow, error)
}

var _ Querier = (*Queries)(nil)
