// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Merchant struct {
	MerchantID int32            `json:"merchant_id"`
	MerchantNo pgtype.UUID      `json:"merchant_no"`
	Name       string           `json:"name"`
	ApiKey     string           `json:"api_key"`
	UserID     int32            `json:"user_id"`
	Status     string           `json:"status"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
	DeletedAt  pgtype.Timestamp `json:"deleted_at"`
}

type MerchantDocument struct {
	DocumentID   int32            `json:"document_id"`
	MerchantID   int32            `json:"merchant_id"`
	DocumentType string           `json:"document_type"`
	DocumentUrl  string           `json:"document_url"`
	Status       string           `json:"status"`
	Note         *string          `json:"note"`
	UploadedAt   pgtype.Timestamp `json:"uploaded_at"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	DeletedAt    pgtype.Timestamp `json:"deleted_at"`
}

type Role struct {
	RoleID    int32            `json:"role_id"`
	RoleName  string           `json:"role_name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	DeletedAt pgtype.Timestamp `json:"deleted_at"`
}

type Transaction struct {
	TransactionID   int32            `json:"transaction_id"`
	TransactionNo   pgtype.UUID      `json:"transaction_no"`
	CardNumber      string           `json:"card_number"`
	Amount          int64            `json:"amount"`
	PaymentMethod   string           `json:"payment_method"`
	MerchantID      int32            `json:"merchant_id"`
	TransactionTime time.Time        `json:"transaction_time"`
	Status          string           `json:"status"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	DeletedAt       pgtype.Timestamp `json:"deleted_at"`
}

type UserRole struct {
	UserRoleID int32            `json:"user_role_id"`
	UserID     int32            `json:"user_id"`
	RoleID     int32            `json:"role_id"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
	DeletedAt  pgtype.Timestamp `json:"deleted_at"`
}
