// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"time"
)

type Querier interface {
	// Create Merchant
	// Purpose: Insert a new merchant record into the database
	// Parameters:
	//   $1: name - The name of the merchant
	//   $2: api_key - Unique API key for the merchant
	//   $3: user_id - ID of the user associated with the merchant
	//   $4: status - Current status of the merchant (e.g., active, inactive)
	// Returns:
	//   - The newly created merchant record
	// Business Logic:
	//   - Inserts a new merchant with the provided details.
	//   - Sets the created_at and updated_at timestamps to the current time.
	//   - Returns the created merchant's data using the RETURNING clause.
	CreateMerchant(ctx context.Context, arg CreateMerchantParams) (*CreateMerchantRow, error)
	CreateMerchantDocument(ctx context.Context, arg CreateMerchantDocumentParams) (*CreateMerchantDocumentRow, error)
	// CreateRole: Inserts a new role into the system
	// Purpose: Add new role definitions (e.g., Admin, Cashier, etc.)
	// Parameters:
	//   $1: Role name
	// Returns:
	//   Newly created role's full data (including timestamps)
	CreateRole(ctx context.Context, roleName string) (*Role, error)
	DeleteAllPermanentMerchantDocuments(ctx context.Context) error
	// Delete All Trashed Merchants Permanently
	// Purpose: Permanently delete all merchants that are soft deleted
	// Business Logic:
	//   - Permanently deletes all merchants that have been soft deleted (i.e., deleted_at is not NULL).
	//   - Removes these merchants completely from the database.
	DeleteAllPermanentMerchants(ctx context.Context) error
	// DeleteAllPermanentRoles: Permanently deletes all soft-deleted roles
	// Purpose: Bulk cleanup of trashed roles
	// Parameters: None
	DeleteAllPermanentRoles(ctx context.Context) error
	DeleteMerchantDocumentPermanently(ctx context.Context, documentID int32) error
	// Delete Merchant Permanently
	// Purpose: Permanently delete a merchant from the database
	// Parameters:
	//   $1: merchant_id - ID of the merchant to be permanently deleted
	// Business Logic:
	//   - Deletes the specified merchant from the database.
	//   - Ensures the merchant is marked as deleted (deleted_at is not NULL).
	DeleteMerchantPermanently(ctx context.Context, merchantID int32) error
	// DeletePermanentRole: Permanently deletes a trashed role
	// Purpose: Remove role from DB after soft delete
	// Parameters:
	//   $1: Role ID
	DeletePermanentRole(ctx context.Context, roleID int32) error
	// FindAllTransactions: Retrieves a paginated list of active transactions with optional search
	// Purpose: Display transaction list with merchant info, filtered by card number or payment method
	// Parameters:
	//   $1: search_query (TEXT, nullable) - Optional search string to match card_number or payment_method
	//   $2: limit (INTEGER) - Maximum number of records to return (pagination)
	//   $3: offset (INTEGER) - Number of records to skip (pagination)
	// Returns:
	//   - transaction_id
	//   - card_number
	//   - amount
	//   - payment_method
	//   - merchant_id
	//   - merchant_name (from join with merchants table)
	//   - transaction_time
	//   - created_at, updated_at, deleted_at (for audit purposes)
	//   - total_count: Total number of records matching the filter (useful for pagination metadata)
	// Business Logic:
	//   - Joins `transactions` with `merchants` to retrieve merchant name
	//   - Filters out soft-deleted transactions (where deleted_at IS NOT NULL)
	//   - Applies case-insensitive partial match on card_number or payment_method if search query is provided
	//   - Uses `COUNT(*) OVER()` to include total matching count for pagination without a separate query
	//   - Results are ordered by `transaction_time` descending
	FindAllTransactions(ctx context.Context, arg FindAllTransactionsParams) ([]*FindAllTransactionsRow, error)
	// FindAllTransactions: Retrieves a paginated list of active transactions with optional search
	// Purpose: Display transaction list with merchant info, filtered by card number or payment method
	// Parameters:
	//   $1: api-key - The merchant to filter transactions
	//   $2: search_query (TEXT, nullable) - Optional search string to match card_number or payment_method
	//   $3: limit (INTEGER) - Maximum number of records to return (pagination)
	//   $4: offset (INTEGER) - Number of records to skip (pagination)
	// Returns:
	//   - transaction_id
	//   - card_number
	//   - amount
	//   - payment_method
	//   - merchant_id
	//   - merchant_name (from join with merchants table)
	//   - transaction_time
	//   - created_at, updated_at, deleted_at (for audit purposes)
	//   - total_count: Total number of records matching the filter (useful for pagination metadata)
	// Business Logic:
	//   - Joins `transactions` with `merchants` to retrieve merchant name
	//   - Filters out soft-deleted transactions (where deleted_at IS NOT NULL)
	//   - Applies case-insensitive partial match on card_number or payment_method if search query is provided
	//   - Uses `COUNT(*) OVER()` to include total matching count for pagination without a separate query
	//   - Results are ordered by `transaction_time` descending
	FindAllTransactionsByApikey(ctx context.Context, arg FindAllTransactionsByApikeyParams) ([]*FindAllTransactionsByApikeyRow, error)
	// FindAllTransactions: Retrieves a paginated list of active transactions with optional search
	// Purpose: Display transaction list with merchant info, filtered by card number or payment method
	// Parameters:
	//   $1: merchant_id - The merchant to filter transactions
	//   $2: search_query (TEXT, nullable) - Optional search string to match card_number or payment_method
	//   $3: limit (INTEGER) - Maximum number of records to return (pagination)
	//   $4: offset (INTEGER) - Number of records to skip (pagination)
	// Returns:
	//   - transaction_id
	//   - card_number
	//   - amount
	//   - payment_method
	//   - merchant_id
	//   - merchant_name (from join with merchants table)
	//   - transaction_time
	//   - created_at, updated_at, deleted_at (for audit purposes)
	//   - total_count: Total number of records matching the filter (useful for pagination metadata)
	// Business Logic:
	//   - Joins `transactions` with `merchants` to retrieve merchant name
	//   - Filters out soft-deleted transactions (where deleted_at IS NOT NULL)
	//   - Applies case-insensitive partial match on card_number or payment_method if search query is provided
	//   - Uses `COUNT(*) OVER()` to include total matching count for pagination without a separate query
	//   - Results are ordered by `transaction_time` descending
	FindAllTransactionsByMerchant(ctx context.Context, arg FindAllTransactionsByMerchantParams) ([]*FindAllTransactionsByMerchantRow, error)
	GetActiveMerchantDocuments(ctx context.Context, arg GetActiveMerchantDocumentsParams) ([]*GetActiveMerchantDocumentsRow, error)
	// GetActiveMerchants: Retrieves paginated list of active merchants with search capability
	// Purpose: List currently active merchants (same as GetMerchants)
	// Parameters:
	//   $1: search_term - Optional text to filter by name, api_key, or status (NULL for no filter)
	//   $2: limit - Maximum number of records to return
	//   $3: offset - Number of records to skip for pagination
	// Returns:
	//   All merchant fields plus total_count of matching records
	// Business Logic:
	//   - Excludes soft-deleted merchants (deleted_at IS NULL)
	//   - Supports case-insensitive partial matching on name, api_key, and status
	//   - Returns results ordered by merchant_id
	//   - Provides total_count for pagination calculations
	GetActiveMerchants(ctx context.Context, arg GetActiveMerchantsParams) ([]*GetActiveMerchantsRow, error)
	// GetActiveRoles: Retrieves only active (non-deleted) roles with optional search and pagination
	// Purpose: Display roles that are currently usable in the system
	// Parameters:
	//   $1: Search query (nullable)
	//   $2: Limit
	//   $3: Offset
	// Returns:
	//   role_id, role_name, timestamps, and total_count
	GetActiveRoles(ctx context.Context, arg GetActiveRolesParams) ([]*GetActiveRolesRow, error)
	// GetMerchantByApiKey: Retrieves a merchant by its API key
	// Purpose: Authenticate or lookup a merchant using its API key
	// Parameters:
	//   $1: api_key - API key of the merchant
	// Returns:
	//   Complete merchant record
	// Business Logic:
	//   - Excludes soft-deleted merchants (deleted_at IS NULL)
	GetMerchantByApiKey(ctx context.Context, apiKey string) (*GetMerchantByApiKeyRow, error)
	// GetMerchantByID: Retrieves a merchant by its unique ID
	// Purpose: Fetch details of a single merchant if not soft-deleted
	// Parameters:
	//   $1: merchant_id - Unique identifier of the merchant
	// Returns:
	//   Complete merchant record
	// Business Logic:
	//   - Excludes soft-deleted merchants (deleted_at IS NULL)
	GetMerchantByID(ctx context.Context, merchantID int32) (*GetMerchantByIDRow, error)
	// GetMerchantByName: Retrieves a merchant by its name
	// Purpose: Find merchant data based on exact name match
	// Parameters:
	//   $1: name - Exact name of the merchant
	// Returns:
	//   Complete merchant record
	// Business Logic:
	//   - Excludes soft-deleted merchants (deleted_at IS NULL)
	GetMerchantByName(ctx context.Context, name string) (*GetMerchantByNameRow, error)
	GetMerchantDocument(ctx context.Context, documentID int32) (*GetMerchantDocumentRow, error)
	GetMerchantDocuments(ctx context.Context, arg GetMerchantDocumentsParams) ([]*GetMerchantDocumentsRow, error)
	// GetMerchants: Retrieves paginated list of all non-deleted merchants with search capability
	// Purpose: Display all active (non-trashed) merchants in admin interface
	// Parameters:
	//   $1: search_term - Optional text to filter by name, api_key, or status (NULL for no filter)
	//   $2: limit - Maximum number of records to return
	//   $3: offset - Number of records to skip for pagination
	// Returns:
	//   All merchant fields plus total_count of matching records
	// Business Logic:
	//   - Excludes soft-deleted merchants (deleted_at IS NULL)
	//   - Supports partial text search on name, api_key, and status (case-insensitive)
	//   - Returns results ordered by merchant_id
	//   - Provides total_count for pagination calculations
	GetMerchants(ctx context.Context, arg GetMerchantsParams) ([]*GetMerchantsRow, error)
	// GetMerchantsByUserID: Retrieves all merchants associated with a user
	// Purpose: List all merchants that belong to a specific user
	// Parameters:
	//   $1: user_id - ID of the user who owns the merchants
	// Returns:
	//   List of merchant records
	// Business Logic:
	//   - Excludes soft-deleted merchants (deleted_at IS NULL)
	GetMerchantsByUserID(ctx context.Context, userID int32) ([]*GetMerchantsByUserIDRow, error)
	// GetMonthlyAmountByApikey: Retrieves total transaction amount per month for a specific merchant and year
	// Purpose: Generate monthly income report for a specific merchant regardless of payment method
	// Parameters:
	//   $1: reference_date - Any date within the target year
	//   $2: api-key - The merchant to filter transactions
	// Returns:
	//   - Month name (e.g., Jan, Feb)
	//   - Total transaction amount (0 if no activity)
	// Business Logic:
	//   - Generates complete 12-month series for the given year
	//   - Filters only active (non-deleted) transactions and merchants
	//   - Filters by specific merchant_id
	//   - Uses LEFT JOIN to ensure each month is represented
	//   - Uses COALESCE to return 0 if a month has no transaction data
	//   - Results are ordered chronologically by month
	GetMonthlyAmountByApikey(ctx context.Context, arg GetMonthlyAmountByApikeyParams) ([]*GetMonthlyAmountByApikeyRow, error)
	// GetMonthlyAmountByMerchants: Retrieves total transaction amount per month for a specific merchant and year
	// Purpose: Generate monthly income report for a specific merchant regardless of payment method
	// Parameters:
	//   $1: reference_date - Any date within the target year
	//   $2: merchant_id - The merchant to filter transactions
	// Returns:
	//   - Month name (e.g., Jan, Feb)
	//   - Total transaction amount (0 if no activity)
	// Business Logic:
	//   - Generates complete 12-month series for the given year
	//   - Filters only active (non-deleted) transactions and merchants
	//   - Filters by specific merchant_id
	//   - Uses LEFT JOIN to ensure each month is represented
	//   - Uses COALESCE to return 0 if a month has no transaction data
	//   - Results are ordered chronologically by month
	GetMonthlyAmountByMerchants(ctx context.Context, arg GetMonthlyAmountByMerchantsParams) ([]*GetMonthlyAmountByMerchantsRow, error)
	// GetMonthlyAmountMerchant: Retrieves total transaction amount per month for a given year
	// Purpose: Generate monthly income report regardless of payment method
	// Parameters:
	//   $1: reference_date - Any date within the target year
	// Returns:
	//   - Month name (e.g., Jan, Feb)
	//   - Total transaction amount (0 if no activity)
	// Business Logic:
	//   - Generates complete 12-month series
	//   - Includes only active (non-deleted) transactions and merchants
	//   - Uses LEFT JOIN to ensure each month is represented
	//   - Uses COALESCE to return 0 if a month has no data
	//   - Ordered chronologically by month
	GetMonthlyAmountMerchant(ctx context.Context, dollar_1 time.Time) ([]*GetMonthlyAmountMerchantRow, error)
	// GetMonthlyPaymentMethodByApikey: Retrieves total transaction amount per payment method per month for a specific merchant
	// Purpose: Analyze monthly transaction totals by payment method for a specific merchant and year
	// Parameters:
	//   $1: reference_date - Any date within the target year
	//   $2: api-key - The merchant to filter transactions
	// Returns:
	//   - Month name (e.g., Jan, Feb)
	//   - Payment method
	//   - Total transaction amount for each combination
	// Business Logic:
	//   - Generates a complete 12-month series for the given year
	//   - Filters only active (non-deleted) transactions and merchants
	//   - Filters by specific merchant_id
	//   - Uses LEFT JOIN and CROSS JOIN to ensure all months and payment methods are included
	//   - Uses COALESCE to return 0 for combinations with no data
	//   - Results are ordered chronologically by month
	GetMonthlyPaymentMethodByApikey(ctx context.Context, arg GetMonthlyPaymentMethodByApikeyParams) ([]*GetMonthlyPaymentMethodByApikeyRow, error)
	// GetMonthlyPaymentMethodByMerchants: Retrieves total transaction amount per payment method per month for a specific merchant
	// Purpose: Analyze monthly transaction totals by payment method for a specific merchant and year
	// Parameters:
	//   $1: reference_date - Any date within the target year
	//   $2: merchant_id - The merchant to filter transactions
	// Returns:
	//   - Month name (e.g., Jan, Feb)
	//   - Payment method
	//   - Total transaction amount for each combination
	// Business Logic:
	//   - Generates a complete 12-month series for the given year
	//   - Filters only active (non-deleted) transactions and merchants
	//   - Filters by specific merchant_id
	//   - Uses LEFT JOIN and CROSS JOIN to ensure all months and payment methods are included
	//   - Uses COALESCE to return 0 for combinations with no data
	//   - Results are ordered chronologically by month
	GetMonthlyPaymentMethodByMerchants(ctx context.Context, arg GetMonthlyPaymentMethodByMerchantsParams) ([]*GetMonthlyPaymentMethodByMerchantsRow, error)
	// GetMonthlyPaymentMethodsMerchant: Retrieves monthly transaction totals per payment method
	// Purpose: Analyze monthly transaction distribution across payment methods for a given year
	// Parameters:
	//   $1: reference_date - Any date within the target year
	// Returns:
	//   - Month name (e.g., Jan, Feb)
	//   - Payment method
	//   - Total transaction amount (0 if no activity)
	// Business Logic:
	//   - Generates complete 12-month series from the reference year
	//   - Cross joins with distinct active payment methods
	//   - Filters only active (non-deleted) transactions and merchants
	//   - Uses LEFT JOIN to ensure all month-method combinations are included
	//   - Uses COALESCE to display 0 for months with no transactions
	//   - Ordered by month and payment method
	GetMonthlyPaymentMethodsMerchant(ctx context.Context, dollar_1 time.Time) ([]*GetMonthlyPaymentMethodsMerchantRow, error)
	// GetMonthlyTotalAmountByApikey: Retrieves total transaction amounts for the current and previous month
	// Purpose: Provide monthly transaction summary including zero values if no transactions exist
	// Parameters:
	//   $1: reference_date - Any date within the target (current) month
	//   $2: api-key - The merchant to filter transactions
	// Returns:
	//   - Year (as text)
	//   - Month (abbreviated name, e.g., Jan, Feb)
	//   - Total transaction amount for each month
	// Business Logic:
	//   - Aggregates total transaction amounts for the target month and the month before
	//   - Filters only active (non-deleted) transactions and merchants
	//   - Includes 0 as total_amount if there's no transaction data for either month
	//   - Uses UNION ALL to combine real data with "missing month" placeholders
	//   - Results are sorted by year and month (most recent first)
	GetMonthlyTotalAmountByApikey(ctx context.Context, arg GetMonthlyTotalAmountByApikeyParams) ([]*GetMonthlyTotalAmountByApikeyRow, error)
	// GetMonthlyTotalAmountByMerchant: Retrieves total transaction amounts for the current and previous month
	// Purpose: Provide monthly transaction summary including zero values if no transactions exist
	// Parameters:
	//   $1: reference_date - Any date within the target (current) month
	//   $2: merchant_id - The merchant to filter transactions
	// Returns:
	//   - Year (as text)
	//   - Month (abbreviated name, e.g., Jan, Feb)
	//   - Total transaction amount for each month
	// Business Logic:
	//   - Aggregates total transaction amounts for the target month and the month before
	//   - Filters only active (non-deleted) transactions and merchants
	//   - Includes 0 as total_amount if there's no transaction data for either month
	//   - Uses UNION ALL to combine real data with "missing month" placeholders
	//   - Results are sorted by year and month (most recent first)
	GetMonthlyTotalAmountByMerchant(ctx context.Context, arg GetMonthlyTotalAmountByMerchantParams) ([]*GetMonthlyTotalAmountByMerchantRow, error)
	// GetMonthlyTotalAmountMerchant: Retrieves total transaction amounts for the current and previous month
	// Purpose: Provide monthly transaction summary including zero values if no transactions exist
	// Parameters:
	//   $1: reference_date - Any date within the target (current) month
	// Returns:
	//   - Year (as text)
	//   - Month (abbreviated name, e.g., Jan, Feb)
	//   - Total transaction amount for each month
	// Business Logic:
	//   - Aggregates total transaction amounts for the target month and the month before
	//   - Filters only active (non-deleted) transactions and merchants
	//   - Includes 0 as total_amount if there's no transaction data for either month
	//   - Uses UNION ALL to combine real data with "missing month" placeholders
	//   - Results are sorted by year and month (most recent first)
	GetMonthlyTotalAmountMerchant(ctx context.Context, dollar_1 time.Time) ([]*GetMonthlyTotalAmountMerchantRow, error)
	// GetRole: Retrieves role details by role_id
	// Purpose: Fetch a single role record (regardless of deleted status)
	// Parameters:
	//   $1: Role ID
	// Returns:
	//   role_id, role_name, and timestamps
	GetRole(ctx context.Context, roleID int32) (*Role, error)
	// GetRoleByName: Retrieves role by exact role name
	// Purpose: Check role existence or fetch role info based on name
	// Parameters:
	//   $1: Role name (exact match)
	// Returns:
	//   role_id, role_name, and timestamps
	GetRoleByName(ctx context.Context, roleName string) (*Role, error)
	// GetRoles: Retrieves all roles (active & trashed) with optional name search and pagination
	// Purpose: General listing of roles regardless of status
	// Parameters:
	//   $1: Search query (role name, nullable)
	//   $2: Limit (number of records per page)
	//   $3: Offset (starting index for pagination)
	// Returns:
	//   role_id, role_name, timestamps, and total_count (for pagination support)
	// Business Logic:
	//   - Supports fuzzy search on role_name
	//   - Includes both active and trashed roles
	//   - Useful for admin panels with filters and pagination
	GetRoles(ctx context.Context, arg GetRolesParams) ([]*GetRolesRow, error)
	// GetTrashedMerchantByID: Retrieves a soft-deleted merchant by ID
	// Purpose: Access trashed merchant record for potential restoration or inspection
	// Parameters:
	//   $1: merchant_id - Unique identifier of the merchant
	// Returns:
	//   Trashed merchant record
	// Business Logic:
	//   - Includes only merchants that have been soft-deleted (deleted_at IS NOT NULL)
	GetTrashedMerchantByID(ctx context.Context, merchantID int32) (*Merchant, error)
	GetTrashedMerchantDocuments(ctx context.Context, arg GetTrashedMerchantDocumentsParams) ([]*GetTrashedMerchantDocumentsRow, error)
	// GetTrashedMerchants: Retrieves paginated list of soft-deleted merchants with search capability
	// Purpose: View trashed merchants for potential restoration or permanent deletion
	// Parameters:
	//   $1: search_term - Optional text to filter by name, api_key, or status (NULL for no filter)
	//   $2: limit - Maximum number of records to return
	//   $3: offset - Number of records to skip for pagination
	// Returns:
	//   All merchant fields plus total_count of matching records
	// Business Logic:
	//   - Only includes soft-deleted merchants (deleted_at IS NOT NULL)
	//   - Supports partial text search (case-insensitive) on name, api_key, and status
	//   - Returns results ordered by merchant_id
	//   - Provides total_count for pagination calculations
	GetTrashedMerchants(ctx context.Context, arg GetTrashedMerchantsParams) ([]*GetTrashedMerchantsRow, error)
	// GetTrashedRoles: Retrieves only soft-deleted roles with optional search and pagination
	// Purpose: For trash/recycle bin management
	// Parameters:
	//   $1: Search query (nullable)
	//   $2: Limit
	//   $3: Offset
	// Returns:
	//   role_id, role_name, timestamps, and total_count
	GetTrashedRoles(ctx context.Context, arg GetTrashedRolesParams) ([]*GetTrashedRolesRow, error)
	// GetUserRoles: Retrieves all roles assigned to a specific user
	// Purpose: Identify the access level(s) of a user
	// Parameters:
	//   $1: User ID
	// Returns:
	//   List of roles (id, name, timestamps)
	GetUserRoles(ctx context.Context, userID int32) ([]*Role, error)
	// GetYearlyAmountByMerchants: Retrieves total transaction amount per year for the last 5 years for a specific merchant
	// Purpose: Show overall yearly revenue trends for a merchant across all payment methods
	// Parameters:
	//   $1: api-key - The merchant to filter transactions
	//   $2: current_year - The latest year to include in the 5-year window
	// Returns:
	//   - Year (e.g., 2021, 2022)
	//   - Total transaction amount
	// Business Logic:
	//   - Filters only active (non-deleted) transactions and merchants
	//   - Filters by specific merchant_id
	//   - Includes data for the last 5 calendar years up to the current year
	//   - Groups by calendar year
	//   - Results are ordered chronologically by year
	GetYearlyAmountByApikey(ctx context.Context, arg GetYearlyAmountByApikeyParams) ([]*GetYearlyAmountByApikeyRow, error)
	// GetYearlyAmountByMerchants: Retrieves total transaction amount per year for the last 5 years for a specific merchant
	// Purpose: Show overall yearly revenue trends for a merchant across all payment methods
	// Parameters:
	//   $1: merchant_id - The merchant to filter transactions
	//   $2: current_year - The latest year to include in the 5-year window
	// Returns:
	//   - Year (e.g., 2021, 2022)
	//   - Total transaction amount
	// Business Logic:
	//   - Filters only active (non-deleted) transactions and merchants
	//   - Filters by specific merchant_id
	//   - Includes data for the last 5 calendar years up to the current year
	//   - Groups by calendar year
	//   - Results are ordered chronologically by year
	GetYearlyAmountByMerchants(ctx context.Context, arg GetYearlyAmountByMerchantsParams) ([]*GetYearlyAmountByMerchantsRow, error)
	// GetYearlyAmountMerchant: Retrieves total transaction amount per year for the last 5 years
	// Purpose: Show overall yearly revenue trends across all payment methods
	// Parameters:
	//   $1: current_year - The latest year to include in the 5-year window
	// Returns:
	//   - Year (e.g., 2021, 2022)
	//   - Total transaction amount
	// Business Logic:
	//   - Aggregates yearly transaction amounts
	//   - Filters only active (non-deleted) transactions and merchants
	//   - Includes data for the last 5 calendar years up to the current year
	//   - Ordered chronologically by year
	GetYearlyAmountMerchant(ctx context.Context, dollar_1 interface{}) ([]*GetYearlyAmountMerchantRow, error)
	// GetYearlyPaymentMethodByApikey: Retrieves total transaction amount per payment method over the last 5 years for a specific merchant
	// Purpose: Analyze yearly transaction totals grouped by payment method for a merchant
	// Parameters:
	//   $1: api-key - The merchant to filter transactions
	//   $2: current_year - The latest year to include in the 5-year window
	// Returns:
	//   - Year (e.g., 2021, 2022)
	//   - Payment method
	//   - Total transaction amount
	// Business Logic:
	//   - Filters only active (non-deleted) transactions and merchants
	//   - Filters by specific merchant_id
	//   - Includes data for the last 5 calendar years up to the current year
	//   - Groups by calendar year and payment method
	//   - Results are ordered chronologically by year
	GetYearlyPaymentMethodByApikey(ctx context.Context, arg GetYearlyPaymentMethodByApikeyParams) ([]*GetYearlyPaymentMethodByApikeyRow, error)
	// GetYearlyPaymentMethodByMerchants: Retrieves total transaction amount per payment method over the last 5 years for a specific merchant
	// Purpose: Analyze yearly transaction totals grouped by payment method for a merchant
	// Parameters:
	//   $1: current_year - The latest year to include in the 5-year window
	//   $2: merchant_id - The merchant to filter transactions
	// Returns:
	//   - Year (e.g., 2021, 2022)
	//   - Payment method
	//   - Total transaction amount
	// Business Logic:
	//   - Filters only active (non-deleted) transactions and merchants
	//   - Filters by specific merchant_id
	//   - Includes data for the last 5 calendar years up to the current year
	//   - Groups by calendar year and payment method
	//   - Results are ordered chronologically by year
	GetYearlyPaymentMethodByMerchants(ctx context.Context, arg GetYearlyPaymentMethodByMerchantsParams) ([]*GetYearlyPaymentMethodByMerchantsRow, error)
	// GetYearlyPaymentMethodMerchant: Retrieves yearly transaction totals per payment method (last 5 years)
	// Purpose: Show transaction trends across payment methods over the past 5 years
	// Parameters:
	//   $1: current_year - The latest year to include in the 5-year window
	// Returns:
	//   - Year (e.g., 2021, 2022)
	//   - Payment method
	//   - Total transaction amount
	// Business Logic:
	//   - Aggregates yearly totals for each payment method
	//   - Includes only active (non-deleted) transactions and merchants
	//   - Covers a 5-year range: (current_year - 4) to current_year
	//   - Ordered by year
	GetYearlyPaymentMethodMerchant(ctx context.Context, dollar_1 interface{}) ([]*GetYearlyPaymentMethodMerchantRow, error)
	// GetYearlyTotalAmountByApikey: Retrieves total transaction amounts for the current and previous year
	// Purpose: Provide yearly transaction summary with fallback to 0 if no transactions exist
	// Parameters:
	//   $1: current_year - The latest year to include in the summary
	//   $2: api-key - The merchant to filter transactions
	// Returns:
	//   - Year (as text)
	//   - Total transaction amount per year
	// Business Logic:
	//   - Aggregates total amounts for both the current year and the previous year
	//   - Filters only active (non-deleted) transactions and merchants
	//   - Ensures both years appear in the result, even if no data exists (returns 0 in such case)
	//   - Uses UNION ALL to combine actual data with 0-filled placeholders
	//   - Results are ordered in descending order by year
	GetYearlyTotalAmountByApikey(ctx context.Context, arg GetYearlyTotalAmountByApikeyParams) ([]*GetYearlyTotalAmountByApikeyRow, error)
	// GetYearlyTotalAmountByMerchant: Retrieves total transaction amounts for the current and previous year
	// Purpose: Provide yearly transaction summary with fallback to 0 if no transactions exist
	// Parameters:
	//   $1: current_year - The latest year to include in the summary
	//   $2: merchant_id - The merchant to filter transactions
	// Returns:
	//   - Year (as text)
	//   - Total transaction amount per year
	// Business Logic:
	//   - Aggregates total amounts for both the current year and the previous year
	//   - Filters only active (non-deleted) transactions and merchants
	//   - Ensures both years appear in the result, even if no data exists (returns 0 in such case)
	//   - Uses UNION ALL to combine actual data with 0-filled placeholders
	//   - Results are ordered in descending order by year
	GetYearlyTotalAmountByMerchant(ctx context.Context, arg GetYearlyTotalAmountByMerchantParams) ([]*GetYearlyTotalAmountByMerchantRow, error)
	// GetYearlyTotalAmountMerchant: Retrieves total transaction amounts for the current and previous year
	// Purpose: Provide yearly transaction summary with fallback to 0 if no transactions exist
	// Parameters:
	//   $1: current_year - The latest year to include in the summary
	// Returns:
	//   - Year (as text)
	//   - Total transaction amount per year
	// Business Logic:
	//   - Aggregates total amounts for both the current year and the previous year
	//   - Filters only active (non-deleted) transactions and merchants
	//   - Ensures both years appear in the result, even if no data exists (returns 0 in such case)
	//   - Uses UNION ALL to combine actual data with 0-filled placeholders
	//   - Results are ordered in descending order by year
	GetYearlyTotalAmountMerchant(ctx context.Context, dollar_1 int32) ([]*GetYearlyTotalAmountMerchantRow, error)
	RestoreAllMerchantDocuments(ctx context.Context) error
	// Restore All Trashed Merchants
	// Purpose: Restore all merchants that are soft deleted
	// Business Logic:
	//   - Resets the `deleted_at` field to NULL for all merchants that have been marked as deleted.
	//   - Restores all merchants to an active state.
	RestoreAllMerchants(ctx context.Context) error
	// RestoreAllRoles: Restores all soft-deleted roles in bulk
	// Purpose: Bulk recovery of all trashed roles
	// Parameters: None
	RestoreAllRoles(ctx context.Context) error
	// Restore Trashed Merchant
	// Purpose: Restore a previously trashed (soft deleted) merchant
	// Parameters:
	//   $1: merchant_id - ID of the merchant to restore
	// Business Logic:
	//   - Resets the `deleted_at` field to NULL, restoring the merchant to an active state.
	//   - Ensures the merchant is currently trashed (deleted_at is not NULL).
	RestoreMerchant(ctx context.Context, merchantID int32) (*Merchant, error)
	RestoreMerchantDocument(ctx context.Context, documentID int32) (*MerchantDocument, error)
	// RestoreRole: Restores a previously trashed role
	// Purpose: Undelete a soft-deleted role
	// Parameters:
	//   $1: Role ID
	RestoreRole(ctx context.Context, roleID int32) (*Role, error)
	// Trash Merchant
	// Purpose: Mark a merchant as deleted (soft delete)
	// Parameters:
	//   $1: merchant_id - ID of the merchant to be trashed
	// Business Logic:
	//   - Sets the `deleted_at` timestamp to the current time for the specified merchant.
	//   - Marks the merchant as deleted, without permanently removing it from the database.
	//   - Ensures the merchant is not already marked as deleted (deleted_at is NULL).
	TrashMerchant(ctx context.Context, merchantID int32) (*Merchant, error)
	TrashMerchantDocument(ctx context.Context, documentID int32) (*MerchantDocument, error)
	// TrashRole: Soft-deletes a role (moves to trash)
	// Purpose: Mark role as deleted without removing it permanently
	// Parameters:
	//   $1: Role ID
	TrashRole(ctx context.Context, roleID int32) (*Role, error)
	// Update Merchant
	// Purpose: Update an existing merchant record
	// Parameters:
	//   $1: merchant_id - ID of the merchant to be updated
	//   $2: name - The new name for the merchant
	//   $3: user_id - New user ID associated with the merchant
	//   $4: status - New status for the merchant
	// Business Logic:
	//   - Updates the specified merchant's name, user_id, and status.
	//   - Ensures the merchant is not marked as deleted (deleted_at is NULL).
	//   - Sets the updated_at timestamp to the current time.
	UpdateMerchant(ctx context.Context, arg UpdateMerchantParams) (*UpdateMerchantRow, error)
	UpdateMerchantDocument(ctx context.Context, arg UpdateMerchantDocumentParams) (*UpdateMerchantDocumentRow, error)
	UpdateMerchantDocumentStatus(ctx context.Context, arg UpdateMerchantDocumentStatusParams) (*UpdateMerchantDocumentStatusRow, error)
	// Purpose: Update only the status of an existing merchant
	// Parameters:
	//   $1: merchant_id - ID of the merchant to update
	//   $2: status - New status to set for the merchant
	// Business Logic:
	//   - Updates the status of the specified merchant.
	//   - Ensures the merchant is not marked as deleted (deleted_at is NULL).
	//   - Sets the updated_at timestamp to the current time.
	UpdateMerchantStatus(ctx context.Context, arg UpdateMerchantStatusParams) (*UpdateMerchantStatusRow, error)
	// UpdateRole: Updates role name by ID
	// Purpose: Modify role information (e.g., name correction)
	// Parameters:
	//   $1: Role ID
	//   $2: New role name
	// Returns:
	//   Updated role's data
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (*Role, error)
}

var _ Querier = (*Queries)(nil)
