package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	errors "github.com/MamangRust/microservice-payment-gateway-grpc/shared/errors"
	"fmt"
	"time"

	pb "github.com/MamangRust/microservice-payment-gateway-grpc/pb/card"
	"github.com/MamangRust/microservice-payment-gateway-grpc/service/apigateway/internal/model"
	"github.com/MamangRust/microservice-payment-gateway-grpc/shared/domain/requests"
	"google.golang.org/protobuf/types/known/emptypb"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// CreateCard is the resolver for the createCard field.
func (r *mutationResolver) CreateCard(ctx context.Context, input model.CreateCardInput) (*model.APIResponseCard, error) {
	return ResolverHandle(r.ResolverHandle, "CreateCard", ctx, func(ctx context.Context) (*model.APIResponseCard, error) {
		expireDate, err := time.Parse("2006-01-02", input.ExpireDate)
		if err != nil {
			return nil, errors.NewBadRequestError(
				"invalid expire_date format, expected YYYY-MM-DD",
			)
		}

		request := requests.CreateCardRequest{
			UserID:       int(input.UserID),
			CardType:     input.CardType,
			ExpireDate:   expireDate,
			CVV:          input.Cvv,
			CardProvider: input.CardProvider,
		}

		if err := request.Validate(); err != nil {
			validations := r.parseValidationErrors(err)
			return nil, errors.NewValidationError(validations)
		}
		req := &pb.CreateCardRequest{
			UserId:       int32(request.UserID),
			CardType:     request.CardType,
			ExpireDate:   timestamppb.New(request.ExpireDate),
			Cvv:          request.CVV,
			CardProvider: request.CardProvider,
		}

		res, err := r.CardGraphql.CardClient.CardCommandClient.CreateCard(ctx, req)

		if err != nil {
			return nil, r.handleGraphQLError(err, "CreateCard")
		}

		so := r.CardGraphql.Mapping.ToGraphqlResponseCard(res)

		return so, nil
	})
}

// UpdateCard is the resolver for the updateCard field.
func (r *mutationResolver) UpdateCard(ctx context.Context, input model.UpdateCardInput) (*model.APIResponseCard, error) {
	return ResolverHandle(r.ResolverHandle, "UpdateCard", ctx, func(ctx context.Context) (*model.APIResponseCard, error) {
		id := int(input.CardID)

		if id == 0 {
			return nil, errors.NewBadRequestError("invalid request: card ID cannot be zero")
		}

		expireDate, err := time.Parse("2006-01-02", input.ExpireDate)
		if err != nil {
			return nil, fmt.Errorf("invalid date format for ExpireDate: %v (expected YYYY-MM-DD)", err)
		}

		request := requests.UpdateCardRequest{
			CardID:       id,
			UserID:       int(input.UserID),
			CardType:     input.CardType,
			ExpireDate:   expireDate,
			CVV:          input.Cvv,
			CardProvider: input.CardProvider,
		}

		if err := request.Validate(); err != nil {
			validations := r.parseValidationErrors(err)
			return nil, errors.NewValidationError(validations)
		}

		req := &pb.UpdateCardRequest{
			CardId:       int32(id),
			UserId:       int32(input.UserID),
			CardType:     input.CardType,
			ExpireDate:   timestamppb.New(expireDate),
			Cvv:          input.Cvv,
			CardProvider: input.CardProvider}
		res, err := r.CardGraphql.CardClient.CardCommandClient.UpdateCard(ctx, req)

		if err != nil {
			return nil, r.handleGraphQLError(err, "UpdateCard")
		}

		so := r.CardGraphql.Mapping.ToGraphqlResponseCard(res)

		r.CardGraphql.Cache.DeleteByIdCache(ctx, request.CardID)

		return so, nil
	})
}

// TrashedCard is the resolver for the trashedCard field.
func (r *mutationResolver) TrashedCard(ctx context.Context, input model.FindByIDCardInput) (*model.APIResponseCardDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "TrashedCard", ctx, func(ctx context.Context) (*model.APIResponseCardDeleteAt, error) {
		id := int32(input.CardID)
		if id == 0 {
			return nil, errors.NewBadRequestError("invalid request: card ID cannot be zero")
		}

		res, errResp := r.CardGraphql.CardClient.CardCommandClient.TrashedCard(ctx, &pb.FindByIdCardRequest{CardId: id})
		if errResp != nil {
			return nil, r.handleGraphQLError(errResp, "TrashedCard")
		}

		so := r.CardGraphql.Mapping.ToGraphqlResponseCardDeleteAt(res)

		r.CardGraphql.Cache.DeleteByIdCache(ctx, int(id))

		return so, nil
	})
}

// RestoreCard is the resolver for the restoreCard field.
func (r *mutationResolver) RestoreCard(ctx context.Context, input model.FindByIDCardInput) (*model.APIResponseCardDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "RestoreCard", ctx, func(ctx context.Context) (*model.APIResponseCardDeleteAt, error) {
		id := int32(input.CardID)
		if id == 0 {
			return nil, errors.NewBadRequestError("invalid request: card ID cannot be zero")
		}

		res, errResp := r.CardGraphql.CardClient.CardCommandClient.RestoreCard(ctx, &pb.FindByIdCardRequest{CardId: id})
		if errResp != nil {
			return nil, r.handleGraphQLError(errResp, "RestoreCard")
		}

		so := r.CardGraphql.Mapping.ToGraphqlResponseCardDeleteAt(res)

		r.CardGraphql.Cache.DeleteByIdCache(ctx, int(id))

		return so, nil
	})
}

// DeleteCardPermanent is the resolver for the deleteCardPermanent field.
func (r *mutationResolver) DeleteCardPermanent(ctx context.Context, input model.FindByIDCardInput) (*model.APIResponseCardDelete, error) {
	return ResolverHandle(r.ResolverHandle, "DeleteCardPermanent", ctx, func(ctx context.Context) (*model.APIResponseCardDelete, error) {
		id := int32(input.CardID)
		if id == 0 {
			return nil, errors.NewBadRequestError("invalid request: card ID cannot be zero")
		}

		res, errResp := r.CardGraphql.CardClient.CardCommandClient.DeleteCardPermanent(ctx, &pb.FindByIdCardRequest{CardId: id})
		if errResp != nil {
			return nil, r.handleGraphQLError(errResp, "DeleteCardPermanent")
		}

		so := r.CardGraphql.Mapping.ToGraphqlResponseDelete(res)

		r.CardGraphql.Cache.DeleteByIdCache(ctx, int(id))

		return so, nil
	})
}

// RestoreAllCard is the resolver for the restoreAllCard field.
func (r *mutationResolver) RestoreAllCard(ctx context.Context) (*model.APIResponseCardAll, error) {
	return ResolverHandle(r.ResolverHandle, "RestoreAllCard", ctx, func(ctx context.Context) (*model.APIResponseCardAll, error) {
		res, errResp := r.CardGraphql.CardClient.CardCommandClient.RestoreAllCard(ctx, &emptypb.Empty{})
		if errResp != nil {
			return nil, r.handleGraphQLError(errResp, "RestoreAllCard")
		}

		so := r.CardGraphql.Mapping.ToGraphqlResponseAll(res)

		return so, nil
	})
}

// DeleteAllCardPermanent is the resolver for the deleteAllCardPermanent field.
func (r *mutationResolver) DeleteAllCardPermanent(ctx context.Context) (*model.APIResponseCardAll, error) {
	return ResolverHandle(r.ResolverHandle, "DeleteAllCardPermanent", ctx, func(ctx context.Context) (*model.APIResponseCardAll, error) {
		res, errResp := r.CardGraphql.CardClient.CardCommandClient.DeleteAllCardPermanent(ctx, &emptypb.Empty{})
		if errResp != nil {
			return nil, r.handleGraphQLError(errResp, "DeleteAllCardPermanent")
		}

		so := r.CardGraphql.Mapping.ToGraphqlResponseAll(res)

		return so, nil
	})
}

// FindAllCard is the resolver for the findAllCard field.
func (r *queryResolver) FindAllCard(ctx context.Context, input model.FindAllCardInput) (*model.APIResponsePaginationCard, error) {
	return ResolverHandle(r.ResolverHandle, "FindAllCard", ctx, func(ctx context.Context) (*model.APIResponsePaginationCard, error) {
		page := int32(1)
		pageSize := int32(10)
		search := ""

		if input.Page != nil {
			page = int32(*input.Page)
		}
		if input.PageSize != nil {
			pageSize = int32(*input.PageSize)
		}
		if input.Search != nil {
			search = *input.Search
		}

		if page <= 0 {
			page = 1
		}
		if pageSize <= 0 {
			pageSize = 10
		}

		req := &pb.FindAllCardRequest{
			Page:     page,
			PageSize: pageSize,
			Search:   search,
		}

		cachedData, found := r.CardGraphql.Cache.GetFindAllCache(ctx, &input)
		if found {
			return cachedData, nil
		}

		res, err := r.CardGraphql.CardClient.CardQueryClient.FindAllCard(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindAllCard")
		}

		so := r.CardGraphql.Mapping.ToGraphqlResponsePaginationCard(res)

		r.CardGraphql.Cache.SetFindAllCache(ctx, &input, so)

		return so, nil
	})
}

// FindByIDCard is the resolver for the findByIdCard field.
func (r *queryResolver) FindByIDCard(ctx context.Context, input model.FindByIDCardInput) (*model.APIResponseCard, error) {
	return ResolverHandle(r.ResolverHandle, "FindByIDCard", ctx, func(ctx context.Context) (*model.APIResponseCard, error) {
		id := int32(input.CardID)
		if id == 0 {
			return nil, errors.NewBadRequestError("invalid request: card ID cannot be zero")
		}

		cachedData, found := r.CardGraphql.Cache.GetByIdCache(ctx, int(id))
		if found {
			return cachedData, nil
		}

		card, err := r.CardGraphql.CardClient.CardQueryClient.FindByIdCard(ctx, &pb.FindByIdCardRequest{
			CardId: id,
		})
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindByIDCard")
		}

		so := r.CardGraphql.Mapping.ToGraphqlResponseCard(card)

		r.CardGraphql.Cache.SetByIdCache(ctx, int(id), so)

		return so, nil
	})
}

// FindByUserIDCard is the resolver for the findByUserIdCard field.
func (r *queryResolver) FindByUserIDCard(ctx context.Context, input model.FindByUserIDCardInput) (*model.APIResponseCard, error) {
	return ResolverHandle(r.ResolverHandle, "FindByUserIDCard", ctx, func(ctx context.Context) (*model.APIResponseCard, error) {
		id := int32(input.UserID)
		if id == 0 {
			return nil, errors.NewBadRequestError("invalid request: card user ID cannot be zero")
		}

		cachedData, found := r.CardGraphql.Cache.GetByUserIDCache(ctx, int(id))
		if found {
			return cachedData, nil
		}

		res, err := r.CardGraphql.CardClient.CardQueryClient.FindByUserIdCard(ctx, &pb.FindByUserIdCardRequest{
			UserId: id,
		})
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindByUserIDCard")
		}

		so := r.CardGraphql.Mapping.ToGraphqlResponseCard(res)

		r.CardGraphql.Cache.SetByUserIDCache(ctx, int(id), so)

		return so, nil
	})
}

// FindByCardNumber is the resolver for the findByCardNumber field.
func (r *queryResolver) FindByCardNumber(ctx context.Context, input model.FindByCardNumberInput) (*model.APIResponseCard, error) {
	return ResolverHandle(r.ResolverHandle, "FindByCardNumber", ctx, func(ctx context.Context) (*model.APIResponseCard, error) {
		cardNumber := input.CardNumber

		if cardNumber == "" {
			return nil, errors.NewBadRequestError("invalid request: card number cannot be empty")
		}

		res, err := r.CardGraphql.CardClient.CardQueryClient.FindByCardNumber(ctx, &pb.FindByCardNumberRequest{
			CardNumber: cardNumber,
		})
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindByCardNumber")
		}

		so := r.CardGraphql.Mapping.ToGraphqlResponseCard(res)
		return so, nil
	})
}

// FindByActiveCard is the resolver for the findByActiveCard field.
func (r *queryResolver) FindByActiveCard(ctx context.Context, input model.FindAllCardInput) (*model.APIResponsePaginationCardDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "FindByActiveCard", ctx, func(ctx context.Context) (*model.APIResponsePaginationCardDeleteAt, error) {
		page := int32(1)
		pageSize := int32(10)
		search := ""

		if input.Page != nil {
			page = int32(*input.Page)
		}
		if input.PageSize != nil {
			pageSize = int32(*input.PageSize)
		}
		if input.Search != nil {
			search = *input.Search
		}

		if page <= 0 {
			page = 1
		}
		if pageSize <= 0 {
			pageSize = 10
		}

		req := &pb.FindAllCardRequest{
			Page:     page,
			PageSize: pageSize,
			Search:   search,
		}

		cachedData, found := r.CardGraphql.Cache.GetByActiveCache(ctx, &input)
		if found {
			return cachedData, nil
		}

		res, err := r.CardGraphql.CardClient.CardQueryClient.FindByActiveCard(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindByActiveCard")
		}

		so := r.CardGraphql.Mapping.ToGraphqlResponsePaginationCardDeleteAt(res)

		r.CardGraphql.Cache.SetByActiveCache(ctx, &input, so)

		return so, nil
	})
}

// FindByTrashedCard is the resolver for the findByTrashedCard field.
func (r *queryResolver) FindByTrashedCard(ctx context.Context, input model.FindAllCardInput) (*model.APIResponsePaginationCardDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "FindByTrashedCard", ctx, func(ctx context.Context) (*model.APIResponsePaginationCardDeleteAt, error) {
		page := int32(1)
		pageSize := int32(10)
		search := ""

		if input.Page != nil {
			page = int32(*input.Page)
		}
		if input.PageSize != nil {
			pageSize = int32(*input.PageSize)
		}
		if input.Search != nil {
			search = *input.Search
		}

		if page <= 0 {
			page = 1
		}
		if pageSize <= 0 {
			pageSize = 10
		}

		req := &pb.FindAllCardRequest{
			Page:     page,
			PageSize: pageSize,
			Search:   search,
		}

		cachedData, found := r.CardGraphql.Cache.GetByTrashedCache(ctx, &input)
		if found {
			return cachedData, nil
		}

		res, err := r.CardGraphql.CardClient.CardQueryClient.FindByTrashedCard(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindByTrashedCard")
		}

		so := r.CardGraphql.Mapping.ToGraphqlResponsePaginationCardDeleteAt(res)

		r.CardGraphql.Cache.SetByTrashedCache(ctx, &input, so)

		return so, nil
	})
}
