package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	errors "github.com/MamangRust/microservice-payment-gateway-grpc/shared/errors"
	"fmt"

	pb "github.com/MamangRust/microservice-payment-gateway-grpc/pb/merchant"
	"github.com/MamangRust/microservice-payment-gateway-grpc/service/apigateway/internal/model"
	"github.com/MamangRust/microservice-payment-gateway-grpc/shared/domain/requests"
	"google.golang.org/protobuf/types/known/emptypb"
)

// CreateMerchant is the resolver for the createMerchant field.
func (r *mutationResolver) CreateMerchant(ctx context.Context, input model.CreateMerchantInput) (*model.APIResponseMerchant, error) {
	return ResolverHandle(r.ResolverHandle, "CreateMerchant", ctx, func(ctx context.Context) (*model.APIResponseMerchant, error) {
		request := requests.CreateMerchantRequest{
			Name:   input.Name,
			UserID: int(input.UserID),
		}

		if err := request.Validate(); err != nil {
			validations := r.parseValidationErrors(err)
			return nil, errors.NewValidationError(validations)
		}

		reqPb := &pb.CreateMerchantRequest{
			Name:   request.Name,
			UserId: int32(request.UserID),
		}

		merchant, err := r.MerchantGraphql.MerchantClient.MerchantCommand.CreateMerchant(ctx, reqPb)
		if err != nil {
			return nil, r.handleGraphQLError(err, "CreateMerchant")
		}

		so := r.MerchantGraphql.Mapping.ToGraphqlResponseMerchant(merchant)
		return so, nil
	})
}

// UpdateMerchant is the resolver for the updateMerchant field.
func (r *mutationResolver) UpdateMerchant(ctx context.Context, input model.UpdateMerchantInput) (*model.APIResponseMerchant, error) {
	return ResolverHandle(r.ResolverHandle, "UpdateMerchant", ctx, func(ctx context.Context) (*model.APIResponseMerchant, error) {
		id := int(input.MerchantID)
		if id == 0 {
			return nil, errors.NewBadRequestError("invalid request: merchant ID cannot be zero")
		}

		request := requests.UpdateMerchantRequest{
			MerchantID: &id,
			Name:       input.Name,
			UserID:     int(input.UserID),
			Status:     input.Status,
		}

		if err := request.Validate(); err != nil {
			validations := r.parseValidationErrors(err)
			return nil, errors.NewValidationError(validations)
		}

		reqpb := &pb.UpdateMerchantRequest{
			MerchantId: int32(*request.MerchantID),
			Name:       request.Name,
			UserId:     int32(request.UserID),
			Status:     request.Status,
		}

		merchant, err := r.MerchantGraphql.MerchantClient.MerchantCommand.UpdateMerchant(ctx, reqpb)
		if err != nil {
			return nil, r.handleGraphQLError(err, "UpdateMerchant")
		}

		so := r.MerchantGraphql.Mapping.ToGraphqlResponseMerchant(merchant)

		r.MerchantGraphql.Cache.DeleteCachedMerchant(ctx, id)

		return so, nil
	})
}

// UpdateMerchantStatus is the resolver for the updateMerchantStatus field.
func (r *mutationResolver) UpdateMerchantStatus(ctx context.Context, input model.UpdateMerchantStatusInput) (*model.APIResponseMerchant, error) {
	return ResolverHandle(r.ResolverHandle, "UpdateMerchantStatus", ctx, func(ctx context.Context) (*model.APIResponseMerchant, error) {
		id := int(input.MerchantID)
		if id == 0 {
			return nil, errors.NewBadRequestError("invalid request: merchant ID cannot be zero")
		}

		request := requests.UpdateMerchantStatusRequest{
			MerchantID: &id,
			Status:     input.Status,
		}

		if err := request.Validate(); err != nil {
			validations := r.parseValidationErrors(err)
			return nil, errors.NewValidationError(validations)
		}

		reqpb := &pb.UpdateMerchantStatusRequest{
			MerchantId: int32(*request.MerchantID),
			Status:     request.Status,
		}

		merchant, err := r.MerchantGraphql.MerchantClient.MerchantCommand.UpdateMerchantStatus(ctx, reqpb)
		if err != nil {
			return nil, r.handleGraphQLError(err, "UpdateMerchantStatus")
		}

		so := r.MerchantGraphql.Mapping.ToGraphqlResponseMerchant(merchant)

		r.MerchantGraphql.Cache.DeleteCachedMerchant(ctx, id)

		return so, nil
	})
}

// TrashedMerchant is the resolver for the trashedMerchant field.
func (r *mutationResolver) TrashedMerchant(ctx context.Context, input model.FindByIDMerchantInput) (*model.APIResponseMerchantDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "TrashedMerchant", ctx, func(ctx context.Context) (*model.APIResponseMerchantDeleteAt, error) {
		id := int32(input.MerchantID)
		if id == 0 {
			return nil, errors.NewBadRequestError("invalid request: merchant ID cannot be zero")
		}

		merchant, err := r.MerchantGraphql.MerchantClient.MerchantCommand.TrashedMerchant(ctx, &pb.FindByIdMerchantRequest{
			MerchantId: id,
		})
		if err != nil {
			return nil, r.handleGraphQLError(err, "TrashedMerchant")
		}

		so := r.MerchantGraphql.Mapping.ToGraphqlResponseMerchantDeleteAt(merchant)

		r.MerchantGraphql.Cache.DeleteCachedMerchant(ctx, int(id))

		return so, nil
	})
}

// RestoreMerchant is the resolver for the restoreMerchant field.
func (r *mutationResolver) RestoreMerchant(ctx context.Context, input model.FindByIDMerchantInput) (*model.APIResponseMerchantDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "RestoreMerchant", ctx, func(ctx context.Context) (*model.APIResponseMerchantDeleteAt, error) {
		id := int32(input.MerchantID)
		if id == 0 {
			return nil, errors.NewBadRequestError("invalid request: merchant ID cannot be zero")
		}

		merchant, err := r.MerchantGraphql.MerchantClient.MerchantCommand.RestoreMerchant(ctx, &pb.FindByIdMerchantRequest{
			MerchantId: id,
		})
		if err != nil {
			return nil, r.handleGraphQLError(err, "RestoreMerchant")
		}

		so := r.MerchantGraphql.Mapping.ToGraphqlResponseMerchantDeleteAt(merchant)

		r.MerchantGraphql.Cache.DeleteCachedMerchant(ctx, int(id))

		return so, nil
	})
}

// DeleteMerchantPermanent is the resolver for the deleteMerchantPermanent field.
func (r *mutationResolver) DeleteMerchantPermanent(ctx context.Context, input model.FindByIDMerchantInput) (*model.APIResponseMerchantDelete, error) {
	return ResolverHandle(r.ResolverHandle, "DeleteMerchantPermanent", ctx, func(ctx context.Context) (*model.APIResponseMerchantDelete, error) {
		id := int32(input.MerchantID)
		if id == 0 {
			return nil, errors.NewBadRequestError("invalid request: merchant ID cannot be zero")
		}

		merchant, err := r.MerchantGraphql.MerchantClient.MerchantCommand.DeleteMerchantPermanent(ctx, &pb.FindByIdMerchantRequest{
			MerchantId: id,
		})
		if err != nil {
			return nil, r.handleGraphQLError(err, "DeleteMerchantPermanent")
		}

		so := r.MerchantGraphql.Mapping.ToGraphqlMerchantDeleteAll(merchant)

		r.MerchantGraphql.Cache.DeleteCachedMerchant(ctx, int(id))

		return so, nil
	})
}

// RestoreAllMerchant is the resolver for the restoreAllMerchant field.
func (r *mutationResolver) RestoreAllMerchant(ctx context.Context) (*model.APIResponseMerchantAll, error) {
	return ResolverHandle(r.ResolverHandle, "RestoreAllMerchant", ctx, func(ctx context.Context) (*model.APIResponseMerchantAll, error) {
		res, err := r.MerchantGraphql.MerchantClient.MerchantCommand.RestoreAllMerchant(ctx, &emptypb.Empty{})
		if err != nil {
			return nil, r.handleGraphQLError(err, "RestoreAllMerchant")
		}

		so := r.MerchantGraphql.Mapping.ToGraphqlMerchantAll(res)
		return so, nil
	})
}

// DeleteAllMerchantPermanent is the resolver for the deleteAllMerchantPermanent field.
func (r *mutationResolver) DeleteAllMerchantPermanent(ctx context.Context) (*model.APIResponseMerchantAll, error) {
	return ResolverHandle(r.ResolverHandle, "DeleteAllMerchantPermanent", ctx, func(ctx context.Context) (*model.APIResponseMerchantAll, error) {
		res, err := r.MerchantGraphql.MerchantClient.MerchantCommand.DeleteAllMerchantPermanent(ctx, &emptypb.Empty{})
		if err != nil {
			return nil, r.handleGraphQLError(err, "DeleteAllMerchantPermanent")
		}

		so := r.MerchantGraphql.Mapping.ToGraphqlMerchantAll(res)
		return so, nil
	})
}

// FindAllMerchant is the resolver for the findAllMerchant field.
func (r *queryResolver) FindAllMerchant(ctx context.Context, input model.FindAllMerchantInput) (*model.APIResponsePaginationMerchant, error) {
	// Normalize input for consistent caching and backend request
	page := int32(1)
	pageSize := int32(10)
	search := ""

	if input.Page != nil {
		page = int32(*input.Page)
	}
	if input.PageSize != nil {
		pageSize = int32(*input.PageSize)
	}
	if input.Search != nil {
		search = *input.Search
	}

	if page <= 0 {
		page = 1
	}
	if pageSize <= 0 {
		pageSize = 10
	}

	normalizedInput := &model.FindAllMerchantInput{
		Page:     &page,
		PageSize: &pageSize,
		Search:   &search,
	}

	cachedData, found := r.MerchantGraphql.Cache.GetCachedMerchants(ctx, normalizedInput)
	if found {
		return cachedData, nil
	}

	req := &pb.FindAllMerchantRequest{
		Page:     page,
		PageSize: pageSize,
		Search:   search,
	}

	res, err := r.MerchantGraphql.MerchantClient.MerchantQuery.FindAllMerchant(ctx, req)
	if err != nil {
		return nil, r.handleGraphQLError(err, "FindAllMerchant")
	}

	so := r.MerchantGraphql.Mapping.ToGraphqlResponsePaginationMerchant(res)

	r.MerchantGraphql.Cache.SetCachedMerchants(ctx, normalizedInput, so)

	return so, nil
}

// FindByIDMerchant is the resolver for the findByIdMerchant field.
func (r *queryResolver) FindByIDMerchant(ctx context.Context, input model.FindByIDMerchantInput) (*model.APIResponseMerchant, error) {
	id := int(input.MerchantID)
	if id == 0 {
		return nil, errors.NewBadRequestError("invalid request: merchant ID cannot be zero")
	}

	cachedData, found := r.MerchantGraphql.Cache.GetCachedMerchant(ctx, id)
	if found {
		return cachedData, nil
	}

	merchant, err := r.MerchantGraphql.MerchantClient.MerchantQuery.FindByIdMerchant(ctx, &pb.FindByIdMerchantRequest{MerchantId: int32(id)})
	if err != nil {
		return nil, r.handleGraphQLError(err, "FindByIDMerchant")
	}

	so := r.MerchantGraphql.Mapping.ToGraphqlResponseMerchant(merchant)

	r.MerchantGraphql.Cache.SetCachedMerchant(ctx, so)

	return so, nil
}

// FindByAPIKey is the resolver for the findByApiKey field.
func (r *queryResolver) FindByAPIKey(ctx context.Context, input model.FindByAPIKeyInput) (*model.APIResponseMerchant, error) {
	apiKey := input.APIKey
	if apiKey == "" {
		return nil, fmt.Errorf("api key is required")
	}

	cachedData, found := r.MerchantGraphql.Cache.GetCachedMerchantByApiKey(ctx, apiKey)
	if found {
		return cachedData, nil
	}

	merchant, err := r.MerchantGraphql.MerchantClient.MerchantQuery.FindByApiKey(ctx, &pb.FindByApiKeyRequest{ApiKey: apiKey})
	if err != nil {
		return nil, r.handleGraphQLError(err, "FindByAPIKey")
	}

	so := r.MerchantGraphql.Mapping.ToGraphqlResponseMerchant(merchant)

	r.MerchantGraphql.Cache.SetCachedMerchantByApiKey(ctx, apiKey, so)

	return so, nil
}

// FindByMerchantUserID is the resolver for the findByMerchantUserId field.
func (r *queryResolver) FindByMerchantUserID(ctx context.Context, input model.FindByMerchantUserIDInput) (*model.APIResponsesMerchant, error) {
	userId := int(input.UserID)
	if userId == 0 {
		return nil, fmt.Errorf("invalid Merchant ID")
	}

	cachedData, found := r.MerchantGraphql.Cache.GetCachedMerchantsByUserId(ctx, userId)
	if found {
		return cachedData, nil
	}

	merchant, err := r.MerchantGraphql.MerchantClient.MerchantQuery.FindByMerchantUserId(ctx, &pb.FindByMerchantUserIdRequest{UserId: int32(userId)})
	if err != nil {
		return nil, r.handleGraphQLError(err, "FindByMerchantUserID")
	}

	so := r.MerchantGraphql.Mapping.ToGraphqlResponsesMerchant(merchant)

	r.MerchantGraphql.Cache.SetCachedMerchantsByUserId(ctx, userId, so)

	return so, nil
}

// FindByActive is the resolver for the findByActive field.
func (r *queryResolver) FindByActive(ctx context.Context, input model.FindAllMerchantInput) (*model.APIResponsePaginationMerchantDeleteAt, error) {
	// Normalize input for consistent caching and backend request
	page := int32(1)
	pageSize := int32(10)
	search := ""

	if input.Page != nil {
		page = int32(*input.Page)
	}
	if input.PageSize != nil {
		pageSize = int32(*input.PageSize)
	}
	if input.Search != nil {
		search = *input.Search
	}

	if page <= 0 {
		page = 1
	}
	if pageSize <= 0 {
		pageSize = 10
	}

	normalizedInput := &model.FindAllMerchantInput{
		Page:     &page,
		PageSize: &pageSize,
		Search:   &search,
	}

	cachedData, found := r.MerchantGraphql.Cache.GetCachedMerchantActive(ctx, normalizedInput)
	if found {
		return cachedData, nil
	}

	req := &pb.FindAllMerchantRequest{
		Page:     page,
		PageSize: pageSize,
		Search:   search,
	}

	res, errResp := r.MerchantGraphql.MerchantClient.MerchantQuery.FindByActive(ctx, req)
	if errResp != nil {
		return nil, r.handleGraphQLError(errResp, "FindByActive")
	}

	so := r.MerchantGraphql.Mapping.ToGraphqlResponsePaginationMerchantDeleteAt(res)

	r.MerchantGraphql.Cache.SetCachedMerchantActive(ctx, normalizedInput, so)

	return so, nil
}

// FindByTrashed is the resolver for the findByTrashed field.
func (r *queryResolver) FindByTrashed(ctx context.Context, input model.FindAllMerchantInput) (*model.APIResponsePaginationMerchantDeleteAt, error) {
	// Normalize input for consistent caching and backend request
	page := int32(1)
	pageSize := int32(10)
	search := ""

	if input.Page != nil {
		page = int32(*input.Page)
	}
	if input.PageSize != nil {
		pageSize = int32(*input.PageSize)
	}
	if input.Search != nil {
		search = *input.Search
	}

	if page <= 0 {
		page = 1
	}
	if pageSize <= 0 {
		pageSize = 10
	}

	normalizedInput := &model.FindAllMerchantInput{
		Page:     &page,
		PageSize: &pageSize,
		Search:   &search,
	}

	cachedData, found := r.MerchantGraphql.Cache.GetCachedMerchantTrashed(ctx, normalizedInput)
	if found {
		return cachedData, nil
	}

	req := &pb.FindAllMerchantRequest{
		Page:     page,
		PageSize: pageSize,
		Search:   search,
	}

	res, errResp := r.MerchantGraphql.MerchantClient.MerchantQuery.FindByTrashed(ctx, req)
	if errResp != nil {
		return nil, r.handleGraphQLError(errResp, "FindByTrashed")
	}

	so := r.MerchantGraphql.Mapping.ToGraphqlResponsePaginationMerchantDeleteAt(res)

	r.MerchantGraphql.Cache.SetCachedMerchantTrashed(ctx, normalizedInput, so)

	return so, nil
}
