package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	"github.com/MamangRust/microservice-payment-gateway-grpc/service/apigateway/internal/model"
)

// WriteTopupEvent is the resolver for the writeTopupEvent field.
func (r *mutationResolver) WriteTopupEvent(ctx context.Context, input model.TopupEventInput) (*model.APIResponseVerifyCode, error) {
	return &model.APIResponseVerifyCode{Status: "success", Message: "not implemented"}, nil
}

// WriteTransactionEvent is the resolver for the writeTransactionEvent field.
func (r *mutationResolver) WriteTransactionEvent(ctx context.Context, input model.TransactionEventInput) (*model.APIResponseVerifyCode, error) {
	return &model.APIResponseVerifyCode{Status: "success", Message: "not implemented"}, nil
}

// WriteTransferEvent is the resolver for the writeTransferEvent field.
func (r *mutationResolver) WriteTransferEvent(ctx context.Context, input model.TransferEventInput) (*model.APIResponseVerifyCode, error) {
	return &model.APIResponseVerifyCode{Status: "success", Message: "not implemented"}, nil
}

// WriteSaldoEvent is the resolver for the writeSaldoEvent field.
func (r *mutationResolver) WriteSaldoEvent(ctx context.Context, input model.SaldoEventInput) (*model.APIResponseVerifyCode, error) {
	return &model.APIResponseVerifyCode{Status: "success", Message: "not implemented"}, nil
}

// WriteWithdrawEvent is the resolver for the writeWithdrawEvent field.
func (r *mutationResolver) WriteWithdrawEvent(ctx context.Context, input model.WithdrawEventInput) (*model.APIResponseVerifyCode, error) {
	return &model.APIResponseVerifyCode{Status: "success", Message: "not implemented"}, nil
}

// DashboardCardStats is the resolver for the dashboardCardStats field.
func (r *queryResolver) DashboardCardStats(ctx context.Context) (*model.APIResponseDashboardCard, error) {
	return &model.APIResponseDashboardCard{Status: "success", Message: "ok", Data: &model.DashboardCardResponse{}}, nil
}

// DashboardCardByNumberStats is the resolver for the dashboardCardByNumberStats field.
func (r *queryResolver) DashboardCardByNumberStats(ctx context.Context, input model.FindByCardNumberInput) (*model.APIResponseDashboardCardByNumber, error) {
	return &model.APIResponseDashboardCardByNumber{Status: "success", Message: "ok"}, nil
}

// FindMonthlyBalanceStats is the resolver for the findMonthlyBalanceStats field.
func (r *queryResolver) FindMonthlyBalanceStats(ctx context.Context, input model.FindYearStatsInput) (*model.APIResponseMonthlyBalance, error) {
	return &model.APIResponseMonthlyBalance{Status: "success", Message: "ok", Data: []*model.MonthlyBalanceResponse{}}, nil
}

// FindYearlyBalanceStats is the resolver for the findYearlyBalanceStats field.
func (r *queryResolver) FindYearlyBalanceStats(ctx context.Context, input model.FindYearStatsInput) (*model.APIResponseYearlyBalance, error) {
	return &model.APIResponseYearlyBalance{Status: "success", Message: "ok", Data: []*model.YearlyBalanceResponse{}}, nil
}

// FindMonthlyBalanceByCardNumberStats is the resolver for the findMonthlyBalanceByCardNumberStats field.
func (r *queryResolver) FindMonthlyBalanceByCardNumberStats(ctx context.Context, input model.FindYearCardNumberStatsInput) (*model.APIResponseMonthlyBalance, error) {
	return &model.APIResponseMonthlyBalance{Status: "success", Message: "ok", Data: []*model.MonthlyBalanceResponse{}}, nil
}

// FindYearlyBalanceByCardNumberStats is the resolver for the findYearlyBalanceByCardNumberStats field.
func (r *queryResolver) FindYearlyBalanceByCardNumberStats(ctx context.Context, input model.FindYearCardNumberStatsInput) (*model.APIResponseYearlyBalance, error) {
	return &model.APIResponseYearlyBalance{Status: "success", Message: "ok", Data: []*model.YearlyBalanceResponse{}}, nil
}

// FindMonthlyTopupAmountStats is the resolver for the findMonthlyTopupAmountStats field.
func (r *queryResolver) FindMonthlyTopupAmountStats(ctx context.Context, input model.FindYearStatsInput) (*model.APIResponseMonthlyAmount, error) {
	return &model.APIResponseMonthlyAmount{Status: "success", Message: "ok", Data: []*model.MonthlyAmountResponse{}}, nil
}

// FindYearlyTopupAmountStats is the resolver for the findYearlyTopupAmountStats field.
func (r *queryResolver) FindYearlyTopupAmountStats(ctx context.Context, input model.FindYearStatsInput) (*model.APIResponseYearlyAmount, error) {
	return &model.APIResponseYearlyAmount{Status: "success", Message: "ok", Data: []*model.YearlyAmountResponse{}}, nil
}

// FindMonthlyTopupAmountByCardNumberStats is the resolver for the findMonthlyTopupAmountByCardNumberStats field.
func (r *queryResolver) FindMonthlyTopupAmountByCardNumberStats(ctx context.Context, input model.FindYearCardNumberStatsInput) (*model.APIResponseMonthlyAmount, error) {
	return &model.APIResponseMonthlyAmount{Status: "success", Message: "ok", Data: []*model.MonthlyAmountResponse{}}, nil
}

// FindYearlyTopupAmountByCardNumberStats is the resolver for the findYearlyTopupAmountByCardNumberStats field.
func (r *queryResolver) FindYearlyTopupAmountByCardNumberStats(ctx context.Context, input model.FindYearCardNumberStatsInput) (*model.APIResponseYearlyAmount, error) {
	return &model.APIResponseYearlyAmount{Status: "success", Message: "ok", Data: []*model.YearlyAmountResponse{}}, nil
}

// FindMonthlyWithdrawAmountStats is the resolver for the findMonthlyWithdrawAmountStats field.
func (r *queryResolver) FindMonthlyWithdrawAmountStats(ctx context.Context, input model.FindYearStatsInput) (*model.APIResponseMonthlyAmount, error) {
	return &model.APIResponseMonthlyAmount{Status: "success", Message: "ok", Data: []*model.MonthlyAmountResponse{}}, nil
}

// FindYearlyWithdrawAmountStats is the resolver for the findYearlyWithdrawAmountStats field.
func (r *queryResolver) FindYearlyWithdrawAmountStats(ctx context.Context, input model.FindYearStatsInput) (*model.APIResponseYearlyAmount, error) {
	return &model.APIResponseYearlyAmount{Status: "success", Message: "ok", Data: []*model.YearlyAmountResponse{}}, nil
}

// FindMonthlyWithdrawAmountByCardNumberStats is the resolver for the findMonthlyWithdrawAmountByCardNumberStats field.
func (r *queryResolver) FindMonthlyWithdrawAmountByCardNumberStats(ctx context.Context, input model.FindYearCardNumberStatsInput) (*model.APIResponseMonthlyAmount, error) {
	return &model.APIResponseMonthlyAmount{Status: "success", Message: "ok", Data: []*model.MonthlyAmountResponse{}}, nil
}

// FindYearlyWithdrawAmountByCardNumberStats is the resolver for the findYearlyWithdrawAmountByCardNumberStats field.
func (r *queryResolver) FindYearlyWithdrawAmountByCardNumberStats(ctx context.Context, input model.FindYearCardNumberStatsInput) (*model.APIResponseYearlyAmount, error) {
	return &model.APIResponseYearlyAmount{Status: "success", Message: "ok", Data: []*model.YearlyAmountResponse{}}, nil
}

// FindMonthlyTransactionAmountStats is the resolver for the findMonthlyTransactionAmountStats field.
func (r *queryResolver) FindMonthlyTransactionAmountStats(ctx context.Context, input model.FindYearStatsInput) (*model.APIResponseMonthlyAmount, error) {
	return &model.APIResponseMonthlyAmount{Status: "success", Message: "ok", Data: []*model.MonthlyAmountResponse{}}, nil
}

// FindYearlyTransactionAmountStats is the resolver for the findYearlyTransactionAmountStats field.
func (r *queryResolver) FindYearlyTransactionAmountStats(ctx context.Context, input model.FindYearStatsInput) (*model.APIResponseYearlyAmount, error) {
	return &model.APIResponseYearlyAmount{Status: "success", Message: "ok", Data: []*model.YearlyAmountResponse{}}, nil
}

// FindMonthlyTransactionAmountByCardNumberStats is the resolver for the findMonthlyTransactionAmountByCardNumberStats field.
func (r *queryResolver) FindMonthlyTransactionAmountByCardNumberStats(ctx context.Context, input model.FindYearCardNumberStatsInput) (*model.APIResponseMonthlyAmount, error) {
	return &model.APIResponseMonthlyAmount{Status: "success", Message: "ok", Data: []*model.MonthlyAmountResponse{}}, nil
}

// FindYearlyTransactionAmountByCardNumberStats is the resolver for the findYearlyTransactionAmountByCardNumberStats field.
func (r *queryResolver) FindYearlyTransactionAmountByCardNumberStats(ctx context.Context, input model.FindYearCardNumberStatsInput) (*model.APIResponseYearlyAmount, error) {
	return &model.APIResponseYearlyAmount{Status: "success", Message: "ok", Data: []*model.YearlyAmountResponse{}}, nil
}

// FindMonthlyTransferAmountStats is the resolver for the findMonthlyTransferAmountStats field.
func (r *queryResolver) FindMonthlyTransferAmountStats(ctx context.Context, input model.FindYearStatsInput) (*model.APIResponseMonthlyAmount, error) {
	return &model.APIResponseMonthlyAmount{Status: "success", Message: "ok", Data: []*model.MonthlyAmountResponse{}}, nil
}

// FindYearlyTransferAmountStats is the resolver for the findYearlyTransferAmountStats field.
func (r *queryResolver) FindYearlyTransferAmountStats(ctx context.Context, input model.FindYearStatsInput) (*model.APIResponseYearlyAmount, error) {
	return &model.APIResponseYearlyAmount{Status: "success", Message: "ok", Data: []*model.YearlyAmountResponse{}}, nil
}

// FindMonthlyTransferSenderAmountStats is the resolver for the findMonthlyTransferSenderAmountStats field.
func (r *queryResolver) FindMonthlyTransferSenderAmountStats(ctx context.Context, input model.FindYearCardNumberStatsInput) (*model.APIResponseMonthlyAmount, error) {
	return &model.APIResponseMonthlyAmount{Status: "success", Message: "ok", Data: []*model.MonthlyAmountResponse{}}, nil
}

// FindYearlyTransferSenderAmountStats is the resolver for the findYearlyTransferSenderAmountStats field.
func (r *queryResolver) FindYearlyTransferSenderAmountStats(ctx context.Context, input model.FindYearCardNumberStatsInput) (*model.APIResponseYearlyAmount, error) {
	return &model.APIResponseYearlyAmount{Status: "success", Message: "ok", Data: []*model.YearlyAmountResponse{}}, nil
}

// FindMonthlyTransferReceiverAmountStats is the resolver for the findMonthlyTransferReceiverAmountStats field.
func (r *queryResolver) FindMonthlyTransferReceiverAmountStats(ctx context.Context, input model.FindYearCardNumberStatsInput) (*model.APIResponseMonthlyAmount, error) {
	return &model.APIResponseMonthlyAmount{Status: "success", Message: "ok", Data: []*model.MonthlyAmountResponse{}}, nil
}

// FindYearlyTransferReceiverAmountStats is the resolver for the findYearlyTransferReceiverAmountStats field.
func (r *queryResolver) FindYearlyTransferReceiverAmountStats(ctx context.Context, input model.FindYearCardNumberStatsInput) (*model.APIResponseYearlyAmount, error) {
	return &model.APIResponseYearlyAmount{Status: "success", Message: "ok", Data: []*model.YearlyAmountResponse{}}, nil
}

// FindMerchantTransactionsStats is the resolver for the findMerchantTransactionsStats field.
func (r *queryResolver) FindMerchantTransactionsStats(ctx context.Context, input model.FindMerchantTransactionsInput) (*model.APIResponseMerchantTransactions, error) {
	return &model.APIResponseMerchantTransactions{Status: "success", Message: "ok", Data: []*model.MerchantTransactionStatsResponse{}}, nil
}

// FindMerchantTransactionsByApikeyStats is the resolver for the findMerchantTransactionsByApikeyStats field.
func (r *queryResolver) FindMerchantTransactionsByApikeyStats(ctx context.Context, input model.FindMerchantTransactionsByApikeyInput) (*model.APIResponseMerchantTransactions, error) {
	return &model.APIResponseMerchantTransactions{Status: "success", Message: "ok", Data: []*model.MerchantTransactionStatsResponse{}}, nil
}

// FindMonthlyTopupStatusSuccessStats is the resolver for the findMonthlyTopupStatusSuccessStats field.
func (r *queryResolver) FindMonthlyTopupStatusSuccessStats(ctx context.Context, input model.FindMonthlyYearStatsInput) (*model.APIResponseMonthlyStatus, error) {
	return &model.APIResponseMonthlyStatus{Status: "success", Message: "ok", Data: []*model.MonthlyStatusResponse{}}, nil
}

// FindYearlyTopupStatusSuccessStats is the resolver for the findYearlyTopupStatusSuccessStats field.
func (r *queryResolver) FindYearlyTopupStatusSuccessStats(ctx context.Context, input model.FindYearStatsInput) (*model.APIResponseYearlyStatus, error) {
	return &model.APIResponseYearlyStatus{Status: "success", Message: "ok", Data: []*model.YearlyStatusResponse{}}, nil
}

// FindMonthlyTopupStatusFailedStats is the resolver for the findMonthlyTopupStatusFailedStats field.
func (r *queryResolver) FindMonthlyTopupStatusFailedStats(ctx context.Context, input model.FindMonthlyYearStatsInput) (*model.APIResponseMonthlyStatus, error) {
	return &model.APIResponseMonthlyStatus{Status: "success", Message: "ok", Data: []*model.MonthlyStatusResponse{}}, nil
}

// FindYearlyTopupStatusFailedStats is the resolver for the findYearlyTopupStatusFailedStats field.
func (r *queryResolver) FindYearlyTopupStatusFailedStats(ctx context.Context, input model.FindYearStatsInput) (*model.APIResponseYearlyStatus, error) {
	return &model.APIResponseYearlyStatus{Status: "success", Message: "ok", Data: []*model.YearlyStatusResponse{}}, nil
}

// FindMonthlyTopupMethodsStats is the resolver for the findMonthlyTopupMethodsStats field.
func (r *queryResolver) FindMonthlyTopupMethodsStats(ctx context.Context, input model.FindYearStatsInput) (*model.APIResponseMonthlyMethod, error) {
	return &model.APIResponseMonthlyMethod{Status: "success", Message: "ok", Data: []*model.MonthlyMethodResponse{}}, nil
}

// FindYearlyTopupMethodsStats is the resolver for the findYearlyTopupMethodsStats field.
func (r *queryResolver) FindYearlyTopupMethodsStats(ctx context.Context, input model.FindYearStatsInput) (*model.APIResponseYearlyMethod, error) {
	return &model.APIResponseYearlyMethod{Status: "success", Message: "ok", Data: []*model.YearlyMethodResponse{}}, nil
}

// FindMonthlyTransactionStatusSuccessStats is the resolver for the findMonthlyTransactionStatusSuccessStats field.
func (r *queryResolver) FindMonthlyTransactionStatusSuccessStats(ctx context.Context, input model.FindMonthlyYearStatsInput) (*model.APIResponseMonthlyStatus, error) {
	return &model.APIResponseMonthlyStatus{Status: "success", Message: "ok", Data: []*model.MonthlyStatusResponse{}}, nil
}

// FindYearlyTransactionStatusSuccessStats is the resolver for the findYearlyTransactionStatusSuccessStats field.
func (r *queryResolver) FindYearlyTransactionStatusSuccessStats(ctx context.Context, input model.FindYearStatsInput) (*model.APIResponseYearlyStatus, error) {
	return &model.APIResponseYearlyStatus{Status: "success", Message: "ok", Data: []*model.YearlyStatusResponse{}}, nil
}

// FindMonthlyTransactionStatusFailedStats is the resolver for the findMonthlyTransactionStatusFailedStats field.
func (r *queryResolver) FindMonthlyTransactionStatusFailedStats(ctx context.Context, input model.FindMonthlyYearStatsInput) (*model.APIResponseMonthlyStatus, error) {
	return &model.APIResponseMonthlyStatus{Status: "success", Message: "ok", Data: []*model.MonthlyStatusResponse{}}, nil
}

// FindYearlyTransactionStatusFailedStats is the resolver for the findYearlyTransactionStatusFailedStats field.
func (r *queryResolver) FindYearlyTransactionStatusFailedStats(ctx context.Context, input model.FindYearStatsInput) (*model.APIResponseYearlyStatus, error) {
	return &model.APIResponseYearlyStatus{Status: "success", Message: "ok", Data: []*model.YearlyStatusResponse{}}, nil
}

// FindMonthlyTransactionMethodsStats is the resolver for the findMonthlyTransactionMethodsStats field.
func (r *queryResolver) FindMonthlyTransactionMethodsStats(ctx context.Context, input model.FindYearStatsInput) (*model.APIResponseMonthlyMethod, error) {
	return &model.APIResponseMonthlyMethod{Status: "success", Message: "ok", Data: []*model.MonthlyMethodResponse{}}, nil
}

// FindYearlyTransactionMethodsStats is the resolver for the findYearlyTransactionMethodsStats field.
func (r *queryResolver) FindYearlyTransactionMethodsStats(ctx context.Context, input model.FindYearStatsInput) (*model.APIResponseYearlyMethod, error) {
	return &model.APIResponseYearlyMethod{Status: "success", Message: "ok", Data: []*model.YearlyMethodResponse{}}, nil
}

// FindMonthlyTransferStatusSuccessStats is the resolver for the findMonthlyTransferStatusSuccessStats field.
func (r *queryResolver) FindMonthlyTransferStatusSuccessStats(ctx context.Context, input model.FindMonthlyYearStatsInput) (*model.APIResponseMonthlyStatus, error) {
	return &model.APIResponseMonthlyStatus{Status: "success", Message: "ok", Data: []*model.MonthlyStatusResponse{}}, nil
}

// FindYearlyTransferStatusSuccessStats is the resolver for the findYearlyTransferStatusSuccessStats field.
func (r *queryResolver) FindYearlyTransferStatusSuccessStats(ctx context.Context, input model.FindYearStatsInput) (*model.APIResponseYearlyStatus, error) {
	return &model.APIResponseYearlyStatus{Status: "success", Message: "ok", Data: []*model.YearlyStatusResponse{}}, nil
}

// FindMonthlyTransferStatusFailedStats is the resolver for the findMonthlyTransferStatusFailedStats field.
func (r *queryResolver) FindMonthlyTransferStatusFailedStats(ctx context.Context, input model.FindMonthlyYearStatsInput) (*model.APIResponseMonthlyStatus, error) {
	return &model.APIResponseMonthlyStatus{Status: "success", Message: "ok", Data: []*model.MonthlyStatusResponse{}}, nil
}

// FindYearlyTransferStatusFailedStats is the resolver for the findYearlyTransferStatusFailedStats field.
func (r *queryResolver) FindYearlyTransferStatusFailedStats(ctx context.Context, input model.FindYearStatsInput) (*model.APIResponseYearlyStatus, error) {
	return &model.APIResponseYearlyStatus{Status: "success", Message: "ok", Data: []*model.YearlyStatusResponse{}}, nil
}

// FindMonthlyWithdrawStatusSuccessStats is the resolver for the findMonthlyWithdrawStatusSuccessStats field.
func (r *queryResolver) FindMonthlyWithdrawStatusSuccessStats(ctx context.Context, input model.FindMonthlyYearStatsInput) (*model.APIResponseMonthlyStatus, error) {
	return &model.APIResponseMonthlyStatus{Status: "success", Message: "ok", Data: []*model.MonthlyStatusResponse{}}, nil
}

// FindYearlyWithdrawStatusSuccessStats is the resolver for the findYearlyWithdrawStatusSuccessStats field.
func (r *queryResolver) FindYearlyWithdrawStatusSuccessStats(ctx context.Context, input model.FindYearStatsInput) (*model.APIResponseYearlyStatus, error) {
	return &model.APIResponseYearlyStatus{Status: "success", Message: "ok", Data: []*model.YearlyStatusResponse{}}, nil
}

// FindMonthlyWithdrawStatusFailedStats is the resolver for the findMonthlyWithdrawStatusFailedStats field.
func (r *queryResolver) FindMonthlyWithdrawStatusFailedStats(ctx context.Context, input model.FindMonthlyYearStatsInput) (*model.APIResponseMonthlyStatus, error) {
	return &model.APIResponseMonthlyStatus{Status: "success", Message: "ok", Data: []*model.MonthlyStatusResponse{}}, nil
}

// FindYearlyWithdrawStatusFailedStats is the resolver for the findYearlyWithdrawStatusFailedStats field.
func (r *queryResolver) FindYearlyWithdrawStatusFailedStats(ctx context.Context, input model.FindYearStatsInput) (*model.APIResponseYearlyStatus, error) {
	return &model.APIResponseYearlyStatus{Status: "success", Message: "ok", Data: []*model.YearlyStatusResponse{}}, nil
}

// FindMonthlySaldoBalanceStats is the resolver for the findMonthlySaldoBalanceStats field.
func (r *queryResolver) FindMonthlySaldoBalanceStats(ctx context.Context, input model.FindYearStatsInput) (*model.APIResponseMonthlyBalance, error) {
	return &model.APIResponseMonthlyBalance{Status: "success", Message: "ok", Data: []*model.MonthlyBalanceResponse{}}, nil
}

// FindYearlySaldoBalanceStats is the resolver for the findYearlySaldoBalanceStats field.
func (r *queryResolver) FindYearlySaldoBalanceStats(ctx context.Context, input model.FindYearStatsInput) (*model.APIResponseYearlyBalance, error) {
	return &model.APIResponseYearlyBalance{Status: "success", Message: "ok", Data: []*model.YearlyBalanceResponse{}}, nil
}

// FindMonthlySaldoTotalStats is the resolver for the findMonthlySaldoTotalStats field.
func (r *queryResolver) FindMonthlySaldoTotalStats(ctx context.Context, input model.FindYearStatsInput) (*model.APIResponseMonthlyAmount, error) {
	return &model.APIResponseMonthlyAmount{Status: "success", Message: "ok", Data: []*model.MonthlyAmountResponse{}}, nil
}

// FindYearlySaldoTotalStats is the resolver for the findYearlySaldoTotalStats field.
func (r *queryResolver) FindYearlySaldoTotalStats(ctx context.Context, input model.FindYearStatsInput) (*model.APIResponseYearlyAmount, error) {
	return &model.APIResponseYearlyAmount{Status: "success", Message: "ok", Data: []*model.YearlyAmountResponse{}}, nil
}

// FindMonthlyMerchantAmountStats is the resolver for the findMonthlyMerchantAmountStats field.
func (r *queryResolver) FindMonthlyMerchantAmountStats(ctx context.Context, input model.FindYearMerchantStatsInput) (*model.APIResponseMonthlyAmount, error) {
	return &model.APIResponseMonthlyAmount{Status: "success", Message: "ok", Data: []*model.MonthlyAmountResponse{}}, nil
}

// FindYearlyMerchantAmountStats is the resolver for the findYearlyMerchantAmountStats field.
func (r *queryResolver) FindYearlyMerchantAmountStats(ctx context.Context, input model.FindYearMerchantStatsInput) (*model.APIResponseYearlyAmount, error) {
	return &model.APIResponseYearlyAmount{Status: "success", Message: "ok", Data: []*model.YearlyAmountResponse{}}, nil
}

// FindMonthlyMerchantMethodStats is the resolver for the findMonthlyMerchantMethodStats field.
func (r *queryResolver) FindMonthlyMerchantMethodStats(ctx context.Context, input model.FindYearMerchantStatsInput) (*model.APIResponseMonthlyMethod, error) {
	return &model.APIResponseMonthlyMethod{Status: "success", Message: "ok", Data: []*model.MonthlyMethodResponse{}}, nil
}

// FindYearlyMerchantMethodStats is the resolver for the findYearlyMerchantMethodStats field.
func (r *queryResolver) FindYearlyMerchantMethodStats(ctx context.Context, input model.FindYearMerchantStatsInput) (*model.APIResponseYearlyMethod, error) {
	return &model.APIResponseYearlyMethod{Status: "success", Message: "ok", Data: []*model.YearlyMethodResponse{}}, nil
}

// FindMonthlyMerchantTotalAmountStats is the resolver for the findMonthlyMerchantTotalAmountStats field.
func (r *queryResolver) FindMonthlyMerchantTotalAmountStats(ctx context.Context, input model.FindYearMerchantStatsInput) (*model.APIResponseMonthlyAmount, error) {
	return &model.APIResponseMonthlyAmount{Status: "success", Message: "ok", Data: []*model.MonthlyAmountResponse{}}, nil
}

// FindYearlyMerchantTotalAmountStats is the resolver for the findYearlyMerchantTotalAmountStats field.
func (r *queryResolver) FindYearlyMerchantTotalAmountStats(ctx context.Context, input model.FindYearMerchantStatsInput) (*model.APIResponseYearlyAmount, error) {
	return &model.APIResponseYearlyAmount{Status: "success", Message: "ok", Data: []*model.YearlyAmountResponse{}}, nil
}

// FindMonthlyMerchantAmountByIDStats is the resolver for the findMonthlyMerchantAmountByIdStats field.
func (r *queryResolver) FindMonthlyMerchantAmountByIDStats(ctx context.Context, input model.FindYearMerchantByIDStatsInput) (*model.APIResponseMonthlyAmount, error) {
	return &model.APIResponseMonthlyAmount{Status: "success", Message: "ok", Data: []*model.MonthlyAmountResponse{}}, nil
}

// FindYearlyMerchantAmountByIDStats is the resolver for the findYearlyMerchantAmountByIdStats field.
func (r *queryResolver) FindYearlyMerchantAmountByIDStats(ctx context.Context, input model.FindYearMerchantByIDStatsInput) (*model.APIResponseYearlyAmount, error) {
	return &model.APIResponseYearlyAmount{Status: "success", Message: "ok", Data: []*model.YearlyAmountResponse{}}, nil
}

// FindMonthlyMerchantMethodByIDStats is the resolver for the findMonthlyMerchantMethodByIdStats field.
func (r *queryResolver) FindMonthlyMerchantMethodByIDStats(ctx context.Context, input model.FindYearMerchantByIDStatsInput) (*model.APIResponseMonthlyMethod, error) {
	return &model.APIResponseMonthlyMethod{Status: "success", Message: "ok", Data: []*model.MonthlyMethodResponse{}}, nil
}

// FindYearlyMerchantMethodByIDStats is the resolver for the findYearlyMerchantMethodByIdStats field.
func (r *queryResolver) FindYearlyMerchantMethodByIDStats(ctx context.Context, input model.FindYearMerchantByIDStatsInput) (*model.APIResponseYearlyMethod, error) {
	return &model.APIResponseYearlyMethod{Status: "success", Message: "ok", Data: []*model.YearlyMethodResponse{}}, nil
}

// FindMonthlyMerchantTotalAmountByIDStats is the resolver for the findMonthlyMerchantTotalAmountByIdStats field.
func (r *queryResolver) FindMonthlyMerchantTotalAmountByIDStats(ctx context.Context, input model.FindYearMerchantByIDStatsInput) (*model.APIResponseMonthlyAmount, error) {
	return &model.APIResponseMonthlyAmount{Status: "success", Message: "ok", Data: []*model.MonthlyAmountResponse{}}, nil
}

// FindYearlyMerchantTotalAmountByIDStats is the resolver for the findYearlyMerchantTotalAmountByIdStats field.
func (r *queryResolver) FindYearlyMerchantTotalAmountByIDStats(ctx context.Context, input model.FindYearMerchantByIDStatsInput) (*model.APIResponseYearlyAmount, error) {
	return &model.APIResponseYearlyAmount{Status: "success", Message: "ok", Data: []*model.YearlyAmountResponse{}}, nil
}

// FindMonthlyMerchantAmountByApikeyStats is the resolver for the findMonthlyMerchantAmountByApikeyStats field.
func (r *queryResolver) FindMonthlyMerchantAmountByApikeyStats(ctx context.Context, input model.FindYearMerchantByApikeyStatsInput) (*model.APIResponseMonthlyAmount, error) {
	return &model.APIResponseMonthlyAmount{Status: "success", Message: "ok", Data: []*model.MonthlyAmountResponse{}}, nil
}

// FindYearlyMerchantAmountByApikeyStats is the resolver for the findYearlyMerchantAmountByApikeyStats field.
func (r *queryResolver) FindYearlyMerchantAmountByApikeyStats(ctx context.Context, input model.FindYearMerchantByApikeyStatsInput) (*model.APIResponseYearlyAmount, error) {
	return &model.APIResponseYearlyAmount{Status: "success", Message: "ok", Data: []*model.YearlyAmountResponse{}}, nil
}

// FindMonthlyMerchantMethodByApikeyStats is the resolver for the findMonthlyMerchantMethodByApikeyStats field.
func (r *queryResolver) FindMonthlyMerchantMethodByApikeyStats(ctx context.Context, input model.FindYearMerchantByApikeyStatsInput) (*model.APIResponseMonthlyMethod, error) {
	return &model.APIResponseMonthlyMethod{Status: "success", Message: "ok", Data: []*model.MonthlyMethodResponse{}}, nil
}

// FindYearlyMerchantMethodByApikeyStats is the resolver for the findYearlyMerchantMethodByApikeyStats field.
func (r *queryResolver) FindYearlyMerchantMethodByApikeyStats(ctx context.Context, input model.FindYearMerchantByApikeyStatsInput) (*model.APIResponseYearlyMethod, error) {
	return &model.APIResponseYearlyMethod{Status: "success", Message: "ok", Data: []*model.YearlyMethodResponse{}}, nil
}

// FindMonthlyMerchantTotalAmountByApikeyStats is the resolver for the findMonthlyMerchantTotalAmountByApikeyStats field.
func (r *queryResolver) FindMonthlyMerchantTotalAmountByApikeyStats(ctx context.Context, input model.FindYearMerchantByApikeyStatsInput) (*model.APIResponseMonthlyAmount, error) {
	return &model.APIResponseMonthlyAmount{Status: "success", Message: "ok", Data: []*model.MonthlyAmountResponse{}}, nil
}

// FindYearlyMerchantTotalAmountByApikeyStats is the resolver for the findYearlyMerchantTotalAmountByApikeyStats field.
func (r *queryResolver) FindYearlyMerchantTotalAmountByApikeyStats(ctx context.Context, input model.FindYearMerchantByApikeyStatsInput) (*model.APIResponseYearlyAmount, error) {
	return &model.APIResponseYearlyAmount{Status: "success", Message: "ok", Data: []*model.YearlyAmountResponse{}}, nil
}
