package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	errors "github.com/MamangRust/microservice-payment-gateway-grpc/shared/errors"

	pb "github.com/MamangRust/microservice-payment-gateway-grpc/pb/topup"
	"github.com/MamangRust/microservice-payment-gateway-grpc/service/apigateway/internal/model"
	"github.com/MamangRust/microservice-payment-gateway-grpc/shared/domain/requests"
	"google.golang.org/protobuf/types/known/emptypb"
)

// CreateTopup is the resolver for the createTopup field.
func (r *mutationResolver) CreateTopup(ctx context.Context, input model.CreateTopupInput) (*model.APIResponseTopup, error) {
	return ResolverHandle(r.ResolverHandle, "CreateTopup", ctx, func(ctx context.Context) (*model.APIResponseTopup, error) {
		request := requests.CreateTopupRequest{
			CardNumber:  input.CardNumber,
			TopupAmount: int(input.TopupAmount),
			TopupMethod: input.TopupMethod,
		}

		if err := request.Validate(); err != nil {
			validations := r.parseValidationErrors(err)
			return nil, errors.NewValidationError(validations)
		}

		req := &pb.CreateTopupRequest{
			CardNumber:  input.CardNumber,
			TopupAmount: int64(input.TopupAmount),
			TopupMethod: input.TopupMethod,
		}

		res, err := r.TopupGraphql.TopupClient.TopupCommandClient.CreateTopup(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "CreateTopup")
		}

		so := r.TopupGraphql.Mapping.ToGraphqlResponseTopup(res)

		return so, nil
	})
}

// UpdateTopup is the resolver for the updateTopup field.
func (r *mutationResolver) UpdateTopup(ctx context.Context, input model.UpdateTopupInput) (*model.APIResponseTopup, error) {
	return ResolverHandle(r.ResolverHandle, "UpdateTopup", ctx, func(ctx context.Context) (*model.APIResponseTopup, error) {
		id := int(input.TopupID)
		if id == 0 {
			return nil, errors.NewBadRequestError("invalid request: topup ID cannot be zero")
		}

		request := requests.UpdateTopupRequest{
			TopupID:     &id,
			CardNumber:  input.CardNumber,
			TopupAmount: int(input.TopupAmount),
			TopupMethod: input.TopupMethod,
		}

		if err := request.Validate(); err != nil {
			validations := r.parseValidationErrors(err)
			return nil, errors.NewValidationError(validations)
		}

		req := &pb.UpdateTopupRequest{
			TopupId:     int32(id),
			CardNumber:  input.CardNumber,
			TopupAmount: int64(input.TopupAmount),
			TopupMethod: input.TopupMethod,
		}

		res, err := r.TopupGraphql.TopupClient.TopupCommandClient.UpdateTopup(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "UpdateTopup")
		}

		so := r.TopupGraphql.Mapping.ToGraphqlResponseTopup(res)

		r.TopupGraphql.Cache.DeleteCachedTopupCache(ctx, id)

		return so, nil
	})
}

// TrashedTopup is the resolver for the trashedTopup field.
func (r *mutationResolver) TrashedTopup(ctx context.Context, input model.FindByIDTopupInput) (*model.APIResponseTopupDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "TrashedTopup", ctx, func(ctx context.Context) (*model.APIResponseTopupDeleteAt, error) {
		id := int(input.TopupID)
		if id == 0 {
			return nil, errors.NewBadRequestError("invalid request: topup ID cannot be zero")
		}

		topup, err := r.TopupGraphql.TopupClient.TopupCommandClient.TrashedTopup(ctx, &pb.FindByIdTopupRequest{
			TopupId: int32(id),
		})
		if err != nil {
			return nil, r.handleGraphQLError(err, "TrashedTopup")
		}

		so := r.TopupGraphql.Mapping.ToGraphqlResponseTopupDeleteAt(topup)

		r.TopupGraphql.Cache.DeleteCachedTopupCache(ctx, id)

		return so, nil
	})
}

// RestoreTopup is the resolver for the restoreTopup field.
func (r *mutationResolver) RestoreTopup(ctx context.Context, input model.FindByIDTopupInput) (*model.APIResponseTopupDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "RestoreTopup", ctx, func(ctx context.Context) (*model.APIResponseTopupDeleteAt, error) {
		id := int(input.TopupID)
		if id == 0 {
			return nil, errors.NewBadRequestError("invalid request: topup ID cannot be zero")
		}

		topup, err := r.TopupGraphql.TopupClient.TopupCommandClient.RestoreTopup(ctx, &pb.FindByIdTopupRequest{
			TopupId: int32(id),
		})
		if err != nil {
			return nil, r.handleGraphQLError(err, "RestoreTopup")
		}

		so := r.TopupGraphql.Mapping.ToGraphqlResponseTopupDeleteAt(topup)

		r.TopupGraphql.Cache.DeleteCachedTopupCache(ctx, id)

		return so, nil
	})
}

// DeleteTopupPermanent is the resolver for the deleteTopupPermanent field.
func (r *mutationResolver) DeleteTopupPermanent(ctx context.Context, input model.FindByIDTopupInput) (*model.APIResponseTopupDelete, error) {
	return ResolverHandle(r.ResolverHandle, "DeleteTopupPermanent", ctx, func(ctx context.Context) (*model.APIResponseTopupDelete, error) {
		id := int(input.TopupID)
		if id == 0 {
			return nil, errors.NewBadRequestError("invalid request: topup ID cannot be zero")
		}

		res, err := r.TopupGraphql.TopupClient.TopupCommandClient.DeleteTopupPermanent(ctx, &pb.FindByIdTopupRequest{TopupId: int32(id)})
		if err != nil {
			return nil, r.handleGraphQLError(err, "DeleteTopupPermanent")
		}

		so := r.TopupGraphql.Mapping.ToGraphqlTopupDelete(res)

		r.TopupGraphql.Cache.DeleteCachedTopupCache(ctx, id)

		return so, nil
	})
}

// RestoreAllTopup is the resolver for the restoreAllTopup field.
func (r *mutationResolver) RestoreAllTopup(ctx context.Context) (*model.APIResponseTopupAll, error) {
	return ResolverHandle(r.ResolverHandle, "RestoreAllTopup", ctx, func(ctx context.Context) (*model.APIResponseTopupAll, error) {
		res, err := r.TopupGraphql.TopupClient.TopupCommandClient.RestoreAllTopup(ctx, &emptypb.Empty{})
		if err != nil {
			return nil, r.handleGraphQLError(err, "RestoreAllTopup")
		}

		so := r.TopupGraphql.Mapping.ToGraphqlTopupAll(res)

		return so, nil
	})
}

// DeleteAllTopupPermanent is the resolver for the deleteAllSaldoPermanent field.
func (r *mutationResolver) DeleteAllTopupPermanent(ctx context.Context) (*model.APIResponseTopupAll, error) {
	return ResolverHandle(r.ResolverHandle, "DeleteAllTopupPermanent", ctx, func(ctx context.Context) (*model.APIResponseTopupAll, error) {
		res, err := r.TopupGraphql.TopupClient.TopupCommandClient.DeleteAllTopupPermanent(ctx, &emptypb.Empty{})
		if err != nil {
			return nil, r.handleGraphQLError(err, "DeleteAllTopupPermanent")
		}

		so := r.TopupGraphql.Mapping.ToGraphqlTopupAll(res)

		return so, nil
	})
}

// FindAllTopup is the resolver for the findAllTopup field.
func (r *queryResolver) FindAllTopup(ctx context.Context, input model.FindAllTopupInput) (*model.APIResponsePaginationTopup, error) {
	return ResolverHandle(r.ResolverHandle, "FindAllTopup", ctx, func(ctx context.Context) (*model.APIResponsePaginationTopup, error) {
		page := int32(1)
		pageSize := int32(10)
		search := ""

		if input.Page != nil && *input.Page > 0 {
			page = int32(*input.Page)
		}
		if input.PageSize != nil && *input.PageSize > 0 {
			pageSize = int32(*input.PageSize)
		}
		if input.Search != nil {
			search = *input.Search
		}

		normalizedInput := model.FindAllTopupInput{
			Page:     input.Page,
			PageSize: input.PageSize,
			Search:   &search,
		}

		cachedData, found := r.TopupGraphql.Cache.GetCachedTopupsCache(ctx, &normalizedInput)
		if found {
			return cachedData, nil
		}

		reqService := &pb.FindAllTopupRequest{
			Page:     page,
			PageSize: pageSize,
			Search:   search,
		}

		topups, errResp := r.TopupGraphql.TopupClient.TopupQueryClient.FindAllTopup(ctx, reqService)
		if errResp != nil {
			return nil, r.handleGraphQLError(errResp, "FindAllTopup")
		}

		so := r.TopupGraphql.Mapping.ToGraphqlResponsePaginationTopup(topups)

		r.TopupGraphql.Cache.SetCachedTopupsCache(ctx, &normalizedInput, so)

		return so, nil
	})
}

// FindByIDTopup is the resolver for the findByIdTopup field.
func (r *queryResolver) FindByIDTopup(ctx context.Context, input model.FindByIDTopupInput) (*model.APIResponseTopup, error) {
	return ResolverHandle(r.ResolverHandle, "FindByIDTopup", ctx, func(ctx context.Context) (*model.APIResponseTopup, error) {
		id := int(input.TopupID)
		if id == 0 {
			return nil, errors.NewBadRequestError("invalid request: topup ID cannot be zero")
		}

		cachedData, found := r.TopupGraphql.Cache.GetCachedTopupCache(ctx, id)
		if found {
			return cachedData, nil
		}

		topup, err := r.TopupGraphql.TopupClient.TopupQueryClient.FindByIdTopup(ctx, &pb.FindByIdTopupRequest{TopupId: int32(id)})
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindByIDTopup")
		}

		so := r.TopupGraphql.Mapping.ToGraphqlResponseTopup(topup)

		r.TopupGraphql.Cache.SetCachedTopupCache(ctx, so)

		return so, nil
	})
}

// FindByCardNumberTopup is the resolver for the findByCardNumberTopup field.
func (r *queryResolver) FindByCardNumberTopup(ctx context.Context, input model.FindByCardNumberTopupInput) (*model.APIResponseTopup, error) {
	return ResolverHandle(r.ResolverHandle, "FindByCardNumberTopup", ctx, func(ctx context.Context) (*model.APIResponseTopup, error) {
		cardNumber := input.CardNumber
		year := int32(0)
		if input.Year != nil {
			year = *input.Year
		}

		if cardNumber == "" {
			return nil, errors.NewBadRequestError("invalid request: card number cannot be empty")
		}

		reqService := &pb.FindByCardNumberTopupRequest{
			CardNumber: cardNumber,
			Year:       year,
		}

		res, err := r.TopupGraphql.TopupClient.TopupQueryClient.FindByCardNumberTopup(ctx, reqService)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindByCardNumberTopup")
		}

		so := r.TopupGraphql.Mapping.ToGraphqlResponseTopup(res)

		return so, nil
	})
}

// FindByActiveTopup is the resolver for the findByActiveTopup field.
func (r *queryResolver) FindByActiveTopup(ctx context.Context, input model.FindAllTopupInput) (*model.APIResponsePaginationTopupDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "FindByActiveTopup", ctx, func(ctx context.Context) (*model.APIResponsePaginationTopupDeleteAt, error) {
		page := int32(1)
		pageSize := int32(10)
		search := ""

		if input.Page != nil && *input.Page > 0 {
			page = int32(*input.Page)
		}
		if input.PageSize != nil && *input.PageSize > 0 {
			pageSize = int32(*input.PageSize)
		}
		if input.Search != nil {
			search = *input.Search
		}

		normalizedInput := model.FindAllTopupInput{
			Page:     input.Page,
			PageSize: input.PageSize,
			Search:   &search,
		}

		cachedData, found := r.TopupGraphql.Cache.GetCachedTopupActiveCache(ctx, &normalizedInput)
		if found {
			return cachedData, nil
		}

		reqService := &pb.FindAllTopupRequest{
			Page:     page,
			PageSize: pageSize,
			Search:   search,
		}

		topups, errResp := r.TopupGraphql.TopupClient.TopupQueryClient.FindByActive(ctx, reqService)
		if errResp != nil {
			return nil, r.handleGraphQLError(errResp, "FindByActiveTopup")
		}

		so := r.TopupGraphql.Mapping.ToGraphqlResponsePaginationTopupDeleteAt(topups)

		r.TopupGraphql.Cache.SetCachedTopupActiveCache(ctx, &normalizedInput, so)

		return so, nil
	})
}

// FindByTrashedTopup is the resolver for the findByTrashedTopup field.
func (r *queryResolver) FindByTrashedTopup(ctx context.Context, input model.FindAllTopupInput) (*model.APIResponsePaginationTopupDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "FindByTrashedTopup", ctx, func(ctx context.Context) (*model.APIResponsePaginationTopupDeleteAt, error) {
		page := int32(1)
		pageSize := int32(10)
		search := ""

		if input.Page != nil && *input.Page > 0 {
			page = int32(*input.Page)
		}
		if input.PageSize != nil && *input.PageSize > 0 {
			pageSize = int32(*input.PageSize)
		}
		if input.Search != nil {
			search = *input.Search
		}

		normalizedInput := model.FindAllTopupInput{
			Page:     input.Page,
			PageSize: input.PageSize,
			Search:   &search,
		}

		cachedData, found := r.TopupGraphql.Cache.GetCachedTopupTrashedCache(ctx, &normalizedInput)
		if found {
			return cachedData, nil
		}

		reqService := &pb.FindAllTopupRequest{
			Page:     page,
			PageSize: pageSize,
			Search:   search,
		}

		topups, errResp := r.TopupGraphql.TopupClient.TopupQueryClient.FindByTrashed(ctx, reqService)
		if errResp != nil {
			return nil, r.handleGraphQLError(errResp, "FindByTrashedTopup")
		}

		so := r.TopupGraphql.Mapping.ToGraphqlResponsePaginationTopupDeleteAt(topups)

		r.TopupGraphql.Cache.SetCachedTopupTrashedCache(ctx, &normalizedInput, so)

		return so, nil
	})
}
