package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	errors "github.com/MamangRust/microservice-payment-gateway-grpc/shared/errors"
	"time"

	pb "github.com/MamangRust/microservice-payment-gateway-grpc/pb/transaction"
	"github.com/MamangRust/microservice-payment-gateway-grpc/service/apigateway/internal/model"
	"github.com/MamangRust/microservice-payment-gateway-grpc/shared/domain/requests"
	"google.golang.org/protobuf/types/known/emptypb"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// CreateTransaction is the resolver for the createTransaction field.
func (r *mutationResolver) CreateTransaction(ctx context.Context, input model.CreateTransactionInput) (*model.APIResponseTransaction, error) {
	return ResolverHandle(r.ResolverHandle, "CreateTransaction", ctx, func(ctx context.Context) (*model.APIResponseTransaction, error) {
		_, err := r.TransactionGraphql.Permission.ValidateMerchant(ctx, input.APIKey)
		if err != nil {
			return nil, errors.NewBadRequestError("failed to validate API key: " + err.Error())
		}

		transactionTime, err := time.Parse("2006-01-02", *input.TransactionTime)
		if err != nil {
			return nil, errors.NewBadRequestError("invalid date format for transactionTime: " + err.Error() + " (expected YYYY-MM-DD)")
		}
		merchantId := int(input.MerchantID)

		request := &requests.CreateTransactionRequest{
			CardNumber:      input.CardNumber,
			Amount:          int(input.Amount),
			PaymentMethod:   input.PaymentMethod,
			MerchantID:      &merchantId,
			TransactionTime: transactionTime,
		}

		if err := request.Validate(); err != nil {
			validations := r.parseValidationErrors(err)
			return nil, errors.NewValidationError(validations)
		}

		req := &pb.CreateTransactionRequest{
			ApiKey:          input.APIKey,
			CardNumber:      input.CardNumber,
			Amount:          int64(input.Amount),
			PaymentMethod:   input.PaymentMethod,
			MerchantId:      int32(merchantId),
			TransactionTime: timestamppb.New(transactionTime),
		}

		res, errResp := r.TransactionGraphql.TransactionClient.TransactionCommandClient.CreateTransaction(ctx, req)
		if errResp != nil {
			return nil, r.handleGraphQLError(errResp, "CreateTransaction")
		}

		so := r.TransactionGraphql.Mapping.ToGraphqlResponseTransaction(res)
		if so != nil && so.Data != nil {
			r.TransactionGraphql.Cache.DeleteTransactionCache(ctx, int(so.Data.ID))
		}

		return so, nil
	})
}

// UpdateTransaction is the resolver for the updateTransaction field.
func (r *mutationResolver) UpdateTransaction(ctx context.Context, input model.UpdateTransactionInput) (*model.APIResponseTransaction, error) {
	return ResolverHandle(r.ResolverHandle, "UpdateTransaction", ctx, func(ctx context.Context) (*model.APIResponseTransaction, error) {
		id := int32(input.TransactionID)
		if id == 0 {
			return nil, errors.NewBadRequestError("Invalid Transaction ID")
		}

		_, err := r.TransactionGraphql.Permission.ValidateMerchant(ctx, input.APIKey)
		if err != nil {
			return nil, errors.NewBadRequestError("failed to validate API key: " + err.Error())
		}

		transactionTime, err := time.Parse("2006-01-02", *input.TransactionTime)
		if err != nil {
			return nil, errors.NewBadRequestError("invalid date format for transactionTime: " + err.Error() + " (expected YYYY-MM-DD)")
		}
		merchantId := int(input.MerchantID)

		txnId := int(id)
		request := &requests.UpdateTransactionRequest{
			TransactionID:   &txnId,
			CardNumber:      input.CardNumber,
			Amount:          int(input.Amount),
			PaymentMethod:   input.PaymentMethod,
			MerchantID:      &merchantId,
			TransactionTime: transactionTime,
		}

		if err := request.Validate(); err != nil {
			validations := r.parseValidationErrors(err)
			return nil, errors.NewValidationError(validations)
		}

		req := &pb.UpdateTransactionRequest{
			ApiKey:          input.APIKey,
			TransactionId:   id,
			CardNumber:      input.CardNumber,
			Amount:          int64(input.Amount),
			PaymentMethod:   input.PaymentMethod,
			MerchantId:      int32(merchantId),
			TransactionTime: timestamppb.New(transactionTime),
		}

		res, errResp := r.TransactionGraphql.TransactionClient.TransactionCommandClient.UpdateTransaction(ctx, req)
		if errResp != nil {
			return nil, r.handleGraphQLError(errResp, "UpdateTransaction")
		}

		so := r.TransactionGraphql.Mapping.ToGraphqlResponseTransaction(res)
		r.TransactionGraphql.Cache.DeleteTransactionCache(ctx, int(id))

		return so, nil
	})
}

// TrashedTransaction is the resolver for the trashedTransaction field.
func (r *mutationResolver) TrashedTransaction(ctx context.Context, input model.FindByIDTransactionInput) (*model.APIResponseTransactionDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "TrashedTransaction", ctx, func(ctx context.Context) (*model.APIResponseTransactionDeleteAt, error) {
		id := int32(input.TransactionID)
		if id == 0 {
			return nil, errors.NewBadRequestError("Invalid Transaction ID")
		}

		res, err := r.TransactionGraphql.TransactionClient.TransactionCommandClient.TrashedTransaction(ctx, &pb.FindByIdTransactionRequest{
			TransactionId: id,
		})
		if err != nil {
			return nil, r.handleGraphQLError(err, "TrashedTransaction")
		}

		so := r.TransactionGraphql.Mapping.ToGraphqlResponseTransactionDeleteAt(res)
		r.TransactionGraphql.Cache.DeleteTransactionCache(ctx, int(id))

		return so, nil
	})
}

// RestoreTransaction is the resolver for the restoreTransaction field.
func (r *mutationResolver) RestoreTransaction(ctx context.Context, input model.FindByIDTransactionInput) (*model.APIResponseTransactionDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "RestoreTransaction", ctx, func(ctx context.Context) (*model.APIResponseTransactionDeleteAt, error) {
		id := int32(input.TransactionID)
		if id == 0 {
			return nil, errors.NewBadRequestError("Invalid Transaction ID")
		}

		res, err := r.TransactionGraphql.TransactionClient.TransactionCommandClient.RestoreTransaction(ctx, &pb.FindByIdTransactionRequest{
			TransactionId: id,
		})
		if err != nil {
			return nil, r.handleGraphQLError(err, "RestoreTransaction")
		}

		so := r.TransactionGraphql.Mapping.ToGraphqlResponseTransactionDeleteAt(res)
		r.TransactionGraphql.Cache.DeleteTransactionCache(ctx, int(id))

		return so, nil
	})
}

// DeleteTransactionPermanent is the resolver for the deleteTransactionPermanent field.
func (r *mutationResolver) DeleteTransactionPermanent(ctx context.Context, input model.FindByIDTransactionInput) (*model.APIResponseTransactionDelete, error) {
	return ResolverHandle(r.ResolverHandle, "DeleteTransactionPermanent", ctx, func(ctx context.Context) (*model.APIResponseTransactionDelete, error) {
		id := int32(input.TransactionID)
		if id == 0 {
			return nil, errors.NewBadRequestError("Invalid Transaction ID")
		}

		res, err := r.TransactionGraphql.TransactionClient.TransactionCommandClient.DeleteTransactionPermanent(ctx, &pb.FindByIdTransactionRequest{
			TransactionId: id,
		})
		if err != nil {
			return nil, r.handleGraphQLError(err, "DeleteTransactionPermanent")
		}

		so := r.TransactionGraphql.Mapping.ToGraphqlTransactionDelete(res)
		r.TransactionGraphql.Cache.DeleteTransactionCache(ctx, int(id))

		return so, nil
	})
}

// RestoreAllTransaction is the resolver for the restoreAllTransaction field.
func (r *mutationResolver) RestoreAllTransaction(ctx context.Context) (*model.APIResponseTransactionAll, error) {
	return ResolverHandle(r.ResolverHandle, "RestoreAllTransaction", ctx, func(ctx context.Context) (*model.APIResponseTransactionAll, error) {
		res, err := r.TransactionGraphql.TransactionClient.TransactionCommandClient.RestoreAllTransaction(ctx, &emptypb.Empty{})
		if err != nil {
			return nil, r.handleGraphQLError(err, "RestoreAllTransaction")
		}

		so := r.TransactionGraphql.Mapping.ToGraphqlTransactionAll(res)
		return so, nil
	})
}

// DeleteAllTransactionPermanent is the resolver for the deleteAllTransactionPermanent field.
func (r *mutationResolver) DeleteAllTransactionPermanent(ctx context.Context) (*model.APIResponseTransactionAll, error) {
	return ResolverHandle(r.ResolverHandle, "DeleteAllTransactionPermanent", ctx, func(ctx context.Context) (*model.APIResponseTransactionAll, error) {
		res, err := r.TransactionGraphql.TransactionClient.TransactionCommandClient.DeleteAllTransactionPermanent(ctx, &emptypb.Empty{})
		if err != nil {
			return nil, r.handleGraphQLError(err, "DeleteAllTransactionPermanent")
		}

		so := r.TransactionGraphql.Mapping.ToGraphqlTransactionAll(res)
		return so, nil
	})
}

// FindAllTransaction is the resolver for the findAllTransaction field.
func (r *queryResolver) FindAllTransaction(ctx context.Context, input model.FindAllTransactionInput) (*model.APIResponsePaginationTransaction, error) {
	return ResolverHandle(r.ResolverHandle, "FindAllTransaction", ctx, func(ctx context.Context) (*model.APIResponsePaginationTransaction, error) {
		// Normalize input
		page := int32(1)
		pageSize := int32(10)
		search := ""

		if input.Page != nil && *input.Page > 0 {
			page = int32(*input.Page)
		}
		if input.PageSize != nil && *input.PageSize > 0 {
			pageSize = int32(*input.PageSize)
		}
		if input.Search != nil {
			search = *input.Search
		}

		normalizedInput := model.FindAllTransactionInput{
			Page:     input.Page,
			PageSize: input.PageSize,
			Search:   &search,
		}

		if cacheData, ok := r.TransactionGraphql.Cache.GetCachedTransactionsCache(ctx, &normalizedInput); ok {
			return cacheData, nil
		}

		req := &pb.FindAllTransactionRequest{
			Search:   search,
			Page:     page,
			PageSize: pageSize,
		}

		res, err := r.TransactionGraphql.TransactionClient.TransactionQueryClient.FindAllTransaction(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindAllTransaction")
		}

		so := r.TransactionGraphql.Mapping.ToGraphqlPaginationTransaction(res)
		r.TransactionGraphql.Cache.SetCachedTransactionsCache(ctx, &normalizedInput, so)

		return so, nil
	})
}

// FindByIDTransaction is the resolver for the findByIdTransaction field.
func (r *queryResolver) FindByIDTransaction(ctx context.Context, input model.FindByIDTransactionInput) (*model.APIResponseTransaction, error) {
	return ResolverHandle(r.ResolverHandle, "FindByIDTransaction", ctx, func(ctx context.Context) (*model.APIResponseTransaction, error) {
		id := int32(input.TransactionID)
		if id == 0 {
			return nil, errors.NewBadRequestError("Invalid Transaction ID")
		}

		if cacheData, ok := r.TransactionGraphql.Cache.GetCachedTransactionCache(ctx, int(id)); ok {
			return cacheData, nil
		}

		res, err := r.TransactionGraphql.TransactionClient.TransactionQueryClient.FindByIdTransaction(ctx, &pb.FindByIdTransactionRequest{
			TransactionId: id,
		})
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindByIDTransaction")
		}

		so := r.TransactionGraphql.Mapping.ToGraphqlResponseTransaction(res)
		r.TransactionGraphql.Cache.SetCachedTransactionCache(ctx, so)

		return so, nil
	})
}

// FindTransactionByMerchantID is the resolver for the findTransactionByMerchantId field.
func (r *queryResolver) FindTransactionByMerchantID(ctx context.Context, input model.FindTransactionByMerchantIDInput) (*model.APIResponseTransactions, error) {
	return ResolverHandle(r.ResolverHandle, "FindTransactionByMerchantID", ctx, func(ctx context.Context) (*model.APIResponseTransactions, error) {
		id := int32(input.MerchantID)
		if id == 0 {
			return nil, errors.NewBadRequestError("Invalid Transaction Merchant ID")
		}

		if cacheData, ok := r.TransactionGraphql.Cache.GetCachedTransactionByMerchantIdCache(ctx, int(id)); ok {
			return cacheData, nil
		}

		res, err := r.TransactionGraphql.TransactionClient.TransactionQueryClient.FindTransactionByMerchantId(ctx, &pb.FindTransactionByMerchantIdRequest{
			MerchantId: id,
		})
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindTransactionByMerchantID")
		}

		so := r.TransactionGraphql.Mapping.ToGraphqlResponseTransactions(res)
		r.TransactionGraphql.Cache.SetCachedTransactionByMerchantIdCache(ctx, int(id), so)

		return so, nil
	})
}

// FindByActiveTransaction is the resolver for the findByActiveTransaction field.
func (r *queryResolver) FindByActiveTransaction(ctx context.Context, input model.FindAllTransactionInput) (*model.APIResponsePaginationTransactionDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "FindByActiveTransaction", ctx, func(ctx context.Context) (*model.APIResponsePaginationTransactionDeleteAt, error) {
		// Normalize input
		page := int32(1)
		pageSize := int32(10)
		search := ""

		if input.Page != nil && *input.Page > 0 {
			page = int32(*input.Page)
		}
		if input.PageSize != nil && *input.PageSize > 0 {
			pageSize = int32(*input.PageSize)
		}
		if input.Search != nil {
			search = *input.Search
		}

		normalizedInput := model.FindAllTransactionInput{
			Page:     input.Page,
			PageSize: input.PageSize,
			Search:   &search,
		}

		if cacheData, ok := r.TransactionGraphql.Cache.GetCachedTransactionActiveCache(ctx, &normalizedInput); ok {
			return cacheData, nil
		}

		req := &pb.FindAllTransactionRequest{
			Search:   search,
			Page:     page,
			PageSize: pageSize,
		}

		res, err := r.TransactionGraphql.TransactionClient.TransactionQueryClient.FindByActiveTransaction(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindByActiveTransaction")
		}

		so := r.TransactionGraphql.Mapping.ToGraphqlPaginationTransactionDeleteAt(res)
		r.TransactionGraphql.Cache.SetCachedTransactionActiveCache(ctx, &normalizedInput, so)

		return so, nil
	})
}

// FindByTrashedTransaction is the resolver for the findByTrashedTransaction field.
func (r *queryResolver) FindByTrashedTransaction(ctx context.Context, input model.FindAllTransactionInput) (*model.APIResponsePaginationTransactionDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "FindByTrashedTransaction", ctx, func(ctx context.Context) (*model.APIResponsePaginationTransactionDeleteAt, error) {
		// Normalize input
		page := int32(1)
		pageSize := int32(10)
		search := ""

		if input.Page != nil && *input.Page > 0 {
			page = int32(*input.Page)
		}
		if input.PageSize != nil && *input.PageSize > 0 {
			pageSize = int32(*input.PageSize)
		}
		if input.Search != nil {
			search = *input.Search
		}

		normalizedInput := model.FindAllTransactionInput{
			Page:     input.Page,
			PageSize: input.PageSize,
			Search:   &search,
		}

		if cacheData, ok := r.TransactionGraphql.Cache.GetCachedTransactionTrashedCache(ctx, &normalizedInput); ok {
			return cacheData, nil
		}

		req := &pb.FindAllTransactionRequest{
			Search:   search,
			Page:     page,
			PageSize: pageSize,
		}

		res, err := r.TransactionGraphql.TransactionClient.TransactionQueryClient.FindByTrashedTransaction(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindByTrashedTransaction")
		}

		so := r.TransactionGraphql.Mapping.ToGraphqlPaginationTransactionDeleteAt(res)
		r.TransactionGraphql.Cache.SetCachedTransactionTrashedCache(ctx, &normalizedInput, so)

		return so, nil
	})
}
