package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	pb "github.com/MamangRust/microservice-payment-gateway-grpc/pb/transfer"
	graphqlerror "github.com/MamangRust/microservice-payment-gateway-grpc/service/apigateway/internal/errors"
	"github.com/MamangRust/microservice-payment-gateway-grpc/service/apigateway/internal/model"
	"github.com/MamangRust/microservice-payment-gateway-grpc/shared/domain/requests"
	sharedErrors "github.com/MamangRust/microservice-payment-gateway-grpc/shared/errors"
	"google.golang.org/protobuf/types/known/emptypb"
)

// CreateTransfer is the resolver for the createTransfer field.
func (r *mutationResolver) CreateTransfer(ctx context.Context, input model.CreateTransferInput) (*model.APIResponseTransfer, error) {
	request := &requests.CreateTransferRequest{
		TransferFrom:   input.TransferFrom,
		TransferTo:     input.TransferTo,
		TransferAmount: int(input.TransferAmount),
	}

	if err := request.Validate(); err != nil {
		validations := r.parseValidationErrors(err)
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(sharedErrors.NewValidationError(validations))
	}

	req := &pb.CreateTransferRequest{
		TransferFrom:   input.TransferFrom,
		TransferTo:     input.TransferTo,
		TransferAmount: int64(input.TransferAmount),
	}

	res, err := r.TransferGraphql.TransferClient.TransferCommandClient.CreateTransfer(ctx, req)
	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TransferGraphql.Mapping.ToGraphqlResponseTransfer(res)

	return so, nil
}

// UpdateTransfer is the resolver for the updateTransfer field.
func (r *mutationResolver) UpdateTransfer(ctx context.Context, input model.UpdateTransferInput) (*model.APIResponseTransfer, error) {
	id := int32(input.TransferID)
	if id == 0 {
		return nil, graphqlerror.ErrGraphqlTransferInvalidID
	}

	transferId := int(id)
	request := &requests.UpdateTransferRequest{
		TransferID:     &transferId,
		TransferFrom:   input.TransferFrom,
		TransferTo:     input.TransferTo,
		TransferAmount: int(input.TransferAmount),
	}

	if err := request.Validate(); err != nil {
		validations := r.parseValidationErrors(err)
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(sharedErrors.NewValidationError(validations))
	}

	req := &pb.UpdateTransferRequest{
		TransferId:     id,
		TransferFrom:   input.TransferFrom,
		TransferTo:     input.TransferTo,
		TransferAmount: int64(input.TransferAmount),
	}

	res, err := r.TransferGraphql.TransferClient.TransferCommandClient.UpdateTransfer(ctx, req)
	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TransferGraphql.Mapping.ToGraphqlResponseTransfer(res)
	return so, nil
}

// TrashedTransfer is the resolver for the trashedTransfer field.
func (r *mutationResolver) TrashedTransfer(ctx context.Context, input model.FindByIDTransferInput) (*model.APIResponseTransferDeleteAt, error) {
	id := int32(input.TransferID)
	if id == 0 {
		return nil, graphqlerror.ErrGraphqlTransferInvalidID
	}

	transfer, err := r.TransferGraphql.TransferClient.TransferCommandClient.TrashedTransfer(ctx, &pb.FindByIdTransferRequest{TransferId: id})
	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TransferGraphql.Mapping.ToGraphqlResponseTransferDeleteAt(transfer)
	return so, nil
}

// RestoreTransfer is the resolver for the restoreTransfer field.
func (r *mutationResolver) RestoreTransfer(ctx context.Context, input model.FindByIDTransferInput) (*model.APIResponseTransferDeleteAt, error) {
	id := int32(input.TransferID)
	if id == 0 {
		return nil, graphqlerror.ErrGraphqlTransferInvalidID
	}

	transfer, err := r.TransferGraphql.TransferClient.TransferCommandClient.RestoreTransfer(ctx, &pb.FindByIdTransferRequest{TransferId: id})
	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TransferGraphql.Mapping.ToGraphqlResponseTransferDeleteAt(transfer)
	return so, nil
}

// DeleteTransferPermanent is the resolver for the deleteTransferPermanent field.
func (r *mutationResolver) DeleteTransferPermanent(ctx context.Context, input model.FindByIDTransferInput) (*model.APIResponseTransferDelete, error) {
	id := int32(input.TransferID)
	if id == 0 {
		return nil, graphqlerror.ErrGraphqlTransferInvalidID
	}

	transfer, err := r.TransferGraphql.TransferClient.TransferCommandClient.DeleteTransferPermanent(ctx, &pb.FindByIdTransferRequest{TransferId: id})
	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TransferGraphql.Mapping.ToGraphqlTransferDelete(transfer)
	return so, nil
}

// RestoreAllTransfer is the resolver for the restoreAllTransfer field.
func (r *mutationResolver) RestoreAllTransfer(ctx context.Context) (*model.APIResponseTransferAll, error) {
	res, err := r.TransferGraphql.TransferClient.TransferCommandClient.RestoreAllTransfer(ctx, &emptypb.Empty{})
	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TransferGraphql.Mapping.ToGraphqlTransferAll(res)
	return so, nil
}

// DeleteAllTransferPermanent is the resolver for the deleteAllTransferPermanent field.
func (r *mutationResolver) DeleteAllTransferPermanent(ctx context.Context) (*model.APIResponseTransferAll, error) {
	res, err := r.TransferGraphql.TransferClient.TransferCommandClient.DeleteAllTransferPermanent(ctx, &emptypb.Empty{})
	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TransferGraphql.Mapping.ToGraphqlTransferAll(res)
	return so, nil
}

// FindAllTransfer is the resolver for the findAllTransfer field.
func (r *queryResolver) FindAllTransfer(ctx context.Context, input model.FindAllTransferInput) (*model.APIResponsePaginationTransfer, error) {
	page := int32(1)
	pageSize := int32(10)
	search := ""

	if input.Page != nil {
		page = int32(*input.Page)
	}
	if input.PageSize != nil {
		pageSize = int32(*input.PageSize)
	}
	if input.Search != nil {
		search = *input.Search
	}

	if page <= 0 {
		page = 1
	}
	if pageSize <= 0 {
		pageSize = 10
	}

	reqService := &pb.FindAllTransferRequest{
		Page:     page,
		PageSize: pageSize,
		Search:   search,
	}

	transfers, errResp := r.TransferGraphql.TransferClient.TransferQueryClient.FindAllTransfer(ctx, reqService)
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.TransferGraphql.Mapping.ToGraphqlResponsePaginationTransfer(transfers)
	return so, nil
}

// FindByIDTransfer is the resolver for the findByIdTransfer field.
func (r *queryResolver) FindByIDTransfer(ctx context.Context, input model.FindByIDTransferInput) (*model.APIResponseTransfer, error) {
	id := int32(input.TransferID)
	if id == 0 {
		return nil, graphqlerror.ErrGraphqlTransferInvalidID
	}

	transfer, err := r.TransferGraphql.TransferClient.TransferQueryClient.FindByIdTransfer(ctx, &pb.FindByIdTransferRequest{TransferId: id})
	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TransferGraphql.Mapping.ToGraphqlResponseTransfer(transfer)
	return so, nil
}

// FindTransferByTransferFrom is the resolver for the findTransferByTransferFrom field.
func (r *queryResolver) FindTransferByTransferFrom(ctx context.Context, input model.FindTransferByTransferFromInput) (*model.APIResponseTransfers, error) {
	transferFrom := input.TransferFrom

	if transferFrom == "" {
		return nil, graphqlerror.ErrGraphqlInvalidCardNumber
	}

	res, err := r.TransferGraphql.TransferClient.TransferQueryClient.FindTransferByTransferFrom(ctx, &pb.FindTransferByTransferFromRequest{
		TransferFrom: transferFrom,
	})

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TransferGraphql.Mapping.ToGraphqlResponseTransfers(res)

	return so, nil
}

// FindTransferByTransferTo is the resolver for the findTransferByTransferTo field.
func (r *queryResolver) FindTransferByTransferTo(ctx context.Context, input model.FindTransferByTransferToInput) (*model.APIResponseTransfers, error) {
	transferTo := input.TransferTo

	if transferTo == "" {
		return nil, graphqlerror.ErrGraphqlInvalidCardNumber
	}

	res, err := r.TransferGraphql.TransferClient.TransferQueryClient.FindTransferByTransferTo(ctx, &pb.FindTransferByTransferToRequest{
		TransferTo: transferTo,
	})

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TransferGraphql.Mapping.ToGraphqlResponseTransfers(res)

	return so, nil
}

// FindByActiveTransfer is the resolver for the findByActiveTransfer field.
func (r *queryResolver) FindByActiveTransfer(ctx context.Context, input model.FindAllTransferInput) (*model.APIResponsePaginationTransferDeleteAt, error) {
	page := int32(1)
	pageSize := int32(10)
	search := ""

	if input.Page != nil {
		page = int32(*input.Page)
	}
	if input.PageSize != nil {
		pageSize = int32(*input.PageSize)
	}
	if input.Search != nil {
		search = *input.Search
	}

	if page <= 0 {
		page = 1
	}
	if pageSize <= 0 {
		pageSize = 10
	}

	req := &pb.FindAllTransferRequest{
		Page:     page,
		PageSize: pageSize,
		Search:   search,
	}

	transfers, errResp := r.TransferGraphql.TransferClient.TransferQueryClient.FindByActiveTransfer(ctx, req)
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.TransferGraphql.Mapping.ToGraphqlResponsePaginationTransferDeleteAt(transfers)

	return so, nil
}

// FindByTrashedTransfer is the resolver for the findByTrashedTransfer field.
func (r *queryResolver) FindByTrashedTransfer(ctx context.Context, input model.FindAllTransferInput) (*model.APIResponsePaginationTransferDeleteAt, error) {
	page := int32(1)
	pageSize := int32(10)
	search := ""

	if input.Page != nil {
		page = int32(*input.Page)
	}
	if input.PageSize != nil {
		pageSize = int32(*input.PageSize)
	}
	if input.Search != nil {
		search = *input.Search
	}

	if page <= 0 {
		page = 1
	}
	if pageSize <= 0 {
		pageSize = 10
	}

	req := &pb.FindAllTransferRequest{
		Page:     page,
		PageSize: pageSize,
		Search:   search,
	}

	transfers, errResp := r.TransferGraphql.TransferClient.TransferQueryClient.FindByTrashedTransfer(ctx, req)
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.TransferGraphql.Mapping.ToGraphqlResponsePaginationTransferDeleteAt(transfers)

	return so, nil
}
