package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"
	"time"

	pb "github.com/MamangRust/microservice-payment-gateway-grpc/pb/withdraw"
	graphqlerror "github.com/MamangRust/microservice-payment-gateway-grpc/service/apigateway/internal/errors"
	"github.com/MamangRust/microservice-payment-gateway-grpc/service/apigateway/internal/model"
	"github.com/MamangRust/microservice-payment-gateway-grpc/shared/domain/requests"
	sharedErrors "github.com/MamangRust/microservice-payment-gateway-grpc/shared/errors"
	"google.golang.org/protobuf/types/known/emptypb"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// CreateWithdraw is the resolver for the createWithdraw field.
func (r *mutationResolver) CreateWithdraw(ctx context.Context, input model.CreateWithdrawInput) (*model.APIResponseWithdraw, error) {
	withdrawTime, err := time.Parse("2006-01-02", input.WithdrawTime)
	if err != nil {
		return nil, fmt.Errorf("invalid date format for withdrawTime: %v (expected YYYY-MM-DD)", err)
	}

	request := &requests.CreateWithdrawRequest{
		CardNumber:     input.CardNumber,
		WithdrawAmount: int(input.WithdrawAmount),
		WithdrawTime:   withdrawTime,
	}

	if err := request.Validate(); err != nil {
		validations := r.parseValidationErrors(err)
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(sharedErrors.NewValidationError(validations))
	}

	req := &pb.CreateWithdrawRequest{
		CardNumber:     input.CardNumber,
		WithdrawAmount: int64(input.WithdrawAmount),
		WithdrawTime:   timestamppb.New(withdrawTime),
	}

	res, errResp := r.WithdrawGraphql.WithdrawClient.WithdrawCommandClient.CreateWithdraw(ctx, req)
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.WithdrawGraphql.Mapping.ToGraphqlResponseWithdraw(res)
	return so, nil
}

// UpdateWithdraw is the resolver for the updateWithdraw field.
func (r *mutationResolver) UpdateWithdraw(ctx context.Context, input model.UpdateWithdrawInput) (*model.APIResponseWithdraw, error) {
	id := int32(input.WithdrawID)
	if id == 0 {
		return nil, graphqlerror.ErrGraphqlWithdrawInvalidID
	}

	withdrawTime, err := time.Parse("2006-01-02", input.WithdrawTime)
	if err != nil {
		return nil, fmt.Errorf("invalid date format for withdrawTime: %v (expected YYYY-MM-DD)", err)
	}

	withdrawId := int(id)
	request := &requests.UpdateWithdrawRequest{
		WithdrawID:     &withdrawId,
		CardNumber:     input.CardNumber,
		WithdrawAmount: int(input.WithdrawAmount),
		WithdrawTime:   withdrawTime,
	}

	if err := request.Validate(); err != nil {
		validations := r.parseValidationErrors(err)
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(sharedErrors.NewValidationError(validations))
	}

	req := &pb.UpdateWithdrawRequest{
		WithdrawId:     id,
		CardNumber:     input.CardNumber,
		WithdrawAmount: int64(input.WithdrawAmount),
		WithdrawTime:   timestamppb.New(withdrawTime),
	}

	res, errResp := r.WithdrawGraphql.WithdrawClient.WithdrawCommandClient.UpdateWithdraw(ctx, req)
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.WithdrawGraphql.Mapping.ToGraphqlResponseWithdraw(res)
	return so, nil
}

// TrashedWithdraw is the resolver for the trashedWithdraw field.
func (r *mutationResolver) TrashedWithdraw(ctx context.Context, input model.FindByIDWithdrawInput) (*model.APIResponseWithdrawDeleteAt, error) {
	id := int32(input.WithdrawID)
	if id == 0 {
		return nil, graphqlerror.ErrGraphqlWithdrawInvalidID
	}

	withdraw, err := r.WithdrawGraphql.WithdrawClient.WithdrawCommandClient.TrashedWithdraw(ctx, &pb.FindByIdWithdrawRequest{
		WithdrawId: id,
	})
	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.WithdrawGraphql.Mapping.ToGraphqlResponseWithdrawDeleteAt(withdraw)

	return so, nil
}

// RestoreWithdraw is the resolver for the restoreWithdraw field.
func (r *mutationResolver) RestoreWithdraw(ctx context.Context, input model.FindByIDWithdrawInput) (*model.APIResponseWithdrawDeleteAt, error) {
	id := int32(input.WithdrawID)
	if id == 0 {
		return nil, graphqlerror.ErrGraphqlWithdrawInvalidID
	}

	withdraw, err := r.WithdrawGraphql.WithdrawClient.WithdrawCommandClient.RestoreWithdraw(ctx, &pb.FindByIdWithdrawRequest{
		WithdrawId: id,
	})
	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.WithdrawGraphql.Mapping.ToGraphqlResponseWithdrawDeleteAt(withdraw)
	return so, nil
}

// DeleteWithdrawPermanent is the resolver for the deleteWithdrawPermanent field.
func (r *mutationResolver) DeleteWithdrawPermanent(ctx context.Context, input model.FindByIDWithdrawInput) (*model.APIResponseWithdrawDelete, error) {
	id := int32(input.WithdrawID)
	if id == 0 {
		return nil, graphqlerror.ErrGraphqlWithdrawInvalidID
	}

	res, err := r.WithdrawGraphql.WithdrawClient.WithdrawCommandClient.DeleteWithdrawPermanent(ctx, &pb.FindByIdWithdrawRequest{WithdrawId: id})
	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.WithdrawGraphql.Mapping.ToGraphqlWithdrawDelete(res)

	return so, nil
}

// RestoreAllWithdraw is the resolver for the restoreAllWithdraw field.
func (r *mutationResolver) RestoreAllWithdraw(ctx context.Context) (*model.APIResponseWithdrawAll, error) {
	res, err := r.WithdrawGraphql.WithdrawClient.WithdrawCommandClient.RestoreAllWithdraw(ctx, &emptypb.Empty{})
	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.WithdrawGraphql.Mapping.ToGraphqlWithdrawAll(res)
	return so, nil
}

// DeleteAllWithdrawPermanent is the resolver for the deleteAllWithdrawPermanent field.
func (r *mutationResolver) DeleteAllWithdrawPermanent(ctx context.Context) (*model.APIResponseWithdrawAll, error) {
	res, err := r.WithdrawGraphql.WithdrawClient.WithdrawCommandClient.DeleteAllWithdrawPermanent(ctx, &emptypb.Empty{})
	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.WithdrawGraphql.Mapping.ToGraphqlWithdrawAll(res)
	return so, nil
}

// FindAllWithdraw is the resolver for the findAllWithdraw field.
func (r *queryResolver) FindAllWithdraw(ctx context.Context, input model.FindAllWithdrawInput) (*model.APIResponsePaginationWithdraw, error) {
	page := int32(1)
	pageSize := int32(10)
	search := ""

	if input.Page != nil {
		page = int32(*input.Page)
	}
	if input.PageSize != nil {
		pageSize = int32(*input.PageSize)
	}
	if input.Search != nil {
		search = *input.Search
	}

	if page <= 0 {
		page = 1
	}
	if pageSize <= 0 {
		pageSize = 10
	}

	reqService := &pb.FindAllWithdrawRequest{
		Page:     page,
		PageSize: pageSize,
		Search:   search,
	}

	withdraws, errResp := r.WithdrawGraphql.WithdrawClient.WithdrawQueryClient.FindAllWithdraw(ctx, reqService)
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.WithdrawGraphql.Mapping.ToGraphqlResponsePaginationWithdraw(withdraws)

	return so, nil
}

// FindByIDWithdraw is the resolver for the findByIdWithdraw field.
func (r *queryResolver) FindByIDWithdraw(ctx context.Context, input model.FindByIDWithdrawInput) (*model.APIResponseWithdraw, error) {
	id := int32(input.WithdrawID)
	if id == 0 {
		return nil, graphqlerror.ErrGraphqlWithdrawInvalidID
	}

	withdraw, errResp := r.WithdrawGraphql.WithdrawClient.WithdrawQueryClient.FindByIdWithdraw(ctx, &pb.FindByIdWithdrawRequest{WithdrawId: id})
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.WithdrawGraphql.Mapping.ToGraphqlResponseWithdraw(withdraw)

	return so, nil
}

// FindByActiveWithdraw is the resolver for the findByActiveWithdraw field.
func (r *queryResolver) FindByActiveWithdraw(ctx context.Context, input model.FindAllWithdrawInput) (*model.APIResponsePaginationWithdrawDeleteAt, error) {
	page := int32(1)
	pageSize := int32(10)
	search := ""

	if input.Page != nil {
		page = int32(*input.Page)
	}
	if input.PageSize != nil {
		pageSize = int32(*input.PageSize)
	}
	if input.Search != nil {
		search = *input.Search
	}

	if page <= 0 {
		page = 1
	}
	if pageSize <= 0 {
		pageSize = 10
	}

	reqService := &pb.FindAllWithdrawRequest{
		Page:     page,
		PageSize: pageSize,
		Search:   search,
	}

	withdraws, errResp := r.WithdrawGraphql.WithdrawClient.WithdrawQueryClient.FindByActive(ctx, reqService)
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.WithdrawGraphql.Mapping.ToGraphqlResponsePaginationWithdrawDeleteAt(withdraws)

	return so, nil
}

// FindByTrashedWithdraw is the resolver for the findByTrashedWithdraw field.
func (r *queryResolver) FindByTrashedWithdraw(ctx context.Context, input model.FindAllWithdrawInput) (*model.APIResponsePaginationWithdrawDeleteAt, error) {
	page := int32(1)
	pageSize := int32(10)
	search := ""

	if input.Page != nil {
		page = int32(*input.Page)
	}
	if input.PageSize != nil {
		pageSize = int32(*input.PageSize)
	}
	if input.Search != nil {
		search = *input.Search
	}

	if page <= 0 {
		page = 1
	}
	if pageSize <= 0 {
		pageSize = 10
	}

	reqService := &pb.FindAllWithdrawRequest{
		Page:     page,
		PageSize: pageSize,
		Search:   search,
	}

	withdraws, errResp := r.WithdrawGraphql.WithdrawClient.WithdrawQueryClient.FindByTrashed(ctx, reqService)
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.WithdrawGraphql.Mapping.ToGraphqlResponsePaginationWithdrawDeleteAt(withdraws)

	return so, nil
}
