// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: user/user_query.proto

package user

import (
	common "github.com/MamangRust/microservice-payment-gateway-grpc/pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApiResponsePaginationUserDeleteAt struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	Status         string                  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message        string                  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data           []*UserResponseDeleteAt `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	PaginationMeta *common.PaginationMeta  `protobuf:"bytes,4,opt,name=paginationMeta,proto3" json:"paginationMeta,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApiResponsePaginationUserDeleteAt) Reset() {
	*x = ApiResponsePaginationUserDeleteAt{}
	mi := &file_user_user_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationUserDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationUserDeleteAt) ProtoMessage() {}

func (x *ApiResponsePaginationUserDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationUserDeleteAt.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationUserDeleteAt) Descriptor() ([]byte, []int) {
	return file_user_user_query_proto_rawDescGZIP(), []int{0}
}

func (x *ApiResponsePaginationUserDeleteAt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationUserDeleteAt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationUserDeleteAt) GetData() []*UserResponseDeleteAt {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationUserDeleteAt) GetPaginationMeta() *common.PaginationMeta {
	if x != nil {
		return x.PaginationMeta
	}
	return nil
}

type ApiResponsePaginationUser struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data           []*UserResponse        `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	PaginationMeta *common.PaginationMeta `protobuf:"bytes,4,opt,name=paginationMeta,proto3" json:"paginationMeta,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApiResponsePaginationUser) Reset() {
	*x = ApiResponsePaginationUser{}
	mi := &file_user_user_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationUser) ProtoMessage() {}

func (x *ApiResponsePaginationUser) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationUser.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationUser) Descriptor() ([]byte, []int) {
	return file_user_user_query_proto_rawDescGZIP(), []int{1}
}

func (x *ApiResponsePaginationUser) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationUser) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationUser) GetData() []*UserResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationUser) GetPaginationMeta() *common.PaginationMeta {
	if x != nil {
		return x.PaginationMeta
	}
	return nil
}

type FindByEmailUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByEmailUserRequest) Reset() {
	*x = FindByEmailUserRequest{}
	mi := &file_user_user_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByEmailUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByEmailUserRequest) ProtoMessage() {}

func (x *FindByEmailUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByEmailUserRequest.ProtoReflect.Descriptor instead.
func (*FindByEmailUserRequest) Descriptor() ([]byte, []int) {
	return file_user_user_query_proto_rawDescGZIP(), []int{2}
}

func (x *FindByEmailUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type FindByVerificationCodeUserRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	VerificationCode string                 `protobuf:"bytes,1,opt,name=verification_code,json=verificationCode,proto3" json:"verification_code,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FindByVerificationCodeUserRequest) Reset() {
	*x = FindByVerificationCodeUserRequest{}
	mi := &file_user_user_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByVerificationCodeUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByVerificationCodeUserRequest) ProtoMessage() {}

func (x *FindByVerificationCodeUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByVerificationCodeUserRequest.ProtoReflect.Descriptor instead.
func (*FindByVerificationCodeUserRequest) Descriptor() ([]byte, []int) {
	return file_user_user_query_proto_rawDescGZIP(), []int{3}
}

func (x *FindByVerificationCodeUserRequest) GetVerificationCode() string {
	if x != nil {
		return x.VerificationCode
	}
	return ""
}

var File_user_user_query_proto protoreflect.FileDescriptor

const file_user_user_query_proto_rawDesc = "" +
	"\n" +
	"\x15user/user_query.proto\x12\apb.user\x1a\x0fuser/user.proto\x1a\x10common/api.proto\"\xcb\x01\n" +
	"!ApiResponsePaginationUserDeleteAt\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x121\n" +
	"\x04data\x18\x03 \x03(\v2\x1d.pb.user.UserResponseDeleteAtR\x04data\x12A\n" +
	"\x0epaginationMeta\x18\x04 \x01(\v2\x19.pb.common.PaginationMetaR\x0epaginationMeta\"\xbb\x01\n" +
	"\x19ApiResponsePaginationUser\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x04data\x18\x03 \x03(\v2\x15.pb.user.UserResponseR\x04data\x12A\n" +
	"\x0epaginationMeta\x18\x04 \x01(\v2\x19.pb.common.PaginationMetaR\x0epaginationMeta\".\n" +
	"\x16FindByEmailUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"P\n" +
	"!FindByVerificationCodeUserRequest\x12+\n" +
	"\x11verification_code\x18\x01 \x01(\tR\x10verificationCode2\x83\x04\n" +
	"\x10UserQueryService\x12J\n" +
	"\aFindAll\x12\x1b.pb.user.FindAllUserRequest\x1a\".pb.user.ApiResponsePaginationUser\x12B\n" +
	"\bFindById\x12\x1c.pb.user.FindByIdUserRequest\x1a\x18.pb.user.ApiResponseUser\x12H\n" +
	"\vFindByEmail\x12\x1f.pb.user.FindByEmailUserRequest\x1a\x18.pb.user.ApiResponseUser\x12^\n" +
	"\x16FindByVerificationCode\x12*.pb.user.FindByVerificationCodeUserRequest\x1a\x18.pb.user.ApiResponseUser\x12Y\n" +
	"\fFindByActive\x12\x1b.pb.user.FindAllUserRequest\x1a*.pb.user.ApiResponsePaginationUserDeleteAt\"\x00\x12Z\n" +
	"\rFindByTrashed\x12\x1b.pb.user.FindAllUserRequest\x1a*.pb.user.ApiResponsePaginationUserDeleteAt\"\x00BAZ?github.com/MamangRust/microservice-payment-gateway-grpc/pb/userb\x06proto3"

var (
	file_user_user_query_proto_rawDescOnce sync.Once
	file_user_user_query_proto_rawDescData []byte
)

func file_user_user_query_proto_rawDescGZIP() []byte {
	file_user_user_query_proto_rawDescOnce.Do(func() {
		file_user_user_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_user_query_proto_rawDesc), len(file_user_user_query_proto_rawDesc)))
	})
	return file_user_user_query_proto_rawDescData
}

var file_user_user_query_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_user_user_query_proto_goTypes = []any{
	(*ApiResponsePaginationUserDeleteAt)(nil), // 0: pb.user.ApiResponsePaginationUserDeleteAt
	(*ApiResponsePaginationUser)(nil),         // 1: pb.user.ApiResponsePaginationUser
	(*FindByEmailUserRequest)(nil),            // 2: pb.user.FindByEmailUserRequest
	(*FindByVerificationCodeUserRequest)(nil), // 3: pb.user.FindByVerificationCodeUserRequest
	(*UserResponseDeleteAt)(nil),              // 4: pb.user.UserResponseDeleteAt
	(*common.PaginationMeta)(nil),             // 5: pb.common.PaginationMeta
	(*UserResponse)(nil),                      // 6: pb.user.UserResponse
	(*FindAllUserRequest)(nil),                // 7: pb.user.FindAllUserRequest
	(*FindByIdUserRequest)(nil),               // 8: pb.user.FindByIdUserRequest
	(*ApiResponseUser)(nil),                   // 9: pb.user.ApiResponseUser
}
var file_user_user_query_proto_depIdxs = []int32{
	4,  // 0: pb.user.ApiResponsePaginationUserDeleteAt.data:type_name -> pb.user.UserResponseDeleteAt
	5,  // 1: pb.user.ApiResponsePaginationUserDeleteAt.paginationMeta:type_name -> pb.common.PaginationMeta
	6,  // 2: pb.user.ApiResponsePaginationUser.data:type_name -> pb.user.UserResponse
	5,  // 3: pb.user.ApiResponsePaginationUser.paginationMeta:type_name -> pb.common.PaginationMeta
	7,  // 4: pb.user.UserQueryService.FindAll:input_type -> pb.user.FindAllUserRequest
	8,  // 5: pb.user.UserQueryService.FindById:input_type -> pb.user.FindByIdUserRequest
	2,  // 6: pb.user.UserQueryService.FindByEmail:input_type -> pb.user.FindByEmailUserRequest
	3,  // 7: pb.user.UserQueryService.FindByVerificationCode:input_type -> pb.user.FindByVerificationCodeUserRequest
	7,  // 8: pb.user.UserQueryService.FindByActive:input_type -> pb.user.FindAllUserRequest
	7,  // 9: pb.user.UserQueryService.FindByTrashed:input_type -> pb.user.FindAllUserRequest
	1,  // 10: pb.user.UserQueryService.FindAll:output_type -> pb.user.ApiResponsePaginationUser
	9,  // 11: pb.user.UserQueryService.FindById:output_type -> pb.user.ApiResponseUser
	9,  // 12: pb.user.UserQueryService.FindByEmail:output_type -> pb.user.ApiResponseUser
	9,  // 13: pb.user.UserQueryService.FindByVerificationCode:output_type -> pb.user.ApiResponseUser
	0,  // 14: pb.user.UserQueryService.FindByActive:output_type -> pb.user.ApiResponsePaginationUserDeleteAt
	0,  // 15: pb.user.UserQueryService.FindByTrashed:output_type -> pb.user.ApiResponsePaginationUserDeleteAt
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_user_user_query_proto_init() }
func file_user_user_query_proto_init() {
	if File_user_user_query_proto != nil {
		return
	}
	file_user_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_user_query_proto_rawDesc), len(file_user_user_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_user_query_proto_goTypes,
		DependencyIndexes: file_user_user_query_proto_depIdxs,
		MessageInfos:      file_user_user_query_proto_msgTypes,
	}.Build()
	File_user_user_query_proto = out.File
	file_user_user_query_proto_goTypes = nil
	file_user_user_query_proto_depIdxs = nil
}
