// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type IdempotencyRecord struct {
	ID              int64       `json:"id"`
	Scope           string      `json:"scope"`
	IdempotencyKey  string      `json:"idempotency_key"`
	RequestHash     string      `json:"request_hash"`
	OperationID     pgtype.UUID `json:"operation_id"`
	Status          string      `json:"status"`
	ResponsePayload []byte      `json:"response_payload"`
	ResourceID      *int32      `json:"resource_id"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
	ExpiresAt       time.Time   `json:"expires_at"`
}

type OutboxEvent struct {
	ID            int64              `json:"id"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   string             `json:"aggregate_id"`
	EventID       string             `json:"event_id"`
	EventType     string             `json:"event_type"`
	EventVersion  int32              `json:"event_version"`
	Payload       []byte             `json:"payload"`
	Status        string             `json:"status"`
	Attempts      int32              `json:"attempts"`
	LastError     *string            `json:"last_error"`
	AvailableAt   pgtype.Timestamptz `json:"available_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
}

type Role struct {
	RoleID    int32            `json:"role_id"`
	RoleName  string           `json:"role_name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	DeletedAt pgtype.Timestamp `json:"deleted_at"`
}

type UserRole struct {
	UserRoleID int32            `json:"user_role_id"`
	UserID     int32            `json:"user_id"`
	RoleID     int32            `json:"role_id"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
	DeletedAt  pgtype.Timestamp `json:"deleted_at"`
}

type Withdraw struct {
	WithdrawID     int32            `json:"withdraw_id"`
	WithdrawNo     pgtype.UUID      `json:"withdraw_no"`
	CardNumber     string           `json:"card_number"`
	WithdrawAmount int64            `json:"withdraw_amount"`
	WithdrawTime   time.Time        `json:"withdraw_time"`
	Status         string           `json:"status"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	DeletedAt      pgtype.Timestamp `json:"deleted_at"`
}
