// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"time"
)

type Querier interface {
	// CreateRole: Inserts a new role into the system
	// Purpose: Add new role definitions (e.g., Admin, Cashier, etc.)
	// Parameters:
	//   $1: Role name
	// Returns:
	//   Newly created role's full data (including timestamps)
	CreateRole(ctx context.Context, roleName string) (*Role, error)
	// CreateWithdraw: Records a new cash withdrawal
	// Purpose: Create a withdrawal transaction in the system
	// Parameters:
	//   $1: card_number - The card used for withdrawal
	//   $2: withdraw_amount - The amount withdrawn
	//   $3: withdraw_time - When the withdrawal occurred
	//   $4: created_at - Timestamp of record creation
	// Returns:
	//   The newly created withdrawal record with all fields
	// Business Logic:
	//   - Sets creation and update timestamps automatically
	//   - Used for recording ATM/branch cash withdrawals
	//   - Typically triggered after successful cash dispense
	CreateWithdraw(ctx context.Context, arg CreateWithdrawParams) (*CreateWithdrawRow, error)
	// DeleteAllPermanentRoles: Permanently deletes all soft-deleted roles
	// Purpose: Bulk cleanup of trashed roles
	// Parameters: None
	DeleteAllPermanentRoles(ctx context.Context) error
	// DeleteAllPermanentWithdraws: Permanently removes all trashed withdrawals
	// Purpose: Clean up all soft-deleted withdrawal records
	// Business Logic:
	//   - Irreversible bulk deletion
	//   - Only affects records marked as deleted
	//   - Frees database space from old records
	//   - Typically used during maintenance periods
	//   - Requires admin privileges
	DeleteAllPermanentWithdraws(ctx context.Context) error
	// DeletePermanentRole: Permanently deletes a trashed role
	// Purpose: Remove role from DB after soft delete
	// Parameters:
	//   $1: Role ID
	DeletePermanentRole(ctx context.Context, roleID int32) error
	// DeleteWithdrawPermanently: Hard-deletes a withdrawal
	// Purpose: Permanently remove a withdrawal from the system
	// Parameters:
	//   $1: withdraw_id - ID of withdrawal to delete
	// Business Logic:
	//   - Physical deletion from database
	//   - Only works on already trashed withdrawals
	//   - Irreversible operation
	//   - Used after retention period expires
	DeleteWithdrawPermanently(ctx context.Context, withdrawID int32) error
	// FindAllWithdrawsByCardNumber: Retrieves all withdrawals for a specific card
	// Purpose: Get complete withdrawal history for a card
	// Parameters:
	//   $1: card_number - The card number to filter withdrawals
	// Returns:
	//   Selected withdrawal fields for all matching records
	// Business Logic:
	//   - Only includes active withdrawals (deleted_at IS NULL)
	//   - Returns all withdrawals without pagination
	//   - Orders by withdraw_time (newest first)
	//   - Useful for complete withdrawal history exports
	FindAllWithdrawsByCardNumber(ctx context.Context, cardNumber string) ([]*FindAllWithdrawsByCardNumberRow, error)
	// GetActiveRoles: Retrieves only active (non-deleted) roles with optional search and pagination
	// Purpose: Display roles that are currently usable in the system
	// Parameters:
	//   $1: Search query (nullable)
	//   $2: Limit
	//   $3: Offset
	// Returns:
	//   role_id, role_name, timestamps, and total_count
	GetActiveRoles(ctx context.Context, arg GetActiveRolesParams) ([]*GetActiveRolesRow, error)
	// GetActiveWithdraws: Retrieves paginated active withdrawals with search
	// Purpose: List all non-deleted withdrawals with filtering options
	// Parameters:
	//   $1: search_term - Optional text to filter withdrawals
	//   $2: limit - Maximum records to return per page
	//   $3: offset - Records to skip for pagination
	// Returns:
	//   All withdrawal fields plus total_count of matching active records
	// Business Logic:
	//   - Only includes active withdrawals (deleted_at IS NULL)
	//   - Same comprehensive filtering as GetWithdraws
	//   - Orders by withdraw_time (newest first)
	//   - Provides pagination metadata
	//   - Used in withdrawal management interfaces
	GetActiveWithdraws(ctx context.Context, arg GetActiveWithdrawsParams) ([]*GetActiveWithdrawsRow, error)
	// GetMonthWithdrawStatusFailed: Retrieves monthly failed metrics for withdrawals
	// Purpose: Analyze failed withdrawal trends across comparison periods
	// Parameters:
	//   $1: period1_start - Start date of first comparison period (timestamp)
	//   $2: period1_end - End date of first comparison period (timestamp)
	//   $3: period2_start - Start date of second comparison period (timestamp)
	//   $4: period2_end - End date of second comparison period (timestamp)
	// Returns:
	//   year: Year as text (e.g., '2023')
	//   month: 3-letter month abbreviation (e.g., 'Jan')
	//   total_failed: Count of failed withdrawals
	//   total_amount: Sum of failed withdrawal amounts
	// Business Logic:
	//   - Only includes failed withdrawals (status = 'failed')
	//   - Covers two customizable time periods for comparison
	//   - Zero-fills months with no withdrawal activity
	//   - Formats output for consistent visualization (year as text, month as 'Mon')
	//   - Orders by year and month (newest first)
	//   - Useful for identifying seasonal cash withdrawal patterns
	GetMonthWithdrawStatusFailed(ctx context.Context, arg GetMonthWithdrawStatusFailedParams) ([]*GetMonthWithdrawStatusFailedRow, error)
	// GetMonthWithdrawStatusFailedCardNumber: Retrieves monthly failed metrics for withdrawals
	// Purpose: Analyze failed withdrawal trends across comparison periods
	// Parameters:
	//   $1: card_number  - filter by card_number
	//   $2: period1_start - Start date of first comparison period (timestamp)
	//   $3: period1_end - End date of first comparison period (timestamp)
	//   $4: period2_start - Start date of second comparison period (timestamp)
	//   $5: period2_end - End date of second comparison period (timestamp)
	// Returns:
	//   year: Year as text (e.g., '2023')
	//   month: 3-letter month abbreviation (e.g., 'Jan')
	//   total_failed: Count of failed withdrawals
	//   total_amount: Sum of failed withdrawal amounts
	// Business Logic:
	//   - Only includes failed withdrawals (status = 'failed')
	//   - Covers two customizable time periods for comparison
	//   - Zero-fills months with no withdrawal activity
	//   - Formats output for consistent visualization (year as text, month as 'Mon')
	//   - Orders by year and month (newest first)
	//   - Useful for identifying seasonal cash withdrawal patterns
	GetMonthWithdrawStatusFailedCardNumber(ctx context.Context, arg GetMonthWithdrawStatusFailedCardNumberParams) ([]*GetMonthWithdrawStatusFailedCardNumberRow, error)
	// GetMonthWithdrawStatusSuccess: Retrieves monthly success metrics for withdrawals
	// Purpose: Analyze successful withdrawal trends across comparison periods
	// Parameters:
	//   $1: period1_start - Start date of first comparison period (timestamp)
	//   $2: period1_end - End date of first comparison period (timestamp)
	//   $3: period2_start - Start date of second comparison period (timestamp)
	//   $4: period2_end - End date of second comparison period (timestamp)
	// Returns:
	//   year: Year as text (e.g., '2023')
	//   month: 3-letter month abbreviation (e.g., 'Jan')
	//   total_success: Count of successful withdrawals
	//   total_amount: Sum of successful withdrawal amounts
	// Business Logic:
	//   - Only includes successful withdrawals (status = 'success')
	//   - Covers two customizable time periods for comparison
	//   - Zero-fills months with no withdrawal activity
	//   - Formats output for consistent visualization (year as text, month as 'Mon')
	//   - Orders by year and month (newest first)
	//   - Useful for identifying seasonal cash withdrawal patterns
	GetMonthWithdrawStatusSuccess(ctx context.Context, arg GetMonthWithdrawStatusSuccessParams) ([]*GetMonthWithdrawStatusSuccessRow, error)
	GetMonthWithdrawStatusSuccessCardNumber(ctx context.Context, arg GetMonthWithdrawStatusSuccessCardNumberParams) ([]*GetMonthWithdrawStatusSuccessCardNumberRow, error)
	// GetMonthlyWithdraws: Retrieves monthly withdrawal totals for a given year
	// Purpose: Analyze monthly cash withdrawal patterns and trends
	// Parameters:
	//   $1: reference_date - Any date within the target year (used to define the year range)
	// Returns:
	//   month: 3-letter month abbreviation (e.g., 'Jan')
	//   total_withdraw_amount: Sum of withdrawal amounts for that month (0 if no withdrawals)
	// Business Logic:
	//   - Generates complete monthly series for the specified year
	//   - Includes all withdrawals regardless of card or status
	//   - Filters out soft-deleted records (deleted_at IS NULL)
	//   - Zero-fills months with no withdrawal activity
	//   - Orders results chronologically by month
	//   - Useful for cash flow analysis and ATM/branch planning
	GetMonthlyWithdraws(ctx context.Context, dollar_1 time.Time) ([]*GetMonthlyWithdrawsRow, error)
	// GetMonthlyWithdrawsByCardNumber: Retrieves monthly withdrawals for a specific card
	// Purpose: Track monthly cash usage patterns for individual cardholders
	// Parameters:
	//   $1: card_number - The card number to filter withdrawals
	//   $2: reference_date - Any date within the target year
	// Returns:
	//   month: 3-letter month abbreviation
	//   total_withdraw_amount: Sum of withdrawals for that card by month
	// Business Logic:
	//   - Generates complete monthly series for the year
	//   - Filters withdrawals by specific card number
	//   - Zero-fills months with no activity for that card
	//   - Orders chronologically
	//   - Useful for individual spending pattern analysis
	GetMonthlyWithdrawsByCardNumber(ctx context.Context, arg GetMonthlyWithdrawsByCardNumberParams) ([]*GetMonthlyWithdrawsByCardNumberRow, error)
	// GetRole: Retrieves role details by role_id
	// Purpose: Fetch a single role record (regardless of deleted status)
	// Parameters:
	//   $1: Role ID
	// Returns:
	//   role_id, role_name, and timestamps
	GetRole(ctx context.Context, roleID int32) (*Role, error)
	// GetRoleByName: Retrieves role by exact role name
	// Purpose: Check role existence or fetch role info based on name
	// Parameters:
	//   $1: Role name (exact match)
	// Returns:
	//   role_id, role_name, and timestamps
	GetRoleByName(ctx context.Context, roleName string) (*Role, error)
	// GetRoles: Retrieves all roles (active & trashed) with optional name search and pagination
	// Purpose: General listing of roles regardless of status
	// Parameters:
	//   $1: Search query (role name, nullable)
	//   $2: Limit (number of records per page)
	//   $3: Offset (starting index for pagination)
	// Returns:
	//   role_id, role_name, timestamps, and total_count (for pagination support)
	// Business Logic:
	//   - Supports fuzzy search on role_name
	//   - Includes both active and trashed roles
	//   - Useful for admin panels with filters and pagination
	GetRoles(ctx context.Context, arg GetRolesParams) ([]*GetRolesRow, error)
	// GetTodayWithdrawSumByCardNumber: Retrieves the sum of today's successful withdrawals for a card
	// Purpose: Enforce the daily withdrawal limit (WITHDRAW_DAILY_LIMIT)
	// Parameters:
	//   $1: card_number - The card number to sum withdrawals for
	// Returns:
	//   total_withdraw_amount: Sum of today's successful withdrawal amounts (0 if none)
	// Business Logic:
	//   - Only counts today's withdrawals (withdraw_time >= start of current day)
	//   - Only counts successful withdrawals (status = 'success')
	//   - Excludes soft-deleted withdrawals (deleted_at IS NULL)
	//   - Used by the withdraw command service before insert to reject over-limit withdrawals
	GetTodayWithdrawSumByCardNumber(ctx context.Context, cardNumber string) (int64, error)
	// GetTrashedRoles: Retrieves only soft-deleted roles with optional search and pagination
	// Purpose: For trash/recycle bin management
	// Parameters:
	//   $1: Search query (nullable)
	//   $2: Limit
	//   $3: Offset
	// Returns:
	//   role_id, role_name, timestamps, and total_count
	GetTrashedRoles(ctx context.Context, arg GetTrashedRolesParams) ([]*GetTrashedRolesRow, error)
	// GetTrashedWithdrawByID: Retrieves a single soft-deleted withdrawal by ID
	// Purpose: View details of a deleted withdrawal for recovery or audit
	// Parameters:
	//   $1: withdraw_id - The ID of the withdrawal to retrieve
	// Returns:
	//   All fields for the specified trashed withdrawal or NULL if not found/active
	// Business Logic:
	//   - Only returns soft-deleted withdrawals (deleted_at IS NOT NULL)
	//   - Used in admin interfaces for withdrawal recovery
	GetTrashedWithdrawByID(ctx context.Context, withdrawID int32) (*Withdraw, error)
	// GetTrashedWithdraws: Retrieves paginated soft-deleted withdrawals
	// Purpose: List all deleted withdrawals for recovery or audit purposes
	// Parameters:
	//   $1: search_term - Optional text to filter deleted withdrawals
	//   $2: limit - Maximum records to return per page
	//   $3: offset - Records to skip for pagination
	// Returns:
	//   All withdrawal fields plus total_count of matching deleted records
	// Business Logic:
	//   - Only includes soft-deleted withdrawals (deleted_at IS NOT NULL)
	//   - Same filtering capabilities as active withdrawals
	//   - Maintains newest-first ordering
	//   - Used in admin interfaces for withdrawal recovery
	GetTrashedWithdraws(ctx context.Context, arg GetTrashedWithdrawsParams) ([]*GetTrashedWithdrawsRow, error)
	// GetUserRoles: Retrieves all roles assigned to a specific user
	// Purpose: Identify the access level(s) of a user
	// Parameters:
	//   $1: User ID
	// Returns:
	//   List of roles (id, name, timestamps)
	GetUserRoles(ctx context.Context, userID int32) ([]*Role, error)
	// GetWithdrawByID: Retrieves a single withdrawal by its ID
	// Purpose: Get detailed information about a specific withdrawal
	// Parameters:
	//   $1: withdraw_id - The ID of the withdrawal to retrieve
	// Returns:
	//   All fields for the specified withdrawal or NULL if not found/deleted
	// Business Logic:
	//   - Only returns active withdrawals (deleted_at IS NULL)
	//   - Useful for withdrawal details viewing and verification
	GetWithdrawByID(ctx context.Context, withdrawID int32) (*GetWithdrawByIDRow, error)
	// GetWithdraws: Retrieves paginated withdrawal records with search capability
	// Purpose: List all withdrawals for management UI with filtering options
	// Parameters:
	//   $1: search_term - Optional text to filter withdrawals by various fields (NULL for no filter)
	//   $2: limit - Maximum number of records to return per page
	//   $3: offset - Number of records to skip for pagination
	// Returns:
	//   All withdrawal fields plus total_count of matching records
	// Business Logic:
	//   - Excludes soft-deleted withdrawals (deleted_at IS NULL)
	//   - Supports partial text matching on multiple fields (case-insensitive):
	//     * card_number
	//     * withdraw_amount (converted to text)
	//     * withdraw_time (converted to text)
	//     * status
	//   - Orders by withdraw_time (newest withdrawals first)
	//   - Provides total_count for pagination calculations
	//   - Useful for withdrawal monitoring and auditing
	GetWithdraws(ctx context.Context, arg GetWithdrawsParams) ([]*GetWithdrawsRow, error)
	// GetWithdrawsByCardNumber: Retrieves paginated withdrawals for a specific card with search
	// Purpose: List all withdrawals associated with a particular card
	// Parameters:
	//   $1: card_number - The card number to filter withdrawals
	//   $2: search_term - Optional text to filter by amount, time, or status
	//   $3: limit - Maximum number of records to return per page
	//   $4: offset - Number of records to skip for pagination
	// Returns:
	//   All withdrawal fields plus total_count of matching records
	// Business Logic:
	//   - Only includes active withdrawals (deleted_at IS NULL)
	//   - Strict card number matching combined with optional search filters:
	//     * withdraw_amount (converted to text for searching)
	//     * withdraw_time (formatted as string for searching)
	//     * status
	//   - Orders by withdraw_time (newest first)
	//   - Provides pagination support with total_count
	//   - Useful for cardholder withdrawal history
	GetWithdrawsByCardNumber(ctx context.Context, arg GetWithdrawsByCardNumberParams) ([]*GetWithdrawsByCardNumberRow, error)
	// GetYearlyWithdrawStatusFailed: Retrieves yearly failed metrics for withdrawals
	// Purpose: Compare annual failedful withdrawal performance year-over-year
	// Parameters:
	//   $1: current_year - The target year (includes this year and previous)
	// Returns:
	//   year: Year as text (e.g., '2023')
	//   total_failed: Count of failedful withdrawals
	//   total_amount: Sum of failedful withdrawal amounts
	// Business Logic:
	//   - Only includes failedful withdrawals (status = 'failed')
	//   - Compares current year with previous year
	//   - Zero-fills years with no withdrawal activity
	//   - Orders by year (newest first)
	//   - Useful for year-over-year cash flow analysis
	//   - Helps identify annual withdrawal patterns and liquidity trends
	GetYearlyWithdrawStatusFailed(ctx context.Context, dollar_1 int32) ([]*GetYearlyWithdrawStatusFailedRow, error)
	// GetYearlyWithdrawStatusFailedCardNumber: Retrieves yearly failed metrics for withdrawals
	// Purpose: Compare annual failedful withdrawal performance year-over-year
	// Parameters:
	//   $1: card_number  - filter by card_number
	//   $2: current_year - The target year (includes this year and previous)
	// Returns:
	//   year: Year as text (e.g., '2023')
	//   total_failed: Count of failedful withdrawals
	//   total_amount: Sum of failedful withdrawal amounts
	// Business Logic:
	//   - Only includes failedful withdrawals (status = 'failed')
	//   - Compares current year with previous year
	//   - Zero-fills years with no withdrawal activity
	//   - Orders by year (newest first)
	//   - Useful for year-over-year cash flow analysis
	//   - Helps identify annual withdrawal patterns and liquidity trends
	GetYearlyWithdrawStatusFailedCardNumber(ctx context.Context, arg GetYearlyWithdrawStatusFailedCardNumberParams) ([]*GetYearlyWithdrawStatusFailedCardNumberRow, error)
	// GetYearlyWithdrawStatusSuccess: Retrieves yearly success metrics for withdrawals
	// Purpose: Compare annual successful withdrawal performance year-over-year
	// Parameters:
	//   $1: current_year - The target year (includes this year and previous)
	// Returns:
	//   year: Year as text (e.g., '2023')
	//   total_success: Count of successful withdrawals
	//   total_amount: Sum of successful withdrawal amounts
	// Business Logic:
	//   - Only includes successful withdrawals (status = 'success')
	//   - Compares current year with previous year
	//   - Zero-fills years with no withdrawal activity
	//   - Orders by year (newest first)
	//   - Useful for year-over-year cash flow analysis
	//   - Helps identify annual withdrawal patterns and liquidity trends
	GetYearlyWithdrawStatusSuccess(ctx context.Context, dollar_1 int32) ([]*GetYearlyWithdrawStatusSuccessRow, error)
	GetYearlyWithdrawStatusSuccessCardNumber(ctx context.Context, arg GetYearlyWithdrawStatusSuccessCardNumberParams) ([]*GetYearlyWithdrawStatusSuccessCardNumberRow, error)
	// GetYearlyWithdraws: Retrieves yearly withdrawal totals for a 5-year period
	// Purpose: Analyze long-term withdrawal trends
	// Parameters:
	//   $1: current_year - The final year to include (includes this year and previous 4 years)
	// Returns:
	//   year: 4-digit year
	//   total_withdraw_amount: Sum of withdrawal amounts for that year
	// Business Logic:
	//   - Covers a 5-year rolling window (current_year-4 to current_year)
	//   - Only includes active withdrawal records
	//   - Groups by calendar year
	//   - Orders results chronologically
	//   - Useful for identifying annual cash usage patterns
	GetYearlyWithdraws(ctx context.Context, dollar_1 interface{}) ([]*GetYearlyWithdrawsRow, error)
	// GetYearlyWithdrawsByCardNumber: Retrieves yearly withdrawals for a specific card
	// Purpose: Analyze long-term cash usage for individual cardholders
	// Parameters:
	//   $1: card_number - The card number to filter withdrawals
	//   $2: current_year - The final year to include (5-year window)
	// Returns:
	//   year: 4-digit year
	//   total_withdraw_amount: Sum of withdrawals for that card by year
	// Business Logic:
	//   - Covers 5-year period (current_year-4 to current_year)
	//   - Filters by specific card number
	//   - Only includes active withdrawals
	//   - Groups by calendar year
	//   - Orders chronologically
	//   - Useful for customer spending habit analysis
	GetYearlyWithdrawsByCardNumber(ctx context.Context, arg GetYearlyWithdrawsByCardNumberParams) ([]*GetYearlyWithdrawsByCardNumberRow, error)
	// RestoreAllRoles: Restores all soft-deleted roles in bulk
	// Purpose: Bulk recovery of all trashed roles
	// Parameters: None
	RestoreAllRoles(ctx context.Context) error
	// RestoreAllWithdraws: Recovers all trashed withdrawals
	// Purpose: Mass restoration of deleted withdrawals
	// Business Logic:
	//   - Clears deleted_at for all trashed withdrawals
	//   - Useful for system recovery scenarios
	//   - Should be used cautiously in production
	//   - Admin-level operation
	RestoreAllWithdraws(ctx context.Context) error
	// RestoreRole: Restores a previously trashed role
	// Purpose: Undelete a soft-deleted role
	// Parameters:
	//   $1: Role ID
	RestoreRole(ctx context.Context, roleID int32) (*Role, error)
	// RestoreWithdraw: Recovers a soft-deleted withdrawal
	// Purpose: Reactivate a previously deleted withdrawal
	// Parameters:
	//   $1: withdraw_id - ID of withdrawal to restore
	// Business Logic:
	//   - Clears the deleted_at timestamp (sets to NULL)
	//   - Only works on currently trashed withdrawals
	//   - Used for data recovery purposes
	RestoreWithdraw(ctx context.Context, withdrawID int32) (*Withdraw, error)
	// TrashRole: Soft-deletes a role (moves to trash)
	// Purpose: Mark role as deleted without removing it permanently
	// Parameters:
	//   $1: Role ID
	TrashRole(ctx context.Context, roleID int32) (*Role, error)
	// TrashWithdraw: Soft-deletes a withdrawal record
	// Purpose: Remove withdrawal from active view without permanent deletion
	// Parameters:
	//   $1: withdraw_id - ID of withdrawal to trash
	// Business Logic:
	//   - Sets deleted_at timestamp to current time
	//   - Only affects active withdrawals
	//   - Preserves data for audit/recovery purposes
	//   - Withdrawal remains in database but hidden
	TrashWithdraw(ctx context.Context, withdrawID int32) (*Withdraw, error)
	// UpdateRole: Updates role name by ID
	// Purpose: Modify role information (e.g., name correction)
	// Parameters:
	//   $1: Role ID
	//   $2: New role name
	// Returns:
	//   Updated role's data
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (*Role, error)
	// UpdateWithdraw: Modifies withdrawal details
	// Purpose: Update withdrawal information
	// Parameters:
	//   $1: withdraw_id - ID of withdrawal to update
	//   $2: card_number - Updated card number
	//   $3: withdraw_amount - Updated withdrawal amount
	//   $4: withdraw_time - Updated withdrawal timestamp
	// Business Logic:
	//   - Only updates active withdrawals (non-deleted)
	//   - Updates modification timestamp automatically
	//   - Used for correcting withdrawal records
	//   - Requires original withdrawal record exists
	UpdateWithdraw(ctx context.Context, arg UpdateWithdrawParams) (*UpdateWithdrawRow, error)
	// UpdateWithdrawStatus: Changes withdrawal status
	// Purpose: Update processing status of a withdrawal
	// Parameters:
	//   $1: withdraw_id - ID of withdrawal to update
	//   $2: status - New status (e.g., 'completed', 'failed', 'pending')
	// Business Logic:
	//   - Only updates active withdrawals
	//   - Updates modification timestamp
	//   - Used to reflect withdrawal processing outcomes
	//   - Important for reconciliation purposes
	UpdateWithdrawStatus(ctx context.Context, arg UpdateWithdrawStatusParams) (*UpdateWithdrawStatusRow, error)
}

var _ Querier = (*Queries)(nil)
