// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: card.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveAuthTransaction = `-- name: ApproveAuthTransaction :one
UPDATE card_auth_transactions
SET status = 'approved', updated_at = CURRENT_TIMESTAMP
WHERE txn_id = $1 AND status = 'pending'
RETURNING auth_id, txn_id, card_number, merchant_id, amount, currency, mcc,
          pos_entry_mode, status, idempotency_key, risk_score, created_at, updated_at
`

func (q *Queries) ApproveAuthTransaction(ctx context.Context, txnID string) (*CardAuthTransaction, error) {
	row := q.db.QueryRow(ctx, approveAuthTransaction, txnID)
	var i CardAuthTransaction
	err := row.Scan(
		&i.AuthID,
		&i.TxnID,
		&i.CardNumber,
		&i.MerchantID,
		&i.Amount,
		&i.Currency,
		&i.Mcc,
		&i.PosEntryMode,
		&i.Status,
		&i.IdempotencyKey,
		&i.RiskScore,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const countCardPayments = `-- name: CountCardPayments :one
SELECT COUNT(*)::INT AS total_count
FROM card_payments
WHERE card_number = $1
`

func (q *Queries) CountCardPayments(ctx context.Context, cardNumber string) (int32, error) {
	row := q.db.QueryRow(ctx, countCardPayments, cardNumber)
	var total_count int32
	err := row.Scan(&total_count)
	return total_count, err
}

const countRecentAuthByCardNumber = `-- name: CountRecentAuthByCardNumber :one
SELECT COUNT(*)::INT AS total_count
FROM card_auth_transactions
WHERE card_number = $1 AND created_at >= $2
`

type CountRecentAuthByCardNumberParams struct {
	CardNumber string           `json:"card_number"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) CountRecentAuthByCardNumber(ctx context.Context, arg CountRecentAuthByCardNumberParams) (int32, error) {
	row := q.db.QueryRow(ctx, countRecentAuthByCardNumber, arg.CardNumber, arg.CreatedAt)
	var total_count int32
	err := row.Scan(&total_count)
	return total_count, err
}

const createBillingCycles = `-- name: CreateBillingCycles :many
INSERT INTO billing_cycles (
    card_number, cycle_start, cycle_end, amount_due, due_date, status
)
SELECT card_number, $1, $2, outstanding_balance, $3, 'unpaid'
FROM cards
WHERE deleted_at IS NULL
ON CONFLICT (card_number, cycle_start) DO NOTHING
RETURNING billing_id, card_number, cycle_start, cycle_end, amount_due, due_date,
          status, created_at, updated_at
`

type CreateBillingCyclesParams struct {
	CycleStart time.Time `json:"cycle_start"`
	CycleEnd   time.Time `json:"cycle_end"`
	DueDate    time.Time `json:"due_date"`
}

// CreateBillingCycles creates one statement per active card for the period.
// The unique period index makes retries and concurrent schedulers safe.
func (q *Queries) CreateBillingCycles(ctx context.Context, arg CreateBillingCyclesParams) ([]*BillingCycle, error) {
	rows, err := q.db.Query(ctx, createBillingCycles, arg.CycleStart, arg.CycleEnd, arg.DueDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*BillingCycle
	for rows.Next() {
		var i BillingCycle
		if err := rows.Scan(
			&i.BillingID,
			&i.CardNumber,
			&i.CycleStart,
			&i.CycleEnd,
			&i.AmountDue,
			&i.DueDate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createCard = `-- name: CreateCard :one
INSERT INTO
    cards (
        user_id,
        card_number,
        card_type,
        expire_date,
        cvv,
        card_provider,
        created_at,
        updated_at
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        current_timestamp,
        current_timestamp
    )
RETURNING
    card_id,
    user_id,
    card_number,
    card_type,
    expire_date,
    cvv,
    card_provider,
    created_at,
    updated_at
`

type CreateCardParams struct {
	UserID       int32       `json:"user_id"`
	CardNumber   string      `json:"card_number"`
	CardType     string      `json:"card_type"`
	ExpireDate   pgtype.Date `json:"expire_date"`
	Cvv          string      `json:"cvv"`
	CardProvider string      `json:"card_provider"`
}

type CreateCardRow struct {
	CardID       int32            `json:"card_id"`
	UserID       int32            `json:"user_id"`
	CardNumber   string           `json:"card_number"`
	CardType     string           `json:"card_type"`
	ExpireDate   pgtype.Date      `json:"expire_date"`
	Cvv          string           `json:"cvv"`
	CardProvider string           `json:"card_provider"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

// GetTotalBalance: Calculates the sum of all active card balances
// Purpose: Get the total balance across all active cards in the system
// Returns:
//
//	Single column 'total_balance' containing the sum of all non-deleted card balances
//
// Business Logic:
//   - Only includes balances from active saldos records (s.deleted_at IS NULL)
//   - Only includes balances from active cards (c.deleted_at IS NULL)
//   - Useful for financial dashboards and system health monitoring
//   - Returns NULL if no active balances exist
func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (*CreateCardRow, error) {
	row := q.db.QueryRow(ctx, createCard,
		arg.UserID,
		arg.CardNumber,
		arg.CardType,
		arg.ExpireDate,
		arg.Cvv,
		arg.CardProvider,
	)
	var i CreateCardRow
	err := row.Scan(
		&i.CardID,
		&i.UserID,
		&i.CardNumber,
		&i.CardType,
		&i.ExpireDate,
		&i.Cvv,
		&i.CardProvider,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const declineAuthTransaction = `-- name: DeclineAuthTransaction :one
UPDATE card_auth_transactions
SET status = 'declined', updated_at = CURRENT_TIMESTAMP
WHERE txn_id = $1 AND status = 'pending'
RETURNING auth_id, txn_id, card_number, merchant_id, amount, currency, mcc,
          pos_entry_mode, status, idempotency_key, risk_score, created_at, updated_at
`

func (q *Queries) DeclineAuthTransaction(ctx context.Context, txnID string) (*CardAuthTransaction, error) {
	row := q.db.QueryRow(ctx, declineAuthTransaction, txnID)
	var i CardAuthTransaction
	err := row.Scan(
		&i.AuthID,
		&i.TxnID,
		&i.CardNumber,
		&i.MerchantID,
		&i.Amount,
		&i.Currency,
		&i.Mcc,
		&i.PosEntryMode,
		&i.Status,
		&i.IdempotencyKey,
		&i.RiskScore,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteAllPermanentCards = `-- name: DeleteAllPermanentCards :exec
DELETE FROM cards WHERE deleted_at IS NOT NULL
`

// DeleteAllPermanentCards: Permanently deletes all trashed cards
// Purpose: Bulk-delete all cards that have been soft-deleted
// Parameters: None
// Returns: Nothing
// Business Logic:
//   - Deletes only cards with deleted_at set
func (q *Queries) DeleteAllPermanentCards(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllPermanentCards)
	return err
}

const deleteCardPermanently = `-- name: DeleteCardPermanently :exec
DELETE FROM cards WHERE card_id = $1 AND deleted_at IS NOT NULL
`

// DeleteCardPermanently: Removes a trashed card from the database
// Purpose: Permanently delete a card that has been soft-deleted
// Parameters:
//
//	$1: card_id - Identifier of the card to permanently delete
//
// Returns: Nothing
// Business Logic:
//   - Only deletes cards that are currently trashed
func (q *Queries) DeleteCardPermanently(ctx context.Context, cardID int32) error {
	_, err := q.db.Exec(ctx, deleteCardPermanently, cardID)
	return err
}

const getActiveCardsWithCount = `-- name: GetActiveCardsWithCount :many
SELECT
    card_id,
    user_id,
    card_number,
    card_type,
    expire_date,
    cvv,
    card_provider,
    created_at,
    updated_at,
    deleted_at,
    COUNT(*) OVER () AS total_count
FROM cards
WHERE
    deleted_at IS NULL
    AND (
        $1::TEXT IS NULL
        OR card_number ILIKE '%' || $1 || '%'
        OR card_type ILIKE '%' || $1 || '%'
        OR card_provider ILIKE '%' || $1 || '%'
    )
ORDER BY card_id
LIMIT $2
OFFSET
    $3
`

type GetActiveCardsWithCountParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type GetActiveCardsWithCountRow struct {
	CardID       int32            `json:"card_id"`
	UserID       int32            `json:"user_id"`
	CardNumber   string           `json:"card_number"`
	CardType     string           `json:"card_type"`
	ExpireDate   pgtype.Date      `json:"expire_date"`
	Cvv          string           `json:"cvv"`
	CardProvider string           `json:"card_provider"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	DeletedAt    pgtype.Timestamp `json:"deleted_at"`
	TotalCount   int64            `json:"total_count"`
}

func (q *Queries) GetActiveCardsWithCount(ctx context.Context, arg GetActiveCardsWithCountParams) ([]*GetActiveCardsWithCountRow, error) {
	rows, err := q.db.Query(ctx, getActiveCardsWithCount, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetActiveCardsWithCountRow
	for rows.Next() {
		var i GetActiveCardsWithCountRow
		if err := rows.Scan(
			&i.CardID,
			&i.UserID,
			&i.CardNumber,
			&i.CardType,
			&i.ExpireDate,
			&i.Cvv,
			&i.CardProvider,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuthTransactionByIdempotencyKey = `-- name: GetAuthTransactionByIdempotencyKey :one
SELECT auth_id, txn_id, card_number, merchant_id, amount, currency, mcc,
       pos_entry_mode, status, idempotency_key, risk_score, created_at, updated_at
FROM card_auth_transactions
WHERE idempotency_key = $1
`

func (q *Queries) GetAuthTransactionByIdempotencyKey(ctx context.Context, idempotencyKey string) (*CardAuthTransaction, error) {
	row := q.db.QueryRow(ctx, getAuthTransactionByIdempotencyKey, idempotencyKey)
	var i CardAuthTransaction
	err := row.Scan(
		&i.AuthID,
		&i.TxnID,
		&i.CardNumber,
		&i.MerchantID,
		&i.Amount,
		&i.Currency,
		&i.Mcc,
		&i.PosEntryMode,
		&i.Status,
		&i.IdempotencyKey,
		&i.RiskScore,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getAuthTransactionByTxnId = `-- name: GetAuthTransactionByTxnId :one
SELECT auth_id, txn_id, card_number, merchant_id, amount, currency, mcc,
       pos_entry_mode, status, idempotency_key, risk_score, created_at, updated_at
FROM card_auth_transactions
WHERE txn_id = $1
`

func (q *Queries) GetAuthTransactionByTxnId(ctx context.Context, txnID string) (*CardAuthTransaction, error) {
	row := q.db.QueryRow(ctx, getAuthTransactionByTxnId, txnID)
	var i CardAuthTransaction
	err := row.Scan(
		&i.AuthID,
		&i.TxnID,
		&i.CardNumber,
		&i.MerchantID,
		&i.Amount,
		&i.Currency,
		&i.Mcc,
		&i.PosEntryMode,
		&i.Status,
		&i.IdempotencyKey,
		&i.RiskScore,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getAuthTransactionsByCardNumber = `-- name: GetAuthTransactionsByCardNumber :many
SELECT auth_id, txn_id, card_number, merchant_id, amount, currency, mcc,
       pos_entry_mode, status, idempotency_key, risk_score, created_at, updated_at,
       COUNT(*) OVER () AS total_count
FROM card_auth_transactions
WHERE card_number = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetAuthTransactionsByCardNumberParams struct {
	CardNumber string `json:"card_number"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
}

type GetAuthTransactionsByCardNumberRow struct {
	AuthID         int32            `json:"auth_id"`
	TxnID          string           `json:"txn_id"`
	CardNumber     string           `json:"card_number"`
	MerchantID     int32            `json:"merchant_id"`
	Amount         int64            `json:"amount"`
	Currency       string           `json:"currency"`
	Mcc            string           `json:"mcc"`
	PosEntryMode   string           `json:"pos_entry_mode"`
	Status         string           `json:"status"`
	IdempotencyKey string           `json:"idempotency_key"`
	RiskScore      int32            `json:"risk_score"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	TotalCount     int64            `json:"total_count"`
}

func (q *Queries) GetAuthTransactionsByCardNumber(ctx context.Context, arg GetAuthTransactionsByCardNumberParams) ([]*GetAuthTransactionsByCardNumberRow, error) {
	rows, err := q.db.Query(ctx, getAuthTransactionsByCardNumber, arg.CardNumber, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetAuthTransactionsByCardNumberRow
	for rows.Next() {
		var i GetAuthTransactionsByCardNumberRow
		if err := rows.Scan(
			&i.AuthID,
			&i.TxnID,
			&i.CardNumber,
			&i.MerchantID,
			&i.Amount,
			&i.Currency,
			&i.Mcc,
			&i.PosEntryMode,
			&i.Status,
			&i.IdempotencyKey,
			&i.RiskScore,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBillingCyclesByCardNumber = `-- name: GetBillingCyclesByCardNumber :many
SELECT billing_id, card_number, cycle_start, cycle_end, amount_due, due_date,
       status, created_at, updated_at
FROM billing_cycles
WHERE card_number = $1
ORDER BY cycle_start DESC
`

func (q *Queries) GetBillingCyclesByCardNumber(ctx context.Context, cardNumber string) ([]*BillingCycle, error) {
	rows, err := q.db.Query(ctx, getBillingCyclesByCardNumber, cardNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*BillingCycle
	for rows.Next() {
		var i BillingCycle
		if err := rows.Scan(
			&i.BillingID,
			&i.CardNumber,
			&i.CycleStart,
			&i.CycleEnd,
			&i.AmountDue,
			&i.DueDate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCardByCardNumber = `-- name: GetCardByCardNumber :one
SELECT
    card_id,
    user_id,
    card_number,
    card_type,
    expire_date,
    cvv,
    card_provider,
    created_at,
    updated_at
FROM cards
WHERE
    card_number = $1
    AND deleted_at IS NULL
`

type GetCardByCardNumberRow struct {
	CardID       int32            `json:"card_id"`
	UserID       int32            `json:"user_id"`
	CardNumber   string           `json:"card_number"`
	CardType     string           `json:"card_type"`
	ExpireDate   pgtype.Date      `json:"expire_date"`
	Cvv          string           `json:"cvv"`
	CardProvider string           `json:"card_provider"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

// GetCardByCardNumber: Retrieves a single active card by its card number
// Purpose: Lookup card information using the physical card number
// Parameters:
//
//	$1: card_number - The exact card number to search for
//
// Returns:
//
//	All fields for the matching card or NULL if not found or deleted
//
// Business Logic:
//   - Only returns active cards (deleted_at IS NULL)
//   - Performs exact match on card_number field (case-sensitive)
//   - Useful for card verification during transactions
func (q *Queries) GetCardByCardNumber(ctx context.Context, cardNumber string) (*GetCardByCardNumberRow, error) {
	row := q.db.QueryRow(ctx, getCardByCardNumber, cardNumber)
	var i GetCardByCardNumberRow
	err := row.Scan(
		&i.CardID,
		&i.UserID,
		&i.CardNumber,
		&i.CardType,
		&i.ExpireDate,
		&i.Cvv,
		&i.CardProvider,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getCardByID = `-- name: GetCardByID :one
SELECT
    card_id,
    user_id,
    card_number,
    card_type,
    expire_date,
    cvv,
    card_provider,
    created_at,
    updated_at
FROM cards
WHERE
    card_id = $1
    AND deleted_at IS NULL
`

type GetCardByIDRow struct {
	CardID       int32            `json:"card_id"`
	UserID       int32            `json:"user_id"`
	CardNumber   string           `json:"card_number"`
	CardType     string           `json:"card_type"`
	ExpireDate   pgtype.Date      `json:"expire_date"`
	Cvv          string           `json:"cvv"`
	CardProvider string           `json:"card_provider"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

// GetCardByID: Retrieves a single card by its ID
// Purpose: Get detailed information about a specific card
// Parameters:
//
//	$1: card_id - The ID of the card to retrieve
//
// Returns:
//
//	All fields for the specified card
//
// Business Logic:
//   - Only returns active cards (deleted_at IS NULL)
//   - Returns NULL if card is not found or has been soft-deleted
func (q *Queries) GetCardByID(ctx context.Context, cardID int32) (*GetCardByIDRow, error) {
	row := q.db.QueryRow(ctx, getCardByID, cardID)
	var i GetCardByIDRow
	err := row.Scan(
		&i.CardID,
		&i.UserID,
		&i.CardNumber,
		&i.CardType,
		&i.ExpireDate,
		&i.Cvv,
		&i.CardProvider,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getCardByUserID = `-- name: GetCardByUserID :one
SELECT
    card_id,
    user_id,
    card_number,
    card_type,
    expire_date,
    cvv,
    card_provider,
    created_at,
    updated_at
FROM cards
WHERE
    user_id = $1
    AND deleted_at IS NULL
LIMIT 1
`

type GetCardByUserIDRow struct {
	CardID       int32            `json:"card_id"`
	UserID       int32            `json:"user_id"`
	CardNumber   string           `json:"card_number"`
	CardType     string           `json:"card_type"`
	ExpireDate   pgtype.Date      `json:"expire_date"`
	Cvv          string           `json:"cvv"`
	CardProvider string           `json:"card_provider"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

// GetCardByUserID: Retrieves a single active card associated with a specific user
// Purpose: Get the card information for a particular user
// Parameters:
//
//	$1: user_id - The ID of the user whose card should be retrieved
//
// Returns:
//
//	All fields for the user's card or NULL if no active card exists
//
// Business Logic:
//   - Only returns active cards (deleted_at IS NULL)
//   - Returns at most one card (LIMIT 1) even if multiple cards exist for the user
//   - Useful for displaying a user's primary/default card
func (q *Queries) GetCardByUserID(ctx context.Context, userID int32) (*GetCardByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getCardByUserID, userID)
	var i GetCardByUserIDRow
	err := row.Scan(
		&i.CardID,
		&i.UserID,
		&i.CardNumber,
		&i.CardType,
		&i.ExpireDate,
		&i.Cvv,
		&i.CardProvider,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getCardPaymentsByCardNumber = `-- name: GetCardPaymentsByCardNumber :many
SELECT payment_id, payment_uuid, card_number, billing_id, amount,
       payment_channel, reference_id, status, created_at, updated_at,
       COUNT(*) OVER () AS total_count
FROM card_payments
WHERE card_number = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetCardPaymentsByCardNumberParams struct {
	CardNumber string `json:"card_number"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
}

type GetCardPaymentsByCardNumberRow struct {
	PaymentID      int32            `json:"payment_id"`
	PaymentUuid    string           `json:"payment_uuid"`
	CardNumber     string           `json:"card_number"`
	BillingID      *int32           `json:"billing_id"`
	Amount         int64            `json:"amount"`
	PaymentChannel string           `json:"payment_channel"`
	ReferenceID    string           `json:"reference_id"`
	Status         string           `json:"status"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	TotalCount     int64            `json:"total_count"`
}

func (q *Queries) GetCardPaymentsByCardNumber(ctx context.Context, arg GetCardPaymentsByCardNumberParams) ([]*GetCardPaymentsByCardNumberRow, error) {
	rows, err := q.db.Query(ctx, getCardPaymentsByCardNumber, arg.CardNumber, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetCardPaymentsByCardNumberRow
	for rows.Next() {
		var i GetCardPaymentsByCardNumberRow
		if err := rows.Scan(
			&i.PaymentID,
			&i.PaymentUuid,
			&i.CardNumber,
			&i.BillingID,
			&i.Amount,
			&i.PaymentChannel,
			&i.ReferenceID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCardRewardBalance = `-- name: GetCardRewardBalance :one
SELECT COALESCE(SUM(points_earned), 0)::BIGINT AS balance
FROM card_rewards
WHERE card_number = $1 AND redeemed = FALSE AND expires_at > CURRENT_TIMESTAMP
`

func (q *Queries) GetCardRewardBalance(ctx context.Context, cardNumber string) (int64, error) {
	row := q.db.QueryRow(ctx, getCardRewardBalance, cardNumber)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const getCardRewardHistory = `-- name: GetCardRewardHistory :many
SELECT reward_id, card_number, txn_id, amount, mcc, points_earned,
       expires_at, redeemed, created_at
FROM card_rewards
WHERE card_number = $1
ORDER BY created_at DESC
`

func (q *Queries) GetCardRewardHistory(ctx context.Context, cardNumber string) ([]*CardReward, error) {
	rows, err := q.db.Query(ctx, getCardRewardHistory, cardNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*CardReward
	for rows.Next() {
		var i CardReward
		if err := rows.Scan(
			&i.RewardID,
			&i.CardNumber,
			&i.TxnID,
			&i.Amount,
			&i.Mcc,
			&i.PointsEarned,
			&i.ExpiresAt,
			&i.Redeemed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCards = `-- name: GetCards :many
SELECT
    card_id,
    user_id,
    card_number,
    card_type,
    expire_date,
    cvv,
    card_provider,
    created_at,
    updated_at,
    COUNT(*) OVER () AS total_count
FROM cards
WHERE
    deleted_at IS NULL
    AND (
        $1::TEXT IS NULL
        OR card_number ILIKE '%' || $1 || '%'
        OR card_type ILIKE '%' || $1 || '%'
        OR card_provider ILIKE '%' || $1 || '%'
    )
ORDER BY card_id
LIMIT $2
OFFSET
    $3
`

type GetCardsParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type GetCardsRow struct {
	CardID       int32            `json:"card_id"`
	UserID       int32            `json:"user_id"`
	CardNumber   string           `json:"card_number"`
	CardType     string           `json:"card_type"`
	ExpireDate   pgtype.Date      `json:"expire_date"`
	Cvv          string           `json:"cvv"`
	CardProvider string           `json:"card_provider"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	TotalCount   int64            `json:"total_count"`
}

// GetCards: Retrieves paginated list of active cards with search capability
// Purpose: List all active cards for management UI
// Parameters:
//
//	$1: search_term - Optional text to filter cards by number, type or provider (NULL for no filter)
//	$2: limit - Maximum number of records to return
//	$3: offset - Number of records to skip for pagination
//
// Returns:
//
//	All card fields plus total_count of matching records
//
// Business Logic:
//   - Excludes soft-deleted cards (deleted_at IS NULL)
//   - Supports partial text matching on card_number, card_type and card_provider fields (case-insensitive)
//   - Returns cards ordered by card_id
//   - Provides total_count for pagination calculations
func (q *Queries) GetCards(ctx context.Context, arg GetCardsParams) ([]*GetCardsRow, error) {
	rows, err := q.db.Query(ctx, getCards, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetCardsRow
	for rows.Next() {
		var i GetCardsRow
		if err := rows.Scan(
			&i.CardID,
			&i.UserID,
			&i.CardNumber,
			&i.CardType,
			&i.ExpireDate,
			&i.Cvv,
			&i.CardProvider,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRedeemableRewardIds = `-- name: GetRedeemableRewardIds :many
SELECT reward_id, points_earned
FROM card_rewards
WHERE card_number = $1 AND redeemed = FALSE AND expires_at > CURRENT_TIMESTAMP
ORDER BY created_at
`

type GetRedeemableRewardIdsRow struct {
	RewardID     int32 `json:"reward_id"`
	PointsEarned int32 `json:"points_earned"`
}

func (q *Queries) GetRedeemableRewardIds(ctx context.Context, cardNumber string) ([]*GetRedeemableRewardIdsRow, error) {
	rows, err := q.db.Query(ctx, getRedeemableRewardIds, cardNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetRedeemableRewardIdsRow
	for rows.Next() {
		var i GetRedeemableRewardIdsRow
		if err := rows.Scan(&i.RewardID, &i.PointsEarned); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTrashedCardByID = `-- name: GetTrashedCardByID :one
SELECT card_id, user_id, card_number, card_type, expire_date, cvv, card_provider, created_at, updated_at, deleted_at, status, credit_limit, outstanding_balance, reward_points FROM cards WHERE card_id = $1 AND deleted_at IS NOT NULL
`

// GetTrashedCardByID: Retrieves a single soft-deleted card by its ID
// Purpose: View details of a specific trashed card for recovery or audit
// Parameters:
//
//	$1: card_id - The ID of the card to retrieve
//
// Returns:
//
//	All fields for the specified trashed card or NULL if not found or not deleted
//
// Business Logic:
//   - Only returns soft-deleted cards (deleted_at IS NOT NULL)
//   - Useful for admin interfaces showing deleted items
//   - Can be used before restoring a deleted card
func (q *Queries) GetTrashedCardByID(ctx context.Context, cardID int32) (*Card, error) {
	row := q.db.QueryRow(ctx, getTrashedCardByID, cardID)
	var i Card
	err := row.Scan(
		&i.CardID,
		&i.UserID,
		&i.CardNumber,
		&i.CardType,
		&i.ExpireDate,
		&i.Cvv,
		&i.CardProvider,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Status,
		&i.CreditLimit,
		&i.OutstandingBalance,
		&i.RewardPoints,
	)
	return &i, err
}

const getTrashedCardsWithCount = `-- name: GetTrashedCardsWithCount :many
SELECT
    card_id,
    user_id,
    card_number,
    card_type,
    expire_date,
    cvv,
    card_provider,
    created_at,
    updated_at,
    deleted_at,
    COUNT(*) OVER () AS total_count
FROM cards
WHERE
    deleted_at IS NOT NULL
    AND (
        $1::TEXT IS NULL
        OR card_number ILIKE '%' || $1 || '%'
        OR card_type ILIKE '%' || $1 || '%'
        OR card_provider ILIKE '%' || $1 || '%'
    )
ORDER BY card_id
LIMIT $2
OFFSET
    $3
`

type GetTrashedCardsWithCountParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type GetTrashedCardsWithCountRow struct {
	CardID       int32            `json:"card_id"`
	UserID       int32            `json:"user_id"`
	CardNumber   string           `json:"card_number"`
	CardType     string           `json:"card_type"`
	ExpireDate   pgtype.Date      `json:"expire_date"`
	Cvv          string           `json:"cvv"`
	CardProvider string           `json:"card_provider"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	DeletedAt    pgtype.Timestamp `json:"deleted_at"`
	TotalCount   int64            `json:"total_count"`
}

// GetTrashedCardsWithCount: Retrieves paginated list of soft-deleted cards with search capability
// Purpose: List all trashed (soft-deleted) cards for recovery or audit purposes
// Parameters:
//
//	$1: search_term - Optional text to filter cards by number, type or provider (NULL for no filter)
//	$2: limit - Maximum number of records to return
//	$3: offset - Number of records to skip for pagination
//
// Returns:
//
//	All card fields plus total_count of matching records
//
// Business Logic:
//   - Includes only soft-deleted cards (deleted_at IS NOT NULL)
//   - Supports partial text matching on card_number, card_type and card_provider fields (case-insensitive)
//   - Returns cards ordered by card_id
//   - Provides total_count for pagination calculations
func (q *Queries) GetTrashedCardsWithCount(ctx context.Context, arg GetTrashedCardsWithCountParams) ([]*GetTrashedCardsWithCountRow, error) {
	rows, err := q.db.Query(ctx, getTrashedCardsWithCount, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetTrashedCardsWithCountRow
	for rows.Next() {
		var i GetTrashedCardsWithCountRow
		if err := rows.Scan(
			&i.CardID,
			&i.UserID,
			&i.CardNumber,
			&i.CardType,
			&i.ExpireDate,
			&i.Cvv,
			&i.CardProvider,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserEmailByCardNumber = `-- name: GetUserEmailByCardNumber :one
SELECT
    card_id,
    ''::TEXT AS email,
    user_id,
    card_number,
    card_type,
    expire_date,
    cvv,
    card_provider,
    created_at,
    updated_at
FROM cards
WHERE
    card_number = $1
    AND deleted_at IS NULL
`

type GetUserEmailByCardNumberRow struct {
	CardID       int32            `json:"card_id"`
	Email        string           `json:"email"`
	UserID       int32            `json:"user_id"`
	CardNumber   string           `json:"card_number"`
	CardType     string           `json:"card_type"`
	ExpireDate   pgtype.Date      `json:"expire_date"`
	Cvv          string           `json:"cvv"`
	CardProvider string           `json:"card_provider"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

// GetUserEmailByCardNumber: Retrieves an active card by number.
// The card database owns cards, while user profile data lives in user_db.
// Email is enriched by the card service through UserQueryService; do not join users here.
func (q *Queries) GetUserEmailByCardNumber(ctx context.Context, cardNumber string) (*GetUserEmailByCardNumberRow, error) {
	row := q.db.QueryRow(ctx, getUserEmailByCardNumber, cardNumber)
	var i GetUserEmailByCardNumberRow
	err := row.Scan(
		&i.CardID,
		&i.Email,
		&i.UserID,
		&i.CardNumber,
		&i.CardType,
		&i.ExpireDate,
		&i.Cvv,
		&i.CardProvider,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const insertAuthTransaction = `-- name: InsertAuthTransaction :one
INSERT INTO card_auth_transactions (
    txn_id, card_number, merchant_id, amount, currency, mcc,
    pos_entry_mode, idempotency_key
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING auth_id, txn_id, card_number, merchant_id, amount, currency, mcc,
          pos_entry_mode, status, idempotency_key, risk_score, created_at, updated_at
`

type InsertAuthTransactionParams struct {
	TxnID          string `json:"txn_id"`
	CardNumber     string `json:"card_number"`
	MerchantID     int32  `json:"merchant_id"`
	Amount         int64  `json:"amount"`
	Currency       string `json:"currency"`
	Mcc            string `json:"mcc"`
	PosEntryMode   string `json:"pos_entry_mode"`
	IdempotencyKey string `json:"idempotency_key"`
}

// InsertAuthTransaction: Creates an idempotent pending card authorization.
func (q *Queries) InsertAuthTransaction(ctx context.Context, arg InsertAuthTransactionParams) (*CardAuthTransaction, error) {
	row := q.db.QueryRow(ctx, insertAuthTransaction,
		arg.TxnID,
		arg.CardNumber,
		arg.MerchantID,
		arg.Amount,
		arg.Currency,
		arg.Mcc,
		arg.PosEntryMode,
		arg.IdempotencyKey,
	)
	var i CardAuthTransaction
	err := row.Scan(
		&i.AuthID,
		&i.TxnID,
		&i.CardNumber,
		&i.MerchantID,
		&i.Amount,
		&i.Currency,
		&i.Mcc,
		&i.PosEntryMode,
		&i.Status,
		&i.IdempotencyKey,
		&i.RiskScore,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const insertBillingCycle = `-- name: InsertBillingCycle :one
INSERT INTO billing_cycles (
    card_number, cycle_start, cycle_end, amount_due, due_date, status
)
VALUES ($1, $2, $3, $4, $5, 'unpaid')
RETURNING billing_id, card_number, cycle_start, cycle_end, amount_due, due_date,
          status, created_at, updated_at
`

type InsertBillingCycleParams struct {
	CardNumber string    `json:"card_number"`
	CycleStart time.Time `json:"cycle_start"`
	CycleEnd   time.Time `json:"cycle_end"`
	AmountDue  int32     `json:"amount_due"`
	DueDate    time.Time `json:"due_date"`
}

func (q *Queries) InsertBillingCycle(ctx context.Context, arg InsertBillingCycleParams) (*BillingCycle, error) {
	row := q.db.QueryRow(ctx, insertBillingCycle,
		arg.CardNumber,
		arg.CycleStart,
		arg.CycleEnd,
		arg.AmountDue,
		arg.DueDate,
	)
	var i BillingCycle
	err := row.Scan(
		&i.BillingID,
		&i.CardNumber,
		&i.CycleStart,
		&i.CycleEnd,
		&i.AmountDue,
		&i.DueDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const insertCardPayment = `-- name: InsertCardPayment :one
INSERT INTO card_payments (
    payment_uuid, card_number, billing_id, amount, payment_channel, reference_id
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING payment_id, payment_uuid, card_number, billing_id, amount,
          payment_channel, reference_id, status, created_at, updated_at
`

type InsertCardPaymentParams struct {
	PaymentUuid    string `json:"payment_uuid"`
	CardNumber     string `json:"card_number"`
	BillingID      *int32 `json:"billing_id"`
	Amount         int64  `json:"amount"`
	PaymentChannel string `json:"payment_channel"`
	ReferenceID    string `json:"reference_id"`
}

func (q *Queries) InsertCardPayment(ctx context.Context, arg InsertCardPaymentParams) (*CardPayment, error) {
	row := q.db.QueryRow(ctx, insertCardPayment,
		arg.PaymentUuid,
		arg.CardNumber,
		arg.BillingID,
		arg.Amount,
		arg.PaymentChannel,
		arg.ReferenceID,
	)
	var i CardPayment
	err := row.Scan(
		&i.PaymentID,
		&i.PaymentUuid,
		&i.CardNumber,
		&i.BillingID,
		&i.Amount,
		&i.PaymentChannel,
		&i.ReferenceID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const insertCardReward = `-- name: InsertCardReward :one
INSERT INTO card_rewards (
    card_number, txn_id, amount, mcc, points_earned, expires_at
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING reward_id, card_number, txn_id, amount, mcc, points_earned,
          expires_at, redeemed, created_at
`

type InsertCardRewardParams struct {
	CardNumber   string    `json:"card_number"`
	TxnID        string    `json:"txn_id"`
	Amount       int64     `json:"amount"`
	Mcc          string    `json:"mcc"`
	PointsEarned int32     `json:"points_earned"`
	ExpiresAt    time.Time `json:"expires_at"`
}

func (q *Queries) InsertCardReward(ctx context.Context, arg InsertCardRewardParams) (*CardReward, error) {
	row := q.db.QueryRow(ctx, insertCardReward,
		arg.CardNumber,
		arg.TxnID,
		arg.Amount,
		arg.Mcc,
		arg.PointsEarned,
		arg.ExpiresAt,
	)
	var i CardReward
	err := row.Scan(
		&i.RewardID,
		&i.CardNumber,
		&i.TxnID,
		&i.Amount,
		&i.Mcc,
		&i.PointsEarned,
		&i.ExpiresAt,
		&i.Redeemed,
		&i.CreatedAt,
	)
	return &i, err
}

const markRewardsRedeemed = `-- name: MarkRewardsRedeemed :one
WITH updated AS (
    UPDATE card_rewards
    SET redeemed = TRUE
    WHERE reward_id = ANY($1::INT[])
    RETURNING points_earned
)
SELECT COALESCE(SUM(points_earned), 0)::BIGINT AS points
FROM updated
`

func (q *Queries) MarkRewardsRedeemed(ctx context.Context, dollar_1 []int32) (int64, error) {
	row := q.db.QueryRow(ctx, markRewardsRedeemed, dollar_1)
	var points int64
	err := row.Scan(&points)
	return points, err
}

const redeemRewardPoints = `-- name: RedeemRewardPoints :one
UPDATE cards
SET reward_points = GREATEST(0, reward_points - $2), updated_at = CURRENT_TIMESTAMP
WHERE card_id = $1 AND deleted_at IS NULL AND reward_points >= $2
RETURNING card_id, user_id, card_number, card_type, expire_date, cvv, card_provider,
          status, credit_limit, outstanding_balance, reward_points, created_at, updated_at
`

type RedeemRewardPointsParams struct {
	CardID       int32 `json:"card_id"`
	RewardPoints int32 `json:"reward_points"`
}

type RedeemRewardPointsRow struct {
	CardID             int32            `json:"card_id"`
	UserID             int32            `json:"user_id"`
	CardNumber         string           `json:"card_number"`
	CardType           string           `json:"card_type"`
	ExpireDate         pgtype.Date      `json:"expire_date"`
	Cvv                string           `json:"cvv"`
	CardProvider       string           `json:"card_provider"`
	Status             string           `json:"status"`
	CreditLimit        int32            `json:"credit_limit"`
	OutstandingBalance int32            `json:"outstanding_balance"`
	RewardPoints       int32            `json:"reward_points"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) RedeemRewardPoints(ctx context.Context, arg RedeemRewardPointsParams) (*RedeemRewardPointsRow, error) {
	row := q.db.QueryRow(ctx, redeemRewardPoints, arg.CardID, arg.RewardPoints)
	var i RedeemRewardPointsRow
	err := row.Scan(
		&i.CardID,
		&i.UserID,
		&i.CardNumber,
		&i.CardType,
		&i.ExpireDate,
		&i.Cvv,
		&i.CardProvider,
		&i.Status,
		&i.CreditLimit,
		&i.OutstandingBalance,
		&i.RewardPoints,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const restoreAllCards = `-- name: RestoreAllCards :exec
UPDATE cards
SET
    deleted_at = NULL
WHERE
    deleted_at IS NOT NULL
`

// RestoreAllCards: Restores all trashed cards
// Purpose: Bulk-restore all soft-deleted cards
// Parameters: None
// Returns: Nothing
// Business Logic:
//   - Sets deleted_at to NULL for all trashed cards
func (q *Queries) RestoreAllCards(ctx context.Context) error {
	_, err := q.db.Exec(ctx, restoreAllCards)
	return err
}

const restoreCard = `-- name: RestoreCard :one
UPDATE cards
SET
    deleted_at = NULL
WHERE
    card_id = $1
    AND deleted_at IS NOT NULL
RETURNING
    card_id,
    user_id,
    card_number,
    card_type,
    expire_date,
    cvv,
    card_provider,
    created_at,
    updated_at,
    deleted_at
`

type RestoreCardRow struct {
	CardID       int32            `json:"card_id"`
	UserID       int32            `json:"user_id"`
	CardNumber   string           `json:"card_number"`
	CardType     string           `json:"card_type"`
	ExpireDate   pgtype.Date      `json:"expire_date"`
	Cvv          string           `json:"cvv"`
	CardProvider string           `json:"card_provider"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	DeletedAt    pgtype.Timestamp `json:"deleted_at"`
}

// RestoreCard: Restores a previously trashed card
// Purpose: Undo soft-delete of a card
// Parameters:
//
//	$1: card_id - Identifier of the card to restore
//
// Returns: Nothing
// Business Logic:
//   - Sets deleted_at to NULL
//   - Only affects cards that are currently trashed
func (q *Queries) RestoreCard(ctx context.Context, cardID int32) (*RestoreCardRow, error) {
	row := q.db.QueryRow(ctx, restoreCard, cardID)
	var i RestoreCardRow
	err := row.Scan(
		&i.CardID,
		&i.UserID,
		&i.CardNumber,
		&i.CardType,
		&i.ExpireDate,
		&i.Cvv,
		&i.CardProvider,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const reverseAuthTransaction = `-- name: ReverseAuthTransaction :one
UPDATE card_auth_transactions
SET status = 'reversed', updated_at = CURRENT_TIMESTAMP
WHERE txn_id = $1 AND status = 'approved'
RETURNING auth_id, txn_id, card_number, merchant_id, amount, currency, mcc,
          pos_entry_mode, status, idempotency_key, risk_score, created_at, updated_at
`

func (q *Queries) ReverseAuthTransaction(ctx context.Context, txnID string) (*CardAuthTransaction, error) {
	row := q.db.QueryRow(ctx, reverseAuthTransaction, txnID)
	var i CardAuthTransaction
	err := row.Scan(
		&i.AuthID,
		&i.TxnID,
		&i.CardNumber,
		&i.MerchantID,
		&i.Amount,
		&i.Currency,
		&i.Mcc,
		&i.PosEntryMode,
		&i.Status,
		&i.IdempotencyKey,
		&i.RiskScore,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const toggleCardStatus = `-- name: ToggleCardStatus :one
UPDATE cards
SET status = CASE WHEN status = 'active' THEN 'suspended' ELSE 'active' END,
    updated_at = CURRENT_TIMESTAMP
WHERE card_id = $1 AND deleted_at IS NULL
RETURNING card_id, user_id, card_number, card_type, expire_date, cvv, card_provider,
          status, credit_limit, outstanding_balance, reward_points, created_at, updated_at
`

type ToggleCardStatusRow struct {
	CardID             int32            `json:"card_id"`
	UserID             int32            `json:"user_id"`
	CardNumber         string           `json:"card_number"`
	CardType           string           `json:"card_type"`
	ExpireDate         pgtype.Date      `json:"expire_date"`
	Cvv                string           `json:"cvv"`
	CardProvider       string           `json:"card_provider"`
	Status             string           `json:"status"`
	CreditLimit        int32            `json:"credit_limit"`
	OutstandingBalance int32            `json:"outstanding_balance"`
	RewardPoints       int32            `json:"reward_points"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) ToggleCardStatus(ctx context.Context, cardID int32) (*ToggleCardStatusRow, error) {
	row := q.db.QueryRow(ctx, toggleCardStatus, cardID)
	var i ToggleCardStatusRow
	err := row.Scan(
		&i.CardID,
		&i.UserID,
		&i.CardNumber,
		&i.CardType,
		&i.ExpireDate,
		&i.Cvv,
		&i.CardProvider,
		&i.Status,
		&i.CreditLimit,
		&i.OutstandingBalance,
		&i.RewardPoints,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const trashCard = `-- name: TrashCard :one
UPDATE cards
SET
    deleted_at = current_timestamp
WHERE
    card_id = $1
    AND deleted_at IS NULL
RETURNING
    card_id,
    user_id,
    card_number,
    card_type,
    expire_date,
    cvv,
    card_provider,
    created_at,
    updated_at,
    deleted_at
`

type TrashCardRow struct {
	CardID       int32            `json:"card_id"`
	UserID       int32            `json:"user_id"`
	CardNumber   string           `json:"card_number"`
	CardType     string           `json:"card_type"`
	ExpireDate   pgtype.Date      `json:"expire_date"`
	Cvv          string           `json:"cvv"`
	CardProvider string           `json:"card_provider"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	DeletedAt    pgtype.Timestamp `json:"deleted_at"`
}

// TrashCard: Soft-deletes a card by marking deleted_at
// Purpose: Temporarily remove a card without deleting it permanently
// Parameters:
//
//	$1: card_id - Identifier of the card to be trashed
//
// Returns: Nothing
// Business Logic:
//   - Sets deleted_at to current timestamp
//   - Only affects cards not already trashed
func (q *Queries) TrashCard(ctx context.Context, cardID int32) (*TrashCardRow, error) {
	row := q.db.QueryRow(ctx, trashCard, cardID)
	var i TrashCardRow
	err := row.Scan(
		&i.CardID,
		&i.UserID,
		&i.CardNumber,
		&i.CardType,
		&i.ExpireDate,
		&i.Cvv,
		&i.CardProvider,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const updateAuthTransactionRiskScore = `-- name: UpdateAuthTransactionRiskScore :exec
UPDATE card_auth_transactions
SET risk_score = $2, updated_at = CURRENT_TIMESTAMP
WHERE txn_id = $1
`

type UpdateAuthTransactionRiskScoreParams struct {
	TxnID     string `json:"txn_id"`
	RiskScore int32  `json:"risk_score"`
}

func (q *Queries) UpdateAuthTransactionRiskScore(ctx context.Context, arg UpdateAuthTransactionRiskScoreParams) error {
	_, err := q.db.Exec(ctx, updateAuthTransactionRiskScore, arg.TxnID, arg.RiskScore)
	return err
}

const updateBillingCycleStatus = `-- name: UpdateBillingCycleStatus :one
UPDATE billing_cycles
SET status = $2, updated_at = CURRENT_TIMESTAMP
WHERE billing_id = $1
RETURNING billing_id, card_number, cycle_start, cycle_end, amount_due, due_date,
          status, created_at, updated_at
`

type UpdateBillingCycleStatusParams struct {
	BillingID int32  `json:"billing_id"`
	Status    string `json:"status"`
}

func (q *Queries) UpdateBillingCycleStatus(ctx context.Context, arg UpdateBillingCycleStatusParams) (*BillingCycle, error) {
	row := q.db.QueryRow(ctx, updateBillingCycleStatus, arg.BillingID, arg.Status)
	var i BillingCycle
	err := row.Scan(
		&i.BillingID,
		&i.CardNumber,
		&i.CycleStart,
		&i.CycleEnd,
		&i.AmountDue,
		&i.DueDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateCard = `-- name: UpdateCard :one
UPDATE cards
SET
    card_type = $2,
    expire_date = $3,
    cvv = $4,
    card_provider = $5,
    updated_at = current_timestamp
WHERE
    card_id = $1
    AND deleted_at IS NULL
RETURNING
    card_id,
    user_id,
    card_number,
    card_type,
    expire_date,
    cvv,
    card_provider,
    created_at,
    updated_at
`

type UpdateCardParams struct {
	CardID       int32       `json:"card_id"`
	CardType     string      `json:"card_type"`
	ExpireDate   pgtype.Date `json:"expire_date"`
	Cvv          string      `json:"cvv"`
	CardProvider string      `json:"card_provider"`
}

type UpdateCardRow struct {
	CardID       int32            `json:"card_id"`
	UserID       int32            `json:"user_id"`
	CardNumber   string           `json:"card_number"`
	CardType     string           `json:"card_type"`
	ExpireDate   pgtype.Date      `json:"expire_date"`
	Cvv          string           `json:"cvv"`
	CardProvider string           `json:"card_provider"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

// UpdateCard: Updates an existing card's details
// Purpose: Modify card attributes for a specific card
// Parameters:
//
//	$1: card_id - Identifier of the card to update
//	$2: card_type - New card type
//	$3: expire_date - New expiration date
//	$4: cvv - New CVV
//	$5: card_provider - New card provider
//
// Returns: Nothing
// Business Logic:
//   - Automatically updates updated_at timestamp
//   - Only updates cards that are not soft-deleted
func (q *Queries) UpdateCard(ctx context.Context, arg UpdateCardParams) (*UpdateCardRow, error) {
	row := q.db.QueryRow(ctx, updateCard,
		arg.CardID,
		arg.CardType,
		arg.ExpireDate,
		arg.Cvv,
		arg.CardProvider,
	)
	var i UpdateCardRow
	err := row.Scan(
		&i.CardID,
		&i.UserID,
		&i.CardNumber,
		&i.CardType,
		&i.ExpireDate,
		&i.Cvv,
		&i.CardProvider,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateCardStatus = `-- name: UpdateCardStatus :one
UPDATE cards
SET status = $2, updated_at = CURRENT_TIMESTAMP
WHERE card_id = $1 AND deleted_at IS NULL
RETURNING card_id, user_id, card_number, card_type, expire_date, cvv, card_provider,
          status, credit_limit, outstanding_balance, reward_points, created_at, updated_at
`

type UpdateCardStatusParams struct {
	CardID int32  `json:"card_id"`
	Status string `json:"status"`
}

type UpdateCardStatusRow struct {
	CardID             int32            `json:"card_id"`
	UserID             int32            `json:"user_id"`
	CardNumber         string           `json:"card_number"`
	CardType           string           `json:"card_type"`
	ExpireDate         pgtype.Date      `json:"expire_date"`
	Cvv                string           `json:"cvv"`
	CardProvider       string           `json:"card_provider"`
	Status             string           `json:"status"`
	CreditLimit        int32            `json:"credit_limit"`
	OutstandingBalance int32            `json:"outstanding_balance"`
	RewardPoints       int32            `json:"reward_points"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) UpdateCardStatus(ctx context.Context, arg UpdateCardStatusParams) (*UpdateCardStatusRow, error) {
	row := q.db.QueryRow(ctx, updateCardStatus, arg.CardID, arg.Status)
	var i UpdateCardStatusRow
	err := row.Scan(
		&i.CardID,
		&i.UserID,
		&i.CardNumber,
		&i.CardType,
		&i.ExpireDate,
		&i.Cvv,
		&i.CardProvider,
		&i.Status,
		&i.CreditLimit,
		&i.OutstandingBalance,
		&i.RewardPoints,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateCreditLimit = `-- name: UpdateCreditLimit :one
UPDATE cards
SET credit_limit = $2, updated_at = CURRENT_TIMESTAMP
WHERE card_id = $1 AND deleted_at IS NULL
RETURNING card_id, user_id, card_number, card_type, expire_date, cvv, card_provider,
          status, credit_limit, outstanding_balance, reward_points, created_at, updated_at
`

type UpdateCreditLimitParams struct {
	CardID      int32 `json:"card_id"`
	CreditLimit int32 `json:"credit_limit"`
}

type UpdateCreditLimitRow struct {
	CardID             int32            `json:"card_id"`
	UserID             int32            `json:"user_id"`
	CardNumber         string           `json:"card_number"`
	CardType           string           `json:"card_type"`
	ExpireDate         pgtype.Date      `json:"expire_date"`
	Cvv                string           `json:"cvv"`
	CardProvider       string           `json:"card_provider"`
	Status             string           `json:"status"`
	CreditLimit        int32            `json:"credit_limit"`
	OutstandingBalance int32            `json:"outstanding_balance"`
	RewardPoints       int32            `json:"reward_points"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) UpdateCreditLimit(ctx context.Context, arg UpdateCreditLimitParams) (*UpdateCreditLimitRow, error) {
	row := q.db.QueryRow(ctx, updateCreditLimit, arg.CardID, arg.CreditLimit)
	var i UpdateCreditLimitRow
	err := row.Scan(
		&i.CardID,
		&i.UserID,
		&i.CardNumber,
		&i.CardType,
		&i.ExpireDate,
		&i.Cvv,
		&i.CardProvider,
		&i.Status,
		&i.CreditLimit,
		&i.OutstandingBalance,
		&i.RewardPoints,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
