// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type BillingCycle struct {
	BillingID  int32            `json:"billing_id"`
	CardNumber string           `json:"card_number"`
	CycleStart time.Time        `json:"cycle_start"`
	CycleEnd   time.Time        `json:"cycle_end"`
	AmountDue  int32            `json:"amount_due"`
	DueDate    time.Time        `json:"due_date"`
	Status     string           `json:"status"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

type Card struct {
	CardID             int32            `json:"card_id"`
	UserID             int32            `json:"user_id"`
	CardNumber         string           `json:"card_number"`
	CardType           string           `json:"card_type"`
	ExpireDate         pgtype.Date      `json:"expire_date"`
	Cvv                string           `json:"cvv"`
	CardProvider       string           `json:"card_provider"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	DeletedAt          pgtype.Timestamp `json:"deleted_at"`
	Status             string           `json:"status"`
	CreditLimit        int32            `json:"credit_limit"`
	OutstandingBalance int32            `json:"outstanding_balance"`
	RewardPoints       int32            `json:"reward_points"`
}

type CardAuthTransaction struct {
	AuthID         int32            `json:"auth_id"`
	TxnID          string           `json:"txn_id"`
	CardNumber     string           `json:"card_number"`
	MerchantID     int32            `json:"merchant_id"`
	Amount         int64            `json:"amount"`
	Currency       string           `json:"currency"`
	Mcc            string           `json:"mcc"`
	PosEntryMode   string           `json:"pos_entry_mode"`
	Status         string           `json:"status"`
	IdempotencyKey string           `json:"idempotency_key"`
	RiskScore      int32            `json:"risk_score"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

type CardPayment struct {
	PaymentID      int32            `json:"payment_id"`
	PaymentUuid    string           `json:"payment_uuid"`
	CardNumber     string           `json:"card_number"`
	BillingID      *int32           `json:"billing_id"`
	Amount         int64            `json:"amount"`
	PaymentChannel string           `json:"payment_channel"`
	ReferenceID    string           `json:"reference_id"`
	Status         string           `json:"status"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

type CardReward struct {
	RewardID     int32            `json:"reward_id"`
	CardNumber   string           `json:"card_number"`
	TxnID        string           `json:"txn_id"`
	Amount       int64            `json:"amount"`
	Mcc          string           `json:"mcc"`
	PointsEarned int32            `json:"points_earned"`
	ExpiresAt    time.Time        `json:"expires_at"`
	Redeemed     bool             `json:"redeemed"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

type Role struct {
	RoleID    int32            `json:"role_id"`
	RoleName  string           `json:"role_name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	DeletedAt pgtype.Timestamp `json:"deleted_at"`
}

type UserRole struct {
	UserRoleID int32            `json:"user_role_id"`
	UserID     int32            `json:"user_id"`
	RoleID     int32            `json:"role_id"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
	DeletedAt  pgtype.Timestamp `json:"deleted_at"`
}
