// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	ApproveAuthTransaction(ctx context.Context, txnID string) (*CardAuthTransaction, error)
	CountCardPayments(ctx context.Context, cardNumber string) (int32, error)
	CountRecentAuthByCardNumber(ctx context.Context, arg CountRecentAuthByCardNumberParams) (int32, error)
	// CreateBillingCycles creates one statement per active card for the period.
	// The unique period index makes retries and concurrent schedulers safe.
	CreateBillingCycles(ctx context.Context, arg CreateBillingCyclesParams) ([]*BillingCycle, error)
	// GetTotalBalance: Calculates the sum of all active card balances
	// Purpose: Get the total balance across all active cards in the system
	// Returns:
	//   Single column 'total_balance' containing the sum of all non-deleted card balances
	// Business Logic:
	//   - Only includes balances from active saldos records (s.deleted_at IS NULL)
	//   - Only includes balances from active cards (c.deleted_at IS NULL)
	//   - Useful for financial dashboards and system health monitoring
	//   - Returns NULL if no active balances exist
	CreateCard(ctx context.Context, arg CreateCardParams) (*CreateCardRow, error)
	// CreateRole: Inserts a new role into the system
	// Purpose: Add new role definitions (e.g., Admin, Cashier, etc.)
	// Parameters:
	//   $1: Role name
	// Returns:
	//   Newly created role's full data (including timestamps)
	CreateRole(ctx context.Context, roleName string) (*Role, error)
	DeclineAuthTransaction(ctx context.Context, txnID string) (*CardAuthTransaction, error)
	// DeleteAllPermanentCards: Permanently deletes all trashed cards
	// Purpose: Bulk-delete all cards that have been soft-deleted
	// Parameters: None
	// Returns: Nothing
	// Business Logic:
	//   - Deletes only cards with deleted_at set
	DeleteAllPermanentCards(ctx context.Context) error
	// DeleteAllPermanentRoles: Permanently deletes all soft-deleted roles
	// Purpose: Bulk cleanup of trashed roles
	// Parameters: None
	DeleteAllPermanentRoles(ctx context.Context) error
	// DeleteCardPermanently: Removes a trashed card from the database
	// Purpose: Permanently delete a card that has been soft-deleted
	// Parameters:
	//   $1: card_id - Identifier of the card to permanently delete
	// Returns: Nothing
	// Business Logic:
	//   - Only deletes cards that are currently trashed
	DeleteCardPermanently(ctx context.Context, cardID int32) error
	// DeletePermanentRole: Permanently deletes a trashed role
	// Purpose: Remove role from DB after soft delete
	// Parameters:
	//   $1: Role ID
	DeletePermanentRole(ctx context.Context, roleID int32) error
	GetActiveCardsWithCount(ctx context.Context, arg GetActiveCardsWithCountParams) ([]*GetActiveCardsWithCountRow, error)
	// GetActiveRoles: Retrieves only active (non-deleted) roles with optional search and pagination
	// Purpose: Display roles that are currently usable in the system
	// Parameters:
	//   $1: Search query (nullable)
	//   $2: Limit
	//   $3: Offset
	// Returns:
	//   role_id, role_name, timestamps, and total_count
	GetActiveRoles(ctx context.Context, arg GetActiveRolesParams) ([]*GetActiveRolesRow, error)
	GetAuthTransactionByIdempotencyKey(ctx context.Context, idempotencyKey string) (*CardAuthTransaction, error)
	GetAuthTransactionByTxnId(ctx context.Context, txnID string) (*CardAuthTransaction, error)
	GetAuthTransactionsByCardNumber(ctx context.Context, arg GetAuthTransactionsByCardNumberParams) ([]*GetAuthTransactionsByCardNumberRow, error)
	GetBillingCyclesByCardNumber(ctx context.Context, cardNumber string) ([]*BillingCycle, error)
	// GetCardByCardNumber: Retrieves a single active card by its card number
	// Purpose: Lookup card information using the physical card number
	// Parameters:
	//   $1: card_number - The exact card number to search for
	// Returns:
	//   All fields for the matching card or NULL if not found or deleted
	// Business Logic:
	//   - Only returns active cards (deleted_at IS NULL)
	//   - Performs exact match on card_number field (case-sensitive)
	//   - Useful for card verification during transactions
	GetCardByCardNumber(ctx context.Context, cardNumber string) (*GetCardByCardNumberRow, error)
	// GetCardByID: Retrieves a single card by its ID
	// Purpose: Get detailed information about a specific card
	// Parameters:
	//   $1: card_id - The ID of the card to retrieve
	// Returns:
	//   All fields for the specified card
	// Business Logic:
	//   - Only returns active cards (deleted_at IS NULL)
	//   - Returns NULL if card is not found or has been soft-deleted
	GetCardByID(ctx context.Context, cardID int32) (*GetCardByIDRow, error)
	// GetCardByUserID: Retrieves a single active card associated with a specific user
	// Purpose: Get the card information for a particular user
	// Parameters:
	//   $1: user_id - The ID of the user whose card should be retrieved
	// Returns:
	//   All fields for the user's card or NULL if no active card exists
	// Business Logic:
	//   - Only returns active cards (deleted_at IS NULL)
	//   - Returns at most one card (LIMIT 1) even if multiple cards exist for the user
	//   - Useful for displaying a user's primary/default card
	GetCardByUserID(ctx context.Context, userID int32) (*GetCardByUserIDRow, error)
	GetCardPaymentsByCardNumber(ctx context.Context, arg GetCardPaymentsByCardNumberParams) ([]*GetCardPaymentsByCardNumberRow, error)
	GetCardRewardBalance(ctx context.Context, cardNumber string) (int64, error)
	GetCardRewardHistory(ctx context.Context, cardNumber string) ([]*CardReward, error)
	// GetCards: Retrieves paginated list of active cards with search capability
	// Purpose: List all active cards for management UI
	// Parameters:
	//   $1: search_term - Optional text to filter cards by number, type or provider (NULL for no filter)
	//   $2: limit - Maximum number of records to return
	//   $3: offset - Number of records to skip for pagination
	// Returns:
	//   All card fields plus total_count of matching records
	// Business Logic:
	//   - Excludes soft-deleted cards (deleted_at IS NULL)
	//   - Supports partial text matching on card_number, card_type and card_provider fields (case-insensitive)
	//   - Returns cards ordered by card_id
	//   - Provides total_count for pagination calculations
	GetCards(ctx context.Context, arg GetCardsParams) ([]*GetCardsRow, error)
	GetRedeemableRewardIds(ctx context.Context, cardNumber string) ([]*GetRedeemableRewardIdsRow, error)
	// GetRole: Retrieves role details by role_id
	// Purpose: Fetch a single role record (regardless of deleted status)
	// Parameters:
	//   $1: Role ID
	// Returns:
	//   role_id, role_name, and timestamps
	GetRole(ctx context.Context, roleID int32) (*Role, error)
	// GetRoleByName: Retrieves role by exact role name
	// Purpose: Check role existence or fetch role info based on name
	// Parameters:
	//   $1: Role name (exact match)
	// Returns:
	//   role_id, role_name, and timestamps
	GetRoleByName(ctx context.Context, roleName string) (*Role, error)
	// GetRoles: Retrieves all roles (active & trashed) with optional name search and pagination
	// Purpose: General listing of roles regardless of status
	// Parameters:
	//   $1: Search query (role name, nullable)
	//   $2: Limit (number of records per page)
	//   $3: Offset (starting index for pagination)
	// Returns:
	//   role_id, role_name, timestamps, and total_count (for pagination support)
	// Business Logic:
	//   - Supports fuzzy search on role_name
	//   - Includes both active and trashed roles
	//   - Useful for admin panels with filters and pagination
	GetRoles(ctx context.Context, arg GetRolesParams) ([]*GetRolesRow, error)
	// GetTrashedCardByID: Retrieves a single soft-deleted card by its ID
	// Purpose: View details of a specific trashed card for recovery or audit
	// Parameters:
	//   $1: card_id - The ID of the card to retrieve
	// Returns:
	//   All fields for the specified trashed card or NULL if not found or not deleted
	// Business Logic:
	//   - Only returns soft-deleted cards (deleted_at IS NOT NULL)
	//   - Useful for admin interfaces showing deleted items
	//   - Can be used before restoring a deleted card
	GetTrashedCardByID(ctx context.Context, cardID int32) (*Card, error)
	// GetTrashedCardsWithCount: Retrieves paginated list of soft-deleted cards with search capability
	// Purpose: List all trashed (soft-deleted) cards for recovery or audit purposes
	// Parameters:
	//   $1: search_term - Optional text to filter cards by number, type or provider (NULL for no filter)
	//   $2: limit - Maximum number of records to return
	//   $3: offset - Number of records to skip for pagination
	// Returns:
	//   All card fields plus total_count of matching records
	// Business Logic:
	//   - Includes only soft-deleted cards (deleted_at IS NOT NULL)
	//   - Supports partial text matching on card_number, card_type and card_provider fields (case-insensitive)
	//   - Returns cards ordered by card_id
	//   - Provides total_count for pagination calculations
	GetTrashedCardsWithCount(ctx context.Context, arg GetTrashedCardsWithCountParams) ([]*GetTrashedCardsWithCountRow, error)
	// GetTrashedRoles: Retrieves only soft-deleted roles with optional search and pagination
	// Purpose: For trash/recycle bin management
	// Parameters:
	//   $1: Search query (nullable)
	//   $2: Limit
	//   $3: Offset
	// Returns:
	//   role_id, role_name, timestamps, and total_count
	GetTrashedRoles(ctx context.Context, arg GetTrashedRolesParams) ([]*GetTrashedRolesRow, error)
	// GetUserEmailByCardNumber: Retrieves an active card by number.
	// The card database owns cards, while user profile data lives in user_db.
	// Email is enriched by the card service through UserQueryService; do not join users here.
	GetUserEmailByCardNumber(ctx context.Context, cardNumber string) (*GetUserEmailByCardNumberRow, error)
	// GetUserRoles: Retrieves all roles assigned to a specific user
	// Purpose: Identify the access level(s) of a user
	// Parameters:
	//   $1: User ID
	// Returns:
	//   List of roles (id, name, timestamps)
	GetUserRoles(ctx context.Context, userID int32) ([]*Role, error)
	// InsertAuthTransaction: Creates an idempotent pending card authorization.
	InsertAuthTransaction(ctx context.Context, arg InsertAuthTransactionParams) (*CardAuthTransaction, error)
	InsertBillingCycle(ctx context.Context, arg InsertBillingCycleParams) (*BillingCycle, error)
	InsertCardPayment(ctx context.Context, arg InsertCardPaymentParams) (*CardPayment, error)
	InsertCardReward(ctx context.Context, arg InsertCardRewardParams) (*CardReward, error)
	MarkRewardsRedeemed(ctx context.Context, dollar_1 []int32) (int64, error)
	RedeemRewardPoints(ctx context.Context, arg RedeemRewardPointsParams) (*RedeemRewardPointsRow, error)
	// RestoreAllCards: Restores all trashed cards
	// Purpose: Bulk-restore all soft-deleted cards
	// Parameters: None
	// Returns: Nothing
	// Business Logic:
	//   - Sets deleted_at to NULL for all trashed cards
	RestoreAllCards(ctx context.Context) error
	// RestoreAllRoles: Restores all soft-deleted roles in bulk
	// Purpose: Bulk recovery of all trashed roles
	// Parameters: None
	RestoreAllRoles(ctx context.Context) error
	// RestoreCard: Restores a previously trashed card
	// Purpose: Undo soft-delete of a card
	// Parameters:
	//   $1: card_id - Identifier of the card to restore
	// Returns: Nothing
	// Business Logic:
	//   - Sets deleted_at to NULL
	//   - Only affects cards that are currently trashed
	RestoreCard(ctx context.Context, cardID int32) (*RestoreCardRow, error)
	// RestoreRole: Restores a previously trashed role
	// Purpose: Undelete a soft-deleted role
	// Parameters:
	//   $1: Role ID
	RestoreRole(ctx context.Context, roleID int32) (*Role, error)
	ReverseAuthTransaction(ctx context.Context, txnID string) (*CardAuthTransaction, error)
	ToggleCardStatus(ctx context.Context, cardID int32) (*ToggleCardStatusRow, error)
	// TrashCard: Soft-deletes a card by marking deleted_at
	// Purpose: Temporarily remove a card without deleting it permanently
	// Parameters:
	//   $1: card_id - Identifier of the card to be trashed
	// Returns: Nothing
	// Business Logic:
	//   - Sets deleted_at to current timestamp
	//   - Only affects cards not already trashed
	TrashCard(ctx context.Context, cardID int32) (*TrashCardRow, error)
	// TrashRole: Soft-deletes a role (moves to trash)
	// Purpose: Mark role as deleted without removing it permanently
	// Parameters:
	//   $1: Role ID
	TrashRole(ctx context.Context, roleID int32) (*Role, error)
	UpdateAuthTransactionRiskScore(ctx context.Context, arg UpdateAuthTransactionRiskScoreParams) error
	UpdateBillingCycleStatus(ctx context.Context, arg UpdateBillingCycleStatusParams) (*BillingCycle, error)
	// UpdateCard: Updates an existing card's details
	// Purpose: Modify card attributes for a specific card
	// Parameters:
	//   $1: card_id - Identifier of the card to update
	//   $2: card_type - New card type
	//   $3: expire_date - New expiration date
	//   $4: cvv - New CVV
	//   $5: card_provider - New card provider
	// Returns: Nothing
	// Business Logic:
	//   - Automatically updates updated_at timestamp
	//   - Only updates cards that are not soft-deleted
	UpdateCard(ctx context.Context, arg UpdateCardParams) (*UpdateCardRow, error)
	UpdateCardStatus(ctx context.Context, arg UpdateCardStatusParams) (*UpdateCardStatusRow, error)
	UpdateCreditLimit(ctx context.Context, arg UpdateCreditLimitParams) (*UpdateCreditLimitRow, error)
	// UpdateRole: Updates role name by ID
	// Purpose: Modify role information (e.g., name correction)
	// Parameters:
	//   $1: Role ID
	//   $2: New role name
	// Returns:
	//   Updated role's data
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (*Role, error)
}

var _ Querier = (*Queries)(nil)
