// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: saldo/saldo_query.proto

package saldo

import (
	card "github.com/MamangRust/microservice-payment-gateway-grpc/pb/card"
	common "github.com/MamangRust/microservice-payment-gateway-grpc/pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApiResponsePaginationSaldo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data           []*SaldoResponse       `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	PaginationMeta *common.PaginationMeta `protobuf:"bytes,4,opt,name=paginationMeta,proto3" json:"paginationMeta,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApiResponsePaginationSaldo) Reset() {
	*x = ApiResponsePaginationSaldo{}
	mi := &file_saldo_saldo_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationSaldo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationSaldo) ProtoMessage() {}

func (x *ApiResponsePaginationSaldo) ProtoReflect() protoreflect.Message {
	mi := &file_saldo_saldo_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationSaldo.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationSaldo) Descriptor() ([]byte, []int) {
	return file_saldo_saldo_query_proto_rawDescGZIP(), []int{0}
}

func (x *ApiResponsePaginationSaldo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationSaldo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationSaldo) GetData() []*SaldoResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationSaldo) GetPaginationMeta() *common.PaginationMeta {
	if x != nil {
		return x.PaginationMeta
	}
	return nil
}

type ApiResponsePaginationSaldoDeleteAt struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	Status         string                   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message        string                   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data           []*SaldoResponseDeleteAt `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	PaginationMeta *common.PaginationMeta   `protobuf:"bytes,4,opt,name=paginationMeta,proto3" json:"paginationMeta,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApiResponsePaginationSaldoDeleteAt) Reset() {
	*x = ApiResponsePaginationSaldoDeleteAt{}
	mi := &file_saldo_saldo_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationSaldoDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationSaldoDeleteAt) ProtoMessage() {}

func (x *ApiResponsePaginationSaldoDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_saldo_saldo_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationSaldoDeleteAt.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationSaldoDeleteAt) Descriptor() ([]byte, []int) {
	return file_saldo_saldo_query_proto_rawDescGZIP(), []int{1}
}

func (x *ApiResponsePaginationSaldoDeleteAt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationSaldoDeleteAt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationSaldoDeleteAt) GetData() []*SaldoResponseDeleteAt {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationSaldoDeleteAt) GetPaginationMeta() *common.PaginationMeta {
	if x != nil {
		return x.PaginationMeta
	}
	return nil
}

type ReconciliationMismatch struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SaldoId        int32                  `protobuf:"varint,1,opt,name=saldo_id,json=saldoId,proto3" json:"saldo_id,omitempty"`
	CardNumber     string                 `protobuf:"bytes,2,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	CurrentBalance int64                  `protobuf:"varint,3,opt,name=current_balance,json=currentBalance,proto3" json:"current_balance,omitempty"`
	LedgerBalance  int64                  `protobuf:"varint,4,opt,name=ledger_balance,json=ledgerBalance,proto3" json:"ledger_balance,omitempty"`
	Difference     int64                  `protobuf:"varint,5,opt,name=difference,proto3" json:"difference,omitempty"`
	LedgerEntries  int64                  `protobuf:"varint,6,opt,name=ledger_entries,json=ledgerEntries,proto3" json:"ledger_entries,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReconciliationMismatch) Reset() {
	*x = ReconciliationMismatch{}
	mi := &file_saldo_saldo_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconciliationMismatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconciliationMismatch) ProtoMessage() {}

func (x *ReconciliationMismatch) ProtoReflect() protoreflect.Message {
	mi := &file_saldo_saldo_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconciliationMismatch.ProtoReflect.Descriptor instead.
func (*ReconciliationMismatch) Descriptor() ([]byte, []int) {
	return file_saldo_saldo_query_proto_rawDescGZIP(), []int{2}
}

func (x *ReconciliationMismatch) GetSaldoId() int32 {
	if x != nil {
		return x.SaldoId
	}
	return 0
}

func (x *ReconciliationMismatch) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *ReconciliationMismatch) GetCurrentBalance() int64 {
	if x != nil {
		return x.CurrentBalance
	}
	return 0
}

func (x *ReconciliationMismatch) GetLedgerBalance() int64 {
	if x != nil {
		return x.LedgerBalance
	}
	return 0
}

func (x *ReconciliationMismatch) GetDifference() int64 {
	if x != nil {
		return x.Difference
	}
	return 0
}

func (x *ReconciliationMismatch) GetLedgerEntries() int64 {
	if x != nil {
		return x.LedgerEntries
	}
	return 0
}

type ReconciliationQueueItem struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	QueueId               int64                  `protobuf:"varint,1,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	SaldoId               int32                  `protobuf:"varint,2,opt,name=saldo_id,json=saldoId,proto3" json:"saldo_id,omitempty"`
	CardNumber            string                 `protobuf:"bytes,3,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	CurrentBalance        int64                  `protobuf:"varint,4,opt,name=current_balance,json=currentBalance,proto3" json:"current_balance,omitempty"`
	LedgerBalance         int64                  `protobuf:"varint,5,opt,name=ledger_balance,json=ledgerBalance,proto3" json:"ledger_balance,omitempty"`
	Difference            int64                  `protobuf:"varint,6,opt,name=difference,proto3" json:"difference,omitempty"`
	LedgerEntries         int64                  `protobuf:"varint,7,opt,name=ledger_entries,json=ledgerEntries,proto3" json:"ledger_entries,omitempty"`
	Status                string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	MismatchCount         int64                  `protobuf:"varint,9,opt,name=mismatch_count,json=mismatchCount,proto3" json:"mismatch_count,omitempty"`
	FirstSeenAt           string                 `protobuf:"bytes,10,opt,name=first_seen_at,json=firstSeenAt,proto3" json:"first_seen_at,omitempty"`
	LastSeenAt            string                 `protobuf:"bytes,11,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	ResolvedAt            string                 `protobuf:"bytes,12,opt,name=resolved_at,json=resolvedAt,proto3" json:"resolved_at,omitempty"`
	ResolutionOperationId string                 `protobuf:"bytes,13,opt,name=resolution_operation_id,json=resolutionOperationId,proto3" json:"resolution_operation_id,omitempty"`
	ResolutionNote        string                 `protobuf:"bytes,14,opt,name=resolution_note,json=resolutionNote,proto3" json:"resolution_note,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ReconciliationQueueItem) Reset() {
	*x = ReconciliationQueueItem{}
	mi := &file_saldo_saldo_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconciliationQueueItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconciliationQueueItem) ProtoMessage() {}

func (x *ReconciliationQueueItem) ProtoReflect() protoreflect.Message {
	mi := &file_saldo_saldo_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconciliationQueueItem.ProtoReflect.Descriptor instead.
func (*ReconciliationQueueItem) Descriptor() ([]byte, []int) {
	return file_saldo_saldo_query_proto_rawDescGZIP(), []int{3}
}

func (x *ReconciliationQueueItem) GetQueueId() int64 {
	if x != nil {
		return x.QueueId
	}
	return 0
}

func (x *ReconciliationQueueItem) GetSaldoId() int32 {
	if x != nil {
		return x.SaldoId
	}
	return 0
}

func (x *ReconciliationQueueItem) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *ReconciliationQueueItem) GetCurrentBalance() int64 {
	if x != nil {
		return x.CurrentBalance
	}
	return 0
}

func (x *ReconciliationQueueItem) GetLedgerBalance() int64 {
	if x != nil {
		return x.LedgerBalance
	}
	return 0
}

func (x *ReconciliationQueueItem) GetDifference() int64 {
	if x != nil {
		return x.Difference
	}
	return 0
}

func (x *ReconciliationQueueItem) GetLedgerEntries() int64 {
	if x != nil {
		return x.LedgerEntries
	}
	return 0
}

func (x *ReconciliationQueueItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReconciliationQueueItem) GetMismatchCount() int64 {
	if x != nil {
		return x.MismatchCount
	}
	return 0
}

func (x *ReconciliationQueueItem) GetFirstSeenAt() string {
	if x != nil {
		return x.FirstSeenAt
	}
	return ""
}

func (x *ReconciliationQueueItem) GetLastSeenAt() string {
	if x != nil {
		return x.LastSeenAt
	}
	return ""
}

func (x *ReconciliationQueueItem) GetResolvedAt() string {
	if x != nil {
		return x.ResolvedAt
	}
	return ""
}

func (x *ReconciliationQueueItem) GetResolutionOperationId() string {
	if x != nil {
		return x.ResolutionOperationId
	}
	return ""
}

func (x *ReconciliationQueueItem) GetResolutionNote() string {
	if x != nil {
		return x.ResolutionNote
	}
	return ""
}

type LedgerEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntryId       int64                  `protobuf:"varint,1,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	OperationId   string                 `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	CardNumber    string                 `protobuf:"bytes,3,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	Direction     string                 `protobuf:"bytes,4,opt,name=direction,proto3" json:"direction,omitempty"`
	Amount        int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Delta         int64                  `protobuf:"varint,6,opt,name=delta,proto3" json:"delta,omitempty"`
	BalanceBefore int64                  `protobuf:"varint,7,opt,name=balance_before,json=balanceBefore,proto3" json:"balance_before,omitempty"`
	BalanceAfter  int64                  `protobuf:"varint,8,opt,name=balance_after,json=balanceAfter,proto3" json:"balance_after,omitempty"`
	SourceType    string                 `protobuf:"bytes,9,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	SourceId      string                 `protobuf:"bytes,10,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerEntryResponse) Reset() {
	*x = LedgerEntryResponse{}
	mi := &file_saldo_saldo_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerEntryResponse) ProtoMessage() {}

func (x *LedgerEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_saldo_saldo_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerEntryResponse.ProtoReflect.Descriptor instead.
func (*LedgerEntryResponse) Descriptor() ([]byte, []int) {
	return file_saldo_saldo_query_proto_rawDescGZIP(), []int{4}
}

func (x *LedgerEntryResponse) GetEntryId() int64 {
	if x != nil {
		return x.EntryId
	}
	return 0
}

func (x *LedgerEntryResponse) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *LedgerEntryResponse) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *LedgerEntryResponse) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *LedgerEntryResponse) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *LedgerEntryResponse) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *LedgerEntryResponse) GetBalanceBefore() int64 {
	if x != nil {
		return x.BalanceBefore
	}
	return 0
}

func (x *LedgerEntryResponse) GetBalanceAfter() int64 {
	if x != nil {
		return x.BalanceAfter
	}
	return 0
}

func (x *LedgerEntryResponse) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *LedgerEntryResponse) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *LedgerEntryResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ApiResponseReconciliation struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Status        string                     `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*ReconciliationQueueItem `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseReconciliation) Reset() {
	*x = ApiResponseReconciliation{}
	mi := &file_saldo_saldo_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseReconciliation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseReconciliation) ProtoMessage() {}

func (x *ApiResponseReconciliation) ProtoReflect() protoreflect.Message {
	mi := &file_saldo_saldo_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseReconciliation.ProtoReflect.Descriptor instead.
func (*ApiResponseReconciliation) Descriptor() ([]byte, []int) {
	return file_saldo_saldo_query_proto_rawDescGZIP(), []int{5}
}

func (x *ApiResponseReconciliation) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseReconciliation) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseReconciliation) GetData() []*ReconciliationQueueItem {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseLedger struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*LedgerEntryResponse `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseLedger) Reset() {
	*x = ApiResponseLedger{}
	mi := &file_saldo_saldo_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseLedger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseLedger) ProtoMessage() {}

func (x *ApiResponseLedger) ProtoReflect() protoreflect.Message {
	mi := &file_saldo_saldo_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseLedger.ProtoReflect.Descriptor instead.
func (*ApiResponseLedger) Descriptor() ([]byte, []int) {
	return file_saldo_saldo_query_proto_rawDescGZIP(), []int{6}
}

func (x *ApiResponseLedger) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseLedger) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseLedger) GetData() []*LedgerEntryResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListReconciliationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReconciliationRequest) Reset() {
	*x = ListReconciliationRequest{}
	mi := &file_saldo_saldo_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReconciliationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReconciliationRequest) ProtoMessage() {}

func (x *ListReconciliationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_saldo_saldo_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReconciliationRequest.ProtoReflect.Descriptor instead.
func (*ListReconciliationRequest) Descriptor() ([]byte, []int) {
	return file_saldo_saldo_query_proto_rawDescGZIP(), []int{7}
}

func (x *ListReconciliationRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListReconciliationRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListLedgerEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardNumber    string                 `protobuf:"bytes,1,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLedgerEntriesRequest) Reset() {
	*x = ListLedgerEntriesRequest{}
	mi := &file_saldo_saldo_query_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLedgerEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLedgerEntriesRequest) ProtoMessage() {}

func (x *ListLedgerEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_saldo_saldo_query_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLedgerEntriesRequest.ProtoReflect.Descriptor instead.
func (*ListLedgerEntriesRequest) Descriptor() ([]byte, []int) {
	return file_saldo_saldo_query_proto_rawDescGZIP(), []int{8}
}

func (x *ListLedgerEntriesRequest) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *ListLedgerEntriesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_saldo_saldo_query_proto protoreflect.FileDescriptor

const file_saldo_saldo_query_proto_rawDesc = "" +
	"\n" +
	"\x17saldo/saldo_query.proto\x12\bpb.saldo\x1a\x10common/api.proto\x1a\x0fcard/card.proto\x1a\x11saldo/saldo.proto\"\xbe\x01\n" +
	"\x1aApiResponsePaginationSaldo\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x04data\x18\x03 \x03(\v2\x17.pb.saldo.SaldoResponseR\x04data\x12A\n" +
	"\x0epaginationMeta\x18\x04 \x01(\v2\x19.pb.common.PaginationMetaR\x0epaginationMeta\"\xce\x01\n" +
	"\"ApiResponsePaginationSaldoDeleteAt\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x123\n" +
	"\x04data\x18\x03 \x03(\v2\x1f.pb.saldo.SaldoResponseDeleteAtR\x04data\x12A\n" +
	"\x0epaginationMeta\x18\x04 \x01(\v2\x19.pb.common.PaginationMetaR\x0epaginationMeta\"\xeb\x01\n" +
	"\x16ReconciliationMismatch\x12\x19\n" +
	"\bsaldo_id\x18\x01 \x01(\x05R\asaldoId\x12\x1f\n" +
	"\vcard_number\x18\x02 \x01(\tR\n" +
	"cardNumber\x12'\n" +
	"\x0fcurrent_balance\x18\x03 \x01(\x03R\x0ecurrentBalance\x12%\n" +
	"\x0eledger_balance\x18\x04 \x01(\x03R\rledgerBalance\x12\x1e\n" +
	"\n" +
	"difference\x18\x05 \x01(\x03R\n" +
	"difference\x12%\n" +
	"\x0eledger_entries\x18\x06 \x01(\x03R\rledgerEntries\"\x8e\x04\n" +
	"\x17ReconciliationQueueItem\x12\x19\n" +
	"\bqueue_id\x18\x01 \x01(\x03R\aqueueId\x12\x19\n" +
	"\bsaldo_id\x18\x02 \x01(\x05R\asaldoId\x12\x1f\n" +
	"\vcard_number\x18\x03 \x01(\tR\n" +
	"cardNumber\x12'\n" +
	"\x0fcurrent_balance\x18\x04 \x01(\x03R\x0ecurrentBalance\x12%\n" +
	"\x0eledger_balance\x18\x05 \x01(\x03R\rledgerBalance\x12\x1e\n" +
	"\n" +
	"difference\x18\x06 \x01(\x03R\n" +
	"difference\x12%\n" +
	"\x0eledger_entries\x18\a \x01(\x03R\rledgerEntries\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12%\n" +
	"\x0emismatch_count\x18\t \x01(\x03R\rmismatchCount\x12\"\n" +
	"\rfirst_seen_at\x18\n" +
	" \x01(\tR\vfirstSeenAt\x12 \n" +
	"\flast_seen_at\x18\v \x01(\tR\n" +
	"lastSeenAt\x12\x1f\n" +
	"\vresolved_at\x18\f \x01(\tR\n" +
	"resolvedAt\x126\n" +
	"\x17resolution_operation_id\x18\r \x01(\tR\x15resolutionOperationId\x12'\n" +
	"\x0fresolution_note\x18\x0e \x01(\tR\x0eresolutionNote\"\xe9\x02\n" +
	"\x13LedgerEntryResponse\x12\x19\n" +
	"\bentry_id\x18\x01 \x01(\x03R\aentryId\x12!\n" +
	"\foperation_id\x18\x02 \x01(\tR\voperationId\x12\x1f\n" +
	"\vcard_number\x18\x03 \x01(\tR\n" +
	"cardNumber\x12\x1c\n" +
	"\tdirection\x18\x04 \x01(\tR\tdirection\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\x12\x14\n" +
	"\x05delta\x18\x06 \x01(\x03R\x05delta\x12%\n" +
	"\x0ebalance_before\x18\a \x01(\x03R\rbalanceBefore\x12#\n" +
	"\rbalance_after\x18\b \x01(\x03R\fbalanceAfter\x12\x1f\n" +
	"\vsource_type\x18\t \x01(\tR\n" +
	"sourceType\x12\x1b\n" +
	"\tsource_id\x18\n" +
	" \x01(\tR\bsourceId\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\"\x84\x01\n" +
	"\x19ApiResponseReconciliation\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x125\n" +
	"\x04data\x18\x03 \x03(\v2!.pb.saldo.ReconciliationQueueItemR\x04data\"x\n" +
	"\x11ApiResponseLedger\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x121\n" +
	"\x04data\x18\x03 \x03(\v2\x1d.pb.saldo.LedgerEntryResponseR\x04data\"I\n" +
	"\x19ListReconciliationRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"Q\n" +
	"\x18ListLedgerEntriesRequest\x12\x1f\n" +
	"\vcard_number\x18\x01 \x01(\tR\n" +
	"cardNumber\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit2\x8b\x05\n" +
	"\x11SaldoQueryService\x12U\n" +
	"\fFindAllSaldo\x12\x1d.pb.saldo.FindAllSaldoRequest\x1a$.pb.saldo.ApiResponsePaginationSaldo\"\x00\x12M\n" +
	"\rFindByIdSaldo\x12\x1e.pb.saldo.FindByIdSaldoRequest\x1a\x1a.pb.saldo.ApiResponseSaldo\"\x00\x12R\n" +
	"\x10FindByCardNumber\x12 .pb.card.FindByCardNumberRequest\x1a\x1a.pb.saldo.ApiResponseSaldo\"\x00\x12]\n" +
	"\fFindByActive\x12\x1d.pb.saldo.FindAllSaldoRequest\x1a,.pb.saldo.ApiResponsePaginationSaldoDeleteAt\"\x00\x12^\n" +
	"\rFindByTrashed\x12\x1d.pb.saldo.FindAllSaldoRequest\x1a,.pb.saldo.ApiResponsePaginationSaldoDeleteAt\"\x00\x12e\n" +
	"\x17ListReconciliationQueue\x12#.pb.saldo.ListReconciliationRequest\x1a#.pb.saldo.ApiResponseReconciliation\"\x00\x12V\n" +
	"\x11ListLedgerEntries\x12\".pb.saldo.ListLedgerEntriesRequest\x1a\x1b.pb.saldo.ApiResponseLedger\"\x00BBZ@github.com/MamangRust/microservice-payment-gateway-grpc/pb/saldob\x06proto3"

var (
	file_saldo_saldo_query_proto_rawDescOnce sync.Once
	file_saldo_saldo_query_proto_rawDescData []byte
)

func file_saldo_saldo_query_proto_rawDescGZIP() []byte {
	file_saldo_saldo_query_proto_rawDescOnce.Do(func() {
		file_saldo_saldo_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_saldo_saldo_query_proto_rawDesc), len(file_saldo_saldo_query_proto_rawDesc)))
	})
	return file_saldo_saldo_query_proto_rawDescData
}

var file_saldo_saldo_query_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_saldo_saldo_query_proto_goTypes = []any{
	(*ApiResponsePaginationSaldo)(nil),         // 0: pb.saldo.ApiResponsePaginationSaldo
	(*ApiResponsePaginationSaldoDeleteAt)(nil), // 1: pb.saldo.ApiResponsePaginationSaldoDeleteAt
	(*ReconciliationMismatch)(nil),             // 2: pb.saldo.ReconciliationMismatch
	(*ReconciliationQueueItem)(nil),            // 3: pb.saldo.ReconciliationQueueItem
	(*LedgerEntryResponse)(nil),                // 4: pb.saldo.LedgerEntryResponse
	(*ApiResponseReconciliation)(nil),          // 5: pb.saldo.ApiResponseReconciliation
	(*ApiResponseLedger)(nil),                  // 6: pb.saldo.ApiResponseLedger
	(*ListReconciliationRequest)(nil),          // 7: pb.saldo.ListReconciliationRequest
	(*ListLedgerEntriesRequest)(nil),           // 8: pb.saldo.ListLedgerEntriesRequest
	(*SaldoResponse)(nil),                      // 9: pb.saldo.SaldoResponse
	(*common.PaginationMeta)(nil),              // 10: pb.common.PaginationMeta
	(*SaldoResponseDeleteAt)(nil),              // 11: pb.saldo.SaldoResponseDeleteAt
	(*FindAllSaldoRequest)(nil),                // 12: pb.saldo.FindAllSaldoRequest
	(*FindByIdSaldoRequest)(nil),               // 13: pb.saldo.FindByIdSaldoRequest
	(*card.FindByCardNumberRequest)(nil),       // 14: pb.card.FindByCardNumberRequest
	(*ApiResponseSaldo)(nil),                   // 15: pb.saldo.ApiResponseSaldo
}
var file_saldo_saldo_query_proto_depIdxs = []int32{
	9,  // 0: pb.saldo.ApiResponsePaginationSaldo.data:type_name -> pb.saldo.SaldoResponse
	10, // 1: pb.saldo.ApiResponsePaginationSaldo.paginationMeta:type_name -> pb.common.PaginationMeta
	11, // 2: pb.saldo.ApiResponsePaginationSaldoDeleteAt.data:type_name -> pb.saldo.SaldoResponseDeleteAt
	10, // 3: pb.saldo.ApiResponsePaginationSaldoDeleteAt.paginationMeta:type_name -> pb.common.PaginationMeta
	3,  // 4: pb.saldo.ApiResponseReconciliation.data:type_name -> pb.saldo.ReconciliationQueueItem
	4,  // 5: pb.saldo.ApiResponseLedger.data:type_name -> pb.saldo.LedgerEntryResponse
	12, // 6: pb.saldo.SaldoQueryService.FindAllSaldo:input_type -> pb.saldo.FindAllSaldoRequest
	13, // 7: pb.saldo.SaldoQueryService.FindByIdSaldo:input_type -> pb.saldo.FindByIdSaldoRequest
	14, // 8: pb.saldo.SaldoQueryService.FindByCardNumber:input_type -> pb.card.FindByCardNumberRequest
	12, // 9: pb.saldo.SaldoQueryService.FindByActive:input_type -> pb.saldo.FindAllSaldoRequest
	12, // 10: pb.saldo.SaldoQueryService.FindByTrashed:input_type -> pb.saldo.FindAllSaldoRequest
	7,  // 11: pb.saldo.SaldoQueryService.ListReconciliationQueue:input_type -> pb.saldo.ListReconciliationRequest
	8,  // 12: pb.saldo.SaldoQueryService.ListLedgerEntries:input_type -> pb.saldo.ListLedgerEntriesRequest
	0,  // 13: pb.saldo.SaldoQueryService.FindAllSaldo:output_type -> pb.saldo.ApiResponsePaginationSaldo
	15, // 14: pb.saldo.SaldoQueryService.FindByIdSaldo:output_type -> pb.saldo.ApiResponseSaldo
	15, // 15: pb.saldo.SaldoQueryService.FindByCardNumber:output_type -> pb.saldo.ApiResponseSaldo
	1,  // 16: pb.saldo.SaldoQueryService.FindByActive:output_type -> pb.saldo.ApiResponsePaginationSaldoDeleteAt
	1,  // 17: pb.saldo.SaldoQueryService.FindByTrashed:output_type -> pb.saldo.ApiResponsePaginationSaldoDeleteAt
	5,  // 18: pb.saldo.SaldoQueryService.ListReconciliationQueue:output_type -> pb.saldo.ApiResponseReconciliation
	6,  // 19: pb.saldo.SaldoQueryService.ListLedgerEntries:output_type -> pb.saldo.ApiResponseLedger
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_saldo_saldo_query_proto_init() }
func file_saldo_saldo_query_proto_init() {
	if File_saldo_saldo_query_proto != nil {
		return
	}
	file_saldo_saldo_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_saldo_saldo_query_proto_rawDesc), len(file_saldo_saldo_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_saldo_saldo_query_proto_goTypes,
		DependencyIndexes: file_saldo_saldo_query_proto_depIdxs,
		MessageInfos:      file_saldo_saldo_query_proto_msgTypes,
	}.Build()
	File_saldo_saldo_query_proto = out.File
	file_saldo_saldo_query_proto_goTypes = nil
	file_saldo_saldo_query_proto_depIdxs = nil
}
