// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: saldo/saldo_command.proto

package saldo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSaldoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardNumber    string                 `protobuf:"bytes,1,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	TotalBalance  int64                  `protobuf:"varint,2,opt,name=total_balance,json=totalBalance,proto3" json:"total_balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSaldoRequest) Reset() {
	*x = CreateSaldoRequest{}
	mi := &file_saldo_saldo_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSaldoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSaldoRequest) ProtoMessage() {}

func (x *CreateSaldoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_saldo_saldo_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSaldoRequest.ProtoReflect.Descriptor instead.
func (*CreateSaldoRequest) Descriptor() ([]byte, []int) {
	return file_saldo_saldo_command_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSaldoRequest) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *CreateSaldoRequest) GetTotalBalance() int64 {
	if x != nil {
		return x.TotalBalance
	}
	return 0
}

type UpdateSaldoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SaldoId       int32                  `protobuf:"varint,1,opt,name=saldo_id,json=saldoId,proto3" json:"saldo_id,omitempty"`
	CardNumber    string                 `protobuf:"bytes,2,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	TotalBalance  int64                  `protobuf:"varint,3,opt,name=total_balance,json=totalBalance,proto3" json:"total_balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSaldoRequest) Reset() {
	*x = UpdateSaldoRequest{}
	mi := &file_saldo_saldo_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSaldoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSaldoRequest) ProtoMessage() {}

func (x *UpdateSaldoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_saldo_saldo_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSaldoRequest.ProtoReflect.Descriptor instead.
func (*UpdateSaldoRequest) Descriptor() ([]byte, []int) {
	return file_saldo_saldo_command_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateSaldoRequest) GetSaldoId() int32 {
	if x != nil {
		return x.SaldoId
	}
	return 0
}

func (x *UpdateSaldoRequest) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *UpdateSaldoRequest) GetTotalBalance() int64 {
	if x != nil {
		return x.TotalBalance
	}
	return 0
}

type ApiResponseSaldoDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseSaldoDelete) Reset() {
	*x = ApiResponseSaldoDelete{}
	mi := &file_saldo_saldo_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseSaldoDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseSaldoDelete) ProtoMessage() {}

func (x *ApiResponseSaldoDelete) ProtoReflect() protoreflect.Message {
	mi := &file_saldo_saldo_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseSaldoDelete.ProtoReflect.Descriptor instead.
func (*ApiResponseSaldoDelete) Descriptor() ([]byte, []int) {
	return file_saldo_saldo_command_proto_rawDescGZIP(), []int{2}
}

func (x *ApiResponseSaldoDelete) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseSaldoDelete) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApiResponseSaldoAll struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseSaldoAll) Reset() {
	*x = ApiResponseSaldoAll{}
	mi := &file_saldo_saldo_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseSaldoAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseSaldoAll) ProtoMessage() {}

func (x *ApiResponseSaldoAll) ProtoReflect() protoreflect.Message {
	mi := &file_saldo_saldo_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseSaldoAll.ProtoReflect.Descriptor instead.
func (*ApiResponseSaldoAll) Descriptor() ([]byte, []int) {
	return file_saldo_saldo_command_proto_rawDescGZIP(), []int{3}
}

func (x *ApiResponseSaldoAll) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseSaldoAll) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateSaldoWithdrawRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CardNumber     string                 `protobuf:"bytes,1,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	TotalBalance   int64                  `protobuf:"varint,2,opt,name=total_balance,json=totalBalance,proto3" json:"total_balance,omitempty"`
	WithdrawTime   string                 `protobuf:"bytes,3,opt,name=withdraw_time,json=withdrawTime,proto3" json:"withdraw_time,omitempty"`
	WithdrawAmount int64                  `protobuf:"varint,4,opt,name=withdraw_amount,json=withdrawAmount,proto3" json:"withdraw_amount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateSaldoWithdrawRequest) Reset() {
	*x = UpdateSaldoWithdrawRequest{}
	mi := &file_saldo_saldo_command_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSaldoWithdrawRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSaldoWithdrawRequest) ProtoMessage() {}

func (x *UpdateSaldoWithdrawRequest) ProtoReflect() protoreflect.Message {
	mi := &file_saldo_saldo_command_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSaldoWithdrawRequest.ProtoReflect.Descriptor instead.
func (*UpdateSaldoWithdrawRequest) Descriptor() ([]byte, []int) {
	return file_saldo_saldo_command_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateSaldoWithdrawRequest) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *UpdateSaldoWithdrawRequest) GetTotalBalance() int64 {
	if x != nil {
		return x.TotalBalance
	}
	return 0
}

func (x *UpdateSaldoWithdrawRequest) GetWithdrawTime() string {
	if x != nil {
		return x.WithdrawTime
	}
	return ""
}

func (x *UpdateSaldoWithdrawRequest) GetWithdrawAmount() int64 {
	if x != nil {
		return x.WithdrawAmount
	}
	return 0
}

type DebitSaldoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardNumber    string                 `protobuf:"bytes,1,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	OperationId   string                 `protobuf:"bytes,3,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	SourceType    string                 `protobuf:"bytes,4,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	SourceId      string                 `protobuf:"bytes,5,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebitSaldoRequest) Reset() {
	*x = DebitSaldoRequest{}
	mi := &file_saldo_saldo_command_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebitSaldoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebitSaldoRequest) ProtoMessage() {}

func (x *DebitSaldoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_saldo_saldo_command_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebitSaldoRequest.ProtoReflect.Descriptor instead.
func (*DebitSaldoRequest) Descriptor() ([]byte, []int) {
	return file_saldo_saldo_command_proto_rawDescGZIP(), []int{5}
}

func (x *DebitSaldoRequest) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *DebitSaldoRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DebitSaldoRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *DebitSaldoRequest) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *DebitSaldoRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

type CreditSaldoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardNumber    string                 `protobuf:"bytes,1,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	OperationId   string                 `protobuf:"bytes,3,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	SourceType    string                 `protobuf:"bytes,4,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	SourceId      string                 `protobuf:"bytes,5,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreditSaldoRequest) Reset() {
	*x = CreditSaldoRequest{}
	mi := &file_saldo_saldo_command_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreditSaldoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditSaldoRequest) ProtoMessage() {}

func (x *CreditSaldoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_saldo_saldo_command_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditSaldoRequest.ProtoReflect.Descriptor instead.
func (*CreditSaldoRequest) Descriptor() ([]byte, []int) {
	return file_saldo_saldo_command_proto_rawDescGZIP(), []int{6}
}

func (x *CreditSaldoRequest) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *CreditSaldoRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreditSaldoRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *CreditSaldoRequest) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *CreditSaldoRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

type ApplySaldoAdjustmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardNumber    string                 `protobuf:"bytes,1,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	Delta         int64                  `protobuf:"varint,2,opt,name=delta,proto3" json:"delta,omitempty"`
	OperationId   string                 `protobuf:"bytes,3,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	SourceType    string                 `protobuf:"bytes,4,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	SourceId      string                 `protobuf:"bytes,5,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Note          string                 `protobuf:"bytes,6,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplySaldoAdjustmentRequest) Reset() {
	*x = ApplySaldoAdjustmentRequest{}
	mi := &file_saldo_saldo_command_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplySaldoAdjustmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplySaldoAdjustmentRequest) ProtoMessage() {}

func (x *ApplySaldoAdjustmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_saldo_saldo_command_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplySaldoAdjustmentRequest.ProtoReflect.Descriptor instead.
func (*ApplySaldoAdjustmentRequest) Descriptor() ([]byte, []int) {
	return file_saldo_saldo_command_proto_rawDescGZIP(), []int{7}
}

func (x *ApplySaldoAdjustmentRequest) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *ApplySaldoAdjustmentRequest) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *ApplySaldoAdjustmentRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *ApplySaldoAdjustmentRequest) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *ApplySaldoAdjustmentRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *ApplySaldoAdjustmentRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type ApiResponseAdjustment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *SaldoResponse         `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseAdjustment) Reset() {
	*x = ApiResponseAdjustment{}
	mi := &file_saldo_saldo_command_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseAdjustment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseAdjustment) ProtoMessage() {}

func (x *ApiResponseAdjustment) ProtoReflect() protoreflect.Message {
	mi := &file_saldo_saldo_command_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseAdjustment.ProtoReflect.Descriptor instead.
func (*ApiResponseAdjustment) Descriptor() ([]byte, []int) {
	return file_saldo_saldo_command_proto_rawDescGZIP(), []int{8}
}

func (x *ApiResponseAdjustment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseAdjustment) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseAdjustment) GetData() *SaldoResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ResolveReconciliationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueId       int64                  `protobuf:"varint,1,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	OperationId   string                 `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Note          string                 `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveReconciliationRequest) Reset() {
	*x = ResolveReconciliationRequest{}
	mi := &file_saldo_saldo_command_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveReconciliationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveReconciliationRequest) ProtoMessage() {}

func (x *ResolveReconciliationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_saldo_saldo_command_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveReconciliationRequest.ProtoReflect.Descriptor instead.
func (*ResolveReconciliationRequest) Descriptor() ([]byte, []int) {
	return file_saldo_saldo_command_proto_rawDescGZIP(), []int{9}
}

func (x *ResolveReconciliationRequest) GetQueueId() int64 {
	if x != nil {
		return x.QueueId
	}
	return 0
}

func (x *ResolveReconciliationRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *ResolveReconciliationRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

var File_saldo_saldo_command_proto protoreflect.FileDescriptor

const file_saldo_saldo_command_proto_rawDesc = "" +
	"\n" +
	"\x19saldo/saldo_command.proto\x12\bpb.saldo\x1a\x11saldo/saldo.proto\x1a\x1bgoogle/protobuf/empty.proto\"Z\n" +
	"\x12CreateSaldoRequest\x12\x1f\n" +
	"\vcard_number\x18\x01 \x01(\tR\n" +
	"cardNumber\x12#\n" +
	"\rtotal_balance\x18\x02 \x01(\x03R\ftotalBalance\"u\n" +
	"\x12UpdateSaldoRequest\x12\x19\n" +
	"\bsaldo_id\x18\x01 \x01(\x05R\asaldoId\x12\x1f\n" +
	"\vcard_number\x18\x02 \x01(\tR\n" +
	"cardNumber\x12#\n" +
	"\rtotal_balance\x18\x03 \x01(\x03R\ftotalBalance\"J\n" +
	"\x16ApiResponseSaldoDelete\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"G\n" +
	"\x13ApiResponseSaldoAll\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb0\x01\n" +
	"\x1aUpdateSaldoWithdrawRequest\x12\x1f\n" +
	"\vcard_number\x18\x01 \x01(\tR\n" +
	"cardNumber\x12#\n" +
	"\rtotal_balance\x18\x02 \x01(\x03R\ftotalBalance\x12#\n" +
	"\rwithdraw_time\x18\x03 \x01(\tR\fwithdrawTime\x12'\n" +
	"\x0fwithdraw_amount\x18\x04 \x01(\x03R\x0ewithdrawAmount\"\xad\x01\n" +
	"\x11DebitSaldoRequest\x12\x1f\n" +
	"\vcard_number\x18\x01 \x01(\tR\n" +
	"cardNumber\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12!\n" +
	"\foperation_id\x18\x03 \x01(\tR\voperationId\x12\x1f\n" +
	"\vsource_type\x18\x04 \x01(\tR\n" +
	"sourceType\x12\x1b\n" +
	"\tsource_id\x18\x05 \x01(\tR\bsourceId\"\xae\x01\n" +
	"\x12CreditSaldoRequest\x12\x1f\n" +
	"\vcard_number\x18\x01 \x01(\tR\n" +
	"cardNumber\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12!\n" +
	"\foperation_id\x18\x03 \x01(\tR\voperationId\x12\x1f\n" +
	"\vsource_type\x18\x04 \x01(\tR\n" +
	"sourceType\x12\x1b\n" +
	"\tsource_id\x18\x05 \x01(\tR\bsourceId\"\xc9\x01\n" +
	"\x1bApplySaldoAdjustmentRequest\x12\x1f\n" +
	"\vcard_number\x18\x01 \x01(\tR\n" +
	"cardNumber\x12\x14\n" +
	"\x05delta\x18\x02 \x01(\x03R\x05delta\x12!\n" +
	"\foperation_id\x18\x03 \x01(\tR\voperationId\x12\x1f\n" +
	"\vsource_type\x18\x04 \x01(\tR\n" +
	"sourceType\x12\x1b\n" +
	"\tsource_id\x18\x05 \x01(\tR\bsourceId\x12\x12\n" +
	"\x04note\x18\x06 \x01(\tR\x04note\"v\n" +
	"\x15ApiResponseAdjustment\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x04data\x18\x03 \x01(\v2\x17.pb.saldo.SaldoResponseR\x04data\"p\n" +
	"\x1cResolveReconciliationRequest\x12\x19\n" +
	"\bqueue_id\x18\x01 \x01(\x03R\aqueueId\x12!\n" +
	"\foperation_id\x18\x02 \x01(\tR\voperationId\x12\x12\n" +
	"\x04note\x18\x03 \x01(\tR\x04note2\x86\b\n" +
	"\x13SaldoCommandService\x12I\n" +
	"\vCreateSaldo\x12\x1c.pb.saldo.CreateSaldoRequest\x1a\x1a.pb.saldo.ApiResponseSaldo\"\x00\x12I\n" +
	"\vUpdateSaldo\x12\x1c.pb.saldo.UpdateSaldoRequest\x1a\x1a.pb.saldo.ApiResponseSaldo\"\x00\x12Y\n" +
	"\x13UpdateSaldoWithdraw\x12$.pb.saldo.UpdateSaldoWithdrawRequest\x1a\x1a.pb.saldo.ApiResponseSaldo\"\x00\x12G\n" +
	"\n" +
	"DebitSaldo\x12\x1b.pb.saldo.DebitSaldoRequest\x1a\x1a.pb.saldo.ApiResponseSaldo\"\x00\x12I\n" +
	"\vCreditSaldo\x12\x1c.pb.saldo.CreditSaldoRequest\x1a\x1a.pb.saldo.ApiResponseSaldo\"\x00\x12`\n" +
	"\x14ApplySaldoAdjustment\x12%.pb.saldo.ApplySaldoAdjustmentRequest\x1a\x1f.pb.saldo.ApiResponseAdjustment\"\x00\x12`\n" +
	"\x15ResolveReconciliation\x12&.pb.saldo.ResolveReconciliationRequest\x1a\x1d.pb.saldo.ApiResponseSaldoAll\"\x00\x12T\n" +
	"\fTrashedSaldo\x12\x1e.pb.saldo.FindByIdSaldoRequest\x1a\".pb.saldo.ApiResponseSaldoDeleteAt\"\x00\x12T\n" +
	"\fRestoreSaldo\x12\x1e.pb.saldo.FindByIdSaldoRequest\x1a\".pb.saldo.ApiResponseSaldoDeleteAt\"\x00\x12Z\n" +
	"\x14DeleteSaldoPermanent\x12\x1e.pb.saldo.FindByIdSaldoRequest\x1a .pb.saldo.ApiResponseSaldoDelete\"\x00\x12J\n" +
	"\x0fRestoreAllSaldo\x12\x16.google.protobuf.Empty\x1a\x1d.pb.saldo.ApiResponseSaldoAll\"\x00\x12R\n" +
	"\x17DeleteAllSaldoPermanent\x12\x16.google.protobuf.Empty\x1a\x1d.pb.saldo.ApiResponseSaldoAll\"\x00BBZ@github.com/MamangRust/microservice-payment-gateway-grpc/pb/saldob\x06proto3"

var (
	file_saldo_saldo_command_proto_rawDescOnce sync.Once
	file_saldo_saldo_command_proto_rawDescData []byte
)

func file_saldo_saldo_command_proto_rawDescGZIP() []byte {
	file_saldo_saldo_command_proto_rawDescOnce.Do(func() {
		file_saldo_saldo_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_saldo_saldo_command_proto_rawDesc), len(file_saldo_saldo_command_proto_rawDesc)))
	})
	return file_saldo_saldo_command_proto_rawDescData
}

var file_saldo_saldo_command_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_saldo_saldo_command_proto_goTypes = []any{
	(*CreateSaldoRequest)(nil),           // 0: pb.saldo.CreateSaldoRequest
	(*UpdateSaldoRequest)(nil),           // 1: pb.saldo.UpdateSaldoRequest
	(*ApiResponseSaldoDelete)(nil),       // 2: pb.saldo.ApiResponseSaldoDelete
	(*ApiResponseSaldoAll)(nil),          // 3: pb.saldo.ApiResponseSaldoAll
	(*UpdateSaldoWithdrawRequest)(nil),   // 4: pb.saldo.UpdateSaldoWithdrawRequest
	(*DebitSaldoRequest)(nil),            // 5: pb.saldo.DebitSaldoRequest
	(*CreditSaldoRequest)(nil),           // 6: pb.saldo.CreditSaldoRequest
	(*ApplySaldoAdjustmentRequest)(nil),  // 7: pb.saldo.ApplySaldoAdjustmentRequest
	(*ApiResponseAdjustment)(nil),        // 8: pb.saldo.ApiResponseAdjustment
	(*ResolveReconciliationRequest)(nil), // 9: pb.saldo.ResolveReconciliationRequest
	(*SaldoResponse)(nil),                // 10: pb.saldo.SaldoResponse
	(*FindByIdSaldoRequest)(nil),         // 11: pb.saldo.FindByIdSaldoRequest
	(*emptypb.Empty)(nil),                // 12: google.protobuf.Empty
	(*ApiResponseSaldo)(nil),             // 13: pb.saldo.ApiResponseSaldo
	(*ApiResponseSaldoDeleteAt)(nil),     // 14: pb.saldo.ApiResponseSaldoDeleteAt
}
var file_saldo_saldo_command_proto_depIdxs = []int32{
	10, // 0: pb.saldo.ApiResponseAdjustment.data:type_name -> pb.saldo.SaldoResponse
	0,  // 1: pb.saldo.SaldoCommandService.CreateSaldo:input_type -> pb.saldo.CreateSaldoRequest
	1,  // 2: pb.saldo.SaldoCommandService.UpdateSaldo:input_type -> pb.saldo.UpdateSaldoRequest
	4,  // 3: pb.saldo.SaldoCommandService.UpdateSaldoWithdraw:input_type -> pb.saldo.UpdateSaldoWithdrawRequest
	5,  // 4: pb.saldo.SaldoCommandService.DebitSaldo:input_type -> pb.saldo.DebitSaldoRequest
	6,  // 5: pb.saldo.SaldoCommandService.CreditSaldo:input_type -> pb.saldo.CreditSaldoRequest
	7,  // 6: pb.saldo.SaldoCommandService.ApplySaldoAdjustment:input_type -> pb.saldo.ApplySaldoAdjustmentRequest
	9,  // 7: pb.saldo.SaldoCommandService.ResolveReconciliation:input_type -> pb.saldo.ResolveReconciliationRequest
	11, // 8: pb.saldo.SaldoCommandService.TrashedSaldo:input_type -> pb.saldo.FindByIdSaldoRequest
	11, // 9: pb.saldo.SaldoCommandService.RestoreSaldo:input_type -> pb.saldo.FindByIdSaldoRequest
	11, // 10: pb.saldo.SaldoCommandService.DeleteSaldoPermanent:input_type -> pb.saldo.FindByIdSaldoRequest
	12, // 11: pb.saldo.SaldoCommandService.RestoreAllSaldo:input_type -> google.protobuf.Empty
	12, // 12: pb.saldo.SaldoCommandService.DeleteAllSaldoPermanent:input_type -> google.protobuf.Empty
	13, // 13: pb.saldo.SaldoCommandService.CreateSaldo:output_type -> pb.saldo.ApiResponseSaldo
	13, // 14: pb.saldo.SaldoCommandService.UpdateSaldo:output_type -> pb.saldo.ApiResponseSaldo
	13, // 15: pb.saldo.SaldoCommandService.UpdateSaldoWithdraw:output_type -> pb.saldo.ApiResponseSaldo
	13, // 16: pb.saldo.SaldoCommandService.DebitSaldo:output_type -> pb.saldo.ApiResponseSaldo
	13, // 17: pb.saldo.SaldoCommandService.CreditSaldo:output_type -> pb.saldo.ApiResponseSaldo
	8,  // 18: pb.saldo.SaldoCommandService.ApplySaldoAdjustment:output_type -> pb.saldo.ApiResponseAdjustment
	3,  // 19: pb.saldo.SaldoCommandService.ResolveReconciliation:output_type -> pb.saldo.ApiResponseSaldoAll
	14, // 20: pb.saldo.SaldoCommandService.TrashedSaldo:output_type -> pb.saldo.ApiResponseSaldoDeleteAt
	14, // 21: pb.saldo.SaldoCommandService.RestoreSaldo:output_type -> pb.saldo.ApiResponseSaldoDeleteAt
	2,  // 22: pb.saldo.SaldoCommandService.DeleteSaldoPermanent:output_type -> pb.saldo.ApiResponseSaldoDelete
	3,  // 23: pb.saldo.SaldoCommandService.RestoreAllSaldo:output_type -> pb.saldo.ApiResponseSaldoAll
	3,  // 24: pb.saldo.SaldoCommandService.DeleteAllSaldoPermanent:output_type -> pb.saldo.ApiResponseSaldoAll
	13, // [13:25] is the sub-list for method output_type
	1,  // [1:13] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_saldo_saldo_command_proto_init() }
func file_saldo_saldo_command_proto_init() {
	if File_saldo_saldo_command_proto != nil {
		return
	}
	file_saldo_saldo_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_saldo_saldo_command_proto_rawDesc), len(file_saldo_saldo_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_saldo_saldo_command_proto_goTypes,
		DependencyIndexes: file_saldo_saldo_command_proto_depIdxs,
		MessageInfos:      file_saldo_saldo_command_proto_msgTypes,
	}.Build()
	File_saldo_saldo_command_proto = out.File
	file_saldo_saldo_command_proto_goTypes = nil
	file_saldo_saldo_command_proto_depIdxs = nil
}
