// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"time"
)

type Querier interface {
	// CreateRole: Inserts a new role into the system
	// Purpose: Add new role definitions (e.g., Admin, Cashier, etc.)
	// Parameters:
	//   $1: Role name
	// Returns:
	//   Newly created role's full data (including timestamps)
	CreateRole(ctx context.Context, roleName string) (*Role, error)
	// CreateTransaction: Creates a new transaction record
	// Purpose: Record a financial transaction in the system
	// Parameters:
	//   $1: card_number - The card used for the transaction
	//   $2: amount - The transaction amount
	//   $3: payment_method - Payment method used (e.g., 'credit', 'debit')
	//   $4: merchant_id - ID of the merchant where transaction occurred
	//   $5: transaction_time - Timestamp of when transaction occurred
	// Returns:
	//   The newly created transaction record with all fields
	// Business Logic:
	//   - Sets creation and update timestamps automatically
	//   - Used for recording purchases, payments, and other financial activities
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (*CreateTransactionRow, error)
	// DeleteAllPermanentRoles: Permanently deletes all soft-deleted roles
	// Purpose: Bulk cleanup of trashed roles
	// Parameters: None
	DeleteAllPermanentRoles(ctx context.Context) error
	// DeleteAllPermanentTransactions: Permanently removes all trashed transactions
	// Purpose: Clean up all soft-deleted transaction records
	// Business Logic:
	//   - Irreversible bulk deletion
	//   - Only affects records marked as deleted
	//   - Frees database space from old records
	//   - Typically used during maintenance periods
	DeleteAllPermanentTransactions(ctx context.Context) error
	// DeletePermanentRole: Permanently deletes a trashed role
	// Purpose: Remove role from DB after soft delete
	// Parameters:
	//   $1: Role ID
	DeletePermanentRole(ctx context.Context, roleID int32) error
	// DeleteTransactionPermanently: Hard-deletes a trashed transaction
	// Purpose: Permanently remove a transaction from the system
	// Parameters:
	//   $1: transaction_id - ID of transaction to delete
	// Business Logic:
	//   - Physical deletion from database
	//   - Only works on already trashed records
	//   - Irreversible operation
	//   - Used for data cleanup after retention period
	DeleteTransactionPermanently(ctx context.Context, transactionID int32) error
	// GetActiveRoles: Retrieves only active (non-deleted) roles with optional search and pagination
	// Purpose: Display roles that are currently usable in the system
	// Parameters:
	//   $1: Search query (nullable)
	//   $2: Limit
	//   $3: Offset
	// Returns:
	//   role_id, role_name, timestamps, and total_count
	GetActiveRoles(ctx context.Context, arg GetActiveRolesParams) ([]*GetActiveRolesRow, error)
	// GetActiveTransactions: Retrieves paginated active transactions with search
	// Purpose: List all non-deleted transactions with filtering options
	// Parameters:
	//   $1: search_term - Optional text to filter by card number or payment method
	//   $2: limit - Maximum records to return
	//   $3: offset - Records to skip for pagination
	// Returns:
	//   All transaction fields plus total_count of matching active records
	// Business Logic:
	//   - Only includes active transactions (deleted_at IS NULL)
	//   - Filters on card_number and payment_method fields
	//   - Orders by transaction_time (newest first)
	//   - Provides pagination metadata
	//   - Used in transaction management interfaces
	GetActiveTransactions(ctx context.Context, arg GetActiveTransactionsParams) ([]*GetActiveTransactionsRow, error)
	// GetMonthTransactionStatusFailed: Retrieves monthly failed metrics for transactions
	// Purpose: Analyze failedful transaction trends across comparison periods
	// Parameters:
	//   $1: period1_start - Start date of first comparison period
	//   $2: period1_end - End date of first comparison period
	//   $3: period2_start - Start date of second comparison period
	//   $4: period2_end - End date of second comparison period
	// Returns:
	//   year: Year as text (e.g., '2023')
	//   month: 3-letter month abbreviation (e.g., 'Jan')
	//   total_failed: Count of failedful transactions
	//   total_amount: Sum of failedful transaction amounts
	// Business Logic:
	//   - Only includes failedful transactions (status = 'failed')
	//   - Covers two customizable time periods for comparison
	//   - Zero-fills months with no activity
	//   - Formats output for consistent visualization (year as text, month as 'Mon')
	//   - Orders by year and month (newest first)
	//   - Useful for identifying seasonal transaction patterns and revenue trends
	GetMonthTransactionStatusFailed(ctx context.Context, arg GetMonthTransactionStatusFailedParams) ([]*GetMonthTransactionStatusFailedRow, error)
	// GetMonthTransactionStatusFailed: Retrieves monthly failed metrics for transactions
	// Purpose: Analyze failedful transaction trends across comparison periods
	// Parameters:
	//   $1: card_number  - filter by card_number
	//   $2: period1_start - Start date of first comparison period
	//   $3: period1_end - End date of first comparison period
	//   $4: period2_start - Start date of second comparison period
	//   $5: period2_end - End date of second comparison period
	// Returns:
	//   year: Year as text (e.g., '2023')
	//   month: 3-letter month abbreviation (e.g., 'Jan')
	//   total_failed: Count of failedful transactions
	//   total_amount: Sum of failedful transaction amounts
	// Business Logic:
	//   - Only includes failedful transactions (status = 'failed')
	//   - Covers two customizable time periods for comparison
	//   - Zero-fills months with no activity
	//   - Formats output for consistent visualization (year as text, month as 'Mon')
	//   - Orders by year and month (newest first)
	//   - Useful for identifying seasonal transaction patterns and revenue trends
	GetMonthTransactionStatusFailedCardNumber(ctx context.Context, arg GetMonthTransactionStatusFailedCardNumberParams) ([]*GetMonthTransactionStatusFailedCardNumberRow, error)
	// GetMonthTransactionStatusSuccess: Retrieves monthly success metrics for transactions
	// Purpose: Analyze successful transaction trends across comparison periods
	// Parameters:
	//   $1: period1_start - Start date of first comparison period
	//   $2: period1_end - End date of first comparison period
	//   $3: period2_start - Start date of second comparison period
	//   $4: period2_end - End date of second comparison period
	// Returns:
	//   year: Year as text (e.g., '2023')
	//   month: 3-letter month abbreviation (e.g., 'Jan')
	//   total_success: Count of successful transactions
	//   total_amount: Sum of successful transaction amounts
	// Business Logic:
	//   - Only includes successful transactions (status = 'success')
	//   - Covers two customizable time periods for comparison
	//   - Zero-fills months with no activity
	//   - Formats output for consistent visualization (year as text, month as 'Mon')
	//   - Orders by year and month (newest first)
	//   - Useful for identifying seasonal transaction patterns and revenue trends
	GetMonthTransactionStatusSuccess(ctx context.Context, arg GetMonthTransactionStatusSuccessParams) ([]*GetMonthTransactionStatusSuccessRow, error)
	// GetMonthTransactionStatusSuccessCardNumber: Retrieves monthly success metrics for transactions
	// Purpose: Analyze successful transaction trends across comparison periods
	// Parameters:
	//   $1: card_number  - filter by card_number
	//   $2: period1_start - Start date of first comparison period
	//   $3: period1_end - End date of first comparison period
	//   $4: period2_start - Start date of second comparison period
	//   $5: period2_end - End date of second comparison period
	// Returns:
	//   year: Year as text (e.g., '2023')
	//   month: 3-letter month abbreviation (e.g., 'Jan')
	//   total_success: Count of successful transactions
	//   total_amount: Sum of successful transaction amounts
	// Business Logic:
	//   - Only includes successful transactions (status = 'success')
	//   - Covers two customizable time periods for comparison
	//   - Zero-fills months with no activity
	//   - Formats output for consistent visualization (year as text, month as 'Mon')
	//   - Orders by year and month (newest first)
	//   - Useful for identifying seasonal transaction patterns and revenue trends
	GetMonthTransactionStatusSuccessCardNumber(ctx context.Context, arg GetMonthTransactionStatusSuccessCardNumberParams) ([]*GetMonthTransactionStatusSuccessCardNumberRow, error)
	// GetMonthlyAmounts: Retrieves total transaction amount per month for a specific year
	// Purpose:
	//   Visualize monthly trends in transaction volume for charting/dashboards
	// Parameters:
	//   $1: reference_date - Any date within the target year
	// Returns:
	//   - month: 3-letter month abbreviation
	//   - total_amount: Sum of transaction amounts in each month
	// Business Logic:
	//   - Uses LEFT JOIN to ensure all months are included, even with 0 transactions
	//   - Filters out soft-deleted data (deleted_at IS NULL)
	GetMonthlyAmounts(ctx context.Context, dollar_1 time.Time) ([]*GetMonthlyAmountsRow, error)
	// GetMonthlyAmountsByCardNumber: Retrieves total transaction amount per month for a specific year
	// Purpose:
	//   Visualize monthly trends in transaction volume for charting/dashboards
	// Parameters:
	//   $1: card_number  - filter by card_number
	//   $2: reference_date - Any date within the target year
	// Returns:
	//   - month: 3-letter month abbreviation
	//   - total_amount: Sum of transaction amounts in each month
	// Business Logic:
	//   - Uses LEFT JOIN to ensure all months are included, even with 0 transactions
	//   - Filters out soft-deleted data (deleted_at IS NULL)
	GetMonthlyAmountsByCardNumber(ctx context.Context, arg GetMonthlyAmountsByCardNumberParams) ([]*GetMonthlyAmountsByCardNumberRow, error)
	// GetMonthlyPaymentMethods: Retrieves a monthly summary of transaction transactions categorized by payment method
	// Purpose:
	//   Useful for visualizing how each payment method is used over time within a given year
	// Parameters:
	//   $1: reference_date - Any date within the target year (used to generate monthly range)
	// Returns:
	//   - month (e.g., 'Jan', 'Feb')
	//   - payment_method (e.g., 'e-wallet', 'bank_transfer')
	//   - total_transactions: Number of transactions for the method that month
	//   - total_amount: Total amount of transactions for the method that month
	// Business Logic:
	//   - Includes all combinations of months and available payment methods (even if 0 data)
	//   - Excludes soft-deleted transactions (deleted_at IS NULL)
	//   - Uses CROSS JOIN to ensure all months and methods are represented
	GetMonthlyPaymentMethods(ctx context.Context, dollar_1 time.Time) ([]*GetMonthlyPaymentMethodsRow, error)
	// GetMonthlyPaymentMethodsByCardNumber: Retrieves a monthly summary of transaction transactions categorized by payment method
	// Purpose:
	//   Useful for visualizing how each payment method is used over time within a given year
	// Parameters:
	//   $1: card_number  - filter by card_number
	//   $2: reference_date - Any date within the target year (used to generate monthly range)
	// Returns:
	//   - month (e.g., 'Jan', 'Feb')
	//   - payment_method (e.g., 'e-wallet', 'bank_transfer')
	//   - total_transactions: Number of transactions for the method that month
	//   - total_amount: Total amount of transactions for the method that month
	// Business Logic:
	//   - Includes all combinations of months and available payment methods (even if 0 data)
	//   - Excludes soft-deleted transactions (deleted_at IS NULL)
	//   - Uses CROSS JOIN to ensure all months and methods are represent
	GetMonthlyPaymentMethodsByCardNumber(ctx context.Context, arg GetMonthlyPaymentMethodsByCardNumberParams) ([]*GetMonthlyPaymentMethodsByCardNumberRow, error)
	// GetRole: Retrieves role details by role_id
	// Purpose: Fetch a single role record (regardless of deleted status)
	// Parameters:
	//   $1: Role ID
	// Returns:
	//   role_id, role_name, and timestamps
	GetRole(ctx context.Context, roleID int32) (*Role, error)
	// GetRoleByName: Retrieves role by exact role name
	// Purpose: Check role existence or fetch role info based on name
	// Parameters:
	//   $1: Role name (exact match)
	// Returns:
	//   role_id, role_name, and timestamps
	GetRoleByName(ctx context.Context, roleName string) (*Role, error)
	// GetRoles: Retrieves all roles (active & trashed) with optional name search and pagination
	// Purpose: General listing of roles regardless of status
	// Parameters:
	//   $1: Search query (role name, nullable)
	//   $2: Limit (number of records per page)
	//   $3: Offset (starting index for pagination)
	// Returns:
	//   role_id, role_name, timestamps, and total_count (for pagination support)
	// Business Logic:
	//   - Supports fuzzy search on role_name
	//   - Includes both active and trashed roles
	//   - Useful for admin panels with filters and pagination
	GetRoles(ctx context.Context, arg GetRolesParams) ([]*GetRolesRow, error)
	// GetTransactionByCardNumber: Retrieves paginated transactions for a specific card with optional filtering
	// Purpose: View transaction history for a particular card with search capability
	// Parameters:
	//   $1: card_number - The card number to filter transactions (exact match)
	//   $2: search_term - Optional text to filter by payment method (NULL for no filter)
	//   $3: limit - Maximum number of records to return per page
	//   $4: offset - Number of records to skip for pagination
	// Returns:
	//   All transaction fields plus total_count of matching records
	// Business Logic:
	//   - Only returns active transactions (non-deleted records)
	//   - Strict matching on card_number combined with optional payment method search
	//   - Case-insensitive partial matching on payment_method when search term provided
	//   - Orders results by transaction_time (newest transactions first)
	//   - Includes pagination metadata via total_count
	//   - Useful for cardholder transaction history views and statements
	GetTransactionByCardNumber(ctx context.Context, arg GetTransactionByCardNumberParams) ([]*GetTransactionByCardNumberRow, error)
	// GetTransactionByID: Retrieves a single transaction by its ID
	// Purpose: Get detailed information about a specific transaction
	// Parameters:
	//   $1: transaction_id - The ID of the transaction to retrieve
	// Returns:
	//   All fields for the specified transaction or NULL if not found/deleted
	// Business Logic:
	//   - Only returns active transactions (deleted_at IS NULL)
	//   - Useful for transaction details viewing and verification
	GetTransactionByID(ctx context.Context, transactionID int32) (*GetTransactionByIDRow, error)
	// GetTransactions: Retrieves paginated transaction records with search capability
	// Purpose: List all transactions for management UI with filtering options
	// Parameters:
	//   $1: search_term - Optional text to filter transactions by card number, payment method, or status (NULL for no filter)
	//   $2: limit - Maximum number of records to return
	//   $3: offset - Number of records to skip for pagination
	// Returns:
	//   All transaction fields plus total_count of matching records
	// Business Logic:
	//   - Excludes soft-deleted transactions (deleted_at IS NULL)
	//   - Supports partial text matching on multiple fields (case-insensitive)
	//   - Orders by transaction_time (newest first)
	//   - Provides total_count for pagination calculations
	//   - Useful for transaction monitoring and auditing
	GetTransactions(ctx context.Context, arg GetTransactionsParams) ([]*GetTransactionsRow, error)
	// GetTransactionsByCardNumber: Retrieves paginated transactions for a specific card
	// Purpose: List all transactions associated with a particular card
	// Parameters:
	//   $1: card_number - The card number to filter transactions
	//   $2: search_term - Optional text to filter by payment method or status
	//   $3: limit - Maximum number of records to return
	//   $4: offset - Number of records to skip for pagination
	// Returns:
	//   All transaction fields plus total_count of matching records
	// Business Logic:
	//   - Only includes active transactions (deleted_at IS NULL)
	//   - Strict card number matching combined with optional search filters
	//   - Orders by transaction_time (newest first)
	//   - Provides pagination support with total_count
	//   - Useful for cardholder transaction history
	GetTransactionsByCardNumber(ctx context.Context, arg GetTransactionsByCardNumberParams) ([]*GetTransactionsByCardNumberRow, error)
	// GetTransactionsByMerchantID: Retrieves transactions for a specific merchant
	// Purpose: List all transactions associated with a merchant
	// Parameters:
	//   $1: merchant_id - The ID of the merchant to filter transactions
	// Returns:
	//   All transaction fields for the merchant's transactions
	// Business Logic:
	//   - Only includes active transactions (deleted_at IS NULL)
	//   - Orders by transaction_time (newest first)
	//   - No pagination (assumes manageable number of records per merchant)
	//   - Useful for merchant transaction reports
	GetTransactionsByMerchantID(ctx context.Context, merchantID int32) ([]*GetTransactionsByMerchantIDRow, error)
	// GetTrashedRoles: Retrieves only soft-deleted roles with optional search and pagination
	// Purpose: For trash/recycle bin management
	// Parameters:
	//   $1: Search query (nullable)
	//   $2: Limit
	//   $3: Offset
	// Returns:
	//   role_id, role_name, timestamps, and total_count
	GetTrashedRoles(ctx context.Context, arg GetTrashedRolesParams) ([]*GetTrashedRolesRow, error)
	// GetTrashedTransactionByID: Retrieves a single soft-deleted transaction by ID
	// Purpose: View details of a deleted transaction for recovery or audit
	// Parameters:
	//   $1: transaction_id - The ID of the transaction to retrieve
	// Returns:
	//   All fields for the specified trashed transaction or NULL if not found/active
	// Business Logic:
	//   - Only returns soft-deleted transactions (deleted_at IS NOT NULL)
	//   - Used in admin interfaces for transaction recovery
	GetTrashedTransactionByID(ctx context.Context, transactionID int32) (*Transaction, error)
	// GetTrashedTransactions: Retrieves paginated soft-deleted transactions
	// Purpose: List all deleted transactions for recovery or audit purposes
	// Parameters:
	//   $1: search_term - Optional text to filter deleted transactions
	//   $2: limit - Maximum records to return
	//   $3: offset - Records to skip for pagination
	// Returns:
	//   All transaction fields plus total_count of matching deleted records
	// Business Logic:
	//   - Only includes soft-deleted transactions (deleted_at IS NOT NULL)
	//   - Same filtering capabilities as active transactions
	//   - Maintains newest-first ordering
	//   - Used in admin interfaces for transaction recovery
	GetTrashedTransactions(ctx context.Context, arg GetTrashedTransactionsParams) ([]*GetTrashedTransactionsRow, error)
	// GetUserRoles: Retrieves all roles assigned to a specific user
	// Purpose: Identify the access level(s) of a user
	// Parameters:
	//   $1: User ID
	// Returns:
	//   List of roles (id, name, timestamps)
	GetUserRoles(ctx context.Context, userID int32) ([]*Role, error)
	// GetYearlyAmounts: Retrieves total transaction amount per year over a 5-year span
	// Purpose:
	//   Analyze annual growth or decline in transaction volume for trend analysis
	// Parameters:
	//   $1: current_year - The most recent year to include (covers current_year - 4 to current_year)
	// Returns:
	//   - year: Year of the transaction
	//   - total_amount: Total transaction amount for the year
	// Business Logic:
	//   - Excludes soft-deleted transactions (deleted_at IS NULL)
	GetYearlyAmounts(ctx context.Context, dollar_1 interface{}) ([]*GetYearlyAmountsRow, error)
	// GetYearlyAmountsByCardNumber:  Retrieves total transaction amount per year over a 5-year span
	// Purpose:
	//   Analyze annual growth or decline in transaction volume for trend analysis
	// Parameters:
	//   $1: card_number  - filter by card_number
	//   $2: current_year - The most recent year to include (covers current_year - 4 to current_year)
	// Returns:
	//   - year: Year of the transaction
	//   - total_amount: Total transaction amount for the year
	// Business Logic:
	//   - Excludes soft-deleted transactions (deleted_at IS NULL)
	GetYearlyAmountsByCardNumber(ctx context.Context, arg GetYearlyAmountsByCardNumberParams) ([]*GetYearlyAmountsByCardNumberRow, error)
	// GetYearlyPaymentMethods: Retrieves yearly summary of transaction transactions grouped by payment method over a 5-year span
	// Purpose:
	//   Analyze long-term trends of transaction method usage across years
	// Parameters:
	//   $1: current_year - The most recent year to include (covers current_year - 4 to current_year)
	// Returns:
	//   - year: Year of transaction (e.g., 2020, 2021)
	//   - payment_method
	//   - total_transactions: Count of transactions per method per year
	//   - total_amount: Sum of amounts per method per year
	// Business Logic:
	//   - Filters data within a 5-year window
	//   - Excludes soft-deleted transactions (deleted_at IS NULL)
	GetYearlyPaymentMethods(ctx context.Context, dollar_1 interface{}) ([]*GetYearlyPaymentMethodsRow, error)
	// GetYearlyPaymentMethodsByCardNumber: Retrieves yearly summary of transaction transactions grouped by payment method over a 5-year span
	// Purpose:
	//   Analyze long-term trends of transaction method usage across years
	// Parameters:
	//   $1: card_number  - filter by card_number
	//   $2: current_year - The most recent year to include (covers current_year - 4 to current_year)
	// Returns:
	//   - year: Year of transaction (e.g., 2020, 2021)
	//   - payment_method
	//   - total_transactions: Count of transactions per method per year
	//   - total_amount: Sum of amounts per method per year
	// Business Logic:
	//   - Filters data within a 5-year window
	//   - Excludes soft-deleted transactions (deleted_at IS NULL)
	GetYearlyPaymentMethodsByCardNumber(ctx context.Context, arg GetYearlyPaymentMethodsByCardNumberParams) ([]*GetYearlyPaymentMethodsByCardNumberRow, error)
	// GetYearlyTransactionStatusFailed: Retrieves yearly failed metrics for transactions
	// Purpose: Compare annual failedful transaction performance
	// Parameters:
	//   $1: current_year - The target year (includes this year and previous)
	// Returns:
	//   year: Year as text (e.g., '2023')
	//   total_failed: Count of failedful transactions
	//   total_amount: Sum of failedful transaction amounts
	// Business Logic:
	//   - Only includes failedful transactions (status = 'failed')
	//   - Compares current year with previous year
	//   - Zero-fills years with no activity
	//   - Orders by year (newest first)
	//   - Useful for year-over-year growth analysis and financial reporting
	//   - Helps identify annual transaction volume and revenue trends
	GetYearlyTransactionStatusFailed(ctx context.Context, dollar_1 int32) ([]*GetYearlyTransactionStatusFailedRow, error)
	// GetYearlyTransactionStatusFailed: Retrieves yearly failed metrics for transactions
	// Purpose: Compare annual failedful transaction performance
	// Parameters:
	//   $1: card_number  - filter by card_number
	//   $2: current_year - The target year (includes this year and previous)
	// Returns:
	//   year: Year as text (e.g., '2023')
	//   total_failed: Count of failedful transactions
	//   total_amount: Sum of failedful transaction amounts
	// Business Logic:
	//   - Only includes failedful transactions (status = 'failed')
	//   - Compares current year with previous year
	//   - Zero-fills years with no activity
	//   - Orders by year (newest first)
	//   - Useful for year-over-year growth analysis and financial reporting
	//   - Helps identify annual transaction volume and revenue trends
	GetYearlyTransactionStatusFailedCardNumber(ctx context.Context, arg GetYearlyTransactionStatusFailedCardNumberParams) ([]*GetYearlyTransactionStatusFailedCardNumberRow, error)
	// GetYearlyTransactionStatusSuccess: Retrieves yearly success metrics for transactions
	// Purpose: Compare annual successful transaction performance
	// Parameters:
	//   $1: current_year - The target year (includes this year and previous)
	// Returns:
	//   year: Year as text (e.g., '2023')
	//   total_success: Count of successful transactions
	//   total_amount: Sum of successful transaction amounts
	// Business Logic:
	//   - Only includes successful transactions (status = 'success')
	//   - Compares current year with previous year
	//   - Zero-fills years with no activity
	//   - Orders by year (newest first)
	//   - Useful for year-over-year growth analysis and financial reporting
	//   - Helps identify annual transaction volume and revenue trends
	GetYearlyTransactionStatusSuccess(ctx context.Context, dollar_1 int32) ([]*GetYearlyTransactionStatusSuccessRow, error)
	// GetYearlyTransactionStatusSuccessCardNumber: Retrieves yearly success metrics for transactions
	// Purpose: Compare annual successful transaction performance
	// Parameters:
	//   $1: card_number  - filter by card_number
	//   $2: current_year - The target year (includes this year and previous)
	// Returns:
	//   year: Year as text (e.g., '2023')
	//   total_success: Count of successful transactions
	//   total_amount: Sum of successful transaction amounts
	// Business Logic:
	//   - Only includes successful transactions (status = 'success')
	//   - Compares current year with previous year
	//   - Zero-fills years with no activity
	//   - Orders by year (newest first)
	//   - Useful for year-over-year growth analysis and financial reporting
	//   - Helps identify annual transaction volume and revenue trends
	GetYearlyTransactionStatusSuccessCardNumber(ctx context.Context, arg GetYearlyTransactionStatusSuccessCardNumberParams) ([]*GetYearlyTransactionStatusSuccessCardNumberRow, error)
	// RestoreAllRoles: Restores all soft-deleted roles in bulk
	// Purpose: Bulk recovery of all trashed roles
	// Parameters: None
	RestoreAllRoles(ctx context.Context) error
	// RestoreAllTransactions: Recovers all trashed transactions
	// Purpose: Mass restoration of deleted transactions
	// Business Logic:
	//   - Clears deleted_at for all trashed records
	//   - Useful for system recovery scenarios
	//   - Should be used cautiously in production
	RestoreAllTransactions(ctx context.Context) error
	// RestoreRole: Restores a previously trashed role
	// Purpose: Undelete a soft-deleted role
	// Parameters:
	//   $1: Role ID
	RestoreRole(ctx context.Context, roleID int32) (*Role, error)
	// RestoreTransaction: Recovers a soft-deleted transaction
	// Purpose: Reactivate a previously trashed transaction
	// Parameters:
	//   $1: transaction_id - ID of transaction to restore
	// Business Logic:
	//   - Clears the deleted_at timestamp
	//   - Only works on currently trashed records
	//   - Used for data recovery purposes
	RestoreTransaction(ctx context.Context, transactionID int32) (*Transaction, error)
	// TrashRole: Soft-deletes a role (moves to trash)
	// Purpose: Mark role as deleted without removing it permanently
	// Parameters:
	//   $1: Role ID
	TrashRole(ctx context.Context, roleID int32) (*Role, error)
	// TrashTransaction: Soft-deletes a transaction record
	// Purpose: Remove transaction from active use without permanent deletion
	// Parameters:
	//   $1: transaction_id - ID of transaction to trash
	// Business Logic:
	//   - Sets deleted_at timestamp
	//   - Preserves data for audit/recovery purposes
	//   - Only affects currently active records
	TrashTransaction(ctx context.Context, transactionID int32) (*Transaction, error)
	// UpdateRole: Updates role name by ID
	// Purpose: Modify role information (e.g., name correction)
	// Parameters:
	//   $1: Role ID
	//   $2: New role name
	// Returns:
	//   Updated role's data
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (*Role, error)
	// UpdateTransaction: Modifies an existing transaction's details
	// Purpose: Update transaction information
	// Parameters:
	//   $1: transaction_id - ID of transaction to update
	//   $2: card_number - Updated card number
	//   $3: amount - Updated transaction amount
	//   $4: payment_method - Updated payment method
	//   $5: merchant_id - Updated merchant ID
	//   $6: transaction_time - Updated transaction timestamp
	// Business Logic:
	//   - Only updates active transactions (non-deleted)
	//   - Automatically updates the modification timestamp
	//   - Used for correcting transaction details
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (*UpdateTransactionRow, error)
	// UpdateTransactionStatus: Changes a transaction's status
	// Purpose: Update transaction processing status
	// Parameters:
	//   $1: transaction_id - ID of transaction to update
	//   $2: status - New status (e.g., 'success', 'failed', 'pending')
	// Business Logic:
	//   - Only updates active transactions
	//   - Used to reflect transaction processing outcomes
	//   - Important for reconciliation and reporting
	UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) (*UpdateTransactionStatusRow, error)
}

var _ Querier = (*Queries)(nil)
