// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: ai_security/ai_security.proto

package ai_security

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AISecurityService_DetectFraud_FullMethodName     = "/pb.ai_security.AISecurityService/DetectFraud"
	AISecurityService_VerifySecurity_FullMethodName  = "/pb.ai_security.AISecurityService/VerifySecurity"
	AISecurityService_BatchTrainModel_FullMethodName = "/pb.ai_security.AISecurityService/BatchTrainModel"
)

// AISecurityServiceClient is the client API for AISecurityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AISecurityServiceClient interface {
	DetectFraud(ctx context.Context, in *FraudRequest, opts ...grpc.CallOption) (*FraudResponse, error)
	VerifySecurity(ctx context.Context, in *SecurityRequest, opts ...grpc.CallOption) (*SecurityResponse, error)
	BatchTrainModel(ctx context.Context, in *TrainRequest, opts ...grpc.CallOption) (*TrainResponse, error)
}

type aISecurityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAISecurityServiceClient(cc grpc.ClientConnInterface) AISecurityServiceClient {
	return &aISecurityServiceClient{cc}
}

func (c *aISecurityServiceClient) DetectFraud(ctx context.Context, in *FraudRequest, opts ...grpc.CallOption) (*FraudResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FraudResponse)
	err := c.cc.Invoke(ctx, AISecurityService_DetectFraud_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aISecurityServiceClient) VerifySecurity(ctx context.Context, in *SecurityRequest, opts ...grpc.CallOption) (*SecurityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SecurityResponse)
	err := c.cc.Invoke(ctx, AISecurityService_VerifySecurity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aISecurityServiceClient) BatchTrainModel(ctx context.Context, in *TrainRequest, opts ...grpc.CallOption) (*TrainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrainResponse)
	err := c.cc.Invoke(ctx, AISecurityService_BatchTrainModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AISecurityServiceServer is the server API for AISecurityService service.
// All implementations must embed UnimplementedAISecurityServiceServer
// for forward compatibility.
type AISecurityServiceServer interface {
	DetectFraud(context.Context, *FraudRequest) (*FraudResponse, error)
	VerifySecurity(context.Context, *SecurityRequest) (*SecurityResponse, error)
	BatchTrainModel(context.Context, *TrainRequest) (*TrainResponse, error)
	mustEmbedUnimplementedAISecurityServiceServer()
}

// UnimplementedAISecurityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAISecurityServiceServer struct{}

func (UnimplementedAISecurityServiceServer) DetectFraud(context.Context, *FraudRequest) (*FraudResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DetectFraud not implemented")
}
func (UnimplementedAISecurityServiceServer) VerifySecurity(context.Context, *SecurityRequest) (*SecurityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifySecurity not implemented")
}
func (UnimplementedAISecurityServiceServer) BatchTrainModel(context.Context, *TrainRequest) (*TrainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchTrainModel not implemented")
}
func (UnimplementedAISecurityServiceServer) mustEmbedUnimplementedAISecurityServiceServer() {}
func (UnimplementedAISecurityServiceServer) testEmbeddedByValue()                           {}

// UnsafeAISecurityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AISecurityServiceServer will
// result in compilation errors.
type UnsafeAISecurityServiceServer interface {
	mustEmbedUnimplementedAISecurityServiceServer()
}

func RegisterAISecurityServiceServer(s grpc.ServiceRegistrar, srv AISecurityServiceServer) {
	// If the following call panics, it indicates UnimplementedAISecurityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AISecurityService_ServiceDesc, srv)
}

func _AISecurityService_DetectFraud_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FraudRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AISecurityServiceServer).DetectFraud(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AISecurityService_DetectFraud_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AISecurityServiceServer).DetectFraud(ctx, req.(*FraudRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AISecurityService_VerifySecurity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecurityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AISecurityServiceServer).VerifySecurity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AISecurityService_VerifySecurity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AISecurityServiceServer).VerifySecurity(ctx, req.(*SecurityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AISecurityService_BatchTrainModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AISecurityServiceServer).BatchTrainModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AISecurityService_BatchTrainModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AISecurityServiceServer).BatchTrainModel(ctx, req.(*TrainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AISecurityService_ServiceDesc is the grpc.ServiceDesc for AISecurityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AISecurityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ai_security.AISecurityService",
	HandlerType: (*AISecurityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DetectFraud",
			Handler:    _AISecurityService_DetectFraud_Handler,
		},
		{
			MethodName: "VerifySecurity",
			Handler:    _AISecurityService_VerifySecurity_Handler,
		},
		{
			MethodName: "BatchTrainModel",
			Handler:    _AISecurityService_BatchTrainModel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ai_security/ai_security.proto",
}
