// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: ai_security/ai_security.proto

package ai_security

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SecurityDomain int32

const (
	SecurityDomain_UNKNOWN     SecurityDomain = 0
	SecurityDomain_CARD        SecurityDomain = 1
	SecurityDomain_MERCHANT    SecurityDomain = 2
	SecurityDomain_SALDO       SecurityDomain = 3
	SecurityDomain_TOPUP       SecurityDomain = 4
	SecurityDomain_TRANSACTION SecurityDomain = 5
	SecurityDomain_TRANSFER    SecurityDomain = 6
	SecurityDomain_WITHDRAW    SecurityDomain = 7
)

// Enum value maps for SecurityDomain.
var (
	SecurityDomain_name = map[int32]string{
		0: "UNKNOWN",
		1: "CARD",
		2: "MERCHANT",
		3: "SALDO",
		4: "TOPUP",
		5: "TRANSACTION",
		6: "TRANSFER",
		7: "WITHDRAW",
	}
	SecurityDomain_value = map[string]int32{
		"UNKNOWN":     0,
		"CARD":        1,
		"MERCHANT":    2,
		"SALDO":       3,
		"TOPUP":       4,
		"TRANSACTION": 5,
		"TRANSFER":    6,
		"WITHDRAW":    7,
	}
)

func (x SecurityDomain) Enum() *SecurityDomain {
	p := new(SecurityDomain)
	*p = x
	return p
}

func (x SecurityDomain) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecurityDomain) Descriptor() protoreflect.EnumDescriptor {
	return file_ai_security_ai_security_proto_enumTypes[0].Descriptor()
}

func (SecurityDomain) Type() protoreflect.EnumType {
	return &file_ai_security_ai_security_proto_enumTypes[0]
}

func (x SecurityDomain) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SecurityDomain.Descriptor instead.
func (SecurityDomain) EnumDescriptor() ([]byte, []int) {
	return file_ai_security_ai_security_proto_rawDescGZIP(), []int{0}
}

type FraudRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	MerchantId    int32                  `protobuf:"varint,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	UserId        int32                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,6,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	DeviceId      string                 `protobuf:"bytes,7,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	IpAddress     string                 `protobuf:"bytes,8,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Timestamp     int64                  `protobuf:"varint,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FraudRequest) Reset() {
	*x = FraudRequest{}
	mi := &file_ai_security_ai_security_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FraudRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FraudRequest) ProtoMessage() {}

func (x *FraudRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_security_ai_security_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FraudRequest.ProtoReflect.Descriptor instead.
func (*FraudRequest) Descriptor() ([]byte, []int) {
	return file_ai_security_ai_security_proto_rawDescGZIP(), []int{0}
}

func (x *FraudRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *FraudRequest) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *FraudRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FraudRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *FraudRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *FraudRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *FraudRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *FraudRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *FraudRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type FraudResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	RiskScore     float64                `protobuf:"fixed64,2,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"` // 0.0 to 1.0
	IsFraudulent  bool                   `protobuf:"varint,3,opt,name=is_fraudulent,json=isFraudulent,proto3" json:"is_fraudulent,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FraudResponse) Reset() {
	*x = FraudResponse{}
	mi := &file_ai_security_ai_security_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FraudResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FraudResponse) ProtoMessage() {}

func (x *FraudResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_security_ai_security_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FraudResponse.ProtoReflect.Descriptor instead.
func (*FraudResponse) Descriptor() ([]byte, []int) {
	return file_ai_security_ai_security_proto_rawDescGZIP(), []int{1}
}

func (x *FraudResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *FraudResponse) GetRiskScore() float64 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *FraudResponse) GetIsFraudulent() bool {
	if x != nil {
		return x.IsFraudulent
	}
	return false
}

func (x *FraudResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type SecurityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        SecurityDomain         `protobuf:"varint,1,opt,name=domain,proto3,enum=pb.ai_security.SecurityDomain" json:"domain,omitempty"`
	EntityId      string                 `protobuf:"bytes,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"` // user_id, merchant_id, or card_number
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityRequest) Reset() {
	*x = SecurityRequest{}
	mi := &file_ai_security_ai_security_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityRequest) ProtoMessage() {}

func (x *SecurityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_security_ai_security_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityRequest.ProtoReflect.Descriptor instead.
func (*SecurityRequest) Descriptor() ([]byte, []int) {
	return file_ai_security_ai_security_proto_rawDescGZIP(), []int{2}
}

func (x *SecurityRequest) GetDomain() SecurityDomain {
	if x != nil {
		return x.Domain
	}
	return SecurityDomain_UNKNOWN
}

func (x *SecurityRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *SecurityRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SecurityRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type SecurityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSafe        bool                   `protobuf:"varint,1,opt,name=is_safe,json=isSafe,proto3" json:"is_safe,omitempty"`
	RiskScore     float64                `protobuf:"fixed64,2,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"` // ALLOW, CHALLENGE, DENY
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityResponse) Reset() {
	*x = SecurityResponse{}
	mi := &file_ai_security_ai_security_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityResponse) ProtoMessage() {}

func (x *SecurityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_security_ai_security_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityResponse.ProtoReflect.Descriptor instead.
func (*SecurityResponse) Descriptor() ([]byte, []int) {
	return file_ai_security_ai_security_proto_rawDescGZIP(), []int{3}
}

func (x *SecurityResponse) GetIsSafe() bool {
	if x != nil {
		return x.IsSafe
	}
	return false
}

func (x *SecurityResponse) GetRiskScore() float64 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *SecurityResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *SecurityResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type TrainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     string                 `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainRequest) Reset() {
	*x = TrainRequest{}
	mi := &file_ai_security_ai_security_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainRequest) ProtoMessage() {}

func (x *TrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_security_ai_security_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainRequest.ProtoReflect.Descriptor instead.
func (*TrainRequest) Descriptor() ([]byte, []int) {
	return file_ai_security_ai_security_proto_rawDescGZIP(), []int{4}
}

func (x *TrainRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *TrainRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type TrainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Accuracy      float64                `protobuf:"fixed64,3,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainResponse) Reset() {
	*x = TrainResponse{}
	mi := &file_ai_security_ai_security_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainResponse) ProtoMessage() {}

func (x *TrainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_security_ai_security_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainResponse.ProtoReflect.Descriptor instead.
func (*TrainResponse) Descriptor() ([]byte, []int) {
	return file_ai_security_ai_security_proto_rawDescGZIP(), []int{5}
}

func (x *TrainResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TrainResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TrainResponse) GetAccuracy() float64 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

var File_ai_security_ai_security_proto protoreflect.FileDescriptor

const file_ai_security_ai_security_proto_rawDesc = "" +
	"\n" +
	"\x1dai_security/ai_security.proto\x12\x0epb.ai_security\"\xa4\x02\n" +
	"\fFraudRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\x05R\n" +
	"merchantId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x05R\x06userId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12%\n" +
	"\x0epayment_method\x18\x06 \x01(\tR\rpaymentMethod\x12\x1b\n" +
	"\tdevice_id\x18\a \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"ip_address\x18\b \x01(\tR\tipAddress\x12\x1c\n" +
	"\ttimestamp\x18\t \x01(\x03R\ttimestamp\"\x92\x01\n" +
	"\rFraudResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x02 \x01(\x01R\triskScore\x12#\n" +
	"\ris_fraudulent\x18\x03 \x01(\bR\fisFraudulent\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\x86\x02\n" +
	"\x0fSecurityRequest\x126\n" +
	"\x06domain\x18\x01 \x01(\x0e2\x1e.pb.ai_security.SecurityDomainR\x06domain\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\tR\bentityId\x12I\n" +
	"\bmetadata\x18\x03 \x03(\v2-.pb.ai_security.SecurityRequest.MetadataEntryR\bmetadata\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"z\n" +
	"\x10SecurityResponse\x12\x17\n" +
	"\ais_safe\x18\x01 \x01(\bR\x06isSafe\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x02 \x01(\x01R\triskScore\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\"H\n" +
	"\fTrainRequest\x12\x1d\n" +
	"\n" +
	"start_date\x18\x01 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x02 \x01(\tR\aendDate\"_\n" +
	"\rTrainResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1a\n" +
	"\baccuracy\x18\x03 \x01(\x01R\baccuracy*x\n" +
	"\x0eSecurityDomain\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\b\n" +
	"\x04CARD\x10\x01\x12\f\n" +
	"\bMERCHANT\x10\x02\x12\t\n" +
	"\x05SALDO\x10\x03\x12\t\n" +
	"\x05TOPUP\x10\x04\x12\x0f\n" +
	"\vTRANSACTION\x10\x05\x12\f\n" +
	"\bTRANSFER\x10\x06\x12\f\n" +
	"\bWITHDRAW\x10\a2\x8a\x02\n" +
	"\x11AISecurityService\x12L\n" +
	"\vDetectFraud\x12\x1c.pb.ai_security.FraudRequest\x1a\x1d.pb.ai_security.FraudResponse\"\x00\x12U\n" +
	"\x0eVerifySecurity\x12\x1f.pb.ai_security.SecurityRequest\x1a .pb.ai_security.SecurityResponse\"\x00\x12P\n" +
	"\x0fBatchTrainModel\x12\x1c.pb.ai_security.TrainRequest\x1a\x1d.pb.ai_security.TrainResponse\"\x00BHZFgithub.com/MamangRust/microservice-payment-gateway-grpc/pb/ai_securityb\x06proto3"

var (
	file_ai_security_ai_security_proto_rawDescOnce sync.Once
	file_ai_security_ai_security_proto_rawDescData []byte
)

func file_ai_security_ai_security_proto_rawDescGZIP() []byte {
	file_ai_security_ai_security_proto_rawDescOnce.Do(func() {
		file_ai_security_ai_security_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_security_ai_security_proto_rawDesc), len(file_ai_security_ai_security_proto_rawDesc)))
	})
	return file_ai_security_ai_security_proto_rawDescData
}

var file_ai_security_ai_security_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ai_security_ai_security_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_ai_security_ai_security_proto_goTypes = []any{
	(SecurityDomain)(0),      // 0: pb.ai_security.SecurityDomain
	(*FraudRequest)(nil),     // 1: pb.ai_security.FraudRequest
	(*FraudResponse)(nil),    // 2: pb.ai_security.FraudResponse
	(*SecurityRequest)(nil),  // 3: pb.ai_security.SecurityRequest
	(*SecurityResponse)(nil), // 4: pb.ai_security.SecurityResponse
	(*TrainRequest)(nil),     // 5: pb.ai_security.TrainRequest
	(*TrainResponse)(nil),    // 6: pb.ai_security.TrainResponse
	nil,                      // 7: pb.ai_security.SecurityRequest.MetadataEntry
}
var file_ai_security_ai_security_proto_depIdxs = []int32{
	0, // 0: pb.ai_security.SecurityRequest.domain:type_name -> pb.ai_security.SecurityDomain
	7, // 1: pb.ai_security.SecurityRequest.metadata:type_name -> pb.ai_security.SecurityRequest.MetadataEntry
	1, // 2: pb.ai_security.AISecurityService.DetectFraud:input_type -> pb.ai_security.FraudRequest
	3, // 3: pb.ai_security.AISecurityService.VerifySecurity:input_type -> pb.ai_security.SecurityRequest
	5, // 4: pb.ai_security.AISecurityService.BatchTrainModel:input_type -> pb.ai_security.TrainRequest
	2, // 5: pb.ai_security.AISecurityService.DetectFraud:output_type -> pb.ai_security.FraudResponse
	4, // 6: pb.ai_security.AISecurityService.VerifySecurity:output_type -> pb.ai_security.SecurityResponse
	6, // 7: pb.ai_security.AISecurityService.BatchTrainModel:output_type -> pb.ai_security.TrainResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ai_security_ai_security_proto_init() }
func file_ai_security_ai_security_proto_init() {
	if File_ai_security_ai_security_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_security_ai_security_proto_rawDesc), len(file_ai_security_ai_security_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_security_ai_security_proto_goTypes,
		DependencyIndexes: file_ai_security_ai_security_proto_depIdxs,
		EnumInfos:         file_ai_security_ai_security_proto_enumTypes,
		MessageInfos:      file_ai_security_ai_security_proto_msgTypes,
	}.Build()
	File_ai_security_ai_security_proto = out.File
	file_ai_security_ai_security_proto_goTypes = nil
	file_ai_security_ai_security_proto_depIdxs = nil
}
