apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-security
  namespace: payment-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-security
  template:
    metadata:
      labels:
        app: ai-security
    spec:
      initContainers:
        - name: wait-for-kafka
          image: busybox:1.35
          command: ["sh", "-c"]
          args:
             - |
               echo "[INIT] Waiting for Kafka to be ready (TCP)..."
               until nc -z kafka-service.payment-gateway.svc.cluster.local 9092; do
                 echo "Kafka is not ready yet. Retrying in 5 seconds..."
                 sleep 5
               done
               echo "[INIT] Kafka is ready!"
        - name: wait-for-redis-cluster
          image: busybox:1.35
          command: ["sh", "-c"]
          args:
            - |
              echo "[INIT] Waiting for Redis Cluster nodes to be ready..."
              until nc -z redis-0.redis-service.payment-gateway.svc.cluster.local 6379; do
                echo "Redis Cluster node 0 is not ready yet. Retrying in 5 seconds..."
                sleep 5
              done
              echo "[INIT] Redis Cluster is accessible!"
      containers:
        - name: ai-security
          image: microservice-payment-gateway-grpc/ai-security:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: app-config
          ports:
            - containerPort: 50051
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
