apiVersion: v1
kind: Service
metadata:
  name: stats-reader
  namespace: payment-gateway
spec:
  selector:
    app: stats-reader
  ports:
  - name: grpc
    port: 50062
    targetPort: 50062
  type: ClusterIP
