package seeder

// amountToInt64 keeps the seeder boundary explicit: seeded amount columns are
// stored as PostgreSQL BIGINT and therefore generated by sqlc as int64, while
// the random generators produce int. The values are intentionally clamped to
// realistic ranges, so the conversion is always lossless.
func amountToInt64(value int64) int64 {
	return value
}
