// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"time"
)

type Querier interface {
	// CreateRole: Inserts a new role into the system
	// Purpose: Add new role definitions (e.g., Admin, Cashier, etc.)
	// Parameters:
	//   $1: Role name
	// Returns:
	//   Newly created role's full data (including timestamps)
	CreateRole(ctx context.Context, roleName string) (*Role, error)
	// CreateTopup: Inserts a new topup transaction into the topups table
	// Purpose: Used when a user performs a topup action
	// Parameters:
	//   $1: card_number - The card number receiving the topup
	//   $2: topup_amount - Amount of the topup
	//   $3: topup_method - Payment method used (e.g., 'e-wallet', 'bank_transfer')
	//   $4: topup_time - Timestamp of the actual topup transaction
	// Returns:
	//   Full topup record including auto-generated fields
	// Business Logic:
	//   - Automatically sets created_at and updated_at to current timestamp
	CreateTopup(ctx context.Context, arg CreateTopupParams) (*CreateTopupRow, error)
	// DeleteAllPermanentRoles: Permanently deletes all soft-deleted roles
	// Purpose: Bulk cleanup of trashed roles
	// Parameters: None
	DeleteAllPermanentRoles(ctx context.Context) error
	// DeleteAllPermanentTopups: Permanently deletes all soft-deleted topups
	// Purpose: Bulk cleanup of trashed topup records
	// Business Logic:
	//   - Cannot be undone; this is a hard delete
	//   - Use for permanent data purging
	DeleteAllPermanentTopups(ctx context.Context) error
	// DeletePermanentRole: Permanently deletes a trashed role
	// Purpose: Remove role from DB after soft delete
	// Parameters:
	//   $1: Role ID
	DeletePermanentRole(ctx context.Context, roleID int32) error
	// DeleteTopupPermanently: Permanently deletes a topup record from the database
	// Purpose: Irrecoverably removes topup data
	// Parameters:
	//   $1: topup_id - ID of the topup to delete
	// Business Logic:
	//   - No soft-delete; data is permanently erased
	//   - Use with caution
	DeleteTopupPermanently(ctx context.Context, topupID int32) error
	// GetActiveRoles: Retrieves only active (non-deleted) roles with optional search and pagination
	// Purpose: Display roles that are currently usable in the system
	// Parameters:
	//   $1: Search query (nullable)
	//   $2: Limit
	//   $3: Offset
	// Returns:
	//   role_id, role_name, timestamps, and total_count
	GetActiveRoles(ctx context.Context, arg GetActiveRolesParams) ([]*GetActiveRolesRow, error)
	// GetActiveTopups: Retrieves paginated list of active (non-deleted) topups with search
	// Purpose: Display only active topups for admin or user dashboards
	// Parameters:
	//   $1: search_term - Optional text to filter by card_number, topup_no, or topup_method
	//   $2: limit - Max records to return
	//   $3: offset - Number of rows to skip
	// Returns:
	//   All active topup fields and total_count
	// Business Logic:
	//   - Filters out soft-deleted topups (deleted_at IS NULL)
	//   - Supports partial, case-insensitive search across multiple fields
	//   - Results sorted by topup_time (most recent first)
	//   - total_count is used for frontend pagination
	GetActiveTopups(ctx context.Context, arg GetActiveTopupsParams) ([]*GetActiveTopupsRow, error)
	// GetMonthTopupStatusFailed: Retrieves monthly failed metrics for topups
	// Purpose: Analyze failedful topup trends across comparison periods
	// Parameters:
	//   $1: period1_start - Start date of first comparison period
	//   $2: period1_end - End date of first comparison period
	//   $3: period2_start - Start date of second comparison period
	//   $4: period2_end - End date of second comparison period
	// Returns:
	//   year: Year as text (e.g., '2023')
	//   month: 3-letter month abbreviation (e.g., 'Jan')
	//   total_failed: Count of failedful topups
	//   total_amount: Sum of failedful topup amounts
	// Business Logic:
	//   - Only includes failedful topups (status = 'failed')
	//   - Covers two customizable time periods for comparison
	//   - Zero-fills months with no activity
	//   - Formats output for consistent visualization
	//   - Orders by year and month (newest first)
	//   - Useful for identifying seasonal topup patterns
	GetMonthTopupStatusFailed(ctx context.Context, arg GetMonthTopupStatusFailedParams) ([]*GetMonthTopupStatusFailedRow, error)
	// GetMonthTopupStatusFailedCardNumber: Retrieves monthly failed metrics for topups
	// Purpose: Analyze failedful topup trends across comparison periods
	// Parameters:
	//   $1: card_number       - Optional filter by card_number (NULL to ignore filter)
	//   $2: period1_start - Start date of first comparison period
	//   $3: period1_end - End date of first comparison period
	//   $4: period2_start - Start date of second comparison period
	//   $5: period2_end - End date of second comparison period
	// Returns:
	//   year: Year as text (e.g., '2023')
	//   month: 3-letter month abbreviation (e.g., 'Jan')
	//   total_failed: Count of failedful topups
	//   total_amount: Sum of failedful topup amounts
	// Business Logic:
	//   - Only includes failedful topups (status = 'failed')
	//   - Covers two customizable time periods for comparison
	//   - Zero-fills months with no activity
	//   - Formats output for consistent visualization
	//   - Orders by year and month (newest first)
	//   - Useful for identifying seasonal topup patterns
	GetMonthTopupStatusFailedCardNumber(ctx context.Context, arg GetMonthTopupStatusFailedCardNumberParams) ([]*GetMonthTopupStatusFailedCardNumberRow, error)
	// GetMonthTopupStatusSuccess: Retrieves monthly success metrics for topups
	// Purpose: Analyze successful topup trends across comparison periods
	// Parameters:
	//   $1: period1_start - Start date of first comparison period
	//   $2: period1_end - End date of first comparison period
	//   $3: period2_start - Start date of second comparison period
	//   $4: period2_end - End date of second comparison period
	// Returns:
	//   year: Year as text (e.g., '2023')
	//   month: 3-letter month abbreviation (e.g., 'Jan')
	//   total_success: Count of successful topups
	//   total_amount: Sum of successful topup amounts
	// Business Logic:
	//   - Only includes successful topups (status = 'success')
	//   - Covers two customizable time periods for comparison
	//   - Zero-fills months with no activity
	//   - Formats output for consistent visualization
	//   - Orders by year and month (newest first)
	//   - Useful for identifying seasonal topup patterns
	GetMonthTopupStatusSuccess(ctx context.Context, arg GetMonthTopupStatusSuccessParams) ([]*GetMonthTopupStatusSuccessRow, error)
	// GetMonthTopupStatusSuccessCardNumber: Retrieves monthly success metrics for topups
	// Purpose: Analyze successful topup trends across comparison periods
	// Parameters:
	//   $1: card_number       - Optional filter by card_number (NULL to ignore filter)
	//   $2: period1_start - Start date of first comparison period
	//   $3: period1_end - End date of first comparison period
	//   $4: period2_start - Start date of second comparison period
	//   $5: period2_end - End date of second comparison period
	// Returns:
	//   year: Year as text (e.g., '2023')
	//   month: 3-letter month abbreviation (e.g., 'Jan')
	//   total_success: Count of successful topups
	//   total_amount: Sum of successful topup amounts
	// Business Logic:
	//   - Only includes successful topups (status = 'success')
	//   - Covers two customizable time periods for comparison
	//   - Zero-fills months with no activity
	//   - Formats output for consistent visualization
	//   - Orders by year and month (newest first)
	//   - Useful for identifying seasonal topup patterns
	GetMonthTopupStatusSuccessCardNumber(ctx context.Context, arg GetMonthTopupStatusSuccessCardNumberParams) ([]*GetMonthTopupStatusSuccessCardNumberRow, error)
	// GetMonthlyTopupAmounts: Retrieves total topup amounts per month for the selected year
	// Purpose: Visualize total topup volume across months in a given year
	// Parameters:
	//   $1: reference_date - Any date within the target year
	// Returns:
	//   month: 3-letter month abbreviation
	//   total_amount: Sum of all topup amounts per month
	// Business Logic:
	//   - Filters soft-deleted entries (deleted_at IS NULL)
	//   - Uses LEFT JOIN to ensure months with no topups are still included with amount = 0
	//   - Useful for monthly topup charts or dashboards
	GetMonthlyTopupAmounts(ctx context.Context, dollar_1 time.Time) ([]*GetMonthlyTopupAmountsRow, error)
	// GetMonthlyTopupAmountsByCardNumber: Retrieves total topup amounts per month for the selected year
	// Purpose: Visualize total topup volume across months in a given year
	// Parameters:
	//   $1: card_number  - filter by card_number
	//   $2: reference_date - Any date within the target year
	// Returns:
	//   month: 3-letter month abbreviation
	//   total_amount: Sum of all topup amounts per month
	// Business Logic:
	//   - Filters soft-deleted entries (deleted_at IS NULL)
	//   - Uses LEFT JOIN to ensure months with no topups are still included with amount = 0
	//   - Useful for monthly topup charts or dashboards
	GetMonthlyTopupAmountsByCardNumber(ctx context.Context, arg GetMonthlyTopupAmountsByCardNumberParams) ([]*GetMonthlyTopupAmountsByCardNumberRow, error)
	// GetMonthlyTopupMethods: Retrieves monthly breakdown of topup usage by method
	// Purpose: Track topup method distribution and amounts over each month of the selected year
	// Parameters:
	//   $1: reference_date - Any date within the target year (used to define monthly range)
	// Returns:
	//   month: 3-letter month abbreviation (e.g., 'Jan')
	//   topup_method: Method used for topup (e.g., 'bank_transfer', 'e-wallet')
	//   total_topups: Count of topups using the method in that month
	//   total_amount: Sum of topup amounts using the method in that month
	// Business Logic:
	//   - Ensures every topup method is shown for every month (even with 0 data)
	//   - Filters out soft-deleted records (deleted_at IS NULL)
	//   - Uses CROSS JOIN to combine months with all available methods
	//   - Useful for visualizing adoption trends of each topup method monthly
	GetMonthlyTopupMethods(ctx context.Context, dollar_1 time.Time) ([]*GetMonthlyTopupMethodsRow, error)
	// GetMonthlyTopupMethodsByCardNumber: Retrieves monthly breakdown of topup usage by method
	// Purpose: Track topup method distribution and amounts over each month of the selected year
	// Parameters:
	//   $1: card_number  - filter by card_number
	//   $2: reference_date - Any date within the target year (used to define monthly range)
	// Returns:
	//   month: 3-letter month abbreviation (e.g., 'Jan')
	//   topup_method: Method used for topup (e.g., 'bank_transfer', 'e-wallet')
	//   total_topups: Count of topups using the method in that month
	//   total_amount: Sum of topup amounts using the method in that month
	// Business Logic:
	//   - Ensures every topup method is shown for every month (even with 0 data)
	//   - Filters out soft-deleted records (deleted_at IS NULL)
	//   - Uses CROSS JOIN to combine months with all available methods
	//   - Useful for visualizing adoption trends of each topup method monthly
	GetMonthlyTopupMethodsByCardNumber(ctx context.Context, arg GetMonthlyTopupMethodsByCardNumberParams) ([]*GetMonthlyTopupMethodsByCardNumberRow, error)
	// GetRole: Retrieves role details by role_id
	// Purpose: Fetch a single role record (regardless of deleted status)
	// Parameters:
	//   $1: Role ID
	// Returns:
	//   role_id, role_name, and timestamps
	GetRole(ctx context.Context, roleID int32) (*Role, error)
	// GetRoleByName: Retrieves role by exact role name
	// Purpose: Check role existence or fetch role info based on name
	// Parameters:
	//   $1: Role name (exact match)
	// Returns:
	//   role_id, role_name, and timestamps
	GetRoleByName(ctx context.Context, roleName string) (*Role, error)
	// GetRoles: Retrieves all roles (active & trashed) with optional name search and pagination
	// Purpose: General listing of roles regardless of status
	// Parameters:
	//   $1: Search query (role name, nullable)
	//   $2: Limit (number of records per page)
	//   $3: Offset (starting index for pagination)
	// Returns:
	//   role_id, role_name, timestamps, and total_count (for pagination support)
	// Business Logic:
	//   - Supports fuzzy search on role_name
	//   - Includes both active and trashed roles
	//   - Useful for admin panels with filters and pagination
	GetRoles(ctx context.Context, arg GetRolesParams) ([]*GetRolesRow, error)
	// GetTopupByID: Retrieves a specific topup by ID
	// Purpose: Used to display details of a single topup transaction
	// Parameters:
	//   $1: topup_id - Unique identifier of the topup
	// Returns:
	//   Topup record matching the ID (if not soft-deleted)
	// Business Logic:
	//   - Only returns record if it is active (deleted_at IS NULL)
	GetTopupByID(ctx context.Context, topupID int32) (*GetTopupByIDRow, error)
	// GetTopups: Retrieves paginated list of active topups with search capability
	// Purpose: Provide admin or user access to topup history with search support
	// Parameters:
	//   $1: search_term - Optional filter to match card_number, topup_no, topup_method, or status (NULL for no filter)
	//   $2: limit - Max number of records to return
	//   $3: offset - Records to skip for pagination
	// Returns:
	//   All topup fields and total_count of matching records
	// Business Logic:
	//   - Filters out soft-deleted topups (deleted_at IS NULL)
	//   - Supports partial, case-insensitive search across multiple fields
	//   - Results sorted by topup_time (most recent first)
	//   - total_count is used for frontend pagination
	GetTopups(ctx context.Context, arg GetTopupsParams) ([]*GetTopupsRow, error)
	// GetTopupsByCardNumber: Retrieves paginated topups based on card number and optional search keyword
	// Purpose: View all topups for a specific card, with filtering and pagination
	// Parameters:
	//   $1: card_number - Exact card number match
	//   $2: keyword - Optional keyword (nullable), filters topup_no, method, status
	//   $3: limit - Number of records to return
	//   $4: offset - Offset for pagination
	// Returns:
	//   All matching topup records with total_count using window function
	// Business Logic:
	//   - Skips soft-deleted records
	//   - Ordered by topup_time descending
	GetTopupsByCardNumber(ctx context.Context, arg GetTopupsByCardNumberParams) ([]*GetTopupsByCardNumberRow, error)
	// GetTrashedRoles: Retrieves only soft-deleted roles with optional search and pagination
	// Purpose: For trash/recycle bin management
	// Parameters:
	//   $1: Search query (nullable)
	//   $2: Limit
	//   $3: Offset
	// Returns:
	//   role_id, role_name, timestamps, and total_count
	GetTrashedRoles(ctx context.Context, arg GetTrashedRolesParams) ([]*GetTrashedRolesRow, error)
	// GetTrashedTopupByID: Retrieves a topup that has been soft-deleted
	// Purpose: Preview or manage trashed entries (e.g., for restore)
	// Parameters:
	//   $1: topup_id - ID of the soft-deleted topup
	// Returns:
	//   Full topup record if found and deleted_at IS NOT NULL
	GetTrashedTopupByID(ctx context.Context, topupID int32) (*Topup, error)
	// GetTrashedTopups: Retrieves trashed (soft-deleted) topups with pagination and search
	// Purpose: Allow recovery or permanent deletion of topups
	// Parameters:
	//   $1: search_term - Optional filter to match card_number, topup_no, or topup_method
	//   $2: limit - Max records to return
	//   $3: offset - Rows to skip
	// Returns:
	//   Trashed topup records with total_count
	// Business Logic:
	//   - Only includes topups where deleted_at IS NOT NULL
	//   - Supports flexible search
	//   - Results sorted by topup_time descending
	GetTrashedTopups(ctx context.Context, arg GetTrashedTopupsParams) ([]*GetTrashedTopupsRow, error)
	// GetUserRoles: Retrieves all roles assigned to a specific user
	// Purpose: Identify the access level(s) of a user
	// Parameters:
	//   $1: User ID
	// Returns:
	//   List of roles (id, name, timestamps)
	GetUserRoles(ctx context.Context, userID int32) ([]*Role, error)
	// GetYearlyTopupAmounts: Retrieves yearly total of topup amounts
	// Purpose: Analyze yearly growth or decline in topup volume
	// Parameters:
	//   $1: current_year - The latest year to include (e.g., 2024), includes 5-year span (current_year - 4)
	// Returns:
	//   year: Year extracted from topup_time
	//   total_amount: Sum of all topup amounts in the year
	// Business Logic:
	//   - Includes topup data from current year and 4 years prior
	//   - Excludes soft-deleted records (deleted_at IS NULL)
	//   - Ideal for trend lines or comparative bar charts by year
	GetYearlyTopupAmounts(ctx context.Context, dollar_1 interface{}) ([]*GetYearlyTopupAmountsRow, error)
	// GetYearlyTopupAmountsByCardNumber: Retrieves yearly total of topup amounts
	// Purpose: Analyze yearly growth or decline in topup volume
	// Parameters:
	//   $1: card_number  - filter by card_number
	//   $2: current_year - The latest year to include (e.g., 2024), includes 5-year span (current_year - 4)
	// Returns:
	//   year: Year extracted from topup_time
	//   total_amount: Sum of all topup amounts in the year
	// Business Logic:
	//   - Includes topup data from current year and 4 years prior
	//   - Excludes soft-deleted records (deleted_at IS NULL)
	//   - Ideal for trend lines or comparative bar charts by year
	GetYearlyTopupAmountsByCardNumber(ctx context.Context, arg GetYearlyTopupAmountsByCardNumberParams) ([]*GetYearlyTopupAmountsByCardNumberRow, error)
	// GetYearlyTopupMethods: Retrieves yearly breakdown of topup usage by method
	// Purpose: Analyze how different topup methods perform over the past 5 years
	// Parameters:
	//   $1: current_year - The final year to include (e.g., 2024), includes 5-year span (current_year - 4)
	// Returns:
	//   year: Year extracted from topup_time
	//   topup_method: Method used for topup
	//   total_topups: Number of topups using that method in the year
	//   total_amount: Total topup amount for the method in the year
	// Business Logic:
	//   - Filters to topups within a 5-year window up to the given year
	//   - Filters out soft-deleted data (deleted_at IS NULL)
	//   - Useful for detecting long-term trends across payment methods
	GetYearlyTopupMethods(ctx context.Context, dollar_1 interface{}) ([]*GetYearlyTopupMethodsRow, error)
	// GetYearlyTopupMethodsByCardNumber: Retrieves yearly breakdown of topup usage by method
	// Purpose: Analyze how different topup methods perform over the past 5 years
	// Parameters:
	//   $1: card_number  - filter by card_number
	//   $2: current_year - The final year to include (e.g., 2024), includes 5-year span (current_year - 4)
	// Returns:
	//   year: Year extracted from topup_time
	//   topup_method: Method used for topup
	//   total_topups: Number of topups using that method in the year
	//   total_amount: Total topup amount for the method in the year
	// Business Logic:
	//   - Filters to topups within a 5-year window up to the given year
	//   - Filters out soft-deleted data (deleted_at IS NULL)
	//   - Useful for detecting long-term trends across payment methods
	GetYearlyTopupMethodsByCardNumber(ctx context.Context, arg GetYearlyTopupMethodsByCardNumberParams) ([]*GetYearlyTopupMethodsByCardNumberRow, error)
	// GetYearlyTopupStatusFailed: Retrieves yearly failed metrics for topups
	// Purpose: Compare annual failedful topup performance
	// Parameters:
	//   $1: current_year - The target year (includes this year and previous)
	// Returns:
	//   year: Year as text (e.g., '2023')
	//   total_failed: Count of failedful topups
	//   total_amount: Sum of failedful topup amounts
	// Business Logic:
	//   - Only includes failedful topups (status = 'failed')
	//   - Compares current year with previous year
	//   - Zero-fills years with no activity
	//   - Orders by year (newest first)
	//   - Useful for year-over-year growth analysis
	GetYearlyTopupStatusFailed(ctx context.Context, dollar_1 int32) ([]*GetYearlyTopupStatusFailedRow, error)
	// GetYearlyTopupStatusFailedCardNumber: Retrieves yearly failed metrics for topups
	// Purpose: Compare annual failedful topup performance
	// Parameters:
	//   $1: card_number  - filter by card_number
	//   $2: current_year - The target year (includes this year and previous)
	// Returns:
	//   year: Year as text (e.g., '2023')
	//   total_failed: Count of failedful topups
	//   total_amount: Sum of failedful topup amounts
	// Business Logic:
	//   - Only includes failedful topups (status = 'failed')
	//   - Compares current year with previous year
	//   - Zero-fills years with no activity
	//   - Orders by year (newest first)
	//   - Useful for year-over-year growth analysis
	GetYearlyTopupStatusFailedCardNumber(ctx context.Context, arg GetYearlyTopupStatusFailedCardNumberParams) ([]*GetYearlyTopupStatusFailedCardNumberRow, error)
	// GetYearlyTopupStatusSuccess: Retrieves yearly success metrics for topups
	// Purpose: Compare annual successful topup performance
	// Parameters:
	//   $1: current_year - The target year (includes this year and previous)
	// Returns:
	//   year: Year as text (e.g., '2023')
	//   total_success: Count of successful topups
	//   total_amount: Sum of successful topup amounts
	// Business Logic:
	//   - Only includes successful topups (status = 'success')
	//   - Compares current year with previous year
	//   - Zero-fills years with no activity
	//   - Orders by year (newest first)
	//   - Useful for year-over-year growth analysis
	GetYearlyTopupStatusSuccess(ctx context.Context, dollar_1 int32) ([]*GetYearlyTopupStatusSuccessRow, error)
	// GetYearlyTopupStatusSuccess: Retrieves yearly success metrics for topups
	// Purpose: Compare annual successful topup performance
	// Parameters:
	//   $1: card_number       - Optional filter by card_number (NULL to ignore filter)
	//   $2: current_year - The target year (includes this year and previous)
	// Returns:
	//   year: Year as text (e.g., '2023')
	//   total_success: Count of successful topups
	//   total_amount: Sum of successful topup amounts
	// Business Logic:
	//   - Only includes successful topups (status = 'success')
	//   - Compares current year with previous year
	//   - Zero-fills years with no activity
	//   - Orders by year (newest first)
	//   - Useful for year-over-year growth analysis
	GetYearlyTopupStatusSuccessCardNumber(ctx context.Context, arg GetYearlyTopupStatusSuccessCardNumberParams) ([]*GetYearlyTopupStatusSuccessCardNumberRow, error)
	// RestoreAllRoles: Restores all soft-deleted roles in bulk
	// Purpose: Bulk recovery of all trashed roles
	// Parameters: None
	RestoreAllRoles(ctx context.Context) error
	// RestoreAllTopups: Restores all soft-deleted topups in bulk
	// Purpose: Batch recovery of trashed topup data
	// Business Logic:
	//   - Sets deleted_at to NULL for all where it was not null
	RestoreAllTopups(ctx context.Context) error
	// RestoreRole: Restores a previously trashed role
	// Purpose: Undelete a soft-deleted role
	// Parameters:
	//   $1: Role ID
	RestoreRole(ctx context.Context, roleID int32) (*Role, error)
	// RestoreTopup: Restores a soft-deleted topup by nullifying deleted_at
	// Purpose: Reactivate a previously trashed topup
	// Parameters:
	//   $1: topup_id - ID of the topup to restore
	// Business Logic:
	//   - Only applies to records where deleted_at IS NOT NULL
	RestoreTopup(ctx context.Context, topupID int32) (*Topup, error)
	// TrashRole: Soft-deletes a role (moves to trash)
	// Purpose: Mark role as deleted without removing it permanently
	// Parameters:
	//   $1: Role ID
	TrashRole(ctx context.Context, roleID int32) (*Role, error)
	// TrashTopup: Soft deletes a topup by setting deleted_at
	// Purpose: Moves topup to trash without losing data
	// Parameters:
	//   $1: topup_id - ID of the topup to soft-delete
	// Business Logic:
	//   - Only active (non-deleted) records can be trashed
	//   - Allows restore in future
	TrashTopup(ctx context.Context, topupID int32) (*Topup, error)
	// UpdateRole: Updates role name by ID
	// Purpose: Modify role information (e.g., name correction)
	// Parameters:
	//   $1: Role ID
	//   $2: New role name
	// Returns:
	//   Updated role's data
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (*Role, error)
	// UpdateTopup: Updates an existing topup transaction
	// Purpose: Modify existing topup information by ID
	// Parameters:
	//   $1: topup_id - ID of the topup to update
	//   $2: card_number - Updated card number
	//   $3: topup_amount - Updated amount
	//   $4: topup_method - Updated payment method
	//   $5: topup_time - Updated transaction time
	// Business Logic:
	//   - Skips soft-deleted records (deleted_at IS NULL)
	//   - Updates updated_at automatically
	UpdateTopup(ctx context.Context, arg UpdateTopupParams) (*UpdateTopupRow, error)
	// UpdateTopupAmount: Updates only the topup_amount field for a specific topup
	// Purpose: Allow adjustment of topup amount without affecting other fields
	// Parameters:
	//   $1: topup_id - ID of the target topup
	//   $2: new topup amount
	// Business Logic:
	//   - Ignores deleted entries
	//   - Automatically updates the updated_at timestamp
	UpdateTopupAmount(ctx context.Context, arg UpdateTopupAmountParams) (*UpdateTopupAmountRow, error)
	// UpdateTopupStatus: Updates the status of a specific topup
	// Purpose: Mark topup as 'success', 'failed', etc.
	// Parameters:
	//   $1: topup_id - ID of the topup
	//   $2: new status value (e.g., 'success', 'failed')
	// Business Logic:
	//   - Applies only to active (non-deleted) records
	//   - updated_at is refreshed
	UpdateTopupStatus(ctx context.Context, arg UpdateTopupStatusParams) (*UpdateTopupStatusRow, error)
}

var _ Querier = (*Queries)(nil)
